### ISSUE TITLE
[v5]

### ISSUE THREAD

**Issue by sridhars20** [reportportal/reportportal#1016]
**Describe the bug**
Installed report-portal via shell installation and was trying to create Generate demo data using default user and encountered below error

```
020-06-12 06:39:28.145 ERROR 14571 --- [nio-8585-exec-4] c.e.t.r.c.e.rest.DefaultErrorResolver    : javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not execute statement

java.util.concurrent.CompletionException: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not execute statement
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not execute statement
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:733)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:695)
	at org.hibernate.engine.spi.CascadingActions$7.cascade(CascadingActions.java:298)
	at org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:492)
	at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:416)
	at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:218)
	at org.hibernate.engine.internal.Cascade.cascadeCollectionElements(Cascade.java:525)
	at org.hibernate.engine.internal.Cascade.cascadeCollection(Cascade.java:456)
	at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:419)
	at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:218)
	at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:151)
	at org.hibernate.event.internal.AbstractSaveEventListener.cascadeAfterSave(AbstractSaveEventListener.java:464)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:298)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:198)
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:128)
	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:192)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:135)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:62)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:108)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:703)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:689)
	at sun.reflect.GeneratedMethodAccessor293.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:314)
	at com.sun.proxy.$Proxy195.persist(Unknown Source)
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.save(SimpleJpaRepository.java:554)
	at sun.reflect.GeneratedMethodAccessor291.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:371)
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:204)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:657)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:621)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:605)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:353)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:178)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy242.save(Unknown Source)
	at com.epam.ta.reportportal.demodata.service.DemoDataLaunchService.startLaunch(DemoDataLaunchService.java:88)
	at com.epam.ta.reportportal.demodata.service.DemoDataLaunchService$$FastClassBySpringCGLIB$$6ebcac72.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:353)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.epam.ta.reportportal.demodata.service.DemoDataLaunchService$$EnhancerBySpringCGLIB$$7fa49d4.startLaunch(<generated>)
	at com.epam.ta.reportportal.demodata.service.DefaultDemoDataFacade.lambda$null$1(DefaultDemoDataFacade.java:102)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	... 3 common frames omitted
Caused by: org.hibernate.exception.SQLGrammarException: could not execute statement
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:103)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:200)
	at org.hibernate.dialect.identity.GetGeneratedKeysDelegate.executeAndExtract(GetGeneratedKeysDelegate.java:57)
	at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:43)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3106)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3699)
	at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:84)
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:645)
	at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:282)
	at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:263)
	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:317)
	at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:335)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:292)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:198)
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:128)
	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:192)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:135)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:118)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:727)
	... 68 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "item_attribute" does not exist
  Position: 13
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
	... 85 common frames omitted
```

**To Reproduce**
Install reportportal via shell installation.
Login as default user.
Try to generate demo data
**Expected behavior**
Expect to that demo data is generated.

**Screenshots**

![Screen Shot 2020-06-12 at 3 06 50 AM](https://user-images.githubusercontent.com/40050588/84475030-d98a2e80-ac59-11ea-942f-f29dd51c9831.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by pbortnik** [comment]
Hi, 
What tables do you have in reportportal database? 
Have you run db-scripts while installing reportportal?

**Comment by kainosact** [comment]
I've followed all the instructions here https://github.com/reportportal/shell-installation

**Comment by kainosact** [comment]
@pbortnik  Sorry forgot to send you the list of tables earlier.. Here you go
`                   List of relations
 Schema |              Name               | Type  | Owner
--------+---------------------------------+-------+-------
 public | acl_class                       | table | <obfuscated>
 public | acl_entry                       | table | <obfuscated>
 public | acl_object_identity             | table | <obfuscated>
 public | acl_sid                         | table | <obfuscated>
 public | active_directory_config         | table | <obfuscated>
 public | activity                        | table | <obfuscated>
 public | attachment                      | table | <obfuscated>
 public | attribute                       | table | <obfuscated>
 public | auth_config                     | table | <obfuscated>
 public | content_field                   | table | <obfuscated>
 public | dashboard                       | table | <obfuscated>
 public | dashboard_widget                | table | <obfuscated>
 public | filter                          | table | <obfuscated>
 public | filter_condition                | table | <obfuscated>
 public | filter_sort                     | table | <obfuscated>
 public | integration                     | table | <obfuscated>
 public | integration_type                | table | <obfuscated>
 public | issue                           | table | <obfuscated>
 public | issue_group                     | table | <obfuscated>
 public | issue_ticket                    | table | <obfuscated>
 public | issue_type                      | table | <obfuscated>
 public | issue_type_project              | table | <obfuscated>
 public | item_attribute                  | table | <obfuscated>
 public | launch                          | table | <obfuscated>
 public | launch_attribute_rules          | table | <obfuscated>
 public | launch_names                    | table | <obfuscated>
 public | launch_number                   | table | <obfuscated>
 public | ldap_config                     | table | <obfuscated>
 public | ldap_synchronization_attributes | table | <obfuscated>
 public | log                             | table | <obfuscated>
 public | oauth_access_token              | table | <obfuscated>
 public | oauth_registration              | table | <obfuscated>
 public | oauth_registration_restriction  | table | <obfuscated>
 public | oauth_registration_scope        | table | <obfuscated>
 public | parameter                       | table | <obfuscated>
 public | pattern_template                | table | <obfuscated>
 public | pattern_template_test_item      | table | <obfuscated>
 public | project                         | table | <obfuscated>
 public | project_attribute               | table | <obfuscated>
 public | project_user                    | table | <obfuscated>
 public | recipients                      | table | <obfuscated>
 public | restore_password_bid            | table | <obfuscated>
 public | saml_provider_details           | table | <obfuscated>
 public | sender_case                     | table | <obfuscated>
 public | server_settings                 | table | <obfuscated>
 public | shareable_entity                | table | <obfuscated>
 public | statistics                      | table | <obfuscated>
 public | statistics_field                | table | <obfuscated>
 public | test_item                       | table | <obfuscated>
 public | test_item_results               | table | <obfuscated>
 public | ticket                          | table | <obfuscated>
 public | user_creation_bid               | table | <obfuscated>
 public | user_preference                 | table | <obfuscated>
 public | users                           | table | <obfuscated>
 public | widget                          | table | <obfuscated>
 public | widget_filter                   | table | <obfuscated>`

**Comment by kainosact** [comment]
@pbortnik  Sorry forgot to send you the list of tables earlier.. Here you go

                   List of relations
 Schema |              Name               | Type  | Owner
--------+---------------------------------+-------+-------
 public | acl_class                       | table | <obfuscated>
 public | acl_entry                       | table | <obfuscated>
 public | acl_object_identity             | table | <obfuscated>
 public | acl_sid                         | table | <obfuscated>
 public | active_directory_config         | table | <obfuscated>
 public | activity                        | table | <obfuscated>
 public | attachment                      | table | <obfuscated>
 public | attribute                       | table | <obfuscated>
 public | auth_config                     | table | <obfuscated>
 public | content_field                   | table | <obfuscated>
 public | dashboard                       | table | <obfuscated>
 public | dashboard_widget                | table | <obfuscated>
 public | filter                          | table | <obfuscated>
 public | filter_condition                | table | <obfuscated>
 public | filter_sort                     | table | <obfuscated>
 public | integration                     | table | <obfuscated>
 public | integration_type                | table | <obfuscated>
 public | issue                           | table | <obfuscated>
 public | issue_group                     | table | <obfuscated>
 public | issue_ticket                    | table | <obfuscated>
 public | issue_type                      | table | <obfuscated>
 public | issue_type_project              | table | <obfuscated>
 public | item_attribute                  | table | <obfuscated>
 public | launch                          | table | <obfuscated>
 public | launch_attribute_rules          | table | <obfuscated>
 public | launch_names                    | table | <obfuscated>
 public | launch_number                   | table | <obfuscated>
 public | ldap_config                     | table | <obfuscated>
 public | ldap_synchronization_attributes | table | <obfuscated>
 public | log                             | table | <obfuscated>
 public | oauth_access_token              | table | <obfuscated>
 public | oauth_registration              | table | <obfuscated>
 public | oauth_registration_restriction  | table | <obfuscated>
 public | oauth_registration_scope        | table | <obfuscated>
 public | parameter                       | table | <obfuscated>
 public | pattern_template                | table | <obfuscated>
 public | pattern_template_test_item      | table | <obfuscated>
 public | project                         | table | <obfuscated>
 public | project_attribute               | table | <obfuscated>
 public | project_user                    | table | <obfuscated>
 public | recipients                      | table | <obfuscated>
 public | restore_password_bid            | table | <obfuscated>
 public | saml_provider_details           | table | <obfuscated>
 public | sender_case                     | table | <obfuscated>
 public | server_settings                 | table | <obfuscated>
 public | shareable_entity                | table | <obfuscated>
 public | statistics                      | table | <obfuscated>
 public | statistics_field                | table | <obfuscated>
 public | test_item                       | table | <obfuscated>
 public | test_item_results               | table | <obfuscated>
 public | ticket                          | table | <obfuscated>
 public | user_creation_bid               | table | <obfuscated>
 public | user_preference                 | table | <obfuscated>
 public | users                           | table | <obfuscated>
 public | widget                          | table | <obfuscated>
 public | widget_filter                   | table | <obfuscated>

**Comment by Yumfriez** [comment]
@evjlobanova We have to update our `shell-installation` repository and docs

**Comment by evjlobanova** [comment]
Added ticket to Jira

**Comment by evjlobanova** [comment]
Closed
All progress should be tracked in the ticket #973
