### ISSUE TITLE
Postgres deadlock occur while sending finish_launch reportportal_client (python) [v5]

### ISSUE THREAD

**Issue by iShimon** [reportportal/reportportal#1061]
**Describe the bug**
pytest client:
when tests are done a finish session is sent to rp using reportportal_client -> service.py -> finish_launch func
It appear when closing session postgres is running queries for statistics but gets catch up by finish_launch api request

`2020-07-14 10:24:25.024 UTC [27093] ERROR:  deadlock detected
2020-07-14 10:24:25.024 UTC [27093] DETAIL:  Process 27093 waits for ShareLock on transaction 15566678; blocked by process 27165.
	Process 27165 waits for ShareLock on transaction 15566681; blocked by process 27093.
	Process 27093: update public.test_item_results set duration=$1, end_time=$2, status=$3 where result_id=$4
	Process 27165: update public.launch set approximate_duration=$1, description=$2, end_time=$3, has_retries=$4, last_modified=$5, mode=$6, name=$7, number=$8, project_id=$9, rerun=$10, start_time=$11, status=$12, user_id=$13, uuid=$14 where id=$15
2020-07-14 10:24:25.024 UTC [27093] HINT:  See server log for query details.
2020-07-14 10:24:25.024 UTC [27093] CONTEXT:  while inserting index tuple (22656,113) in relation "statistics"
	SQL statement "INSERT INTO statistics (s_counter, statistics_field_id, item_id)
	            (SELECT 1, executions_field_id, item_id
	             FROM (SELECT item_id FROM test_item WHERE path @> (SELECT path FROM test_item WHERE item_id = new.result_id)) AS temp_bulk)
	        ON CONFLICT (statistics_field_id,
	            item_id)
	            DO UPDATE SET s_counter = statistics.s_counter + 1"
	PL/pgSQL function update_executions_statistics() line 72 at SQL statement
2020-07-14 10:24:25.024 UTC [27093] STATEMENT:  update public.test_item_results set duration=$1, end_time=$2, status=$3 where result_id=$4` 

**To Reproduce**
I'm not sure what load is causing the db to take a while to finish statistics.

**Additional context**
Using:
pytest-reportportal==5.0.3
reportportal-client==5.0.3
reportportal 5.1.0

**Comment by evjlobanova** [comment]
Which version of ReportPortal do you use?

**Comment by iShimon** [comment]
5.1.1

**Comment by evjlobanova** [comment]
@iShimon please update to the latest version 5.2.3

**Comment by iShimon** [comment]
tested with 5.2.3 issue with interrupted still appear, but deadlock messages does not seen in the log
i do see this error repeating in the api log:
` {"endTime":1595674162527,"status":"PASSED","issue":{"issueType":"ti001","autoAnalyzed":false,"ignoreAnalyzer":false},"launchUuid":"230b5df2-a828-4226-9769-966fcb902bdd"}
2020-07-25 10:49:22.536 DEBUG 7 --- [nio-8585-exec-9] c.e.t.r.w.c.TestItemAsyncController      : finishTestItem (763892) - Response  (0 ms)
 Status - OK (method return)
 -- Body --
 {"message":"Accepted finish request for test item ID = 169e2c6e-0c54-4c40-85bc-f3a1c0aa1b80"}
2020-07-25 10:49:22.553 ERROR 7 --- [nio-8585-exec-8] .AuthUtils$SerialUidReplacingInputStream : Potentially Fatal Deserialization Operation.

java.io.InvalidClassException: Overriding serialized class version mismatch: local serialVersionUID = -7964674894404781266 stream serialVersionUID = -4305814551308420811
	at com.epam.ta.reportportal.auth.util.AuthUtils$SerialUidReplacingInputStream.readClassDescriptor(AuthUtils.java:105)
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
	at java.base/java.io.ObjectInputStream.readClassDesc(Unknown Source)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.base/java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.base/java.io.ObjectInputStream.defaultReadFields(Unknown Source)
	at java.base/java.io.ObjectInputStream.readSerialData(Unknown Source)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.base/java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.base/java.io.ObjectInputStream.defaultReadFields(Unknown Source)
	at java.base/java.io.ObjectInputStream.readSerialData(Unknown Source)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.base/java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.base/java.io.ObjectInputStream.readObject(Unknown Source)
	at java.base/java.io.ObjectInputStream.readObject(Unknown Source)
	at com.epam.ta.reportportal.auth.util.AuthUtils.deserializeSafely(AuthUtils.java:69)
	at com.epam.ta.reportportal.auth.CombinedTokenStore.readAuthentication(CombinedTokenStore.java:68)
	at org.springframework.security.oauth2.provider.token.store.JwtTokenStore.readAuthentication(JwtTokenStore.java:70)
	at com.epam.ta.reportportal.auth.CombinedTokenStore.readAuthentication(CombinedTokenStore.java:55)
	at com.epam.ta.reportportal.auth.CombinedTokenStore$$FastClassBySpringCGLIB$$753697c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.epam.ta.reportportal.auth.CombinedTokenStore$$EnhancerBySpringCGLIB$$4a5ff1af.readAuthentication(<generated>)
	at org.springframework.security.oauth2.provider.token.DefaultTokenServices.loadAuthentication(DefaultTokenServices.java:242)
	at org.springframework.security.oauth2.provider.token.DefaultTokenServices$$FastClassBySpringCGLIB$$5a1f25c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	at org.springframework.security.oauth2.provider.token.DefaultTokenServices$$EnhancerBySpringCGLIB$$6eb8184f.loadAuthentication(<generated>)
	at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationManager.authenticate(OAuth2AuthenticationManager.java:87)
	at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:154)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by Yumfriez** [comment]
@iShimon Probably there is a problem with `api` token, regenerate it and try to run your tests with the new one

**Comment by babantax** [comment]
Good morning! Is there any new about this issue? We just migrated to version 5.3 and its logging this error all the time (like a loop) Thanks a lot

**Comment by iShimon** [comment]
I still haven't done the api token change , i need the clear time for that ... but upgrade did fixed the deadlocks , interrupted still appear, i will probably check it next week

**Comment by evjlobanova** [comment]
please regenerate token on the profile page, and then update token in all needed places
