### ISSUE TITLE
Long parameters fail server report

### ISSUE THREAD

**Issue by KanstantsinSudzilouski** [reportportal/reportportal#1065]
Put into StartTestItemRQ.parameters value with more than 256 characters, and will cause validation error on server:

```
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 400
Status message: Bad Request
Error Message: Incorrect Request. [Field 'parameters[0].value' should have size from '0' to '256'.] 
Error Type: INCORRECT_REQUEST

    at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:62)
    at com.epam.restendpoint.http.DefaultErrorHandler.handle(DefaultErrorHandler.java:56)
    at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:547)
    at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:518)
```

I belive we need to add triming at LaunchImpl.startTestItem + we need to merge two startTestItem methods. They match ~70%

**Comment by nvborisenko** [comment]
The same for test/launch name. API requires length 1..256

**Comment by Yumfriez** [comment]
@evjlobanova Probably we can increase parameters length on the back-end side or/and implement logic for parameters shortening

**Comment by evjlobanova** [comment]
@HardNorth what do you think about launch mane/parameter length increasing?

**Comment by nvborisenko** [comment]
https://github.com/reportportal/client-net/issues/57 and there is limitation for attributes value. I propose to get rid of any kind of string length limitations on server side.

**Comment by rplevka** [comment]
@evjlobanova, are the attr. vlaue length restrictions still in place in the recent version? Are there any plans to remove them?
thanks!

**Comment by HardNorth** [comment]
@evjlobanova For me that's no different, client will send it in either case. But since we are using relational database it depends on what we are indexing or going to index. The longer string we index the slower and more inefficient will be saving/getting operations. I can't recall a case when we perform a search through 'parameter' field, but we definitely search launches by name. Thus for me it's safe to increase parameter size, unless we are planing to index it.
