### ISSUE TITLE
[v5] Docker: Unable to login

### ISSUE THREAD

**Issue by orgads** [reportportal/reportportal#1079]
**Describe the bug**
I can not login. Call to /api/v1/user returns 502 Bad Gateway, and I see that the api service doesn't listen on port 8585.

**To Reproduce**
I'm unsure what exactly caused this.

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
Log:
```
INFO 6 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getWidgetUsingGET_1
INFO 6 --- [           main] o.s.s.quartz.SchedulerFactoryBean        : Starting Quartz Scheduler now
INFO 6 --- [           main] o.s.s.quartz.LocalDataSourceJobStore     : ClusterManager: detected 1 failed or restarted instances.
INFO 6 --- [           main] o.s.s.quartz.LocalDataSourceJobStore     : ClusterManager: Scanning for instance "api:4c577770e38b29b5e9e48b0244f94cdf"'s failed in-progress jobs.
INFO 6 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler reportportal_$_api:452b683e3ae92771f6b65e0c9807e4f2 started.
INFO 6 --- [_MisfireHandler] o.s.s.quartz.LocalDataSourceJobStore     : Handling 5 trigger(s) that missed their scheduled fire-time.
WARN 6 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 23505
ERROR 6 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: duplicate key value violates unique constraint "users_pk"
  Detail: Key (id)=(2) already exists.
INFO 6 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
INFO 6 --- [           main] ConditionEvaluationReportLoggingListener :
api_1            |
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
ERROR 6 --- [           main] o.s.boot.SpringApplication               : Application run failed
api_1            |
org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [users_pk]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
     at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:298)
     at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:255)
     at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:538)
     at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743)
     at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
     at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:631)
     at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:385)
     at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
     at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
     at com.epam.ta.reportportal.core.events.handler.AttachDefaultPhotoEventHandler$$EnhancerBySpringCGLIB$$e97f62b7.handleContextRefresh(<generated>)
     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
     at java.base/java.lang.reflect.Method.invoke(Unknown Source)
     at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:305)
     at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:190)
     at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:153)
     at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
     at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
     at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
     at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403)
     at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360)
     at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:897)
     at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162)
     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
     at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
     at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
     at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
     at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
     at com.epam.ta.reportportal.core.configs.ReportPortalApp.main(ReportPortalApp.java:37)
     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
     at java.base/java.lang.reflect.Method.invoke(Unknown Source)
     at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
     at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
     at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
     at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
     at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:109)
     at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
     at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
     at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
     at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:200)
     at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3430)
     at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:3292)
     at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3704)
     at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:201)
     at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
     at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
     at java.base/java.util.LinkedHashMap.forEach(Unknown Source)
     at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
     at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:348)
     at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40)
     at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:102)
     at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1352)
     at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:443)
     at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3202)
     at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2370)
     at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:447)
     at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:183)
     at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:40)
     at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:281)
     at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101)
     at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:534)
     ... 39 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_pk"
  Detail: Key (id)=(2) already exists.
     at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2578)
     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2313)
     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:331)
     at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
     at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
     at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159)
     at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:125)
     at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
     at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
     at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
     ... 60 common frames omitted
api_1            |
INFO 6 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler reportportal_$_api:452b683e3ae92771f6b65e0c9807e4f2 paused.
INFO 6 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Waiting for workers to finish.
INFO 6 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Successfully waited for workers to finish.
INFO 6 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Waiting for workers to finish.
INFO 6 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Successfully waited for workers to finish.
INFO 6 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Waiting for workers to finish.
INFO 6 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Successfully waited for workers to finish.
WARN 6 --- [           main] o.s.b.f.support.DisposableBeanAdapter    : Invocation of destroy method failed on bean with name 'tomcatMetricsBinder': java.lang.NullPointerException
INFO 6 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Shutdown ignored - container is not active already
INFO 6 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Shutdown ignored - container is not active already
INFO 6 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Shutdown ignored - container is not active already
INFO 6 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'autoAnalyzeTaskExecutor'
INFO 6 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
INFO 6 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'saveLogsTaskExecutor'
INFO 6 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'emailExecutorService'
INFO 6 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'patternAnalysisTaskExecutor'
INFO 6 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'demoDataTaskExecutor'
INFO 6 --- [           main] o.s.s.quartz.SchedulerFactoryBean        : Shutting down Quartz Scheduler
INFO 6 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler reportportal_$_api:452b683e3ae92771f6b65e0c9807e4f2 shutting down.
INFO 6 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler reportportal_$_api:452b683e3ae92771f6b65e0c9807e4f2 paused.
INFO 6 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler reportportal_$_api:452b683e3ae92771f6b65e0c9807e4f2 shutdown complete.
INFO 6 --- [cTaskExecutor-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@6965c32: tags=[[amq.ctag-_JSv3Dm7YU88E-EeXkj2Hg]], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbitmq@172.62.2.7:5672/,1), conn: Proxy@79c9a128 Shared Rabbit Connection: SimpleConnection@6dacde96 [delegate=amqp://rabbitmq@172.62.2.7:5672/, localPort= 55312], acknowledgeMode=AUTO local queue size=0
INFO 6 --- [cTaskExecutor-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@5f6dd89c: tags=[[amq.ctag-0ySifzRa7E4V8QbCWGfckA]], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbitmq@172.62.2.7:5672/,2), conn: Proxy@79c9a128 Shared Rabbit Connection: SimpleConnection@6dacde96 [delegate=amqp://rabbitmq@172.62.2.7:5672/, localPort= 55312], acknowledgeMode=AUTO local queue size=0
INFO 6 --- [cTaskExecutor-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@1b914e36: tags=[[amq.ctag-9hTg2e3AQ7TiPEINL9SuXA]], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbitmq@172.62.2.7:5672/,3), conn: Proxy@79c9a128 Shared Rabbit Connection: null, acknowledgeMode=AUTO local queue size=0
INFO 6 --- [cTaskExecutor-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@18eb6ea3: tags=[[amq.ctag-oZkcokExAyeLg1o0lfwfOA]], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbitmq@172.62.2.7:5672/,4), conn: Proxy@79c9a128 Shared Rabbit Connection: null, acknowledgeMode=AUTO local queue size=0
INFO 6 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
INFO 6 --- [cTaskExecutor-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@8850865: tags=[[amq.ctag-i5Vw78IqHrzjAuKn19CJHQ]], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbitmq@172.62.2.7:5672/,5), conn: Proxy@79c9a128 Shared Rabbit Connection: null, acknowledgeMode=AUTO local queue size=0
INFO 6 --- [cTaskExecutor-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@7dcc6679: tags=[[amq.ctag-A9I06QXB7hziWPDk0pH36A]], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbitmq@172.62.2.7:5672/,6), conn: Proxy@79c9a128 Shared Rabbit Connection: null, acknowledgeMode=AUTO local queue size=0
INFO 6 --- [cTaskExecutor-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@4842a683: tags=[[amq.ctag-YUc-BDndWxXYQHZD72pjxA]], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbitmq@172.62.2.7:5672/,8), conn: Proxy@79c9a128 Shared Rabbit Connection: null, acknowledgeMode=AUTO local queue size=0
INFO 6 --- [cTaskExecutor-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@64cbc28e: tags=[[amq.ctag-v7Dlqfsp9b9Py5LG05A5EA]], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbitmq@172.62.2.7:5672/,7), conn: Proxy@79c9a128 Shared Rabbit Connection: null, acknowledgeMode=AUTO local queue size=0
INFO 6 --- [cTaskExecutor-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@5f455d91: tags=[[amq.ctag-BBOAhMgYyofXos1LyZ8CKQ]], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbitmq@172.62.2.7:5672/,9), conn: Proxy@79c9a128 Shared Rabbit Connection: null, acknowledgeMode=AUTO local queue size=0
INFO 6 --- [cTaskExecutor-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@4b682e71: tags=[[amq.ctag-SG4-2Y5VVKsf3ZzykpUTmQ]], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbitmq@172.62.2.7:5672/,10), conn: Proxy@79c9a128 Shared Rabbit Connection: null, acknowledgeMode=AUTO local queue size=0
INFO 6 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
INFO 6 --- [cTaskExecutor-2] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@66c96027: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
INFO 6 --- [cTaskExecutor-2] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@56d08f00: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
INFO 6 --- [cTaskExecutor-2] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@63322da: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
INFO 6 --- [cTaskExecutor-2] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@ff80271: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
INFO 6 --- [cTaskExecutor-2] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@68148f42: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
INFO 6 --- [cTaskExecutor-2] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@77e6ec52: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
INFO 6 --- [cTaskExecutor-2] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@34ca6dec: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
INFO 6 --- [cTaskExecutor-2] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@2f93ea0b: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
INFO 6 --- [cTaskExecutor-2] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@59aad1a6: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
INFO 6 --- [cTaskExecutor-2] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@58f4de95: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
INFO 6 --- [cTaskExecutor-3] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@2e6bcb90: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
INFO 6 --- [cTaskExecutor-3] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@106c4c0e: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
INFO 6 --- [cTaskExecutor-3] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@7e30a1ca: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
INFO 6 --- [cTaskExecutor-3] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@4e999058: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
```

And indeed the postgres database had a duplicate user entry:
```
reportportal=# select * from users;
 id |   login    |                           password                           |           email            |       attachment       |        attachment_thumbnail         |     role      |   type   | expired | full_name |                                      metadata
----+------------+--------------------------------------------------------------+----------------------------+------------------------+-------------------------------------+---------------+----------+---------+-----------+------------------------------------------------------------------------------------
  3 | tester     | $2a$10$jqjuDRXoEeY/xSlxKv9ntO.7xyHmNZJE/2Z9/1KDONEYN6/Ow4EOi | default@domain.com         |                        |                                     | USER          | INTERNAL | f       | audc      | {"metadata": {"last_login": 1595428701975}}
  2 | default    | $2a$10$ypPHtHXs87EKMrPPpZahsOlGsBlCiRKh1oWn2WMzLVvIfH1VfNRdy | testers@domain.com         | dXNlcnMvZGVmYXVsdA     | dXNlcnMvdGh1bWJuYWlsLWRlZmF1bHQ     | USER          | INTERNAL | f       | testers   | {"metadata": {"last_login": 1595335475576, "attachmentContentType": "image/png"}}
  1 | superadmin | $2a$10$vhlxLsj.HcuQVrbRTmOu6OOjTYK/ZeiLTKEA2Sf5JOaxZ98/KHGem | superadminemail@domain.com | dXNlcnMvc3VwZXJhZG1pbg | dXNlcnMvdGh1bWJuYWlsLXN1cGVyYWRtaW4 | ADMINISTRATOR | INTERNAL | f       | tester    | {"metadata": {"last_login": 1595428812464, "attachmentContentType": "image/jpeg"}}
  2 | default    | $2a$10$WS7BhDl4caORMzBQz7y9zeF.iwLr87OipoubI5oo0D7OQ1qIZN8Jm | defaultemail@domain.com    | dXNlcnMvZGVmYXVsdA     | dXNlcnMvdGh1bWJuYWlsLWRlZmF1bHQ     | USER          | INTERNAL | f       | tester    | {"metadata": {"last_login": 1594886361625, "attachmentContentType": "image/png"}}
(4 rows)
```

And it was fixed by deleting the extra user and restarting the service:
```
reportportal=# delete from users where email = 'defaultemail@domain.com';
DELETE 1
```

**Comment by evjlobanova** [comment]
@orgads All services are running? Do you follow steps which are described here https://reportportal.io/docs/Deploy-with-Docker?

**Comment by orgads** [comment]
Yes. It worked for about a week, and suddenly broke. Possibly after upgrading (we started with 5.2.0 and upgraded to 5.2.2). Maybe another user added a user. Like I said, even the API service is running, but it is not listening on port 8585 (it has several other ports though).

After I deleted the row from the db and restarted the api service everything works again.

**Comment by evjlobanova** [comment]
@orgads So the problem has been resolved?

**Comment by orgads** [comment]
Yes, but I think it's worth investigating how this extra user got there.

Can you suggest how to track it?

Maybe it was added in DB migration process?

How come the DB didn't reject it in the first place?

**Comment by evjlobanova** [comment]
@Yumfriez Ivan, could you please check this issue?

**Comment by Yumfriez** [comment]
@evjlobanova We need to investigate this issue

**Comment by evjlobanova** [comment]
@e-olga could you please add a new task to Jira

**Comment by e-olga** [comment]
@evjlobanova, 
the ticket is added to RP backlog

**Comment by adelstrinidad** [comment]
I'm facing the same issue on windows. I just installed RP with Docker on Windows, I checked that all services are running ok, but when I try to login, I get "error 502".

**Comment by Invictum** [comment]
I've faced with the same issue on fresh RP install. Interesting that issue resolves itself if I wait for 3-5 minutes before login right after instance starting.

**Comment by alena-babrova** [comment]
Hello @orgads @adelstrinidad @Invictum 
Could you please tell me if the issue is still relevant?

**Comment by orgads** [comment]
Never happened again since then. Closing.
