### ISSUE TITLE
Attributes and Values are added but still the report has not stopped.

### ISSUE THREAD

**Issue by troyhugs** [reportportal/reportportal#1090]
Using const ReportportalAgent = require('@reportportal/agent-js-jasmine');

Looks like it is in an infinite loop.
![image](https://user-images.githubusercontent.com/17424203/88833738-5c5a4f00-d1f0-11ea-9591-55999f7f7eb2.png)

![image](https://user-images.githubusercontent.com/17424203/88833778-6da35b80-d1f0-11ea-83c8-c8cacdbab210.png)

**Comment by troyhugs** [comment]
Error: Request failed with status code 400: {"errorCode":40019,"message":"Test item status is ambiguous. There is no status provided from request and there are no descendants to check statistics for test item id '178143'"}
    at /Users/john/Documents/node_modules/@reportportal/client-javascript/lib/rest.js:31:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)


**Noticed an error**

**Comment by evjlobanova** [comment]
@AmsterGet Could you please take a look

**Comment by AmsterGet** [comment]
@troyhugs Hi!
The problem seems to arise when you try to send a `describe` block with no children, so the status for it cannot be calculated correctly.
**Possible solution:**
If you would like to report a suite without any tests / steps, please set your preferred status directly using [https://github.com/reportportal/agent-js-jasmine#finish-launchsuitespec-with-status](this) API.

**Comment by AmsterGet** [comment]
Improvement task create.

**Comment by troyhugs** [comment]
@AmsterGet 
![image](https://user-images.githubusercontent.com/17424203/90030372-9d1a9380-dcd9-11ea-9e75-818197736436.png)

Every describe block has enough tests and methods
