### ISSUE TITLE
[v5] Exception when starting API java.nio.file.AccessDeniedException: /plugins

### ISSUE THREAD

**Issue by naddison** [reportportal/reportportal#1112]
**Describe the bug**
I am trying to start the API as a deployment in K8, I am getting the following error.

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pf4jPluginBox' defined in class path resource [com/epam/ta/reportportal/core/configs/PluginConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.epam.ta.reportportal.core.plugin.Pf4jPluginBox]: Factory method 'pf4jPluginBox' threw exception; nested exception is java.nio.file.AccessDeniedException: /plugins
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:656)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:484)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
	... 122 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.epam.ta.reportportal.core.plugin.Pf4jPluginBox]: Factory method 'pf4jPluginBox' threw exception; nested exception is java.nio.file.AccessDeniedException: /plugins
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651)
	... 135 common frames omitted
Caused by: java.nio.file.AccessDeniedException: /plugins
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createDirectories(Unknown Source)
	at com.epam.ta.reportportal.plugin.Pf4jPluginManager.<init>(Pf4jPluginManager.java:97)
	at com.epam.ta.reportportal.core.configs.PluginConfiguration.pf4jPluginBox(PluginConfiguration.java:70)
	at com.epam.ta.reportportal.core.configs.PluginConfiguration$$EnhancerBySpringCGLIB$$e9aaacc4.CGLIB$pf4jPluginBox$1(<generated>)
	at com.epam.ta.reportportal.core.configs.PluginConfiguration$$EnhancerBySpringCGLIB$$e9aaacc4$$FastClassBySpringCGLIB$$bb87a2b2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.epam.ta.reportportal.core.configs.PluginConfiguration$$EnhancerBySpringCGLIB$$e9aaacc4.pf4jPluginBox(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 136 common frames omitted
```

This is related to https://github.com/reportportal/kubernetes/issues/127. I am unsure if /plugins is a problem trying to access a folder in the container in which the API process is running, or if it's a minio access issue.

Here is my K8 resource manifests. We are using bitnami images because we have a PSP that we cannot run containers as root:

Minio - https://gist.github.com/naddison/27ac4a39f12c35809954a6209332289e
API - https://gist.github.com/naddison/045d6fdeb2e315faf93d68cf8076f794

**Comment by Cyberglamdring** [comment]
Try adding [configpath](​​https://github.com/helm/charts/blob/master/stable/minio/values.yaml#L68) to MinIO values. Also the same issue is [here](https://github.com/waynesun09/reportportal-operator/issues/1#issuecomment-649520917)

**Comment by Cyberglamdring** [comment]
No response from requestor
