### ISSUE TITLE
Launches can not started in Report Portal

### ISSUE THREAD

**Issue by gavrillina** [reportportal/reportportal#1122]
Hello report portal team,
My framework has 3 threads for running tests, I integrated rp to my project and now i have this error:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: com.epam.reportportal.exception.InternalReportPortalClientException: Wait for Launch start timed out
	at com.epam.reportportal.utils.Waiter.till(Waiter.java:131)
	at com.epam.reportportal.service.launch.SecondaryLaunch.waitForLaunchStart(SecondaryLaunch.java:56)
	at com.epam.reportportal.service.launch.SecondaryLaunch.start(SecondaryLaunch.java:88)
	at com.epam.reportportal.testng.TestNGService.startLaunch(TestNGService.java:148)
	at com.epam.reportportal.testng.BaseTestNGListener.onExecutionStart(BaseTestNGListener.java:52)
	at org.testng.TestNG.runExecutionListeners(TestNG.java:1051)
	at org.testng.TestNG.run(TestNG.java:1002)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	... 9 more
I use TestNG.
I tried to find any information on google but there isn't. Could you help me to resolve this issue?

**Comment by gavrillina** [comment]
The problem was using testng version
I used 7.1.0. After changing version to  <testng.version>6.14.2</testng.version> it starts work. 
Working version are:
`<testng.version>6.14.2</testng.version>`
`<reportportal-agent-testng.version>4.2.1</reportportal-agent-testng.version>`
May be it's helpful somebody.
