### ISSUE TITLE
"TypeError: Object of type 'LocalPath' is not JSON serializable" is seen when working on 5.0.4

### ISSUE THREAD

**Issue by nilaya123** [reportportal/reportportal#1125]
"TypeError: Object of type 'LocalPath' is not JSON serializable" is seen when working on 5.0.4

Logs:
====
$ py -3 -m pytest test_example_form.py --reportportal
============================= test session starts =============================
platform win32 -- Python 3.6.5, pytest-4.1.1, py-1.8.0, pluggy-0.13.0 -- C:\Python36\python.exe
metadata: {'Python': '3.6.5', 'Platform': 'Windows-10-10.0.18362-SP0', 'Packages': {'pytest': '4.1.1', 'py': '1.8.0', 'pluggy': '0.13.0'}, 'Plugins': {'django': '3.4.7', 'forked': '1.0.2', 'html': '1.19.0', 'metadata': '1.7.0', 'reportportal': '5.0.4', 'rerunfailures': '4.1', 'xdist': '1.22.0'}, 'JAVA_HOME': 'C:\\Program Files\\Java\\jdk-14.0.1'}
rootdir: C:\Users\Qxf2 Services\newgithub\qxf2-page-object-model, inifile: pytest.ini
plugins: django-3.4.7, forked-1.0.2, html-1.19.0, metadata-1.7.0, reportportal-5.0.4, rerunfailures-4.1, xdist-1.22.0
collecting ... collected 1 item
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Python36\lib\site-packages\_pytest\main.py", line 203, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "C:\Python36\lib\site-packages\_pytest\main.py", line 243, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "C:\Python36\lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "C:\Python36\lib\site-packages\pluggy\manager.py", line 92, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Python36\lib\site-packages\pluggy\manager.py", line 86, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "C:\Python36\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Python36\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Python36\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Python36\lib\site-packages\_pytest\main.py", line 264, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "C:\Python36\lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "C:\Python36\lib\site-packages\pluggy\manager.py", line 92, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Python36\lib\site-packages\pluggy\manager.py", line 86, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "C:\Python36\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Python36\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Python36\lib\site-packages\pluggy\callers.py", line 182, in _multicall
INTERNALERROR>     next(gen)  # first yield
INTERNALERROR>   File "C:\Python36\lib\site-packages\pytest_reportportal\listener.py", line 55, in pytest_runtest_protocol
INTERNALERROR>     item_id = self.PyTestService.start_pytest_item(item)
INTERNALERROR>   File "C:\Python36\lib\site-packages\pytest_reportportal\service.py", line 297, in start_pytest_item
INTERNALERROR>     item_id = self.rp.start_test_item(**payload)
INTERNALERROR>   File "C:\Python36\lib\site-packages\reportportal_client\service.py", line 298, in start_test_item
INTERNALERROR>     r = self.session.post(url=url, json=data, verify=self.verify_ssl)
INTERNALERROR>   File "C:\Python36\lib\site-packages\requests\sessions.py", line 578, in post
INTERNALERROR>     return self.request('POST', url, data=data, json=json, **kwargs)
INTERNALERROR>   File "C:\Python36\lib\site-packages\requests\sessions.py", line 516, in request
INTERNALERROR>     prep = self.prepare_request(req)
INTERNALERROR>   File "C:\Python36\lib\site-packages\requests\sessions.py", line 459, in prepare_request
INTERNALERROR>     hooks=merge_hooks(request.hooks, self.hooks),
INTERNALERROR>   File "C:\Python36\lib\site-packages\requests\models.py", line 317, in prepare
INTERNALERROR>     self.prepare_body(data, files, json)
INTERNALERROR>   File "C:\Python36\lib\site-packages\requests\models.py", line 467, in prepare_body
INTERNALERROR>     body = complexjson.dumps(json)
INTERNALERROR>   File "C:\Python36\lib\json\__init__.py", line 231, in dumps
INTERNALERROR>     return _default_encoder.encode(obj)
INTERNALERROR>   File "C:\Python36\lib\json\encoder.py", line 199, in encode
INTERNALERROR>     chunks = self.iterencode(o, _one_shot=True)
INTERNALERROR>   File "C:\Python36\lib\json\encoder.py", line 257, in iterencode
INTERNALERROR>     return _iterencode(o, 0)
INTERNALERROR>   File "C:\Python36\lib\json\encoder.py", line 180, in default
INTERNALERROR>     o.__class__.__name__)
INTERNALERROR> TypeError: Object of type 'LocalPath' is not JSON serializable

======================== no tests ran in 0.32 seconds =========================

**Comment by RakeshSharma04** [comment]
I am facing the same

**Comment by ssharma555** [comment]
I deployed report portal and `pytest-reportportal` today and facing the same issue.

**Comment by Damianofds** [comment]
Same issue here, we needed to rollback to 5.0.3

**Comment by nalherbawi** [comment]
+! same issue here

**Comment by Phoenix7351** [comment]
Same.

**Comment by evjlobanova** [comment]
@iivanou Ivan, is this issue in pytest agent?

**Comment by iivanou** [comment]
@evjlobanova It is.
