### ISSUE TITLE
Azure AD integration in Report Portal

### ISSUE THREAD

**Issue by amitngm** [reportportal/reportportal#1198]
Is there any roadmap with Azure AD authentication? A configuration for it would be nice to have.

**Comment by evjlobanova** [comment]
Begining of 2021

**Comment by amitngm** [comment]
Thank You. Please do it early as we want to use it.

**Comment by evjlobanova** [comment]
We are delivering features in accordance with our roadmap. Our plans can be changed by paid requests from our users. Paid requests are implemented with the first priority.

We can propose a paid contract, in the scope of this agreement we will collect requirements from your side and make this feature earlier.

If it is interesting for you, please drop us a letter on support@reportportal.io

**Comment by amitngm** [comment]
Hi,

Is there any update on this?

Thanks,
Amit

**Comment by amitngm** [comment]
Hi All,

Do you have any plan to implement this feature?

Regards,
Amit

**Comment by herman-zubenko** [comment]
No news so far?

**Comment by evjlobanova** [comment]
ETA are not defined yet.
Our team can propose a paid support for this functionality.
If you are interested in this feature, please drop us a letter on our support@reportportal.io

**Comment by defied** [comment]
Has this been instrumented, or is it still further down the roadmap?

**Comment by amitngm** [comment]
Has this been implemented?? We are waiting for this since years :)

**Comment by ASaiAnudeep** [comment]
@DzmitryHumianiuk I think this issue is related to integration of Azure AD. The plugin you attached is a bts for Azure DevOps. Please correct me if I'm wrong. Could you please re-open the issue.

**Comment by DzmitryHumianiuk** [comment]
@ASaiAnudeep good catch. re-open

**Comment by badrinrs** [comment]
@DzmitryHumianiuk do you know when this would be available as this is a requirement for us to use ReportPortal.

**Comment by ASaiAnudeep** [comment]
I tried integrating ReportPortal with Azure AD SAML, but no luck as there is an existing issue #1268

**Comment by Yumfriez** [comment]
As I can see from logs, the problem with user email attribute mapping - it tries to save the user after successful authorization and fails because email attribute naming mismatch.
Please create a new issue with log and your configurations attached, so it will help us investigate and help others with a similar problem

**Comment by samagarw** [comment]
Issue while setting up the SAML integration with Azure . 

Getting Authorization Denied with following logs : 

2022-07-05 10:07:11.299 DEBUG 1 --- [nio-9999-exec-8] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/error'; against '/sso/login/**'
2022-07-05 10:07:11.299 DEBUG 1 --- [nio-9999-exec-8] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/error'; against '/epam/**'
2022-07-05 10:07:11.299 DEBUG 1 --- [nio-9999-exec-8] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/error'; against '/info'
2022-07-05 10:07:11.299 DEBUG 1 --- [nio-9999-exec-8] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/error'; against '/health'
2022-07-05 10:07:11.299 DEBUG 1 --- [nio-9999-exec-8] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/error'; against '/api-docs/**'
2022-07-05 10:07:11.299 DEBUG 1 --- [nio-9999-exec-8] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/error'; against '/saml/**'
2022-07-05 10:07:11.299 DEBUG 1 --- [nio-9999-exec-8] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/error'; against '/templates/**'
2022-07-05 10:07:11.299 DEBUG 1 --- [nio-9999-exec-8] o.s.s.w.a.i.FilterSecurityInterceptor    : Secure object: FilterInvocation: URL: /error; Attributes: [authenticated]
2022-07-05 10:07:11.299 DEBUG 1 --- [nio-9999-exec-8] o.s.s.w.a.i.FilterSecurityInterceptor    : Previously Authenticated: org.springframework.security.authentication.AnonymousAuthenticationToken@5db26b6c: Principal: anonymousUser; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@ffff4c9c: RemoteIpAddress: x.x.x.x ; SessionId: null; Granted Authorities: ROLE_ANONYMOUS
2022-07-05 10:07:11.299 DEBUG 1 --- [nio-9999-exec-8] o.s.s.access.vote.AffirmativeBased       : Voter: org.springframework.security.web.access.expression.WebExpressionVoter@41eb7cb5, returned: -1
2022-07-05 10:07:11.300 DEBUG 1 --- [nio-9999-exec-8] o.s.s.w.a.ExceptionTranslationFilter     : Access is denied (user is anonymous); redirecting to authentication entry point

org.springframework.security.access.AccessDeniedException: Access is denied
	at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:84) ~[spring-security-core-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:233) ~[spring-security-core-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:123) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]


I am getting Authorization successful with the same role for other users ( Admin AND Custom Users ) 

2022-07-05 10:53:02.143 DEBUG 1 --- [nio-9999-exec-5] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/health'; against '/epam/**'
2022-07-05 10:53:02.143 DEBUG 1 --- [nio-9999-exec-5] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/health'; against '/info'
2022-07-05 10:53:02.143 DEBUG 1 --- [nio-9999-exec-5] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/health'; against '/health'
2022-07-05 10:53:02.143 DEBUG 1 --- [nio-9999-exec-5] o.s.s.w.a.i.FilterSecurityInterceptor    : Secure object: FilterInvocation: URL: /health; Attributes: [permitAll]
2022-07-05 10:53:02.143 DEBUG 1 --- [nio-9999-exec-5] o.s.s.w.a.i.FilterSecurityInterceptor    : Previously Authenticated: org.springframework.security.authentication.AnonymousAuthenticationToken@5dc51b5a: Principal: anonymousUser; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@ffffa64e: RemoteIpAddress: 10.213.0.68; SessionId: null; Granted Authorities: ROLE_ANONYMOUS
2022-07-05 10:53:02.143 DEBUG 1 --- [nio-9999-exec-5] o.s.s.access.vote.AffirmativeBased       : Voter: org.springframework.security.web.access.expression.WebExpressionVoter@41eb7cb5, returned: 1
2022-07-05 10:53:02.143 DEBUG 1 --- [nio-9999-exec-5] o.s.s.w.a.i.FilterSecurityInterceptor    : Authorization successful
2022-07-05 10:53:02.143 DEBUG 1 --- [nio-9999-exec-5] o.s.s.w.a.i.FilterSecurityInterceptor    : RunAsManager did not change Authentication object
2022-07-05 10:53:02.143 DEBUG 1 --- [nio-9999-exec-5] o.s.security.web.FilterChainProxy        : /health reached end of additional filter chain; procee

**Comment by vikrant-sancheti** [comment]
Any further updates on this?
