### ISSUE TITLE
Edit Defect type seems to be blocked by Auto Analysis

### ISSUE THREAD

**Issue by staind825** [reportportal/reportportal#1200]
Version: 5.3.2 on Kubernetes

When attempting to update a defect type from "To Investigate", there is a loading spinner that just keeps going down below the defect description and we are unable to save the new defect type. 

If we choose "Ignore in Auto Analysis" we can then update it. However, we are having to do this for every bug. We disabled Auto Analysis at the project level but it still seems to be trying to perform the analysis each time we edit a defect type. 

![image](https://user-images.githubusercontent.com/36093419/98158123-6f905100-1ea8-11eb-8c36-d26329bd7e4e.png)

**Comment by staind825** [comment]
any update on this issue?

**Comment by evjlobanova** [comment]
Hello!
Do you instance meet requirements for instance https://reportportal.io/docs/Optimal-Performance-Hardware?
Is your service analyzer and service Elastic Serch up?

**Comment by staind825** [comment]
Thanks for the response! Yes, we did follow the optimal approach for setup and our Elastic Search and Service Analyzer are up and running. 

In this particular situation though, we have disabled the auto analyzer for this project, but it seems like it's still trying to do it when we open up the defect.

**Comment by evjlobanova** [comment]
Auto Analysis is doing another sthings, this feature is separate from AA.
Which version of ReportPortal do you use?

**Comment by staind825** [comment]
We are using 5.3.2. Is there anyway i can disable this? I'm not sure what it's actually trying to do here on the defect.

**Comment by evjlobanova** [comment]
No, you can not.
Description of feature you can find here https://reportportal.io/docs/Search-for-the

@irynakozak2 could you please help us to find the root cause?

**Comment by staind825** [comment]
I grabbed some of the logs from Service analyzer:

2020-11-12 14:21:35,235 - analyzerApp.amqpHandler - DEBUG - Started processing <Basic.Deliver(['consumer_tag=ctag1.b400a37c4f004923aac97bcdc02eb37d', 'delivery_tag=23', 'exchange=analyzer-default', 'redelivered=False', 'routing_key=search'])> method <BasicProperties(['content_encoding=UTF-8', 'content_type=application/json', 'correlation_id=377', 'delivery_mode=2', "headers={'__TypeId__': 'com.epam.ta.reportportal.ws.model.analyzer.SearchRq'}", 'priority=0', 'reply_to=amq.rabbitmq.reply-to.g2dkAEdyYWJiaXRAcmFiYml0bXEtMC5yYWJiaXRtcS1oZWFkbGVzcy5yZXBvcnRwb3J0YWwtcHJvZC5zdmMuY2x1c3Rlci5sb2NhbAAAY2UAAAA1AQ==.wAMNjQbOl+DSxZE00pcTBQ=='])> props
2020-11-12 14:21:35,236 - analyzerApp.amqpHandler - DEBUG - Started processing data b'{"launchId":70670,"launchName":"Panda Unit Tests","itemId":4562662,"projectId":273,"filteredLaunchIds":[70670],"logMessages":["Stacktrace: Error: \\u001B[2mexpect(\\u001B[22m\\u001B[31mreceived\\u001B[39m\\u001B[2m).\\u001B[22mtoBe\\u001B[2m(\\u001B[22m\\u001B[32mexpected\\u001B[39m\\u001B[2m) // Object.is equality\\u001B[22m\\n\\nExpected: \\u001B[32m1\\u001B[39m\\nReceived: \\u001B[31m0\\u001B[39m\\n at Object.<anonymous> (/Users/mmclain/Source/FRMSGitLab/ecom-abiliti-ui/src/AbilitiUI/ClientApp/src/__tests__/auth/LogoutMessage.test.js:66:30)\\n at Object.asyncJestTest (/Users/mmclain/Source/FRMSGitLab/ecom-abiliti-ui/src/AbilitiUI/ClientApp/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)\\n at /Users/mmclain/Source/FRMSGitLab/ecom-abiliti-ui/src/AbilitiUI/ClientApp/node_modules/jest-jasmine2/build/queueRunner.js:43:12\\n at new Promise (<anonymous>)\\n at mapper (/Users/mmclain/Source/FRMSGitLab/ecom-abiliti-ui/src/AbilitiUI/ClientApp/node_modules/jest-jasmine2/build/queueRunner.js:26:19)\\n at /Users/mmclain/Source/FRMSGitLab/ecom-abiliti-ui/src/AbilitiUI/ClientApp/node_modules/jest-jasmine2/build/queueRunner.js:73:41\\n at processTicksAndRejections (internal/process/task_queues.js:97:5)\\n"],"logLines":3}'
2020-11-12 14:21:35,237 - analyzerApp.esclient - INFO - Started searching by request {"launchId": 70670, "launchName": "Panda Unit Tests", "itemId": 4562662, "projectId": 273, "filteredLaunchIds": [70670], "logMessages": ["Stacktrace: Error: \u001b[2mexpect(\u001b[22m\u001b[31mreceived\u001b[39m\u001b[2m).\u001b[22mtoBe\u001b[2m(\u001b[22m\u001b[32mexpected\u001b[39m\u001b[2m) // Object.is equality\u001b[22m\n\nExpected: \u001b[32m1\u001b[39m\nReceived: \u001b[31m0\u001b[39m\n at Object.<anonymous> (/Users/mmclain/Source/FRMSGitLab/ecom-abiliti-ui/src/AbilitiUI/ClientApp/src/__tests__/auth/LogoutMessage.test.js:66:30)\n at Object.asyncJestTest (/Users/mmclain/Source/FRMSGitLab/ecom-abiliti-ui/src/AbilitiUI/ClientApp/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)\n at /Users/mmclain/Source/FRMSGitLab/ecom-abiliti-ui/src/AbilitiUI/ClientApp/node_modules/jest-jasmine2/build/queueRunner.js:43:12\n at new Promise (<anonymous>)\n at mapper (/Users/mmclain/Source/FRMSGitLab/ecom-abiliti-ui/src/AbilitiUI/ClientApp/node_modules/jest-jasmine2/build/queueRunner.js:26:19)\n at /Users/mmclain/Source/FRMSGitLab/ecom-abiliti-ui/src/AbilitiUI/ClientApp/node_modules/jest-jasmine2/build/queueRunner.js:73:41\n at processTicksAndRejections (internal/process/task_queues.js:97:5)\n"], "logLines": 3}
2020-11-12 14:21:35,237 - analyzerApp.esclient - INFO - ES Url http://elasticsearch-master.reportportal-prod.svc.local.cluster:9200
2020-11-12 14:21:41,347 - analyzerApp.esclient - ERROR - Error in bulk
2020-11-12 14:21:41,348 - analyzerApp.esclient - ERROR - ES Url http://elasticsearch-master.reportportal-prod.svc.local.cluster:9200
2020-11-12 14:21:41,348 - analyzerApp.esclient - ERROR - ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f8f78654cd0>: Failed to establish a new connection: [Errno -2] Name or service not known) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f8f78654cd0>: Failed to establish a new connection: [Errno -2] Name or service not known)
2020-11-12 14:21:41,349 - analyzerApp.esclient - DEBUG - Delete merged logs for 1 test items
2020-11-12 14:22:31,862 - analyzerApp.esclient - ERROR - Error in bulk
2020-11-12 14:22:31,863 - analyzerApp.esclient - ERROR - ES Url http://elasticsearch-master.reportportal-prod.svc.local.cluster:9200
2020-11-12 14:22:31,863 - analyzerApp.esclient - ERROR - ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f8f78751ad0>: Failed to establish a new connection: [Errno -2] Name or service not known) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f8f78751ad0>: Failed to establish a new connection: [Errno -2] Name or service not known)
2020-11-12 14:22:31,864 - analyzerApp.esclient - DEBUG - Delete merged logs for 1 test items
2020-11-12 14:22:32,311 - analyzerApp.esclient - ERROR - Index 273 was not found
2020-11-12 14:22:32,312 - analyzerApp.esclient - ERROR - ES Url http://elasticsearch-master.reportportal-prod.svc.local.cluster:9200
2020-11-12 14:22:32,312 - analyzerApp.esclient - ERROR - ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f8f7c858810>: Failed to establish a new connection: [Errno -2] Name or service not known) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f8f7c858810>: Failed to establish a new connection: [Errno -2] Name or service not known)
2020-11-12 14:22:32,313 - analyzerApp.amqpHandler - DEBUG - Finished processing <Basic.Deliver(['consumer_tag=ctag1.b400a37c4f004923aac97bcdc02eb37d', 'delivery_tag=23', 'exchange=analyzer-default', 'redelivered=False', 'routing_key=search'])> method

Eventually i get this on the UI, however when i update the defect type and click save, it doesnt do anything. The layer goes away but the defect is still to investigate.
![image](https://user-images.githubusercontent.com/36093419/98951934-de813180-24c8-11eb-9bef-b17b21e2aa6a.png)

**Comment by irynakozak2** [comment]
@staind825 hello, thank you for sharing logs. Correlating these logs with the issue, it looks like your service-analyzer cannot connect to the elastic search, and as a result, unload similar items. Please check that all services are working correctly and do not restart, then check that your analyzer service establishes the connection to the ElasticSearch successfully.

**Comment by staind825** [comment]
@irynakozak2 Thanks for the help. This was indeed our problem. There was a miss-type in the url pointing to elastic search. Got that hooked up and we are good to go.
