### ISSUE TITLE
Unable to login with password which contain symbol `

### ISSUE THREAD

**Issue by atyrin** [reportportal/reportportal#121]
After upgrade to version 3.0.1 on logon with password which contain symbol ` (grave accent), receive 400 error on UI side.

In docker Gateway service logs see:

```
gateway_1   | 2017-05-02 12:17:20.794  INFO 8 --- [nio-8080-exec-8] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
gateway_1   |  Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
gateway_1   |
gateway_1   | java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
gateway_1   |   at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:471) ~[tomcat-embed-core-8.5.11.jar!/:8.5.11]
gateway_1   |   at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:667) ~[tomcat-embed-core-8.5.11.jar!/:8.5.11]
gateway_1   |   at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
gateway_1   |   at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
gateway_1   |   at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
gateway_1   |   at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
gateway_1   |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
gateway_1   |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
gateway_1   |   at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
gateway_1   |   at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
```

**Comment by avarabyeu** [comment]
@lexecon  Seems like UI does not escape special symbols. Could you please have a look?
