### ISSUE TITLE
[v5] ReportPortalExceptionResolver > Launch 'null' not found. Did you use correct Launch ID?

### ISSUE THREAD

**Issue by Ngaur** [reportportal/reportportal#1239]
**Describe the bug**
Reportportal is deployed via kubernetes v5 chart.
We are using multiple integrations to this server -- python-client, soapUI client, and java client.
And suddenly all the integrations are breaking, without any change since yesterday.

NEED HELP ASAP!

**SoapUI-agent error**
(Thread.java:830)
Caused by: com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 500
Status message: 
Error Message: Unclassified error [org.hibernate.exception.GenericJDBCException: could not execute statement]
Error Type: null

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:57)
	at com.epam.reportportal.restendpoint.http.DefaultErrorHandler.handle(DefaultErrorHandler.java:56)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.call(HttpClientRestEndpoint.java:486)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.call(HttpClientRestEndpoint.java:455)
	at io.reactivex.internal.operators.maybe.Mayb11:12:50,668 DEBUG [HttpClientSupport$SoapUIHttpClient] Stale connection check
eFromCallable.subscribeActual(MaybeFromCallable.java:46)
	... 12 more

** python-client **
```
2020-12-03 04:29:30.499 ERROR 7 --- [o-8585-exec-206] .t.r.c.e.r.ReportPortalExceptionResolver : ReportPortalExceptionResolver > Launch 'null' not found. Did you use correct Launch ID?

com.epam.ta.reportportal.exception.ReportPortalException: Launch 'null' not found. Did you use correct Launch ID?
at com.epam.ta.reportportal.core.log.impl.CreateLogHandlerImpl.lambda$createLog$0(CreateLogHandlerImpl.java:95)
at java.base/java.util.Optional.orElseThrow(Unknown Source)
at com.epam.ta.reportportal.core.log.impl.CreateLogHandlerImpl.createLog(CreateLogHandlerImpl.java:95)
at com.epam.ta.reportportal.core.log.impl.CreateLogHandlerImpl$$FastClassBySpringCGLIB$$1c35ca0e.invoke()
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
at com.epam.ta.reportportal.core.log.impl.CreateLogHandlerImpl$$EnhancerBySpringCGLIB$$8d2302d5.createLog()
at com.epam.ta.reportportal.ws.controller.LogController.createLog(LogController.java:101)
at com.epam.ta.reportportal.ws.controller.LogController$$FastClassBySpringCGLIB$$f7673969.invoke()
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
at com.epam.ta.reportportal.ws.controller.LogController$$EnhancerBySpringCGLIB$$1da3b675.createLog()
at jdk.internal.reflect.GeneratedMethodAccessor940.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)

```
** Also this one **
```
2020-12-03 04:58:55.731 DEBUG 7 --- [TaskExecutor-87] c.e.t.r.w.rabbit.AsyncReportingListener : exception : com.epam.ta.reportportal.exception.ReportPortalException, message : Test Item '7f996775-5bfa-4aa1-89e1-ce0630b79077' not found. Did you use correct Test Item ID?, cause :
2020-12-03 04:58:55.731 WARN 7 --- [TaskExecutor-87] s.a.r.l.ConditionalRejectingErrorHandler : Execution of Rabbit message listener failed.

org.springframework.amqp.rabbit.support.ListenerExecutionFailedException: Listener threw exception
at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.wrapToListenerExecutionFailedExceptionIfNeeded(AbstractMessageListenerContainer.java:1693)
at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1639)
at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1509)
at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1486)
at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1477)
at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1421)
at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:963)
at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:913)
at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:81)
at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1284)
at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1190)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.springframework.amqp.AmqpRejectAndDontRequeueException: null
at com.epam.ta.reportportal.ws.rabbit.AsyncReportingListener.onMessage(AsyncReportingListener.java:177)
at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1635)
... 10 common frames omitted
Caused by: com.epam.ta.reportportal.exception.ReportPortalException: Test Item '7f996775-5bfa-4aa1-89e1-ce0630b79077' not found. Did you use correct Test Item ID?
at com.epam.ta.reportportal.core.item.impl.FinishTestItemHandlerImpl.lambda$finishTestItem$0(FinishTestItemHandlerImpl.java:142)
at java.base/java.util.Optional.orElseThrow(Unknown Source)
at com.epam.ta.reportportal.core.item.impl.FinishTestItemHandlerImpl.finishTestItem(FinishTestItemHandlerImpl.java:142)
at com.epam.ta.reportportal.core.item.impl.FinishTestItemHandlerImpl$$FastClassBySpringCGLIB$$a8a02107.invoke()
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
at com.epam.ta.reportportal.core.item.impl.FinishTestItemHandlerImpl$$EnhancerBySpringCGLIB$$96cfab60.finishTestItem()
at com.epam.ta.reportportal.ws.rabbit.AsyncReportingListener.onFinishItem(AsyncReportingListener.java:204)
at com.epam.ta.reportportal.ws.rabbit.AsyncReportingListener.onMessage(AsyncReportingListener.java:146)
... 11 common frames omitted
```

**Comment by Richard1ybb** [comment]
I have the same error:
`2020-12-09 02:59:38.229 ERROR 6 --- [io-8585-exec-16] .t.r.c.e.r.ReportPortalExceptionResolver : ReportPortalExceptionResolver > Launch '4469584a-0f23-476c-ac4d-06d200da8ad8' not found. Did you use correct Launch ID?

com.epam.ta.reportportal.exception.ReportPortalException: Launch '4469584a-0f23-476c-ac4d-06d200da8ad8' not found. Did you use correct Launch ID?
	at com.epam.ta.reportportal.core.launch.impl.FinishLaunchHandlerImpl.lambda$finishLaunch$0(FinishLaunchHandlerImpl.java:78)
	at java.base/java.util.Optional.orElseThrow(Unknown Source)
	at com.epam.ta.reportportal.core.launch.impl.FinishLaunchHandlerImpl.finishLaunch(FinishLaunchHandlerImpl.java:78)
	at com.epam.ta.reportportal.core.launch.impl.FinishLaunchHandlerImpl$$FastClassBySpringCGLIB$$ec54b939.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.epam.ta.reportportal.core.launch.impl.FinishLaunchHandlerImpl$$EnhancerBySpringCGLIB$$a212758a.finishLaunch(<generated>)
	at com.epam.ta.reportportal.ws.controller.LaunchController.finishLaunch(LaunchController.java:120)
	at com.epam.ta.reportportal.ws.controller.LaunchController$$FastClassBySpringCGLIB$$702dfa6.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.epam.ta.reportportal.ws.controller.LaunchController$$EnhancerBySpringCGLIB$$cbf9a97b.finishLaunch(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)`

**Comment by ersuniljoshi** [comment]
Worksournd this problem to move start launch and start test as a sync call. if you are using v2 API, they all are async.

**Comment by vrajasg** [comment]
Hello guys,
am having similar issue, anything I mis-configured? for instance, please refer to screenshot for configurations.
Note: Facing same issue for default or custom launches. 

> pom.xml: agent-java-cucumber6 with 5.0.1 version

![Screenshot 2020-12-29 at 13 06 48](https://user-images.githubusercontent.com/10340041/103286149-b0ec3b00-49d7-11eb-91b0-6e436d3b8dd0.png)

**Comment by priyankachaturvedi30** [comment]
@evjlobanova : Facing a similar issue, but I notice scenario this only in case where my rerun = true.  
![image](https://user-images.githubusercontent.com/50797731/115719105-67b26380-a399-11eb-833c-b3571416f0b7.png)

@DzmitryHumianiuk Re-run functionality really need to be verified for 5.3.5 version. That's the 3rd issue I observed around re-run lately. #1358 #1356

**Comment by DzmitryHumianiuk** [comment]
@priyankachaturvedi30 Re-run fix is on the way for 5.4

**Comment by MaryiaRymarchyk** [comment]
Hello @priyankachaturvedi30 , @vrajasg,
could you please check if the issue still reproduced  with latest version of RP?

**Comment by MaryiaRymarchyk** [comment]
Hello @priyankachaturvedi30 , @vrajasg,
as we haven't received a reply from you, we'll close the issue for now.
If  the issue still relevant, just get in touch.
