### ISSUE TITLE
[v5] [20] ReportPortal execution error

### ISSUE THREAD

**Issue by volodyatrots** [reportportal/reportportal#1248]
**Describe the bug**
 It works fine on local machine and I am able to open reportportal UI on remote machine but when I am running it from jenkins then we are getting this:
[rp-io-1] ERROR com.epam.reportportal.service.Launch - [20] ReportPortal execution error

**More Details**
`rp.org.apache.http.conn.HttpHostConnectException: Connect to cr-reportportal.1129.aws.test.com:443 [cr-reportportal.1129.aws.test.com/54.161.228.46, cr-reportportal.1129.aws.test.com/34.201.89.164, cr-reportportal.1129.aws.test.com/54.86.204.241] failed: Connection timed out: connect
	at rp.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
	at rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
	at rp.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at rp.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at rp.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at rp.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at rp.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at rp.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:502)
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at rp.org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:348)
	at rp.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 20 more`

**Expected behavior**
should display the launch in report portal

**Comment by volodyatrots** [comment]
I found how to properly set proxy so now it's resolved (rp.http.proxy=your.service:80)
