### ISSUE TITLE
ReportPortal Exсeption status 406

### ISSUE THREAD

**Issue by ivanovstepan** [reportportal/reportportal#126]
![image](https://cloud.githubusercontent.com/assets/11019580/25941483/5d55efba-3642-11e7-9424-07b2e6774e86.png)

**Comment by dkorobtsov** [comment]
Btw, getting 406 error as well. Feels like pretty common problem - it happens absolutely at random on practically every 3rd execution:
Stack trace is in attach.
![rp_406](https://cloud.githubusercontent.com/assets/13999072/26026816/4c616930-380b-11e7-813b-0e27a6d1336b.png)

**Comment by avarabyeu** [comment]
@dkorobtsov Could you please specify the following info:
1) client version
2) how do you add listener
3) how do you start the tests
4) how many threads is used for parallel execution (and what actually is executed in parallel - methods, classes, suites, etc)
Thanks!

**Comment by dkorobtsov** [comment]
@avarabyeu 

<groupId>com.epam.reportportal</groupId>
<artifactId>agent-java-testng</artifactId>
<version>2.7.0</version>

<groupId>com.epam.reportportal</groupId>
<artifactId>logger-java-log4j</artifactId>
<version>2.6.1</version>

listener added in testng.xml:
        <listener class-name="com.epam.reportportal.testng.ReportPortalTestNGListener"/>

issue reproduces when tests are started from IDE (IntelliJ)

single thread, tests run on 1 Android device.

Basically, it's just a Sandbox environment, playing  :)

Btw, it seems I've figured out what is the problem.
Basically, I have parameterized UI tests, @BeforeClass section validates page - if all elements are present on page. In that case all tests are executed, otherwise SkipException is thrown. It seems that after receiving SkipException from BeforeClass method RP never finishes the test. It worked just fine with native testng reports, but looks like it's not supported scenario on RP :)

    @BeforeClass(alwaysRun = true)
    public void beforeClass() {
        super.beforeClass();
        if (!validator.validatePage(home)) {
            throw new SkipException(home.getName() + "UI status check failed, skipping requirements validation.");
        }
    }

**Comment by daroshchanka** [comment]
Hi! Very often this error makes our builds failed.

![image](https://cloud.githubusercontent.com/assets/28945630/26440403/d1846806-4134-11e7-9bb3-bb8b9d2b4dc8.png)

We use
```
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.9.13.6</version>
        </dependency>
	<dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-testng</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-log4j</artifactId>
            <version>3.0.0</version>
        </dependency>
```
Listener defined in _maven-surefire-plugin(2.17)_
Tests executed in parallel (3 threads).
I found 19 same errors in my logs for one launch (3-hours)

See stacktrace

```
май 24, 2017 11:39:03 PM com.epam.reportportal.service.LoggingCallback$2 accept
SEVERE: ReportPortal execution error
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 406
Status message: 
Error Message: Finish test item is not allowed. 
Error Type: FINISH_ITEM_NOT_ALLOWED

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:62)
	at com.epam.restendpoint.http.DefaultErrorHandler.handle(DefaultErrorHandler.java:56)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:547)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:518)
	at rp.org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
	at rp.org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
	at rp.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
	at rp.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
	at rp.org.apache.http.impl.nio.client.InternalRequestExecutor.inputReady(InternalRequestExecutor.java:83)
	at rp.org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at rp.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at rp.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at rp.org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at rp.org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at rp.org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at rp.org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Unknown Source)

io.reactivex.exceptions.OnErrorNotImplementedException: Report Portal returned error
Status code: 406
Status message: 
Error Message: Finish test item is not allowed. 
Error Type: FINISH_ITEM_NOT_ALLOWED

	at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:50)
	at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onError(CompletableSubscribeOn.java:74)
	at io.reactivex.internal.operators.completable.CompletableCache.onError(CompletableCache.java:81)
	at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.onError(CompletableConcatArray.java:60)
	at io.reactivex.internal.operators.maybe.MaybeIgnoreElementCompletable$IgnoreMaybeObserver.onError(MaybeIgnoreElementCompletable.java:73)
	at io.reactivex.internal.operators.maybe.MaybeDoAfterSuccess$DoAfterObserver.onError(MaybeDoAfterSuccess.java:81)
	at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver$InnerObserver.onError(MaybeFlatten.java:125)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onErrorInner(MaybePeek.java:147)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onError(MaybePeek.java:134)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onErrorInner(MaybePeek.java:147)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onError(MaybePeek.java:134)
	at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver.onError(MaybeFlatten.java:103)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeOnMaybeObserver.onError(MaybeSubscribeOn.java:96)
	at io.reactivex.internal.operators.maybe.MaybeCache.onError(MaybeCache.java:103)
	at io.reactivex.internal.operators.maybe.MaybeCreate$Emitter.onError(MaybeCreate.java:94)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:569)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:518)
	at rp.org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
	at rp.org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
	at rp.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
	at rp.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
	at rp.org.apache.http.impl.nio.client.InternalRequestExecutor.inputReady(InternalRequestExecutor.java:83)
	at rp.org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at rp.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at rp.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at rp.org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at rp.org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at rp.org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at rp.org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 406
Status message: 
Error Message: Finish test item is not allowed. 
Error Type: FINISH_ITEM_NOT_ALLOWED

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:62)
	at com.epam.restendpoint.http.DefaultErrorHandler.handle(DefaultErrorHandler.java:56)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:547)
	... 17 more
Exception in thread "I/O dispatcher 1" io.reactivex.exceptions.OnErrorNotImplementedException: Report Portal returned error
Status code: 406
Status message: 
Error Message: Finish test item is not allowed. 
Error Type: FINISH_ITEM_NOT_ALLOWED

	at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:50)
	at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onError(CompletableSubscribeOn.java:74)
	at io.reactivex.internal.operators.completable.CompletableCache.onError(CompletableCache.java:81)
	at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.onError(CompletableConcatArray.java:60)
	at io.reactivex.internal.operators.maybe.MaybeIgnoreElementCompletable$IgnoreMaybeObserver.onError(MaybeIgnoreElementCompletable.java:73)
	at io.reactivex.internal.operators.maybe.MaybeDoAfterSuccess$DoAfterObserver.onError(MaybeDoAfterSuccess.java:81)
	at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver$InnerObserver.onError(MaybeFlatten.java:125)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onErrorInner(MaybePeek.java:147)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onError(MaybePeek.java:134)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onErrorInner(MaybePeek.java:147)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onError(MaybePeek.java:134)
	at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver.onError(MaybeFlatten.java:103)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeOnMaybeObserver.onError(MaybeSubscribeOn.java:96)
	at io.reactivex.internal.operators.maybe.MaybeCache.onError(MaybeCache.java:103)
	at io.reactivex.internal.operators.maybe.MaybeCreate$Emitter.onError(MaybeCreate.java:94)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:569)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:518)
	at rp.org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
	at rp.org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
	at rp.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
	at rp.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
	at rp.org.apache.http.impl.nio.client.InternalRequestExecutor.inputReady(InternalRequestExecutor.java:83)
	at rp.org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at rp.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at rp.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at rp.org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at rp.org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at rp.org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at rp.org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 406
Status message: 
Error Message: Finish test item is not allowed. 
Error Type: FINISH_ITEM_NOT_ALLOWED

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:62)
	at com.epam.restendpoint.http.DefaultErrorHandler.handle(DefaultErrorHandler.java:56)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:547)
	... 17 more
```

**Comment by dkorobtsov** [comment]
Btw, it feels like this error randomly appears when any exception is thrown inside BeforeClass method.

**Comment by avarabyeu** [comment]
@dkorobtsov could you please update your client: testng 3.0.2, log4j 3.0.1. Update should fix the issue, but i assume you added several listeners somewhere. For example, one in pom.xml and another in testng.xml

**Comment by dkorobtsov** [comment]
@avarabyeu thanks! updated, will observe the behavior...

**Comment by avarabyeu** [comment]
@dkorobtsov are you still able to reproduce issue?

**Comment by dkorobtsov** [comment]
@avarabyeu nope, does not reproduce with latest version

**Comment by DzmitryHumianiuk** [comment]
@dkorobtsov @ivanovstepan @avarabyeu can be closed?
