### ISSUE TITLE
Intermittently some Tests/Suites launches are not getting pushed to RP

### ISSUE THREAD

**Issue by VenkatVanacharlaTR** [reportportal/reportportal#1291]
I observed that some of the tests/suite launches are not getting posted to RP and when I checked the logs related to missing test/suite I can see the error logs related RP as below

This issue occurs intermittently and even after re-running the particular tests also not updated to existing launch.

Report Portal Logs:

[rp-io-8] DEBUG- io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
   [testng] 04:00:07.319 [rp-io-8] DEBUG- 	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
   [testng] 04:00:07.319 [rp-io-8] DEBUG- 	at io.reactivex.internal.operators.maybe.MaybeCreate$Emitter.onError(MaybeCreate.java:87)
   [testng] [rp-io-3] ERROR com.epam.reportportal.service.Launch - [18] ReportPortal execution error
   [testng] javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
   [testng] 	at sun.security.ssl.SSLSocketImpl.handleEOF(Unknown Source)
   [testng] 	at sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
   [testng] 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
   [testng] 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
   [testng] 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
   [testng] 	at rp.org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:404)
   [testng] 	at rp.org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:364)
   [testng] 	at rp.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
   [testng] 	at rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
   [testng] 	at rp.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
   [testng] 	at rp.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
   [testng] 	at rp.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
   [testng] 	at rp.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
   [testng] 	at rp.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
   [testng] 	at rp.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
   [testng] 	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
   [testng] 	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
   [testng] 	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
   [testng] 	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:502)
   [testng] 	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
   [testng] 	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
   [testng] 	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
   [testng] 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
   [testng] 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
   [testng] 	at java.util.concurrent.FutureTask.run(Unknown Source)
   [testng] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   [testng] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   [testng] 	at java.lang.Thread.run(Unknown Source)
   [testng] Caused by: java.io.EOFException: SSL peer shut down incorrectly
   [testng] 	at sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
   [testng] 	at sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
   [testng] 	at sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source)
   [testng] 	at sun.security.ssl.SSLTransport.decode(Unknown Source)
   [testng] 	... 27 more
   [testng] 
   [testng] 
   [testng] [rp-io-3] ERROR com.epam.reportportal.utils.SubscriptionUtils - Logging context completed with error 
   [testng] javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
   [testng] 	at sun.security.ssl.SSLSocketImpl.handleEOF(Unknown Source)
   [testng] 	at sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
   [testng] 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
   [testng] 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
   [testng] 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
   [testng] 	at rp.org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:404)
   [testng] 	at rp.org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:364)
   [testng] 	at rp.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
   [testng] 	at rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
   [testng] 	at rp.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
   [testng] 	at rp.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
   [testng] 	at rp.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
   [testng] 	at rp.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
   [testng] 	at rp.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
   [testng] 	at rp.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
   [testng] 	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
   [testng] 	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
   [testng] 	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
   [testng] 	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:502)
   [testng] 	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
   [testng] 	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
   [testng] 	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
   [testng] 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
   [testng] 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
   [testng] 	at java.util.concurrent.FutureTask.run(Unknown Source)
   [testng] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   [testng] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   [testng] 	at java.lang.Thread.run(Unknown Source)
   [testng] Caused by: java.io.EOFException: SSL peer shut down incorrectly
   [testng] 	at sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
   [testng] 	at sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
   [testng] 	at sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source)
   [testng] 	at sun.security.ssl.SSLTransport.decode(Unknown Source)
   [testng] 	... 27 more
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 04:00:07.412 [rp-io-8] DEBUG- 	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:547)
   [testng] 04:00:07.412 [rp-io-8] DEBUG- 	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
   [testng] 04:00:07.412 [rp-io-8] DEBUG- 	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
   [testng] 04:00:07.412 [rp-io-8] DEBUG- 	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
   [testng] 04:00:07.412 [rp-io-8] DEBUG- 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
   [testng] 04:00:07.412 [rp-io-8] DEBUG- 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
   [testng] 04:00:07.412 [rp-io-8] DEBUG- 	at java.util.concurrent.FutureTask.run(Unknown Source)
   [testng] 04:00:07.412 [rp-io-8] DEBUG- 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   [testng] 04:00:07.412 [rp-io-8] DEBUG- 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   [testng] 04:00:07.412 [rp-io-8] DEBUG- 	at java.lang.Thread.run(Unknown Source)
   [testng] 04:00:07.412 [rp-io-8] DEBUG- Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
   [testng] 04:00:07.412 [rp-io-8] DEBUG- 	at sun.security.ssl.SSLSocketImpl.handleEOF(Unknown Source)
   [testng] 04:00:07.412 [rp-io-8] DEBUG- 	at sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
   [testng] 04:00:07.412 [rp-io-8] DEBUG- 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
   [testng] 04:00:07.412 [rp-io-8] DEBUG- 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
   [testng] 04:00:07.412 [rp-io-8] DEBUG- 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
   [testng] 04:00:07.412 [rp-io-8] DEBUG- 	at rp.org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:404)
   [testng] 04:00:07.412 [rp-io-8] DEBUG- 	at rp.org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:364)
   [testng] 04:00:07.428 [rp-io-8] DEBUG- 	at rp.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
   [testng] 04:00:07.428 [rp-io-8] DEBUG- 	at rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
   [testng] 04:00:07.428 [rp-io-8] DEBUG- 	at rp.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
   [testng] 04:00:07.428 [rp-io-8] DEBUG- 	at rp.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
   [testng] 04:00:07.428 [rp-io-8] DEBUG- 	at rp.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
   [testng] 04:00:07.428 [rp-io-8] DEBUG- 	at rp.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
   [testng] 04:00:07.428 [rp-io-8] DEBUG- 	at rp.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
   [testng] 04:00:07.428 [rp-io-8] DEBUG- 	at rp.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
   [testng] 04:00:07.428 [rp-io-8] DEBUG- 	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
   [testng] 04:00:07.428 [rp-io-8] DEBUG- 	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
   [testng] 04:00:07.428 [rp-io-8] DEBUG- 	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
   [testng] 04:00:07.428 [rp-io-8] DEBUG- 	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:502)
   [testng] 04:00:07.428 [rp-io-8] DEBUG- 	... 9 more
   [testng] 04:00:07.428 [rp-io-8] DEBUG- Caused by: java.io.EOFException: SSL peer shut down incorrectly
   [testng] 04:00:07.428 [rp-io-8] DEBUG- 	at sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
   [testng] 04:00:07.428 [rp-io-8] DEBUG- 	at sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
   [testng] 04:00:07.428 [rp-io-8] DEBUG- 	at sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source)
   [testng] 04:00:07.428 [rp-io-8] DEBUG- 	at sun.security.ssl.SSLTransport.decode(Unknown Source)
   [testng] 04:00:07.428 [rp-io-8] DEBUG- 	... 27 more
   [testng] 04:00:07.428 [rp-io-8] DEBUG- Exception in thread "rp-io-8" 
   [testng] 04:00:07.428 [rp-io-8] DEBUG- io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at io.reactivex.internal.operators.maybe.MaybeCreate$Emitter.onError(MaybeCreate.java:87)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:547)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at java.util.concurrent.FutureTask.run(Unknown Source)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at java.lang.Thread.run(Unknown Source)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at sun.security.ssl.SSLSocketImpl.handleEOF(Unknown Source)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at rp.org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:404)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at rp.org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:364)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at rp.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at rp.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at rp.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at rp.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at rp.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at rp.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at rp.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:502)
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	... 9 more
   [testng] 04:00:07.522 [rp-io-8] DEBUG- Caused by: java.io.EOFException: SSL peer shut down incorrectly
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	at sun.security.ssl.SSLTransport.decode(Unknown Source)
   [testng] 04:00:07.522 [rp-io-8] DEBUG- 	... 27 more

**Comment by HardNorth** [comment]
@VenkatVanacharlaTR 
Please specify the following things:
1. Report Portal version
2. Agent version
3. How did you install RP (docker or kubernetes)

**Comment by VenkatVanacharlaTR** [comment]
> 1. Report Portal version -- 5.3.3
> 2. Agent version -- agent-java-testng-5.0.6-TESTNG6
> 3. How did you install RP (docker or kubernetes) -- using docker
