### ISSUE TITLE
[v5]Rerun - Scenario’s with the same name instead of merging with an existing test item is creating a new test item in our launch

### ISSUE THREAD

**Issue by ReddyNitheeesh** [reportportal/reportportal#1317]
**Describe the bug**
Scenario’s with the same name instead of merging with an existing test item is creating a new test item in our launch

**To Reproduce**
It is reproducible on every run, we are facing this issue on 1 out of 5 times
Project Config: Java+ Cucumber
**Maven dependencies used:**
<dependency>
    <groupId>com.epam.reportportal</groupId>
    <artifactId>agent-java-cucumber</artifactId>
    <version>5.0.1</version>
</dependency>

<dependency>
    <groupId>com.epam.reportportal</groupId>
    <artifactId>client-java</artifactId>
    <version>5.0.15</version>
</dependency>

<dependency>
    <groupId>com.epam.reportportal</groupId>
    <artifactId>logger-java-logback</artifactId>
    <version>5.0.2</version>
</dependency>

**Expected behavior**
Scenario’s with the same name must merge with existing test item in the launch for Rerun

**Screenshots**

![image](https://user-images.githubusercontent.com/28997011/108511794-63f55880-72e6-11eb-9dad-60914997361d.png)
![image](https://user-images.githubusercontent.com/28997011/108511930-90a97000-72e6-11eb-9f6e-db0ed4a6c191.png)
![image](https://user-images.githubusercontent.com/28997011/108512134-cb130d00-72e6-11eb-9381-758d83f88bb5.png)

**Desktop (please complete the following information):**
Report Portal Version 5.3.3

Error Console:

2021-02-18 09:29:23,327 [rp-io-92] ERROR com.epam.reportportal.service.Launch - [184] ReportPortal execution error
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 406
Status message: Not Acceptable
Error Message: Finish launch is not allowed. Launch '585806' already finished with status 'FAILED'
Error Type: FINISH_LAUNCH_NOT_ALLOWED

        at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:85) ~[client-java-5.0.15.jar:na]
        at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:61) ~[client-java-5.0.15.jar:na]
        at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:526) ~[client-java-5.0.15.jar:na]
        at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45) ~[rxjava-2.2.10.jar:na]
        at io.reactivex.Maybe.subscribe(Maybe.java:4290) ~[rxjava-2.2.10.jar:na]
        at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54) ~[rxjava-2.2.10.jar:na]
        at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38) ~[rxjava-2.2.10.jar:na]
        at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26) ~[rxjava-2.2.10.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_272]

2021-02-18 09:29:23,328 [pool-1-thread-1] ERROR com.epam.reportportal.service.Launch - Unable to finish launch in ReportPortal
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 406
Status message: Not Acceptable
Error Message: Finish launch is not allowed. Launch '585806' already finished with status 'FAILED'
Error Type: FINISH_LAUNCH_NOT_ALLOWED

        at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:85) ~[client-java-5.0.15.jar:na]
        at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:61) ~[client-java-5.0.15.jar:na]
        at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:526) ~[client-java-5.0.15.jar:na]
        at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45) ~[rxjava-2.2.10.jar:na]
        at io.reactivex.Maybe.subscribe(Maybe.java:4290) ~[rxjava-2.2.10.jar:na]
        at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54) ~[rxjava-2.2.10.jar:na]
        at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38) ~[rxjava-2.2.10.jar:na]
        at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26) ~[rxjava-2.2.10.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_272]

**Additional context**
In addition for few test items we see screenshots, logs are missing missing
![image](https://user-images.githubusercontent.com/28997011/108512546-63a98d00-72e7-11eb-99a4-7d0df1bb3700.png)

**Comment by sspieker-cc** [comment]
We too are facing this same behavior.  The total number of tests are being inflated due to the re-run of a failed test and so the analytics are being skewed due to this incorrect reporting.

Is there a change that is needed in the XML or is this issue actually a valid defect?

**Comment by HardNorth** [comment]
@ReddyNitheeesh Unfortunately your screenshots too small for me to distinguish anything. Can you attach them in better resolution?

Also I need to know: 
1. Test Case IDs for both of not merged tests. You can find them if you click edit on a test on test case list view.
2. How you perform re-runs? Can you provide StartLaunchRQ you send on RP? You can capture it with the latest versions of postman.
3. It would be nice to have StartTestItemRQs for both of test items which weren't merged.

**Comment by ReddyNitheeesh** [comment]
Hi Please find attachments below

![image](https://user-images.githubusercontent.com/28997011/108986929-b5bc2b00-76b8-11eb-93f6-f8dc67a99a0d.png)
![image](https://user-images.githubusercontent.com/28997011/108987017-cff60900-76b8-11eb-92ae-bfbd33eef38d.png)
![image](https://user-images.githubusercontent.com/28997011/108987168-fa47c680-76b8-11eb-9a94-c4934290517d.png)

Test Details below for both cases:
Test 1:

[
  {
    "id": 26515900,
    "uuid": "a56ce3ea-af41-40c6-8081-53dab013f6e9",
    "name": "Scenario:",
    "codeRef": "com/thomsonreuters/fastdraft/features/users/fastDraftForPAUsers.feature:7",
    "description": "com/thomsonreuters/fastdraft/features/users/fastDraftForPAUsers.feature",
    "parameters": [],
    "attributes": [],
    "type": "STEP",
    "startTime": 1613639505761,
    "endTime": 1613639574502,
    "status": "FAILED",
    "statistics": {
      "executions": {
        "total": 1,
        "failed": 1
      },
      "defects": {
        "product_bug": {
          "total": 1,
          "pb_uvbcttccxkqe": 1
        }
      }
    },
    "parent": 26515899,
    "pathNames": {
      "launchPathName": {
        "name": "FastDraft Demo",
        "number": 110
      },
      "itemPaths": [
        {
          "id": 26514843,
          "name": "Root User Story"
        },
        {
          "id": 26515899,
          "name": "Feature: [780907] FD3 Testing FD PA Users"
        }
      ]
    },
    "issue": {
      "issueType": "pb_uvbcttccxkqe",
      "comment": "after rerun failed due to Bug 1433743: Errors are logged on console on navigating to documents from Standard documents and drafting notes",
      "autoAnalyzed": true,
      "ignoreAnalyzer": false,
      "externalSystemIssues": []
    },
    "hasChildren": false,
    "hasStats": true,
    "launchId": 585806,
    "uniqueId": "auto:3e1ef25c10aee9b8e5166c4f66f31250",
    "testCaseId": "com/thomsonreuters/fastdraft/features/users/fastDraftForPAUsers.feature:7",
    "testCaseHash": 440177270,
    "patternTemplates": [],
    "path": "26514843.26515899.26515900"
  }
]
-------------------------------------------------------------------------------------------------------

Test 2:

[
  {
    "id": 26518647,
    "uuid": "7e585952-38dd-401c-b260-d66efa6ad11a",
    "name": "Scenario:",
    "codeRef": "com/thomsonreuters/fastdraft/features/users/fastDraftForPAUsers.feature:7",
    "description": "com/thomsonreuters/fastdraft/features/users/fastDraftForPAUsers.feature",
    "parameters": [],
    "attributes": [],
    "type": "STEP",
    "startTime": 1613640366047,
    "endTime": 1613640430433,
    "status": "FAILED",
    "statistics": {
      "executions": {
        "total": 1,
        "failed": 1
      },
      "defects": {
        "to_investigate": {
          "total": 1,
          "ti001": 1
        }
      }
    },
    "parent": 26515899,
    "pathNames": {
      "launchPathName": {
        "name": "FastDraft Demo",
        "number": 110
      },
      "itemPaths": [
        {
          "id": 26514843,
          "name": "Root User Story"
        },
        {
          "id": 26515899,
          "name": "Feature: [780907] FD3 Testing FD PA Users"
        }
      ]
    },
    "issue": {
      "issueType": "ti001",
      "autoAnalyzed": false,
      "ignoreAnalyzer": false,
      "externalSystemIssues": []
    },
    "hasChildren": false,
    "hasStats": true,
    "launchId": 585806,
    "uniqueId": "auto:3e1ef25c10aee9b8e5166c4f66f31250",
    "testCaseId": "com/thomsonreuters/fastdraft/features/users/fastDraftForPAUsers.feature:7",
    "testCaseHash": 440177270,
    "patternTemplates": [],
    "path": "26514843.26515899.26518647"
  }
]
------------------------------------------------------------------------------------------------


Parent Launch: (after rerun update)

{
  "rerun": true,
  "owner": "superadmin",
  "share": false,
  "description": "",
  "id": 585806,
  "uuid": "4d0a00eb-1d1f-4763-838f-2d2e9f95f040",
  "name": "FastDraft Demo",
  "number": 110,
  "startTime": 1613639151000,
  "endTime": 1613640258780,
  "lastModified": 1613640258848,
  "status": "FAILED",
  "statistics": {
    "executions": {
      "total": 18,
      "passed": 10,
      "failed": 8
    },
    "defects": {
      "product_bug": {
        "total": 4,
        "pb_uvbcttccxkqe": 4
      },
      "to_investigate": {
        "total": 4,
        "ti001": 4
      }
    }
  },
  "attributes": [
    {
      "key": "Product",
      "value": "PLUKR"
    },
    {
      "key": "Suite",
      "value": "Full"
    },
    {
      "key": "Owner",
      "value": "Nitheesh Gaddam"
    },
    {
      "key": "Host",
      "value": "Grid"
    },
    {
      "key": "Result",
      "value": "Obsolete"
    },
    {
      "key": "Month",
      "value": "Feb"
    },
    {
      "key": "Suite Name",
      "value": "FastDraft"
    },
    {
      "key": "Env",
      "value": "Demo"
    },
    {
      "key": "Day",
      "value": "18"
    },
    {
      "key": "Release",
      "value": "53.1"
    },
    {
      "key": "Trigger",
      "value": "Manual"
    }
  ],
  "mode": "DEFAULT",
  "analysing": [],
  "approximateDuration": 909.3858,
  "hasRetries": true
}

2. Rerun is performed in the below manner. we are using  (java + cucumber framework)
    > we have multiple runner files that create multiple items in the report portal, later we merge all items and create a single launch
  > then rerun = true it picks the latest launch and merges


Please let me know for additional details

**Comment by ReddyNitheeesh** [comment]
Hi Team,
can you please provide a look into this.

Thanks,
Nitheesh

**Comment by HardNorth** [comment]
@ReddyNitheeesh It's still not clear what causes the issue, so I have to guess. You didn't posted StartTestItemRQs as I asked.

**Comment by ReddyNitheeesh** [comment]
@HardNorth, It is not reproducible every time, so that's why I have posted entire test item details before rerun and after rerun. If still required I can spend some time and provide details. But I don't think it would be helpful as it is not reproducible every time

**Comment by ReddyNitheeesh** [comment]
@HardNorth , Please find below basic StartTestItemRQ for both test's:
------------------------------------
Test 1:
-----------------------------------
codeRef: "com/thomsonreuters/fastdraft/features/users/fastDraftForPAUsers.feature:7"
description: "com/thomsonreuters/fastdraft/features/users/fastDraftForPAUsers.feature"
endTime: 1613639574502
hasChildren: false
hasStats: true
id: 26515900
launchId: 585806
name: "Scenario:"
parameters: []
parent: 26515899
path: "26514843.26515899.26515900
patternTemplates: []
startTime: 1613639505761

--------------------
Test 2:
-------------------------
attributes: []
codeRef: "com/thomsonreuters/fastdraft/features/users/fastDraftForPAUsers.feature:7"
description: "com/thomsonreuters/fastdraft/features/users/fastDraftForPAUsers.feature"
endTime: 1613640430433
hasChildren: false
hasStats: true
id: 26518647
launchId: 585806
name: "Scenario:"
parameters: []
parent: 26515899
path: "26514843.26515899.26518647"
patternTemplates: []
startTime: 1613640366047

----------------------------------------

As per my observation, here if you compare the below test items start time and end time I see before finishing the first test time, it started the second item due to this it is creating one more test item. I see an error in the report portal as finished launch issue, Please find logs and time stat's below.

Status code: 406
Status message: Not Acceptable
Error Message: Finish launch is not allowed. Launch '585806' already finished with status 'FAILED'
Error Type: FINISH_LAUNCH_NOT_ALLOWED

Test 1:
startTime: 1613639505761
End Time :1613639574502

Test 2:
startTime: 1613640366047
End Time: 1613640430433

Please let me know for additional details.

Thanks,
Nitheesh

**Comment by ReddyNitheeesh** [comment]
@rplevka ,

can you please look into this issue?

Thanks,
Nitheesh

**Comment by HardNorth** [comment]
@ReddyNitheeesh nothing to look at my side, since it's a server issue. Backend guys are aware of this, so we just need to wait.

**Comment by ReddyNitheeesh** [comment]
@HardNorth do you any info or ETA when this issue will be fixed

**Comment by sspieker-cc** [comment]
In my use case, I am importing the JUnit XML records using the API rather than the ReportPortal tooling specifically.  This approach has allowed our organization to have one centralized method to report results with a single tool.  I understand that the tooling does provide for retry-handling but the tooling is not as reliable with the variety of Runners and variations that our testing framework supports.

**Comment by evjlobanova** [comment]
Bug with rerun would be fixed in version 5.4.1.
±ETA end of the June

**Comment by rplevka** [comment]
@evjlobanova can you tell us what the bug is and what is the reproducer?
I'm curious because I'm not hitting it.

**Comment by sspieker-cc** [comment]
@rplevka - We experience this issue with our solution that uses the ZIP file import operations to load results.  The JUnit output XML does not have any designation as to rerun/retry operations for tests and therefore RP does not recognize them as the same test being re-run but as individual tests and cause the number of tests to be inflated by the number of retries attempted on tests that have failed.

If there are 20 tests in the suite and there is one retry on a single failed test, then RP reports a total of 21 tests in this launch.  If all tests run again and all pass in the first attempt, then only 20 tests are reported in this launch.  When aggregating the results, the total number of tests are skewed by one and this issue is only made worse with the number of retries attempted and the number of times that the suite is executed.

**Comment by rplevka** [comment]
@sspieker-cc thanks. So this looks like a bug (lack of feature) of the junit importer.

**Comment by ReddyNitheeesh** [comment]
@evjlobanova  is this issue fixed with the latest 5.5 RP release ??
