### ISSUE TITLE
service.start_launch(name="xxx",start_time=timestamp()) fail to connect reportprotal

### ISSUE THREAD

**Issue by geliu2016** [reportportal/reportportal#1376]
Hello, 

I try to excute start_launch api, but failed with err:

>>> service = ReportPortalService(endpoint="http://172.x.x.x:8080",project="default_personal",token="27e71acc-100b-4a2d-b77e-84xxxxxx")
>>> service.start_launch(name="lgtest",start_time=timestamp())
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/reportportal_client/service.py", line 67, in _get_json
    return response.json()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/reportportal_client/service.py", line 153, in start_launch
    self.launch_id = _get_id(r)
  File "/usr/local/lib/python3.6/site-packages/reportportal_client/service.py", line 32, in _get_id
    return _get_data(response)["id"]
  File "/usr/local/lib/python3.6/site-packages/reportportal_client/service.py", line 47, in _get_data
    data = _get_json(response)
  File "/usr/local/lib/python3.6/site-packages/reportportal_client/service.py", line 72, in _get_json
    "Invalid response: {0}: {1}".format(value_error, response.text))
reportportal_client.errors.ResponseError: Invalid response: Expecting value: line 1 column 1 (char 0): <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta http-equiv="Content-Type" CONTENT="text/html; charset=utf-8">
<title>ERROR: The requested URL could not be retrieved</title>
<style type="text/css"></style>
</head><body id=ERR_CONNECT_FAIL>
<div id="titles">
<h1>ERROR</h1>
<h2>The requested URL could not be retrieved</h2>
</div>
<hr>

<div id="content">
<p>The following error was encountered while trying to retrieve the URL: <a href="http://172.xx.0.1:8080/api/v1/default_personal/launch">http://172.x.0.1:8080/api/v1/default_personal/launch</a></p>

<blockquote id="error">
<p><b>Connection to 172.x.0.1 failed.</b></p>
</blockquote>

<p id="sysmsg">The system returned: <i>(110) Connection timed out</i></p>

<p>The remote host or network may be down. Please try the request again.</p>

<p>Your cache administrator is <a href="com</a>.</p>

<br>
</div>

<hr>
<div id="footer">
<p>Generated Thu, 22 Apr 2021 05:42:42 GMT by file01.intranet.prod.int.xx.xx.com (squid/3.1.23)</p>

</div>
</body></html>

**Comment by alena-babrova** [comment]
Hello @geliu2016,
Is the issue still relevant? Have you managed to resolve it?

**Comment by alena-babrova** [comment]
Dear @geliu2016,
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.
