### ISSUE TITLE
[v5] Connection timeout to google analytics.

### ISSUE THREAD

**Issue by mchundi** [reportportal/reportportal#1400]
I am using RP version 5.3.5 and I see the below error when the tests are running in jenkins.
```
15:23:06 [rp-io-1] INFO  rp.org.apache.http.impl.execchain.RetryExec  - I/O exception (java.net.SocketException) caught when processing request to {s}->https://www.google-analytics.com:443: Connection timed out (Read failed)
15:23:06   [rp-io-1] INFO  rp.org.apache.http.impl.execchain.RetryExec  - Retrying request to {s}->https://www.google-analytics.com:443
15:23:51   [rp-io-1] INFO  rp.org.apache.http.impl.execchain.RetryExec  - I/O exception (java.net.SocketException) caught when processing request to {s}->https://www.google-analytics.com:443: Socket closed
15:23:51   [rp-io-1] INFO  rp.org.apache.http.impl.execchain.RetryExec  - Retrying request to {s}->https://www.google-analytics.com:443
15:23:51   [ERROR] Unable to complete execution of all dependencies
15:23:51 io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.util.concurrent.RejectedExecutionException: Task io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker@2e6705e4 rejected from java.util.concurrent.ThreadPoolExecutor@32cb636e[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 467]
15:23:51 	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
15:23:51 	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.schedule(ExecutorScheduler.java:175)
15:23:51 	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.trySchedule(FlowableObserveOn.java:166)
15:23:51 	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.onError(FlowableObserveOn.java:128)
15:23:51 	at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onError(FlowableDoOnEach.java:111)
15:23:51 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.checkTerminate(FlowableFlatMap.java:567)
15:23:51 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:374)
15:23:51 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:366)
15:23:51 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onError(FlowableFlatMap.java:325)
15:23:51 	at io.reactivex.internal.operators.flowable.FlowableBuffer$PublisherBufferExactSubscriber.onError(FlowableBuffer.java:139)
15:23:51 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.checkTerminate(FlowableFlatMap.java:567)
15:23:51 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:374)
15:23:51 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:366)
15:23:51 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.innerError(FlowableFlatMap.java:606)
15:23:51 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onError(FlowableFlatMap.java:672)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybeToFlowable$MaybeToFlowableSubscriber.onError(MaybeToFlowable.java:75)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybeZipArray$ZipCoordinator.innerError(MaybeZipArray.java:136)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybeZipArray$ZipMaybeObserver.onError(MaybeZipArray.java:181)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybeCache.onError(MaybeCache.java:103)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver$InnerObserver.onError(MaybeFlatten.java:124)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver.onError(MaybeFlatten.java:102)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybeCache.onError(MaybeCache.java:103)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver$InnerObserver.onError(MaybeFlatten.java:124)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver.onError(MaybeFlatten.java:102)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybeCache.onError(MaybeCache.java:103)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver.onSuccess(MaybeFlatten.java:91)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybeCache.onSuccess(MaybeCache.java:92)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybeCreate$Emitter.onSuccess(MaybeCreate.java:73)
15:23:51 	at com.epam.reportportal.service.LaunchImpl.lambda$null$4(LaunchImpl.java:131)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybeCallbackObserver.onSuccess(MaybeCallbackObserver.java:71)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybeCache.onSuccess(MaybeCache.java:92)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeOnMaybeObserver.onSuccess(MaybeSubscribeOn.java:91)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onSuccess(MaybePeek.java:122)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onSuccess(MaybePeek.java:122)
15:23:51 	at io.reactivex.internal.operators.flowable.FlowableSingleMaybe$SingleElementSubscriber.onComplete(FlowableSingleMaybe.java:104)
15:23:51 	at io.reactivex.internal.operators.flowable.FlowableRetryPredicate$RetrySubscriber.onComplete(FlowableRetryPredicate.java:104)
15:23:51 	at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:134)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybeToFlowable$MaybeToFlowableSubscriber.onSuccess(MaybeToFlowable.java:70)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver$InnerObserver.onSuccess(MaybeFlatten.java:119)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybeJust.subscribeActual(MaybeJust.java:36)
15:23:51 	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver.onSuccess(MaybeFlatten.java:96)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeOnMaybeObserver.onSuccess(MaybeSubscribeOn.java:91)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybeCreate$Emitter.onSuccess(MaybeCreate.java:73)
15:23:51 	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:536)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
15:23:51 	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
15:23:51 	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
15:23:51 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
15:23:51 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
15:23:51 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
15:23:51 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
15:23:51 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
15:23:51 	at java.lang.Thread.run(Thread.java:748)
15:23:51 Caused by: java.util.concurrent.RejectedExecutionException: Task io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker@2e6705e4 rejected from java.util.concurrent.ThreadPoolExecutor@32cb636e[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 467]
15:23:51 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
15:23:51 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
15:23:51 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
15:23:51 	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.schedule(ExecutorScheduler.java:171)
15:23:51 	... 52 more
15:23:51 Exception in thread "rp-io-1" io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.util.concurrent.RejectedExecutionException: Task io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker@2e6705e4 rejected from java.util.concurrent.ThreadPoolExecutor@32cb636e[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 467]
```

**Comment by mchundi** [comment]
Observed this error in the following scenarios:
1. when any of the before methods fail.
2. if the memory allocated is less.

**Comment by HardNorth** [comment]
@mchundi Does it affects your launch?

**Comment by mchundi** [comment]
@HardNorth  yes. the launches hang and the build fails because of this error even though the tests are executed.

**Comment by HardNorth** [comment]
@mchundi If you specify `AGENT_NO_ANALYTICS` environment variable on your worker node it will disable analytics sending.

**Comment by mchundi** [comment]
@HardNorth does this effect reportportal data in any way? or just effect his error?

**Comment by mchundi** [comment]
@evjlobanova it would help to keep this issue open till the suggested fix is tested so that I can get followup questions answered.

**Comment by mchundi** [comment]
@HardNorth should I be adding the variable on RP server or the node where the tests are running? Also, is assumption that the value of this variable should be false is correct?

**Comment by HardNorth** [comment]
@mchundi Any non-empty value on the node were tests are running. No it doesn't affect test data.
