### ISSUE TITLE
GitLab Pipeline Report Portal Integration

### ISSUE THREAD

**Issue by rbecerraj** [reportportal/reportportal#1437]
Hi, I'm running WinAppDriver (Windows UI Automation tool) to automate an app within GitLab CI/CD and Report Portal. The thing is that when I run the automation locally I'm able to see the report results  in Report Portal but when I run the automation from the gitlab pipeline the test cases are executed but the results are not sent to report portal, here is the error message:

`'An unknown error occurred in the remote end while processing the command.'. (9.9s)
Finishing to send the results to Report Portal... ReportPortal exception was thrown.
System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendHttpRequestAsync[TResponse](HttpMethod httpMethod, String uri, HttpContent httpContent)
   at ReportPortal.Shared.Internal.Delegating.BaseRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttemptCallback, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass25_0.<<Start>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at ReportPortal.Shared.Reporter.LaunchReporter.Sync()
   at ReportPortal.NUnitExtension.ReportPortalListener.FinishRun(String report) in C:\projects\agent-net-nunit\src\ReportPortal.NUnitExtension\ReportPortalListener.Launch.cs:line 113`

the remote server has access and comunication to the report portal site, but everytime the pipeline is executed, i get this error, i hope you can help me

**Comment by MaryiaRymarchyk** [comment]
Hi @rbecerraj, sorry for the silence.
Did you managed to solve the issue? or support from ReportPortal team still required?

**Comment by MaryiaRymarchyk** [comment]
As we haven't received a reply from you, we'll close the issue for now.
If  the issue still relevant, just get in touch.
