### ISSUE TITLE
[v5] Error logs in api service container

### ISSUE THREAD

**Issue by Invictum** [reportportal/reportportal#1443]
**Describe the bug**
Logs cleanup job error in logs after upgrade from 5.3.3 to 5.4

**To Reproduce**
1. Run RP v5.4 using Docker.
2. Inspect `api` service logs and wait till logs cleanup job to trigger.

**Expected behavior**
No errors related to logs cleanup in the console.

**Additional context**
`api` container tries to trigger logs cleanup job every 3-5 minutes, but always fails with errors in the logs
```
api_1             | 2021-06-22 18:19:23.597  INFO 7 --- [_MisfireHandler] o.s.s.quartz.LocalDataSourceJobStore     : Handling 3 trigger(s) that missed their scheduled fire-time.
api_1             | 2021-06-22 18:19:23.605 ERROR 7 --- [_MisfireHandler] o.s.s.quartz.LocalDataSourceJobStore     : MisfireHandler: Error handling misfires: Couldn't store trigger 'DEFAULT.createCleanLogsTrigger' for 'DEFAULT.cleanLogsJobBean' job:Couldn't retrieve job because a required class was not found: com.epam.ta.reportportal.job.CleanLogsJob
api_1             |
api_1             | org.quartz.JobPersistenceException: Couldn't store trigger 'DEFAULT.createCleanLogsTrigger' for 'DEFAULT.cleanLogsJobBean' job:Couldn't retrieve job because a required class was not found: com.epam.ta.reportportal.job.CleanLogsJob
api_1             | 	at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1228)
api_1             | 	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doUpdateOfMisfiredTrigger(JobStoreSupport.java:1042)
api_1             | 	at org.quartz.impl.jdbcjobstore.JobStoreSupport.recoverMisfiredJobs(JobStoreSupport.java:991)
api_1             | 	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3264)
api_1             | 	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:4012)
api_1             | 	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4033)
api_1             | Caused by: org.quartz.JobPersistenceException: Couldn't retrieve job because a required class was not found: com.epam.ta.reportportal.job.CleanLogsJob
api_1             | 	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveJob(JobStoreSupport.java:1393)
api_1             | 	at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1210)
api_1             | 	... 5 common frames omitted
api_1             | Caused by: java.lang.ClassNotFoundException: com.epam.ta.reportportal.job.CleanLogsJob
api_1             | 	at com.epam.reportportal.extension.classloader.DelegatingClassLoader.loadClass(DelegatingClassLoader.java:52)
api_1             | 	at com.epam.ta.reportportal.core.configs.ReportPortalClassLoadHelper.loadClass(ReportPortalClassLoadHelper.java:39)
api_1             | 	at com.epam.ta.reportportal.core.configs.ReportPortalClassLoadHelper.loadClass(ReportPortalClassLoadHelper.java:45)
api_1             | 	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectJobDetail(StdJDBCDelegate.java:852)
api_1             | 	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveJob(JobStoreSupport.java:1390)
api_1             | 	... 6 common frames omitted
api_1             |
```
As I understand clean up logic was moved to `jobs` container. Maybe something wasn't fully removed during refactor, so `api` container tries to trigger cleanup itself.

**Comment by evjlobanova** [comment]
@svettsova @irynakozak2

**Comment by Invictum** [comment]
Updated description. Job works as expected and the only effect of this issue is errors in a logs.

**Comment by evjlobanova** [comment]
@pbortnik please describe how it can be fixed

**Comment by pbortnik** [comment]
Hi @Invictum,
Yes, there were not removed old job triggers from the database. 
You have to options:
1. Pull the newer 5.4.0 version of migrations service again. We've updated it with a script that removes triggers
2. Manually run script on the database from [here](https://github.com/reportportal/migrations/blob/5.4.0/migrations/47_quartz_remove_triggers.up.sql)

**Comment by Invictum** [comment]
@pbortnik @evjlobanova 
New migration service image did the trick. Thank you!
