### ISSUE TITLE
[v5] Migration was not happened after upgrading from 5.3 to 5.4

### ISSUE THREAD

**Issue by Kanaduchi** [reportportal/reportportal#1468]
**Describe the bug**
I upgraded version 5.3 to 5.4 3 days ago. And looks like migration was not happened. 

**Problems**
1. I don't see stacktraces in the launches
2. I can't delete any project - 
`Unclassified error [SQL [delete from \"public\".\"log\" where \"public\".\"log\".\"project_id\" = ?]; ERROR: column log.project_id does not exist\n  Position: 34]"`
3. In the logs I see a lot of messages like
```postgres_1        | 	RETURNING *
postgres_1        | 2021-07-09 08:49:09.803 UTC [160] ERROR:  column "project_id" of relation "log" does not exist at character 100
postgres_1        | 2021-07-09 08:49:09.803 UTC [160] STATEMENT:  insert into public.log (attachment_id, last_modified, launch_id, log_level, log_message, log_time, project_id, item_id, uuid) values ($1, $2,
 $3, $4, $5, $6, $7, $8, $9)
postgres_1        | 	RETURNING *
postgres_1        | 2021-07-09 08:49:09.806 UTC [160] ERROR:  column "project_id" of relation "log" does not exist at character 100
postgres_1        | 2021-07-09 08:49:09.806 UTC [160] STATEMENT:  insert into public.log (attachment_id, last_modified, launch_id, log_level, log_message, log_time, project_id, item_id, uuid) values ($1, $2,
 $3, $4, $5, $6, $7, $8, $9)
postgres_1        | 	RETURNING *
postgres_1        | 2021-07-09 08:49:09.809 UTC [160] ERROR:  column "project_id" of relation "log" does not exist at character 100
postgres_1        | 2021-07-09 08:49:09.809 UTC [160] STATEMENT:  insert into public.log (attachment_id, last_modified, launch_id, log_level, log_message, log_time, project_id, item_id, uuid) values ($1, $2,
 $3, $4, $5, $6, $7, $8, $9)
postgres_1        | 	RETURNING *
postgres_1        | 2021-07-09 08:49:09.812 UTC [160] ERROR:  column "project_id" of relation "log" does not exist at character 100
postgres_1        | 2021-07-09 08:49:09.812 UTC [160] STATEMENT:  insert into public.log (attachment_id, last_modified, launch_id, log_level, log_message, log_time, project_id, item_id, uuid) values ($1, $2,
 $3, $4, $5, $6, $7, $8, $9)
postgres_1        | 	RETURNING *
postgres_1        | 2021-07-09 08:49:09.815 UTC [160] ERROR:  column "project_id" of relation "log" does not exist at character 100
postgres_1        | 2021-07-09 08:49:09.815 UTC [160] STATEMENT:  insert into public.log (attachment_id, last_modified, launch_id, log_level, log_message, log_time, project_id, item_id, uuid) values ($1, $2,
 $3, $4, $5, $6, $7, $8, $9)
postgres_1        | 	RETURNING *
postgres_1        | 2021-07-09 08:49:10.026 UTC [164] ERROR:  column "project_id" of relation "log" does not exist at character 100
postgres_1        | 2021-07-09 08:49:10.026 UTC [164] STATEMENT:  insert into public.log (attachment_id, last_modified, launch_id, log_level, log_message, log_time, project_id, item_id, uuid) values ($1, $2,
 $3, $4, $5, $6, $7, $8, $9)
postgres_1        | 	RETURNING *
postgres_1        | 2021-07-09 08:49:10.029 UTC [164] ERROR:  column "project_id" of relation "log" does not exist at character 100
postgres_1        | 2021-07-09 08:49:10.029 UTC [164] STATEMENT:  insert into public.log (attachment_id, last_modified, launch_id, log_level, log_message, log_time, project_id, item_id, uuid) values ($1, $2,
 $3, $4, $5, $6, $7, $8, $9)
postgres_1        | 	RETURNING *
postgres_1        | 2021-07-09 08:49:10.031 UTC [164] ERROR:  column "project_id" of relation "log" does not exist at character 100
postgres_1        | 2021-07-09 08:49:10.031 UTC [164] STATEMENT:  insert into public.log (attachment_id, last_modified, launch_id, log_level, log_message, log_time, project_id, item_id, uuid) values ($1, $2,
 $3, $4, $5, $6, $7, $8, $9)
postgres_1        | 	RETURNING *
postgres_1        | 2021-07-09 08:49:10.034 UTC [164] ERROR:  column "project_id" of relation "log" does not exist at character 100
postgres_1        | 2021-07-09 08:49:10.034 UTC [164] STATEMENT:  insert into public.log (attachment_id, last_modified, launch_id, log_level, log_message, log_time, project_id, item_id, uuid) values ($1, $2,
 $3, $4, $5, $6, $7, $8, $9)
postgres_1        | 	RETURNING *
postgres_1        | 2021-07-09 08:49:10.037 UTC [164] ERROR:  column "project_id" of relation "log" does not exist at character 100
postgres_1        | 2021-07-09 08:49:10.037 UTC [164] STATEMENT:  insert into public.log (attachment_id, last_modified, launch_id, log_level, log_message, log_time, project_id, item_id, uuid) values ($1, $2,
 $3, $4, $5, $6, $7, $8, $9)```

```jobs_1            | org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [UPDATE shedlock SET lock_until = timezone('utc', CURRENT_TIMESTAMP) + cast(? as interval), loc
ked_at = timezone('utc', CURRENT_TIMESTAMP), locked_by = ? WHERE shedlock.name = ? AND shedlock.lock_until <= timezone('utc', CURRENT_TIMESTAMP)]; nested exception is org.postgresql.util.PSQLException: ERROR
: relation "shedlock" does not exist
jobs_1            |   Position: 8
jobs_1            | 	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
jobs_1            | 	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
jobs_1            | 	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
jobs_1            | 	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:667) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
jobs_1            | 	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:960) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
jobs_1            | 	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:981) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
jobs_1            | 	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:328) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
jobs_1            | 	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:333) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
jobs_1            | 	at net.javacrumbs.shedlock.provider.jdbctemplate.JdbcTemplateStorageAccessor.lambda$updateRecord$1(JdbcTemplateStorageAccessor.java:82) ~[shedlock-provider-jdbc-template-4.21.0.jar!/:
na]
jobs_1            | 	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.3.4.jar!/:5.3.4]
jobs_1            | 	at net.javacrumbs.shedlock.provider.jdbctemplate.JdbcTemplateStorageAccessor.updateRecord(JdbcTemplateStorageAccessor.java:81) ~[shedlock-provider-jdbc-template-4.21.0.jar!/:na]
jobs_1            | 	at net.javacrumbs.shedlock.support.StorageBasedLockProvider.doLock(StorageBasedLockProvider.java:91) ~[shedlock-core-4.21.0.jar!/:na]
jobs_1            | 	at net.javacrumbs.shedlock.support.StorageBasedLockProvider.lock(StorageBasedLockProvider.java:65) ~[shedlock-core-4.21.0.jar!/:na]
jobs_1            | 	at jdk.internal.reflect.GeneratedMethodAccessor44.invoke(Unknown Source) ~[na:na]
```

```
jobs_1            | org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [UPDATE shedlock SET lock_until = timezone('utc', CURRENT_TIMESTAMP) + cast(? as interval), loc
ked_at = timezone('utc', CURRENT_TIMESTAMP), locked_by = ? WHERE shedlock.name = ? AND shedlock.lock_until <= timezone('utc', CURRENT_TIMESTAMP)]; nested exception is org.postgresql.util.PSQLException: ERROR
: relation "shedlock" does not exist
jobs_1            |   Position: 8
jobs_1            | 	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
jobs_1            | 	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
jobs_1            | 	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
jobs_1            | 	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:667) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
jobs_1            | 	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:960) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
jobs_1            | 	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:981) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
jobs_1            | 	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:328) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
jobs_1            | 	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:333) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
jobs_1            | 	at net.javacrumbs.shedlock.provider.jdbctemplate.JdbcTemplateStorageAccessor.lambda$updateRecord$1(JdbcTemplateStorageAccessor.java:82) ~[shedlock-provider-jdbc-template-4.21.0.jar!/:
na]
jobs_1            | 	at org.springframework.transaction.suppo
```

How can fix this errors? Is it possible to start migration manually? I do not want to delete all previous launches...

**Comment by Kanaduchi** [comment]
I found a solution to resolve this problem:
1. Manually change version in schema_migrations to 22 with f (not dirty) flag
2. Create custom docker-compose file:
```
version: '2'
services:
  migrations:
    image: reportportal/migrations:5.4.0
    environment:
      POSTGRES_USER: rpuser
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: rppass
      POSTGRES_SERVER: postgres
      POSTGRES_DB: reportportal
    restart: on-failure
```
3. Connect to Postgres database: docker exec -it <container> psql -U rpuser -d reportportal
4. Execute TRUNCATE TABLE log;
5. Run sudo docker-compose run --rm migrations

After that all migrations were done and RP returned to normal work

**Comment by talmoshe24** [comment]
@Kanaduchi I'm having an issue with migration to 5.4 too, why did you choose schema_migrations 22? Mine was failing on 37:

```
reportportal=# select * from schema_migrations;
 version | dirty
---------+-------
      37 | t
(1 row)
reportportal=#
```

**Comment by evjlobanova** [comment]
@pbortnik could you please check&

**Comment by heilwood** [comment]
Had the same issue, my solution:

```
docker exec -it reportportal_postgres_1 psql -U rpuser -d reportportal
UPDATE schema_migrations SET dirty = 'f' WHERE dirty = 't';
TRUNCATE TABLE log;
\q [Enter]
curl -LO  https://raw.githubusercontent.com/reportportal/reportportal/5.5.0/docker-compose.yml
docker-compose -p reportportal up -d --force-recreate

docker exec -it reportportal_postgres_1 psql -U rpuser -d reportportal
select * from schema_migrations;
dirty should be 'f', if no - repeat the steps.
```

**Comment by miracle8484** [comment]
Hello, we have appropriate page in case of your kind of issue, please have a look at https://github.com/reportportal/documentation/blob/master/src/md/src/TipsAndTricks/MigrationIssue.md

**Comment by unmurphy** [comment]
> TRUNCATE TABLE log;

@heilwood  thanks, heilwood, you save my life
