### ISSUE TITLE
relation "shedlock" does not exist on starting service-jobs service 

### ISSUE THREAD

**Issue by ERankur91** [reportportal/reportportal#1485]
**Getting following exception on starting service-jobs service** 

`Caused by: org.postgresql.util.PSQLException: ERROR: relation "shedlock" does not exist
  Position: 8
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553) ~[postgresql-42.2.18.jar!/:42.2.18]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285) ~[postgresql-42.2.18.jar!/:42.2.18]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323) ~[postgresql-42.2.18.jar!/:42.2.18]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473) ~[postgresql-42.2.18.jar!/:42.2.18]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393) ~[postgresql-42.2.18.jar!/:42.2.18]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164) ~[postgresql-42.2.18.jar!/:42.2.18]
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130) ~[postgresql-42.2.18.jar!/:42.2.18]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-3.4.5.jar!/:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.5.jar!/:na]
	at org.springframework.jdbc.core.JdbcTemplate.lambda$update$2(JdbcTemplate.java:965) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651) ~[spring-jdbc-5.3.4.jar!/:5.3.4]`

Impact: **Not able to delete any launch** 

**Versions:**
 - CentOS Linux 7 (Core)
 - Version of RP Current version:API Service: 5.4.0;Index Service: 5.0.10;Jobs Service: 5.4.0;Authorization Service: 5.4.0;Service UI: 5.4.0;

NOTE:
Setup was working fine when is role back to version [5.3.5](https://github.com/reportportal/reportportal/blob/5.3.5/docker-compose.yml)

**Comment by irynakozak2** [comment]
Looks like the required migration from v5.3.5 to v5.4 wasn't completed properly.
Did you follow the migration guide and your migrations service is in a healthy state and does not show any errors?
https://github.com/reportportal/reportportal/wiki/Migration-to-ReportPortal-v.5.4

**Comment by ERankur91** [comment]
Migration seems to be successful, db-scripts working successfully. Instance was also working properly.
We started facing issue after some time when realised old data are not getting deleted and then deletion of individual launch seems not to be working.

**Comment by evjlobanova** [comment]
@irynakozak2 could you please check

**Comment by irynakozak2** [comment]
@ERankur91 hello,
if there any errors occur in the `service-jobs` container?
Please also check the state of the `shedlock` table in the database, it should look like the following:
![image](https://user-images.githubusercontent.com/51473435/130199996-1e90741e-ca44-4493-91e5-2c96f0e3d941.png)

**Comment by ERankur91** [comment]
@irynakozak2 shedlock table not existing in db.

**Comment by ERankur91** [comment]
@irynakozak2 we can close this issue.
Thanks for help.
