### ISSUE TITLE
[v5] SMTP 550 error when trying to configure Sendgrid as SMTP server

### ISSUE THREAD

**Issue by jrzdudek** [reportportal/reportportal#1502]
**Describe the bug**
When trying to add a new SMTP integration, an error displayed in the screenshot occurs. This is happening with Sendgrid, regardless of chosen encryption / port.

**Screenshots**
![Screenshot 2021-08-17 at 14 08 20](https://user-images.githubusercontent.com/7613326/129723686-ceff52dd-141c-47b2-a017-4f569ab8f512.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Browser chrome
 - Version 92
 
**Additional context**
reportportal version `5.5.0`
The most relevant part of the stack trace:
```
com.epam.ta.reportportal.exception.ReportPortalException: Email server is not configured or configuration is incorrect. Unable to send connection test email. Failed messages: com.sun.mail.smtp.SMTPSendFailedException: 550 MIME message is missing 'From' header

	at com.epam.ta.reportportal.commons.validation.AlwaysFailRuleValidator.withError(AlwaysFailRuleValidator.java:31)
	at com.epam.ta.reportportal.core.integration.util.EmailServerIntegrationService.checkConnection(EmailServerIntegrationService.java:145)
	at com.epam.ta.reportportal.core.integration.impl.CreateIntegrationHandlerImpl.createGlobalIntegration(CreateIntegrationHandlerImpl.java:98)
	at com.epam.ta.reportportal.ws.controller.IntegrationController.createGlobalIntegration(IntegrationController.java:110)
	at com.epam.ta.reportportal.ws.controller.IntegrationController$$FastClassBySpringCGLIB$$255e9ef9.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
```

**Comment by evjlobanova** [comment]
@VolhaKarenko could you please reproduce?

**Comment by VolhaKarenko** [comment]
Hi @jrzdudek, try providing your email address in "username" field

**Comment by jrzdudek** [comment]
@VolhaKarenko I confirm, setting email in the field resolved the issue. 
Just as a suggestion to reduce confusion, perhaps it would be worth it to name the field `sender email` instead of `sender name` as those tend to be 2 distinct values in SMTP configs.

**Comment by evjlobanova** [comment]
@VolhaKarenko Could you please add a task to the net sprint please

**Comment by jrzdudek** [comment]
Hey @AaronMT, I no longer work with that project and don't remember much of it. It seems you're creating a "Project Integration", while the issue was around creating a "Global Integration". Unsure why one would have the `Username` field but not the other. Perhaps the UI just changed since 2021.
