### ISSUE TITLE
LDAP Active Directory Issues ReportPortal [v5]

### ISSUE THREAD

**Issue by aleon1220** [reportportal/reportportal#1510]
**Describe the bug**
there are multiple bugs with this LDAP plugin. I will describe only 2 in this issue:

There is **Not** enough info in the [LDAP-Auth-integration Docs](https://reportportal.io/docs/LDAP-Auth-integration) to configure LDAP authentication successfully. I suggest examples are added.

I tried multiple ways to configure the Authentication with the LDAP implementation of Microsoft active directory. 
Below you will find the only possible way I was able to achieve my own authentication (see table below) and the print screen

> NOTE: even if is connecting to Active Directory AD I used the LDAP Plugin. I gave up trying with the AD Plugin

## Successful Authentication scenario
Here is the only successful authentication scenario I had. The setup is like this: I have access to a **service user** username/pass from AWS Secret manager. I used that user to run multiple queries with `ldapsearch`

In the table below you will see the options I used for the LDAP Plugin. I will only add the options where I set a value. Any other option available in the LDAP plugin I left as blank.

#### Table with properties and values for LDAP

|          Property         |                                                          Value                                                          |
|:---------------------:|:----------------------------------------------------------------------------------------------------------------------:|
| Url                   | auth-servers.domain.org.int:3358                                                                                       |
| Base DN               | OU=MAIN,DC=DOMAIN,DC=ORG,DC=INT                                                                                        |
| Manager DN            | cn=Service UserBind,ou=Service Accounts,ou=Colombia,ou=America,ou=ServiceAccounts,dc=DOMAIN,dc=ORG,dc=INT              |
| User search filter    | (\|(sAMAccountName=Andres.Leon*)) I am forcing it to use my name. I also forced it to use (sAMAccountName=Andres.Leon) |
| Password encoder type | NO                                                                                                                     |
| Email attribute       | mail                                                                                                                   |
| Full name attribute   | displayName                                                                                                            |
| Photo attribute       | thumbnailPhoto                                                                                                         |

* Once I set the values above with **superadmin** I rebooted the stack
``` bash
docker-compose --file /opt/report_portal/docker-compose.yml --project-name reportportal-dev restart
```
* I tried to connect with my user **andres.leon** and my password
* In the logs I could see that It found my user
* This is what I got in the UI for a successful login
![2021-08-21_200133-success](https://user-images.githubusercontent.com/2084646/130316038-21e90969-ab78-4a3c-909e-27c93cce7862.png)

**To Reproduce Errors**
Use the same as the table above but change the user search Filter for the ObjectClass=person filter value such as:

|          Property         |                                                          Value                                                          |
|:---------------------:|:----------------------------------------------------------------------------------------------------------------------:|
| User search filter                   | (objectClass=person)                                                                                  |

### Errors that you will get
``` bash
uat_1               | org.springframework.security.authentication.InternalAuthenticationServiceException: [LDAP: error code 4 - Sizelimit Exceeded]; nested exception is javax.naming.SizeLimitExceededException: [LDAP: error code 4 - Sizelimit Exceeded]; remaining name '/'
uat_1               | 	at org.springframework.security.ldap.authentication.LdapAuthenticationProvider.doAuthentication(LdapAuthenticationProvider.java:206) ~[spring-security-ldap-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
uat_1               | 	at org.springframework.security.ldap.authentication.AbstractLdapAuthenticationProvider.authenticate(AbstractLdapAuthenticationProvider.java:85) ~[spring-security-ldap-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
uat_1               | 	at com.epam.reportportal.auth.EnableableAuthProvider.authenticate(EnableableAuthProvider.java:49) ~[classes!/:na]
uat_1               | 	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:175) ~[spring-security-core-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.oauth2.provider.password.ResourceOwnerPasswordTokenGranter.getOAuth2Authentication(ResourceOwnerPasswordTokenGranter.java:75) ~[spring-security-oauth2-2.4.0.RELEASE.jar!/:na]
uat_1               | 	at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.getAccessToken(AbstractTokenGranter.java:76) ~[spring-security-oauth2-2.4.0.RELEASE.jar!/:na]
uat_1               | 	at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.grant(AbstractTokenGranter.java:71) ~[spring-security-oauth2-2.4.0.RELEASE.jar!/:na]
uat_1               | 	at org.springframework.security.oauth2.provider.CompositeTokenGranter.grant(CompositeTokenGranter.java:42) ~[spring-security-oauth2-2.4.0.RELEASE.jar!/:na]
uat_1               | 	at org.springframework.security.oauth2.config.annotation.web.configurers.AuthorizationServerEndpointsConfigurer$4.grant(AuthorizationServerEndpointsConfigurer.java:587) ~[spring-security-oauth2-2.4.0.RELEASE.jar!/:na]
uat_1               | 	at org.springframework.security.oauth2.provider.endpoint.TokenEndpoint.postAccessToken(TokenEndpoint.java:136) ~[spring-security-oauth2-2.4.0.RELEASE.jar!/:na]
uat_1               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
uat_1               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
uat_1               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
uat_1               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
uat_1               | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652) ~[tomcat-embed-core-9.0.37.jar!/:4.0.FR]
uat_1               | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.37.jar!/:4.0.FR]
uat_1               | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:204) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.springframework.security.oauth2.client.filter.OAuth2ClientContextFilter.doFilter(OAuth2ClientContextFilter.java:64) ~[spring-security-oauth2-2.4.0.RELEASE.jar!/:na]
uat_1               | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109) ~[spring-boot-actuator-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
uat_1               | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.springframework.web.filter.ForwardedHeaderFilter.doFilterInternal(ForwardedHeaderFilter.java:158) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
uat_1               | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
uat_1               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
uat_1               | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
uat_1               | 	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
uat_1               | Caused by: org.springframework.ldap.SizeLimitExceededException: [LDAP: error code 4 - Sizelimit Exceeded]; nested exception is javax.naming.SizeLimitExceededException: [LDAP: error code 4 - Sizelimit Exceeded]; remaining name '/'
uat_1               | 	at org.springframework.ldap.support.LdapUtils.convertLdapException(LdapUtils.java:157) ~[spring-ldap-core-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
uat_1               | 	at org.springframework.ldap.core.LdapTemplate.executeWithContext(LdapTemplate.java:820) ~[spring-ldap-core-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
uat_1               | 	at org.springframework.ldap.core.LdapTemplate.executeReadOnly(LdapTemplate.java:803) ~[spring-ldap-core-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
uat_1               | 	at org.springframework.security.ldap.SpringSecurityLdapTemplate.searchForSingleEntry(SpringSecurityLdapTemplate.java:312) ~[spring-security-ldap-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
uat_1               | 	at org.springframework.security.ldap.search.FilterBasedLdapUserSearch.searchForUser(FilterBasedLdapUserSearch.java:128) ~[spring-security-ldap-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
uat_1               | 	at org.springframework.security.ldap.authentication.BindAuthenticator.authenticate(BindAuthenticator.java:95) ~[spring-security-ldap-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
uat_1               | 	at org.springframework.security.ldap.authentication.LdapAuthenticationProvider.doAuthentication(LdapAuthenticationProvider.java:187) ~[spring-security-ldap-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
uat_1               | 	... 105 common frames omitted
uat_1               | Caused by: javax.naming.SizeLimitExceededException: [LDAP: error code 4 - Sizelimit Exceeded]
uat_1               | 	at java.naming/com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3311) ~[na:na]
uat_1               | 	at java.naming/com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3205) ~[na:na]
uat_1               | 	at java.naming/com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2996) ~[na:na]
uat_1               | 	at java.naming/com.sun.jndi.ldap.AbstractLdapNamingEnumeration.getNextBatch(AbstractLdapNamingEnumeration.java:148) ~[na:na]
uat_1               | 	at java.naming/com.sun.jndi.ldap.AbstractLdapNamingEnumeration.hasMoreImpl(AbstractLdapNamingEnumeration.java:217) ~[na:na]
uat_1               | 	at java.naming/com.sun.jndi.ldap.AbstractLdapNamingEnumeration.hasMore(AbstractLdapNamingEnumeration.java:189) ~[na:na]
uat_1               | 	at org.springframework.security.ldap.SpringSecurityLdapTemplate.searchForSingleEntryInternal(SpringSecurityLdapTemplate.java:335) ~[spring-security-ldap-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
uat_1               | 	at org.springframework.security.ldap.SpringSecurityLdapTemplate.lambda$searchForSingleEntry$2(SpringSecurityLdapTemplate.java:312) ~[spring-security-ldap-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
uat_1               | 	at org.springframework.ldap.core.LdapTemplate.executeWithContext(LdapTemplate.java:817) ~[spring-ldap-core-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
uat_1               | 	... 110 common frames omitted
```

**Expected behaviour**
I only expect to use the **Base DN** with no filter. I expect that i can use any single user name and password in the organization and be able to login. I do that for another application called testrail and they only need the main Base DN.

**Screenshots**
some screenshot of failure in the login UI when using the filter **(objectClass=person**
![2021-08-21_201048-error-objectclass-person](https://user-images.githubusercontent.com/2084646/130316182-249c423f-b337-4de6-929e-10f643f55894.png)

**Desktop (please complete the following information):**
 - OS: testing in Ubuntu 20.01
 - Browser 
 - chrome
 - Version 92.0.4515.159 (Official Build) (64-bit)

**Additional context**
i deploy the infrastructure using terraform. There is an AWS EC2 instance running the docker engine. The Active Directory server runs in a physical server. I only have access to a service user.

**Comment by aleon1220** [comment]
some references
https://stackoverflow.com/questions/58638194/how-to-fix-ldap-connection-error-javax-naming-sizelimitexceededexception-ldap
https://docs.oracle.com/javase/7/docs/api/javax/naming/ldap/PagedResultsControl.html

**Comment by evjlobanova** [comment]
@VolhaKarenko Could you please recheck the iisue?

**Comment by Yumfriez** [comment]
@aleon1220 
As LDAP error says: Sizelimit Exceeded - because of **objectClass=person** you retrieve all users data on login attempt.
Correct way of configuration on the RP side is to provide filter with common pattern that will allow **username** extraction:
(&(objectClass=user)(userPrincipalName={0})) - by default (userPrincipalName is user login attribute)

**userPrincipalName** attribute can be different (we had case with users where it was named **samaccountname**

So full filter will be:
(&(objectClass=user)(samaccountname ={0}))
<img width="456" alt="image" src="https://user-images.githubusercontent.com/31598109/130431082-5ffa9b59-3389-4b81-90a0-9e29f7101043.png">


By passing this filter you will allow RP and LDAP dynamically retrieve **username** for log-in operation

**Comment by aleon1220** [comment]
Thank you Ivan @Yumfriez 
yes the filtering you mentioned is the correct one. Again I am using Microsoft Active Directory. I suggest the documentation is updated with examples. I am happy to add them to the docs.

Please find the table of configurations that worked successfully

#### Table with properties and values for LDAP Microsoft Active Directory

|          Property         |                                                          Value                                                          |
|:---------------------:|:----------------------------------------------------------------------------------------------------------------------:|
| Url                   | auth-servers.domain.org.int:3358                                                                                       |
| Base DN               | OU=MAIN,DC=DOMAIN,DC=ORG,DC=INT                                                                                        |
| Manager DN            | cn=Service UserBind,ou=Service Accounts,ou=Colombia,ou=America,ou=ServiceAccounts,dc=DOMAIN,dc=ORG,dc=INT              |
| User search filter    | (&(objectClass=user)(sAMAccountName={0})) |
| Password encoder type | NO                                                                                                                     |
| Email attribute       | mail                                                                                                                   |
| Full name attribute   | displayName                                                                                                            |
| Photo attribute       | thumbnailPhoto                                                                                                         |

**Comment by aleon1220** [comment]
I have asked other users to login and is been successful. 
Thank you

**Comment by evjlobanova** [comment]
@aleon1220 thank you for sharing the example, we have updated documentation with it https://reportportal.io/docs/Active-Directory-Auth

**Comment by archit57** [comment]
> I have asked other users to login and is been successful. Thank you



> I have asked other users to login and is been successful. Thank you

Can you please help me i am unable to integrate with LDAP.
Getting below error:
   "message":"You do not have enough permissions. [LDAP: error code 49 - 80090308: LdapErr: DSID-0C090447, comment: AcceptSecurityContext error, data 52e, v3839]; nested exception is javax.naming.AuthenticationException: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C090447, comment: AcceptSecurityContext error, data 52e, v3839]".
   
   kindly assist me.
