### ISSUE TITLE
Test log not created in ReportPortal for successful test

### ISSUE THREAD

**Issue by chan90git** [reportportal/reportportal#1513]
Hi ReportPortal team,

I'm facing the issue below while using reportportal for logging results (TestNG+Selenium+Java+ReportPortal). We have installed RP in our AWS EC2 machine (with all needed config)

console error log :
**********************************************************
[rp-io-26] ERROR com.epam.reportportal.service.Launch - [57] ReportPortal execution error
rp.org.apache.http.conn.HttpHostConnectException: Connect to reportportal.hippovideo.us:8080 [reportportal.hippovideo.us/3.239.95.217] failed: Connection timed out: connect
at rp.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
at rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
at rp.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
at rp.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
at rp.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
at rp.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
at rp.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
at rp.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:502)
at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
at io.reactivex.Maybe.subscribe(Maybe.java:4290)
at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.net.ConnectException: Connection timed out: connect
at java.base/sun.nio.ch.Net.connect0(Native Method)
at java.base/sun.nio.ch.Net.connect(Net.java:574)
at java.base/sun.nio.ch.Net.connect(Net.java:563)
at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
at java.base/java.net.Socket.connect(Socket.java:648)
at rp.org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
at rp.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
... 20 more
[rp-io-27] ERROR com.epam.reportportal.utils.SubscriptionUtils - Logging context completed with error
rp.org.apache.http.conn.HttpHostConnectException: Connect to reportportal.hippovideo.us:8080 [reportportal.hippovideo.us/3.239.95.217] failed: Connection timed out: connect
at rp.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
at rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
at rp.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
at rp.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
at rp.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
at rp.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
at rp.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
at rp.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:502)
at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
at io.reactivex.Maybe.subscribe(Maybe.java:4290)
at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.net.ConnectException: Connection timed out: connect
at java.base/sun.nio.ch.Net.connect0(Native Method)
at java.base/sun.nio.ch.Net.connect(Net.java:574)
at java.base/sun.nio.ch.Net.connect(Net.java:563)
at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
at java.base/java.net.Socket.connect(Socket.java:648)
at rp.org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
at rp.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
... 20 more
**********************************************************
The same scripts were working fine earlier (a few days back). No issue with the internet, network, reportportal server machine, or my automation framework.

![image](https://user-images.githubusercontent.com/27766769/130802837-d3dbfd2d-b3dd-421f-99b6-b96812cb783b.png)

Not sure about this behavior. Kindly help us in this context.

And the scenario where I face this issue is :
* i'll be launching 2 browsers in our test case
    -> primary browser will always keep running - do some settings changes
    -> open a secondary browser (login with different user), verify the settings changes, close the secondary browser alone
only for this scenario, we are facing this issue.

I would request to look into this asap and provide us a fix.

Thanks,
Chandra
https://www.hippovideo.io/

**Comment by chan90git** [comment]
pom.xml : 
<repositories>
	     <repository>
	        <snapshots>
	          <enabled>false</enabled>
	        </snapshots>
	        <id>bintray-epam-reportportal</id>
	        <name>bintray</name>
	        <url>http://dl.bintray.com/epam/reportportal</url>
	     </repository>
	</repositories>

**Comment by MaryiaRymarchyk** [comment]
Hi @chan90git
As we haven't received a reply from you, we'll close the issue for now.
If  the issue still relevant, just get in touch.
