### ISSUE TITLE
[v5] Incompatibility with Minio-Operator

### ISSUE THREAD

**Issue by Roshick** [reportportal/reportportal#1520]
**Describe the bug**
We are using the minio-operator (https://github.com/minio/operator) in version 4.2.5 deployed via helm and created a tenant for reportportal. At startup of the uat pod we get the following error which causes the pod to fail:

```
Unable to find file 'keystore/secret-integration-salt'

io.minio.errors.ErrorResponseException: The Access Key Id you provided does not exist in our records.
```

Checking the tenant, reportportal created two buckets "prj-keystore" and "prj-user" and a file within "prj-keystore" named "secret-integration-salt", but fails anyway.

**To Reproduce**
Install the minio-operator in version 4.2.5 via helm, create a tenant and configure reportportal to use this tenant.

**Comment by AsoTora** [comment]
Having the same issue:
Helm charts installed from documentation:
<img width="607" alt="image" src="https://user-images.githubusercontent.com/36507055/133422274-abb449df-f092-4485-9b67-dffe5a9d9ffa.png">

Error log from the api pod:
`2021-09-15 11:06:43.827  INFO 1 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler meta-data: Quartz Scheduler (v2.3.2) 'reportportal' with instanceId 'api:912f27cbc994c09458fc9443f87021e8'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 1 threads.
  Using job-store 'org.springframework.scheduling.quartz.LocalDataSourceJobStore' - which supports persistence. and is clustered.

2021-09-15 11:06:43.827  INFO 1 --- [           main] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler 'reportportal' initialized from an externally provided properties instance.
2021-09-15 11:06:43.827  INFO 1 --- [           main] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler version: 2.3.2
2021-09-15 11:06:43.827  INFO 1 --- [           main] org.quartz.core.QuartzScheduler          : JobFactory set to: com.epam.ta.reportportal.core.configs.SchedulerConfiguration$2@34eb5d01
2021-09-15 11:06:47.109  INFO 1 --- [           main] org.pf4j.DefaultPluginStatusProvider     : Enabled plugins: []
2021-09-15 11:06:47.109  INFO 1 --- [           main] org.pf4j.DefaultPluginStatusProvider     : Disabled plugins: []
2021-09-15 11:06:47.112  INFO 1 --- [           main] org.pf4j.DefaultPluginManager            : PF4J version 2.4.0 in 'deployment' mode
2021-09-15 11:06:50.543  INFO 1 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'logIndexTaskExecutor'
2021-09-15 11:06:50.898  INFO 1 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'demoDataTaskExecutor'
2021-09-15 11:06:51.102  INFO 1 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService 'taskScheduler'
2021-09-15 11:06:51.619 ERROR 1 --- [           main] c.e.t.r.f.d.minio.MinioDataStore         : Unable to find file 'test/secret-integration-salt'

io.minio.errors.ErrorResponseException: The specified bucket does not exist
	at io.minio.MinioClient.executeReq(MinioClient.java:1220)
	at io.minio.MinioClient.execute(MinioClient.java:1082)
	at io.minio.MinioClient.updateRegionCache(MinioClient.java:1235)
	at io.minio.MinioClient.getRegion(MinioClient.java:1280)
	at io.minio.MinioClient.executeGet(MinioClient.java:1339)
	at io.minio.MinioClient.getObject(MinioClient.java:1854)
	at io.minio.MinioClient.getObject(MinioClient.java:1647)
	at com.epam.ta.reportportal.filesystem.distributed.minio.MinioDataStore.load(MinioDataStore.java:83)
	at com.epam.ta.reportportal.config.EncryptConfiguration.loadOrGenerateIntegrationSalt(EncryptConfiguration.java:93)
	at com.epam.ta.reportportal.config.EncryptConfiguration.afterPropertiesSet(EncryptConfiguration.java:88)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:409)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:228)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.epam.ta.reportportal.core.configs.ReportPortalApp.main(ReportPortalApp.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
`

Kubernetes version:
`
Client Version: Major:"1", Minor:"21", GitVersion:"v1.21.4"
Server Version: Major:"1", Minor:"19", GitVersion:"v1.19.8+k3s1"
`

**Comment by AsoTora** [comment]
I am so lost here. Manually added files to minio bucket, yet the issue still persists.

**Comment by Roshick** [comment]
I see he is looking for "test/*" in your case, is there maybe some mismatch between the values in the helm chart and the values/envs in the pods/application? I'm also confused why it created the buckets with a "prj-" prefix which is undefined in my values.yaml as well as the default values.yaml.

**Comment by AsoTora** [comment]
@Roshick so did you fix it?

**Comment by Roshick** [comment]
Unfortunately not. :(

**Comment by evjlobanova** [comment]
@Cyberglamdring Could you please check?

**Comment by Cyberglamdring** [comment]
Hello,

By default, ReportPortal services create 3 buckets `prj-keystore`, `prj-users`, `rp-buket`. If this bucket isn't created automatically, please, compare your Helm chart / Docker-Compose with the actual [Kubernetes](https://github.com/reportportal/kubernetes/tree/master/reportportal) / [Docker](https://github.com/reportportal/reportportal/blob/master/docker-compose.yml) guide

Also, you can set additional values for `API`, `UAT`, `JOBS` services.

Helm chart template:
```yaml
- name: RP_BINARYSTORE_MINIO_DEFAULTBUCKETNAME
  value: "<BUCKET_NAME_1>"
- name: RP_INTEGRATION_SALT_PATH
  value: "<BUCKET_NAME_2>"
```

Docker-Compose:
```yaml
RP_BINARYSTORE_MINIO_DEFAULTBUCKETNAME: "<BUCKET_NAME_1>"
RP_INTEGRATION_SALT_PATH: "<BUCKET_NAME_2>"
```
