### ISSUE TITLE
Jenkins job got hang with error: System.NullReferenceException: Object reference not set to an instance of an object.     at ReportPortal.NUnitExtension.ReportPortalListener.FinishRun(XmlDocument xmlDoc)

### ISSUE THREAD

**Issue by Ashu171** [reportportal/reportportal#1540]
I know this issue was reported previously but i have used the versions greater then those which had fixes, but my Jenkins build got failed with below error :

Finishing to send the results to Report Portal... ReportPortal exception was thrown.

System.NullReferenceException: Object reference not set to an instance of an object.

   at ReportPortal.NUnitExtension.ReportPortalListener.FinishRun(XmlDocument xmlDoc)

Here is the package versions i am using for Report Portal:

<PackageReference Include="ReportPortal.Client" Version="2.1.14" />
    <PackageReference Include="ReportPortal.NUnitExtension.Bank" Version="0.12.0" />
    <PackageReference Include="ReportPortal.Serilog" Version="1.0.4" />
    <PackageReference Include="ReportPortal.Shared" Version="2.3.2" />
    <PackageReference Include="ReportPortalCaller" Version="0.8.0" />

**Comment by nvborisenko** [comment]
`ReportPortal.NUnitExtension.Bank` looks like your custom implementation, and this implementation is based on `ReportPortal.Shared v2.3.2` which was released 2 years ago. During this time the `ReportPortal.Shared` was significantly improved, particularly in exception handling area.

**Comment by Ashu171** [comment]
The issue got resolved after running tests on Selenium Grid environment on Jenkins.
