### ISSUE TITLE
reportportal_client.errors.Error: Service already stopped.

### ISSUE THREAD

**Issue by Tset-Noitamotua** [reportportal/reportportal#156]
I am trying to run this [PyTest example](https://github.com/reportportal/agent-python-pytest). On every run after the initial run I am getting this error:

```shell
File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/reportportal_client/service_async.py", line 153, in terminate
    raise Error("Service already stopped.")
reportportal_client.errors.Error: Service already stopped.
```
If I check `docker-compose ps` all services seem to be up and running
```shell
reportportal_api_1        sh -c java $JAVA_OPTS -Dja ...   Up      8080/tcp                                       
reportportal_gateway_1    sh -c java $JAVA_OPTS -Dja ...   Up      0.0.0.0:8080->8080/tcp, 0.0.0.0:8443->8443/tcp 
reportportal_mongodb_1    docker-entrypoint.sh --sma ...   Up      27017/tcp                                      
reportportal_redis_1      docker-entrypoint.sh redis ...   Up      6379/tcp                                       
reportportal_registry_1   sh -c java $JAVA_OPTS -Dja ...   Up      0.0.0.0:8761->8761/tcp                         
reportportal_uat_1        sh -c java $JAVA_OPTS -Dja ...   Up      8080/tcp                                       
reportportal_ui_1         sh -c java $JAVA_OPTS -Dja ...   Up      8080/tcp
```

So what am I missing or doing wrong?

here the full stack trace of above error
```shell
(ROBOT_2.7) wlad@wlad-VirtualBox:~/_GITHUB/catinabox$ pytest
=========================================== test session starts ============================================
platform linux2 -- Python 2.7.13, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /home/wlad/_GITHUB/catinabox, inifile: pytest.ini
plugins: reportportal-1.0.0, pep8-1.0.6, mock-1.6.0, mccabe-0.1, flakes-2.0.0, cov-2.5.1
collected 25 items 

rp_tests/test_reportportal.py s...
catinabox/__init__.py s..
catinabox/catactivities.py s..
catinabox/catgenerator.py s..
catinabox/catmath.py s..
catinabox/cattery.py s..Coverage.py warning: No data was collected. (no-data-collected)

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/main.py", line 105, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/main.py", line 141, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
INTERNALERROR>     wrap_controller.send(call_outcome)
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 280, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/main.py", line 164, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 254, in _wrapped_call
INTERNALERROR>     return call_outcome.get_result()
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 280, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 254, in _wrapped_call
INTERNALERROR>     return call_outcome.get_result()
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 280, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/runner.py", line 60, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/runner.py", line 75, in runtestprotocol
INTERNALERROR>     nextitem=nextitem))
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/runner.py", line 129, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
INTERNALERROR>     wrap_controller.send(call_outcome)
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/pytest_reportportal/plugin.py", line 55, in pytest_runtest_makereport
INTERNALERROR>     PyTestService.finish_pytest_item(item_result)
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/pytest_reportportal/service.py", line 116, in finish_pytest_item
INTERNALERROR>     self.RP.finish_test_item(**fta_rq)
INTERNALERROR>   File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/reportportal_client/service_async.py", line 256, in finish_test_item
INTERNALERROR>     self.queue.put_nowait(("finish_test_item", args))
INTERNALERROR> AttributeError: 'NoneType' object has no attribute 'put_nowait'
Traceback (most recent call last):
  File "/home/wlad/.virtualenvs/ROBOT_2.7/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/config.py", line 60, in main
    config._ensure_unconfigure()
  File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/config.py", line 917, in _ensure_unconfigure
    self.hook.pytest_unconfigure(config=self)
  File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/pytest_reportportal/plugin.py", line 92, in pytest_unconfigure
    PyTestService.terminate_service()
  File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/pytest_reportportal/service.py", line 54, in terminate_service
    self.RP.terminate()
  File "/home/wlad/.virtualenvs/ROBOT_2.7/local/lib/python2.7/site-packages/reportportal_client/service_async.py", line 153, in terminate
    raise Error("Service already stopped.")
reportportal_client.errors.Error: Service already stopped.
```

**Comment by Tset-Noitamotua** [comment]
Yes, I am able to login via UI.

But I will close this issue because I noticed that I have messed around a bit by mixing your pytest example with some other tests from [catinthebox][1] repo. The error happens when I try to run the tests of catinthebox repo. Sorry for bothering :-/

I am now able to execute the example from [agent-python-pytest][2] repo and can see the results in reportportal UI. It takes some time but I think I am starting to understand how reportportal works :)

[1]: https://github.com/keeppythonweird/catinabox
[2]: https://github.com/reportportal/agent-python-pytest
