### ISSUE TITLE
Docker-compose:  Connection to postgres:5432 refused

### ISSUE THREAD

**Issue by patsevanton** [reportportal/reportportal#1650]
Hello!
```
git clone https://github.com/reportportal/reportportal.git
cd reportportal
docker-compose up
```

Get error `Connection to postgres:5432 refused`
```
downloads-uat-1               | 2022-01-31 07:22:08.978 ERROR 1 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Exception during pool initialization.
downloads-uat-1               |
downloads-uat-1               | org.postgresql.util.PSQLException: Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
downloads-uat-1               |         at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:285) ~[postgresql-42.2.13.jar!/:42.2.13]
downloads-uat-1               |         at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49) ~[postgresql-42.2.13.jar!/:42.2.13]
downloads-uat-1               |         at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:217) ~[postgresql-42.2.13.jar!/:42.2.13]
```

**Comment by patsevanton** [comment]
Fix by https://github.com/reportportal/reportportal/pull/1651
