### ISSUE TITLE
ERROR: failed to add item to index page in "path_gist_idx" 

### ISSUE THREAD

**Issue by rahulk79** [reportportal/reportportal#1673]
When we are executing our test cases we are getting error -500 on client side . 

Please check log from deployed envirnment of client side report portal. -

```
[ERROR] 2022-02-11 14:56:50.430 [rp-io-21] c.e.r.u.SubscriptionUtils - Start test item completed with error
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 500
Status message: Internal Server Error
Error Message: Unclassified error [could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement]
Error Type: UNCLASSIFIED_ERROR



at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:85)
at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:61)
at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:526)
at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
at io.reactivex.Maybe.subscribe(Maybe.java:4290)
at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
[ERROR] 2022-02-11 14:56:50.430 [rp-io-22] c.e.r.u.SubscriptionUtils - [41] ReportPortal Finish test item execution error
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
```

On deployed environment we are getting following error -
```html
<html>
<body>
<!--StartFragment-->

used by: org.hibernate.exception.GenericJDBCException: could not execute statement
--
at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:200)
at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3449)
at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:3311)
at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3723)
at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:201)
at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:348)
at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:57)
at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:102)
at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1325)
at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1405)
at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1565)
at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1533)
... 76 common frames omitted
**Caused by: org.postgresql.util.PSQLException: ERROR: failed to add item to index page in "path_gist_idx"**
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:153)
at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:119)
at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
... 91 common frames omitted
2022-02-11 07:37:39.837 DEBUG 1 --- [cTaskExecutor-4] c.e.t.r.w.rabbit.AsyncReportingListener : onMessage - Rabbit message
parentItemId: d1174a6f-8931-4e25-93c2-41da10d18941
requestType: START_TEST
x-first-death-exchange: reporting

<!--EndFragment-->
</body>
</html> 
```

**Comment by rahulk79** [comment]
@MariyaIvanina , Can you please look into this issue.

**Comment by rahulk79** [comment]
Hi Team, 
Can we switch from GIST to GIN index to resolve this issue . Please let us know your thoughts on this approach ?

**Comment by rahulk79** [comment]
@[evjlobanova](https://github.com/evjlobanova) , Can you please look into this issue.

**Comment by DzmitryHumianiuk** [comment]
@rahulk79 what is the reason to switch it from `gist` to `gin`?

**Comment by rahulk79** [comment]
Hi @DzmitryHumianiuk , We thought of switching to gin to resolve index issue but it is not working . 

Can you please suggest solution for below error - 

 org.postgresql.util.PSQLException: ERROR: failed to add item to index page in "path_gist_idx"**
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:153)

**Comment by mrbinwin** [comment]
We also have the same issue.
v. 5.5.1

`2022-03-02 12:31:05.157 UTC [30999] LOG:  fixing incomplete split in index "path_gist_idx", block 2407659
2022-03-02 12:31:05.157 UTC [30999] STATEMENT:  update public.test_item set code_ref=$1, description=$2, has_children=$3, has_retries=$4, has_stats=$5, last_modified=$6, launch_id=$7, name=$8, parent_id=$9, path=$10, retry_of=$11, start_time=$12, test_case_hash=$13, test_case_id=$14, type=$15, unique_id=$16, uuid=$17 where item_id=$18
2022-03-02 12:31:05.157 UTC [30999] ERROR:  failed to add item to index page in "path_gist_idx"`

**Comment by Oleksii-kh89** [comment]
Hi @rahulk79 

Please, update to the latest version
