### ISSUE TITLE
[v5.6.0] Exception at the end of launch

### ISSUE THREAD

**Issue by talmoshe24** [reportportal/reportportal#1682]
I recently upgraded RP via docker from 5.4.0 to 5.6.0, and using agent-java-junit 5.0.0

Since the upgrade, we started to get errors in our test executions.
It doesn't happen all the time, but a few times during the last 2 days:

```
23:58:09  org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException There was an error in the forked processTest mechanism :: Report Portal returned error
23:58:09  Status code: 500
23:58:09  Status message: Internal Server Error
23:58:09  Error Message: Unclassified error [could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.LockAcquisitionException: could not execute statement]
23:58:09  Error Type: UNCLASSIFIED_ERROR
23:58:09  
23:58:09  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:513)
23:58:09  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkPerTestSet(ForkStarter.java:460)
23:58:09  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:301)
23:58:09  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:249)
23:58:09  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1217)
23:58:09  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1063)
23:58:09  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:889)
23:58:09  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
23:58:09  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
23:58:09  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
23:58:09  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
23:58:09  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
23:58:09  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
23:58:09  	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
23:58:09  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
23:58:09  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
23:58:09  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
23:58:09  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
23:58:09  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
23:58:09  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
23:58:09  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
23:58:09  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:58:09  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:58:09  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:58:09  	at java.lang.reflect.Method.invoke(Method.java:498)
23:58:09  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
23:58:09  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
23:58:09  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
23:58:09  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
23:58:09  Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked processTest mechanism :: Report Portal returned error
23:58:09  Status code: 500
23:58:09  Status message: Internal Server Error
23:58:09  Error Message: Unclassified error [could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.LockAcquisitionException: could not execute statement]
23:58:09  Error Type: UNCLASSIFIED_ERROR
23:58:09  
23:58:09  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:675)
23:58:09  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.access$600(ForkStarter.java:118)
23:58:09  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$2.call(ForkStarter.java:447)
23:58:09  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$2.call(ForkStarter.java:423)
23:58:09  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
23:58:09  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
23:58:09  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
23:58:09  	at java.lang.Thread.run(Thread.java:748)
```

**Comment by DzmitryHumianiuk** [comment]
@talmoshe24 first off, please update the the latest junit agent https://github.com/reportportal/agent-java-junit/releases/tag/5.1.0

as for the error: 500 code means that your server is in a bad shape, like really bad.
You should look into the logs of `service-api` once you see such a log again.

**Comment by talmoshe24** [comment]
@DzmitryHumianiuk I moved the VM to another host as it was overloaded.
Will keep track of this issue

**Comment by DzmitryHumianiuk** [comment]
then i assume it is resolved
