### ISSUE TITLE
[v5.6.3] Login failed with correct credentials.

### ISSUE THREAD

**Issue by SubratKumarTR** [reportportal/reportportal#1684]
We have upgraded from 5.6.2 to 5.6.3, But it was showing as login failed . we checked the docker container all the docker container are completely healthy .

Please find the below logs -
```
Basic Authentication Authorization header found for user 'ui'
2022-02-18 19:15:28.171 DEBUG 1 --- [nio-9999-exec-3] o.s.s.authentication.ProviderManager     : Authentication attempt using org.springframework.security.authentication.dao.DaoAuthenticationProvider
2022-02-18 19:15:28.270 DEBUG 1 --- [nio-9999-exec-3] o.s.s.w.a.www.BasicAuthenticationFilter  : Authentication success: org.springframework.security.authentication.UsernamePasswordAuthenticationToken@bdcc: Principal: org.springframework.security.core.userdetails.User@e94: Username: ui; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Not granted any authorities; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@ffff4c9c: RemoteIpAddress: 10.114.56.163; SessionId: null; Not granted any authorities
2022-02-18 19:15:28.270 DEBUG 1 --- [nio-9999-exec-3] o.s.security.web.FilterChainProxy        : /sso/oauth/token at position 6 of 11 in additional filter chain; firing Filter: 'RequestCacheAwareFilter'
2022-02-18 19:15:28.270 DEBUG 1 --- [nio-9999-exec-3] o.s.s.w.s.HttpSessionRequestCache        : saved request doesn't match
2022-02-18 19:15:28.270 DEBUG 1 --- [nio-9999-exec-3] o.s.security.web.FilterChainProxy        : /sso/oauth/token at position 7 of 11 in additional filter chain; firing Filter: 'SecurityContextHolderAwareRequestFilter'
2022-02-18 19:15:28.270 DEBUG 1 --- [nio-9999-exec-3] o.s.security.web.FilterChainProxy        : /sso/oauth/token at position 8 of 11 in additional filter chain; firing Filter: 'AnonymousAuthenticationFilter'
2022-02-18 19:15:28.270 DEBUG 1 --- [nio-9999-exec-3] o.s.s.w.a.AnonymousAuthenticationFilter  : SecurityContextHolder not populated with anonymous token, as it already contained: 'org.springframework.security.authentication.UsernamePasswordAuthenticationToken@bdcc: Principal: org.springframework.security.core.userdetails.User@e94: Username: ui; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Not granted any authorities; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@ffff4c9c: RemoteIpAddress: 10.114.56.163; SessionId: null; Not granted any authorities'
2022-02-18 19:15:28.270 DEBUG 1 --- [nio-9999-exec-3] o.s.security.web.FilterChainProxy        : /sso/oauth/token at position 9 of 11 in additional filter chain; firing Filter: 'SessionManagementFilter'
2022-02-18 19:15:28.270 DEBUG 1 --- [nio-9999-exec-3] s.CompositeSessionAuthenticationStrategy : Delegating to org.springframework.security.web.authentication.session.ChangeSessionIdAuthenticationStrategy@6075a4ea
2022-02-18 19:15:28.270 DEBUG 1 --- [nio-9999-exec-3] o.s.security.web.FilterChainProxy        : /sso/oauth/token at position 10 of 11 in additional filter chain; firing Filter: 'ExceptionTranslationFilter'
2022-02-18 19:15:28.270 DEBUG 1 --- [nio-9999-exec-3] o.s.security.web.FilterChainProxy        : /sso/oauth/token at position 11 of 11 in additional filter chain; firing Filter: 'FilterSecurityInterceptor'
2022-02-18 19:15:28.270 DEBUG 1 --- [nio-9999-exec-3] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/sso/oauth/token'; against '/sso/oauth/token'
2022-02-18 19:15:28.270 DEBUG 1 --- [nio-9999-exec-3] o.s.s.w.a.i.FilterSecurityInterceptor    : Secure object: FilterInvocation: URL: /sso/oauth/token; Attributes: [fullyAuthenticated]
2022-02-18 19:15:28.270 DEBUG 1 --- [nio-9999-exec-3] o.s.s.w.a.i.FilterSecurityInterceptor    : Previously Authenticated: org.springframework.security.authentication.UsernamePasswordAuthenticationToken@bdcc: Principal: org.springframework.security.core.userdetails.User@e94: Username: ui; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Not granted any authorities; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@ffff4c9c: RemoteIpAddress: 10.114.56.163; SessionId: null; Not granted any authorities
2022-02-18 19:15:28.271 DEBUG 1 --- [nio-9999-exec-3] o.s.s.access.vote.AffirmativeBased       : Voter: org.springframework.security.web.access.expression.WebExpressionVoter@2d32b341, returned: 1
2022-02-18 19:15:28.271 DEBUG 1 --- [nio-9999-exec-3] o.s.s.w.a.i.FilterSecurityInterceptor    : Authorization successful
2022-02-18 19:15:28.271 DEBUG 1 --- [nio-9999-exec-3] o.s.s.w.a.i.FilterSecurityInterceptor    : RunAsManager did not change Authentication object
2022-02-18 19:15:28.271 DEBUG 1 --- [nio-9999-exec-3] o.s.security.web.FilterChainProxy        : /sso/oauth/token reached end of additional filter chain; proceeding with original chain
2022-02-18 19:15:28.272 DEBUG 1 --- [nio-9999-exec-3] .s.o.p.e.FrameworkEndpointHandlerMapping : Mapped to org.springframework.security.oauth2.provider.endpoint.TokenEndpoint#postAccessToken(Principal, Map)
2022-02-18 19:15:28.272 DEBUG 1 --- [nio-9999-exec-3] .o.p.p.ResourceOwnerPasswordTokenGranter : Getting access token for: ui
2022-02-18 19:15:28.273 DEBUG 1 --- [nio-9999-exec-3] o.s.s.authentication.ProviderManager     : Authentication attempt using com.epam.reportportal.auth.basic.BasicPasswordAuthenticationProvider
2022-02-18 19:15:28.277  WARN 1 --- [nio-9999-exec-3] o.s.s.c.bcrypt.BCryptPasswordEncoder     : Empty encoded password
2022-02-18 19:15:28.285  INFO 1 --- [nio-9999-exec-3] s.s.l.DefaultSpringSecurityContextSource :  URL 'ldaps://vds-qa.int.thomsonreuters.com:636/ou=ead,ou=users,dc=enterpriseAD', root DN is 'ou=ead,ou=users,dc=enterpriseAD'
2022-02-18 19:15:28.287 ERROR 1 --- [nio-9999-exec-3] c.e.t.r.c.e.rest.RestExceptionHandler    : Handled error:

org.jasypt.exceptions.EncryptionOperationNotPossibleException: null
        at org.jasypt.encryption.pbe.StandardPBEByteEncryptor.decrypt(StandardPBEByteEncryptor.java:1169) ~[jasypt-1.9.3.jar!/:na]
        at org.jasypt.encryption.pbe.StandardPBEStringEncryptor.decrypt(StandardPBEStringEncryptor.java:738) ~[jasypt-1.9.3.jar!/:na]
        at org.jasypt.util.text.BasicTextEncryptor.decrypt(BasicTextEncryptor.java:112) ~[jasypt-1.9.3.jar!/:na]
        at com.epam.reportportal.auth.integration.ldap.LdapAuthProvider.lambda$getDelegate$1(LdapAuthProvider.java:72) ~[classes!/:na]
        at java.base/java.util.Optional.ifPresent(Optional.java:183) ~[na:na]
        at com.epam.reportportal.auth.integration.ldap.LdapAuthProvider.getDelegate(LdapAuthProvider.java:72) ~[classes!/:na]
        at com.epam.reportportal.auth.EnableableAuthProvider.supports(EnableableAuthProvider.java:59) ~[classes!/:na]
        at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:165) ~[spring-security-core-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.security.oauth2.provider.password.ResourceOwnerPasswordTokenGranter.getOAuth2Authentication(ResourceOwnerPasswordTokenGranter.java:75) ~[spring-security-oauth2-2.4.0.RELEASE.jar!/:na]
        at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.getAccessToken(AbstractTokenGranter.java:76) ~[spring-security-oauth2-2.4.0.RELEASE.jar!/:na]
        at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.grant(AbstractTokenGranter.java:71) ~[spring-security-oauth2-2.4.0.RELEASE.jar!/:na]
        at org.springframework.security.oauth2.provider.CompositeTokenGranter.grant(CompositeTokenGranter.java:42) ~[spring-security-oauth2-2.4.0.RELEASE.jar!/:na]
        at org.springframework.security.oauth2.config.annotation.web.configurers.AuthorizationServerEndpointsConfigurer$4.grant(AuthorizationServerEndpointsConfigurer.java:587) ~[spring-security-oauth2-2.4.0.RELEASE.jar!/:na]
        at org.springframework.security.oauth2.provider.endpoint.TokenEndpoint.postAccessToken(TokenEndpoint.java:136) ~[spring-security-oauth2-2.4.0.RELEASE.jar!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:652) ~[tomcat-embed-core-9.0.37.jar!/:4.0.FR]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.37.jar!/:4.0.FR]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.37.jar!/:9.0.37]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:204) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77) ~[spring-security-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
```

Its should allow us to login , but it was giving error while login and in superadmin credential it was  not giving error but not sign in. the error while login in with our  credential is "An error occurred while connecting to server: Unclassified error [null] ". Please find the below screenshot.

![image](https://user-images.githubusercontent.com/76808612/155210552-3d3866bb-7699-4566-bda9-fe2ca87fda6d.png)

The error message is in the bottom of the screenshot.

Please let us know , if any additional information is required .

Regards,
Subrat.

**Comment by SubratKumarTR** [comment]
Hi Team,

Can i get some update on this as we are planning to migrate  from 5.6.2 to 5.6.3 ?

Please let us know , if any additional information is required .
Regards,
Subrat.

**Comment by SubratKumarTR** [comment]
Hi Team,

Please can we get  some update on this as we are planning to migrate from 5.6.2 to 5.6.3 ?

Please let us know , if any additional information is required .

Regards,
Subrat.

**Comment by Oleksii-kh89** [comment]
Hi, @SubratKumarTR I recommend you to update to the latest version and try again. Or another option is to rebuild services
