### ISSUE TITLE
Getting below error while trying integrate with TESTNG FRAMEWORK (Log4j)

### ISSUE THREAD

**Issue by NareshIM** [reportportal/reportportal#1690]
ava.lang.NoSuchMethodError: 'okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.callTimeout(java.time.Duration)'
	at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:542)
	at com.epam.reportportal.service.ReportPortal$Builder.lambda$buildClient$1(ReportPortal.java:430)
	at java.base/java.util.Optional.orElseGet(Optional.java:362)
	at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:430)
	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:407)
	at com.epam.reportportal.testng.TestNGService.<clinit>(TestNGService.java:93)
	at com.epam.reportportal.utils.MemoizingSupplier.get(MemoizingSupplier.java:42)
	at com.epam.reportportal.testng.ReportPortalTestNGListener.<init>(ReportPortalTestNGListener.java:33)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:350)
	at java.base/java.lang.Class.newInstance(Class.java:645)
	at org.testng.internal.ClassHelper.newInstance(ClassHelper.java:69)
	at org.testng.TestNG.addListeners(TestNG.java:949)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:912)
	at org.testng.TestNG.initializeEverything(TestNG.java:996)
	at org.testng.remote.support.RemoteTestNG6_12.initialize(RemoteTestNG6_12.java:22)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:98)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by HardNorth** [comment]
Duplicate: https://github.com/reportportal/agent-java-testNG/issues/182
