### ISSUE TITLE
Test run breaks with unclassified error (jbehave)

### ISSUE THREAD

**Issue by ksuglotova** [reportportal/reportportal#170]
Received from Andrew Patin:

Sometimes test run breaks with follow error. Is that possible to fix ? 

Stack-trace:
```
com.epam.reportportal.exception.ReportPortalServerException: Report Portal returned error
Status code: 500
Status message: 
Error Message: Unclassified error [Null return value from advice does not match primitive return type for: public abstract boolean com.epam.ta.reportportal.database.dao.ProjectRepositoryCustom.isAssignedToProject(java.lang.String,java.lang.String)]
Error Type: UNCLASSIFIED_ERROR
Stack Trace: 
 at com.epam.reportportal.service.ReportPortalErrorHandler.handleServerError(ReportPortalErrorHandler.java:52)
 at com.epam.reportportal.restclient.endpoint.DefaultErrorHandler.handle(DefaultErrorHandler.java:76)
 at com.epam.reportportal.restclient.endpoint.DefaultErrorHandler.handle(DefaultErrorHandler.java:40)
 at com.epam.reportportal.restclient.endpoint.HttpClientRestEndpoint.executeInternal(HttpClientRestEndpoint.java:341)
 at com.epam.reportportal.restclient.endpoint.HttpClientRestEndpoint.post(HttpClientRestEndpoint.java:106)
 at com.epam.reportportal.service.ReportPortalService.startTestItem(ReportPortalService.java:246)
 at com.epam.reportportal.jbehave.JBehaveUtils.startStep(JBehaveUtils.java:253)
 at com.epam.reportportal.jbehave.ReportPortalStoryReporter.beforeStep(ReportPortalStoryReporter.java:70)
 at org.jbehave.core.reporters.DelegatingStoryReporter.beforeStep(DelegatingStoryReporter.java:127)
 at org.jbehave.core.reporters.ConcurrentStoryReporter.beforeStep(ConcurrentStoryReporter.java:227)
 at org.jbehave.core.steps.StepCreator$ParametrisedStep.describeTo(StepCreator.java:587)
 at org.jbehave.core.embedder.StoryRunner$FineSoFar.run(StoryRunner.java:532)
 at org.jbehave.core.embedder.StoryRunner.runStepsWhileKeepingState(StoryRunner.java:515)
 at org.jbehave.core.embedder.StoryRunner.runScenarioSteps(StoryRunner.java:479)
 at org.jbehave.core.embedder.StoryRunner.runStepsWithLifecycle(StoryRunner.java:445)
 at org.jbehave.core.embedder.StoryRunner.runScenariosParametrisedByExamples(StoryRunner.java:434)
 at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:303)
 at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:220)
 at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:181)
 at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:262)
 at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:229)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)
``` 
 Agent jbehave, version 2.6.0

One of the suggestions is that error was caused by updating RP server. 
Link to the step after which launch was broken
https://rp.epam.com/ui/#epm-prmo/launches/592eebef36d1a000069c5ac9/5956dd9136d1a00006bbada1/5956dd9236d1a00006bbadff/5956dd9736d1a00006bbaf25?page.page=2&page.size=50&page.sort=start_time%2CASC&log.item=5956df0736d1a00006bbf6db
The rest stories run well. 
Launch started at 2017-07-01 02:24:00
Last broken stop started at 2017-07-01 02:30:15
Got the error at Jenkins, version 2.60.1

**Comment by ksuglotova** [comment]
Andrew Patin:

Today 2 tests broke in a one launch the same way:
"ECA-2341 Permission Matrix Without ASSIGNMENT Line 04.story" and "ECA-2341 Permission Matrix Without ASSIGNMENT Line 05.story" (both dropped down during the run)

https://rp.epam.com/ui/#epm-prmo/launches/592eebef36d1a000069c5ac9/595c217036d1a00006601e8b/595c28bb36d1a0000662d6e2/595c28c036d1a0000662d8bc?page.page=2&page.size=50&page.sort=start_time%2CASC

https://rp.epam.com/ui/#epm-prmo/launches/592eebef36d1a000069c5ac9/595c217036d1a00006601e8b/595c283536d1a0000662a3ce/595c283936d1a0000662a483?page.page=1&page.size=50&page.sort=start_time%2CASC

**Comment by avarabyeu** [comment]
@ksuglotova could you please check whether it can be reproduced with agent v3.0.0

**Comment by ksuglotova** [comment]
@avarabyeu They use a framework e3s. Asked about version

**Comment by avarabyeu** [comment]
Closing due to inactivity. Seems like issue is related to server side, e.g. to integration of spring-cache and redis. Redis is supposed to be remove in nearest future.
