### ISSUE TITLE
Can't login to RP...stuck at "Loading" (top-left of screen).....console showing TypeError in main.app.8524ca.js:375

### ISSUE THREAD

**Issue by jsmith085** [reportportal/reportportal#1736]
**Describe the bug**
...
Kubernetes 1.22 deploy of RP 
All pods in RUNNING state.  Access currently via NodePort (31080) config made to service/reportport-ui (in lieu of getting a working nginx ingress!).
Attempting first login to ReportPortal.  Stuck at "Loading" in top left of screen....no exceptions stemming from login attempt that I can see in logs across all pods.  Relevant logs below.  Chrome and Firefox DevTools > Console revealing this error:

TypeError: can't convert undefined to object (in main.app.8524ca.js:375:136058)

Finally, because the symptom matched with what I was reading here......
http://reportportal.io/documentation/documentation.html?n
(Referring to section 6, Application connections pool tuning)

.....I upgraded the PG max connections (to 500) and RP_DATASOURCE_MAXIMUM_POOL_SIZE (to 100) per the above doc  recommendations: 

**Expected behavior**
Get presented with login screen requesting credentials.

**Screenshots**
Here: 
![ReportPortal_Login_Error1](https://user-images.githubusercontent.com/388280/167746166-044a14da-2301-403c-b561-4484567cbb50.PNG)

**Versions:**
 - Windows 10 + FF v100, Ubuntu 20.04 + FFv99 and Chrome Version 96.0.4664.110 (Official Build) (64-bit)
 - RP installed from here: https://github.com/reportportal/kubernetes/releases/tag/reportportal-5.7.0
 - Can't get to Login form so can't provide that sorry

**Logs**

2 sections below, pod logs for reporport-api and reportportal-ui, last 100 lines of each after stalled login, 

**pod log reportportal-ui**

```
[operations@lum-reportportal-kubernetes-master-vm-0 reportportal]$ kg pods
NAME                                                              READY   STATUS    RESTARTS      AGE
elasticsearch-master-0                                            1/1     Running   0             36h
elasticsearch-master-1                                            1/1     Running   0             36h
elasticsearch-master-2                                            1/1     Running   0             36h
minio-69bdd44947-b85zc                                            1/1     Running   1 (36h ago)   36h
nginx-1-nginx-ingress-controller-597c6c8bf8-jqcgc                 1/1     Running   0             38h
nginx-1-nginx-ingress-controller-default-backend-6d7bbcf65v8w9j   1/1     Running   0             38h
postgresql-postgresql-0                                           1/1     Running   0             106m
rabbitmq-0                                                        1/1     Running   0             36h
reportportal-analyzer-0                                           1/1     Running   0             104m
reportportal-analyzer-train-0                                     1/1     Running   0             104m
reportportal-api-c9787df58-gz4tz                                  1/1     Running   0             104m
reportportal-index-6f4449946b-g59bw                               1/1     Running   0             104m
reportportal-jobs-6c766f68b-q9sh8                                 1/1     Running   0             104m
reportportal-metrics-gatherer-54fb568694-szg5k                    1/1     Running   0             104m
reportportal-uat-56dd5dfbbd-wd6qk                                 1/1     Running   0             104m
reportportal-ui-5b75f8f95d-7fsn6                                  1/1     Running   0             104m
[operations@lum-reportportal-kubernetes-master-vm-0 reportportal]$ 


[operations@lum-reportportal-kubernetes-master-vm-0 reportportal]$ kl reportportal-ui-5b75f8f95d-7fsn6 --tail=100
10.244.1.1 - - [11/May/2022:00:03:05 +0000] "GET /health HTTP/1.1" 200 1956 "-" "kube-probe/1.22"
10.244.1.1 - - [11/May/2022:00:03:15 +0000] "GET /health HTTP/1.1" 200 1956 "-" "kube-probe/1.22"

.....81 duplicate lines removed to improve readability.....

10.244.1.1 - - [11/May/2022:00:16:55 +0000] "GET /health HTTP/1.1" 200 1956 "-" "kube-probe/1.22"
10.244.1.1 - - [11/May/2022:00:17:05 +0000] "GET /health HTTP/1.1" 200 1956 "-" "kube-probe/1.22"
10.244.0.0 - - [11/May/2022:00:17:12 +0000] "GET / HTTP/1.1" 200 1037 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
10.244.0.0 - - [11/May/2022:00:17:12 +0000] "GET /polyfills.app.8524ca.js HTTP/1.1" 200 15979 "http://10.22.14.10:31080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
10.244.0.0 - - [11/May/2022:00:17:12 +0000] "GET /styles.app.8524ca.js HTTP/1.1" 200 140 "http://10.22.14.10:31080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
10.244.0.0 - - [11/May/2022:00:17:13 +0000] "GET /styles.8524ca.css HTTP/1.1" 200 44431 "http://10.22.14.10:31080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
10.244.0.0 - - [11/May/2022:00:17:15 +0000] "GET /main.8524ca.css HTTP/1.1" 200 136308 "http://10.22.14.10:31080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
10.244.1.1 - - [11/May/2022:00:17:15 +0000] "GET /health HTTP/1.1" 200 1956 "-" "kube-probe/1.22"
10.244.1.1 - - [11/May/2022:00:17:25 +0000] "GET /health HTTP/1.1" 200 1956 "-" "kube-probe/1.22"
10.244.0.0 - - [11/May/2022:00:17:26 +0000] "GET /main.app.8524ca.js HTTP/1.1" 200 2493906 "http://10.22.14.10:31080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
10.244.0.0 - - [11/May/2022:00:17:30 +0000] "GET /3.app.8524ca.js HTTP/1.1" 200 13445 "http://10.22.14.10:31080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
10.244.0.0 - - [11/May/2022:00:17:31 +0000] "GET /composite/info HTTP/1.1" 200 1037 "http://10.22.14.10:31080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
10.244.0.0 - - [11/May/2022:00:17:31 +0000] "GET /media/OpenSans-Regular-webfont.woff2 HTTP/1.1" 200 41040 "http://10.22.14.10:31080/main.8524ca.css" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
10.244.0.0 - ui [11/May/2022:00:17:31 +0000] "GET /api/v1/user HTTP/1.1" 200 1037 "http://10.22.14.10:31080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
10.244.0.0 - - [11/May/2022:00:17:32 +0000] "GET /favicon.ico HTTP/1.1" 200 5137 "http://10.22.14.10:31080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
10.244.1.1 - - [11/May/2022:00:17:35 +0000] "GET /health HTTP/1.1" 200 1956 "-" "kube-probe/1.22"
10.244.1.1 - - [11/May/2022:00:17:45 +0000] "GET /health HTTP/1.1" 200 1956 "-" "kube-probe/1.22"
[operations@lum-reportportal-kubernetes-master-vm-0 reportportal]$ 
```

**pod log reportportal-api**

```
[operations@lum-reportportal-kubernetes-master-vm-0 reportportal]$ kg pods
NAME                                                              READY   STATUS    RESTARTS      AGE
elasticsearch-master-0                                            1/1     Running   0             36h
elasticsearch-master-1                                            1/1     Running   0             36h
elasticsearch-master-2                                            1/1     Running   0             36h
minio-69bdd44947-b85zc                                            1/1     Running   1 (36h ago)   36h
nginx-1-nginx-ingress-controller-597c6c8bf8-jqcgc                 1/1     Running   0             38h
nginx-1-nginx-ingress-controller-default-backend-6d7bbcf65v8w9j   1/1     Running   0             38h
postgresql-postgresql-0                                           1/1     Running   0             106m
rabbitmq-0                                                        1/1     Running   0             36h
reportportal-analyzer-0                                           1/1     Running   0             104m
reportportal-analyzer-train-0                                     1/1     Running   0             104m
reportportal-api-c9787df58-gz4tz                                  1/1     Running   0             104m
reportportal-index-6f4449946b-g59bw                               1/1     Running   0             104m
reportportal-jobs-6c766f68b-q9sh8                                 1/1     Running   0             104m
reportportal-metrics-gatherer-54fb568694-szg5k                    1/1     Running   0             104m
reportportal-uat-56dd5dfbbd-wd6qk                                 1/1     Running   0             104m
reportportal-ui-5b75f8f95d-7fsn6                                  1/1     Running   0             104m
[operations@lum-reportportal-kubernetes-master-vm-0 reportportal]$ 


[operations@lum-reportportal-kubernetes-master-vm-0 reportportal]$ kl reportportal-api-c9787df58-gz4tz --tail=100
2022-05-10 22:30:16.698  INFO 1 --- [           main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
2022-05-10 22:30:16.913  INFO 1 --- [           main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
2022-05-10 22:30:17.701  INFO 1 --- [           main] org.jooq.Constants                       : 
                                      
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@  @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@
@@@@@@@@@@@@@@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@  @@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@        @@  @  @  @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  Thank you for using jOOQ 3.12.4
                                      
2022-05-10 22:30:17.923  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getActivitiesUsingGET_1
2022-05-10 22:30:18.108  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getAllowableIssueTypesUsingGET_1
2022-05-10 22:30:18.118  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getSetOfIntegrationSystemFieldsUsingGET_1
2022-05-10 22:30:18.413  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getGlobalIntegrationsUsingGET_1
2022-05-10 22:30:18.421  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getProjectIntegrationsUsingGET_1
2022-05-10 22:30:18.426  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: testIntegrationConnectionUsingGET_1
2022-05-10 22:30:18.721  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: finishLaunchUsingPUT_1
2022-05-10 22:30:18.915  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: mergeLaunchesUsingPOST_1
2022-05-10 22:30:18.918  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: startLaunchUsingPOST_1
2022-05-10 22:30:19.016  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: createLogUsingPOST_1
2022-05-10 22:30:19.019  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: createLogEntryUsingPOST_1
2022-05-10 22:30:19.126  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: onBoardingUsingGET_1
2022-05-10 22:30:19.216  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: deleteProjectUsingDELETE_1
2022-05-10 22:30:19.329  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getProjectUsersUsingGET_1
2022-05-10 22:30:19.599  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: bulkUpdateUsingPUT_1
2022-05-10 22:30:19.612  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: finishTestItemUsingPUT_1
2022-05-10 22:30:19.615  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getAttributeKeysUsingGET_1
2022-05-10 22:30:19.618  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getAttributeKeysUsingGET_2
2022-05-10 22:30:19.624  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getAttributeValuesUsingGET_1
2022-05-10 22:30:19.627  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getAttributeValuesUsingGET_2
2022-05-10 22:30:19.729  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getTestItemsUsingGET_1
2022-05-10 22:30:19.800  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getTestItemsUsingGET_2
2022-05-10 22:30:19.822  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: startChildItemUsingPOST_1
2022-05-10 22:30:19.824  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: startRootItemUsingPOST_1
2022-05-10 22:30:19.921  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getMyselfUsingGET_1
2022-05-10 22:30:20.033  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getWidgetUsingGET_1
2022-05-10 22:30:20.110  INFO 1 --- [           main] c.e.t.r.c.c.SchedulerConfiguration$1     : Starting Quartz Scheduler now
2022-05-10 22:30:20.122  INFO 1 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler reportportal_$_api:ca551b044d93edfc6ae7a3b44bb8698b started.
2022-05-10 22:30:20.557  INFO 1 --- [portal_Worker-1] c.e.t.r.job.CleanExpiredCreationBidsJob  : Cleaning expired user creation bids finished. Deleted 0 bids
2022-05-10 22:30:35.502  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8585 (http) with context path ''
2022-05-10 22:30:35.506  INFO 1 --- [           main] c.e.t.r.core.configs.ReportPortalApp     : Started ReportPortalApp in 75.905 seconds (JVM running for 78.126)
2022-05-10 22:30:36.408 ERROR 1 --- [           main] c.e.t.r.f.d.minio.MinioDataStore         : Unable to find file 'keystore/migration'

io.minio.errors.ErrorResponseException: The specified key does not exist.
	at io.minio.MinioClient.executeReq(MinioClient.java:1220)
	at io.minio.MinioClient.execute(MinioClient.java:1082)
	at io.minio.MinioClient.executeGet(MinioClient.java:1339)
	at io.minio.MinioClient.getObject(MinioClient.java:1854)
	at io.minio.MinioClient.getObject(MinioClient.java:1647)
	at com.epam.ta.reportportal.filesystem.distributed.minio.MinioDataStore.load(MinioDataStore.java:83)
	at com.epam.ta.reportportal.core.events.handler.IntegrationSecretsMigrationHandler.migrate(IntegrationSecretsMigrationHandler.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:305)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:190)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:153)
	at com.epam.ta.reportportal.core.events.multicaster.DelegatingApplicationEventMulticaster.doInvokeListener(DelegatingApplicationEventMulticaster.java:59)
	at com.epam.ta.reportportal.core.events.multicaster.DelegatingApplicationEventMulticaster.lambda$invokeListener$2(DelegatingApplicationEventMulticaster.java:50)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:203)
	at com.epam.ta.reportportal.core.events.multicaster.DelegatingApplicationEventMulticaster.invokeListener(DelegatingApplicationEventMulticaster.java:44)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360)
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:103)
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:77)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.epam.ta.reportportal.core.configs.ReportPortalApp.main(ReportPortalApp.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)

2022-05-10 22:30:36.408  INFO 1 --- [           main] c.e.h.IntegrationSecretsMigrationHandler : Secrets migration is not needed
2022-05-10 22:30:55.332  INFO 1 --- [nio-8585-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-05-10 22:30:55.332  INFO 1 --- [nio-8585-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2022-05-10 22:30:55.403  INFO 1 --- [nio-8585-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 71 ms
2022-05-10 22:30:55.538  INFO 1 --- [nio-8585-exec-1] o.s.a.r.c.CachingConnectionFactory       : Attempting to connect to: rabbitmq.default.svc.cluster.local:5672
2022-05-10 22:30:55.598  INFO 1 --- [nio-8585-exec-1] o.s.a.r.c.CachingConnectionFactory       : Created new connection: analyzerConnectionFactory#6a97517:0/SimpleConnection@7b412603 [delegate=amqp://rabbitadmin@10.110.89.224:5672/analyzer, localPort= 40014]
2022-05-10 23:29:51.256  INFO 1 --- [portal_Worker-1] c.e.t.r.job.InterruptBrokenLaunchesJob   : Interrupt broken launches job has been started
2022-05-10 23:29:52.028  INFO 1 --- [portal_Worker-1] c.e.t.r.job.CleanExpiredCreationBidsJob  : Cleaning expired user creation bids finished. Deleted 0 bids
[operations@lum-reportportal-kubernetes-master-vm-0 reportportal]$
```

**Comment by Jmainguy** [comment]
@jsmith085 you figure it out? We running into the same thing, wondering if its related to elasticsearch or not.

**Comment by ShanmukhaGajula** [comment]
I am facing similar issue 
![image](https://github.com/reportportal/reportportal/assets/21192877/96dd8ac8-72b4-4d69-9982-99f77100a52d)

**Comment by jamaalscarlett** [comment]
@irynakozak2 I am still seeing this on the latest version

**Comment by irynakozak2** [comment]
@jamaalscarlett Hi! The error in the API service doesn't directly relate to that behavior, I guess everything is OK on the API side and the Application connection pool tuning is a great update, however isn't the issue route-cause. We had the same issue on the UI side, let me check and I'll come back to you shortly.

**Comment by ShaiShalevSQream** [comment]
Also just try to install RP helm chart and faced same issue where all pods ar running but the UI stucked on loading.

**Comment by irynakozak2** [comment]
Hi everyone! We are going to proceed with the investigation from our side, I'll keep you updated on that.

**Comment by GTmAster** [comment]
Have the same issue at the latest version

**Comment by PhuongTMR** [comment]
same here with the latest version using the develop branch. please keep me on an update.

**Comment by hlebkanonik** [comment]
Hello everyone! To access the ReportPortal UI, you need to use any [Ingress Controller](https://github.com/reportportal/kubernetes/blob/master/reportportal/values.yaml#L609) in the Cluster. Attempting to connect directly to the UI pod IP or Node Port will not redirect correctly. Can you confirm that you are using NGINX Ingress?

**Comment by ShaiShalevSQream** [comment]
I Was able to access the UI only when using ingress.

**Comment by GTmAster** [comment]
Solved it today for myself. For some reason it doesn't work with Traefik (default ingress controller for Rancher Desktop). Switched it to NGINX controller, and everything run smoothly.
