### ISSUE TITLE
Any plugins available to connect report portal with fitnesse framework

### ISSUE THREAD

**Issue by ZINGYRAJEEV** [reportportal/reportportal#1819]
Is there any plugins available to connect reportportal with fitnesse framework?

**Comment by ZINGYRAJEEV** [comment]
Any update on this please?

**Comment by HardNorth** [comment]
@ZINGYRAJEEV No, there is no such integration.

**Comment by ZINGYRAJEEV** [comment]
We are using fitnesse framework where  java.util.logging.Logger is used for logging ; For java.util.logging.Logger, there is no options available to send the logs to report portal ; in such scenarios what are possible solutions to implement report portal solution?

**Comment by HardNorth** [comment]
@ZINGYRAJEEV You can use [jul-to-slf4j](https://stackoverflow.com/questions/9117030/jul-to-slf4j-bridge) bridge and then use Logback, for instance.

**Comment by ZINGYRAJEEV** [comment]
Hi HardNorth

I am using Logback-test.xml for as listner but getting below error . Do you know the reason for same?

23:21:31,864 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [com.epam.reportportal.logback.appender.ReportPortalAppender]
23:21:31,885 |-ERROR in ch.qos.logback.core.joran.action.AppenderAction - Could not create an Appender of type [com.epam.reportportal.logback.appender.ReportPortalAppender]. ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type com.epam.reportportal.logback.appender.ReportPortalAppender
	at ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type com.epam.reportportal.logback.appender.ReportPortalAppender
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:68)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:44)

Caused by: java.lang.NoClassDefFoundError: com/epam/reportportal/service/logs/LoggingSubscriber
	at 	at com.epam.reportportal.logback.appender.ReportPortalAppender.<clinit>(ReportPortalAppender.java:41)
	at 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at 	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
	at 	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
	at 	at java.base/java.lang.Class.newInstance(Class.java:645)

**Comment by DzmitryHumianiuk** [comment]
@ZINGYRAJEEV what is used in Fitness to trigger test cases itself?
is it jUnit behind the scene?

**Comment by ZINGYRAJEEV** [comment]
yes It's junit

thanks
Rajeev Kumar

**Comment by DzmitryHumianiuk** [comment]
@ZINGYRAJEEV did you try a regular jUnit integration?
since RP connects to test runner, not the test framework

**Comment by ZINGYRAJEEV** [comment]
Okay. I will check it.

thank you
Rajeev Kumar
