### ISSUE TITLE
Jira cloud integration fails with SSL error

### ISSUE THREAD

**Issue by chahalprabh92** [reportportal/reportportal#1834]
**Describe the bug**
I am trying the jira cloud integration. 

Reqiest
Request URL: http://10.66.2.42:8080/api/v1/integration/zscaler_release_62_automation/JIRA%20Cloud
Request Method: POST
Status Code: 409 Conflict
Remote Address: 10.66.2.42:8080
Referrer Policy: strict-origin-when-cross-origin

Response
{"errorCode":40302,"message":"Impossible interact with integration. Unable to connect to Cloud Jira. Message: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"}

Backend shows below exception
23:05:01.749 ERROR 1 --- [nio-8585-exec-4] org.hibernate.orm.bytecode               : Unable to connect to Cloud Jira: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.atlassian.httpclient.apache.httpcomponents.ApacheAsyncHttpClient.lambda$doExecute$4(ApacheAsyncHttpClient.java:345)
	at io.atlassian.util.concurrent.Promises.lambda$biFunction$7(Promises.java:424)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$1.lambda$doFailed$1(SettableFuturePromiseHttpPromiseAsyncClient.java:42)
	at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient.runInContext(SettableFuturePromiseHttpPromiseAsyncClient.java:61)
	at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable.run(SettableFuturePromiseHttpPromiseAsyncClient.java:129)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
		

**Expected behavior**
...
Integration should work
**Screenshots**
If applicable
<img width="1392" alt="Screen Shot 2022-09-02 at 12 26 35 PM" src="https://user-images.githubusercontent.com/74168134/188226658-10ab3990-ffd3-418b-9b82-fa429d325fab.png">

**Versions:**
 - OS, Browser Mac , Version 104.0.5112.79 
 - Version of RP 5.7.2
 - Reportportal  is running on Ubuntu 20.04.1 using docker

**Comment by dhirennotani19** [comment]
Hi @chahalprabh92,

This is Dhiren from Exalate.

[Exalate](https://marketplace.atlassian.com/apps/1213645/exalate-jira-issue-sync-more?hosting=cloud&tab=overview), provides a fully bi-directional synchronization between GitHub and Jira (among other ITSM systems) that is fully customizable. It is easy to set up and Exalate uses a scripting engine which is based on Groovy scripts where you can control what data you want to share and even you can independently handle the incoming information. You can achieve complex use-cases with ease. 

You can easily fetch data from GitHub repositories and sync issues from GitHub to issues in Jira.

If you would like to see a customized demo of the product in action, feel free to [book a slot](https://exalate.com/book-demo/) with us. 

Thanks
Dhiren

**Comment by DzmitryHumianiuk** [comment]
@chahalprabh92 your RP instance should also have a trusted SSL certificate.

in your case JIRA cloud rejects connections from untrusted endpoint.

**Comment by chahalprabh92** [comment]
hi @DzmitryHumianiuk 

Can you please share the steps or any documentation?

I am running the reportportal instance by docker. I have not changed anything.

**Comment by DzmitryHumianiuk** [comment]
@chahalprabh92 here we go: https://reportportal.io/docs/Setup-TLS(SSL)-in
