### ISSUE TITLE
UAT / Authorization Okta integration with proxy failing

### ISSUE THREAD

**Issue by imigu17** [reportportal/reportportal#1887]
Hey team! I recently tried to deploy Report Portal. One of the acceptance criteria was integration with SSO (OKTA). After configuring the plugin I got a Timeout error. Unfortunately, the place where the container is running requires setting up a proxy to access public endpoints (and the URL for SSO is such). 
I tried several methods to accomplish it:
1. setting up `PROXY_PATH` - I found it's used in one of the other modules, but UAT is ignoring it.
2. setting up `http_proxy / no_proxy` env - Unfortunately it's also ignored
3. modifying JAVA_OPTS with `-Dhttp.proxyHost= -Dhttp.proxyPort= -Dhttp.nonProxyHosts=`
The last approach worked (at least I did not get the Timeout error anymore), but the UAT container started to crash.
I started to investigate what's happening and here are my findings:
`Unable to find file 'keystore/secret-integration-salt'
io.minio.errors.InvalidResponseException: Non-XML response from server`
I tried to compare it with a deployment without proxy settings :
Default deployment create / use `prj-keystore/secret-integration-salt` bucket.
I tried to manually create `keystore` bucket in minio without salt file - still the same error. I also copied secret-integration-salt to a `keystore` bucket - without any success, I was still getting the same error.
I also tried to add some additional env - bucket prefix - also no change in behavior. 

I'm not sure if that's a bug in UAT or I'm missing something? 
Below is the full log I got from the container before it crashed.

```
2022-11-10 20:36:48.563 INFO 1 --- [ main] c.e.r.auth.AuthServerApplication : Starting AuthServerApplication on globalqa.aws-usw2-dev.stage.reportportal.services.2863db5d74ff7 with PID 1 (/service-authorization-5.7.0-exec.jar started by root in /)
2022-11-10 20:36:48.566 INFO 1 --- [ main] c.e.r.auth.AuthServerApplication : The following profiles are active: default
2022-11-10 20:36:51.448 INFO 1 --- [ main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2022-11-10 20:36:51.957 INFO 1 --- [ main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 500ms. Found 32 JPA repository interfaces.
2022-11-10 20:37:03.251 INFO 1 --- [ main] o.s.b.w.embedded.tomcat.TomcatWebServer : Tomcat initialized with port(s): 9999 (http)
2022-11-10 20:37:03.331 INFO 1 --- [ main] o.apache.catalina.core.StandardService : Starting service [Tomcat]
2022-11-10 20:37:03.331 INFO 1 --- [ main] org.apache.catalina.core.StandardEngine : Starting Servlet engine: [Apache Tomcat/9.0.37]
2022-11-10 20:37:03.523 INFO 1 --- [ main] o.a.c.c.C.[Tomcat].[localhost].[/] : Initializing Spring embedded WebApplicationContext
2022-11-10 20:37:03.523 INFO 1 --- [ main] o.s.web.context.ContextLoader : Root WebApplicationContext: initialization completed in 14781 ms
2022-11-10 20:37:03.937 INFO 1 --- [ main] com.zaxxer.hikari.HikariDataSource : HikariPool-1 - Starting...
2022-11-10 20:37:04.862 INFO 1 --- [ main] com.zaxxer.hikari.HikariDataSource : HikariPool-1 - Start completed.
2022-11-10 20:37:06.234 INFO 1 --- [ main] o.hibernate.jpa.internal.util.LogHelper : HHH000204: Processing PersistenceUnitInfo [name: default]
2022-11-10 20:37:06.544 INFO 1 --- [ main] org.hibernate.Version : HHH000412: Hibernate ORM core version 5.4.18.Final
2022-11-10 20:37:07.329 INFO 1 --- [ main] o.hibernate.annotations.common.Version : HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
2022-11-10 20:37:08.859 INFO 1 --- [ main] org.hibernate.dialect.Dialect : HHH000400: Using dialect: com.epam.ta.reportportal.commons.JsonbAwarePostgresDialect
2022-11-10 20:37:13.441 INFO 1 --- [ main] o.h.e.t.j.p.i.JtaPlatformInitiator : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2022-11-10 20:37:13.451 INFO 1 --- [ main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2022-11-10 20:37:15.931 WARN 1 --- [ main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2022-11-10 20:37:16.989 ERROR 1 --- [ main] c.e.t.r.f.d.minio.MinioDataStore : Unable to find file 'keystore/secret-integration-salt'
io.minio.errors.InvalidResponseException: Non-XML response from server
at io.minio.MinioClient.executeReq(MinioClient.java:1155) ~[minio-6.0.13.jar!/:6.0.13]
at io.minio.MinioClient.execute(MinioClient.java:1082) ~[minio-6.0.13.jar!/:6.0.13]
at io.minio.MinioClient.updateRegionCache(MinioClient.java:1235) ~[minio-6.0.13.jar!/:6.0.13]
at io.minio.MinioClient.getRegion(MinioClient.java:1280) ~[minio-6.0.13.jar!/:6.0.13]
at io.minio.MinioClient.executeGet(MinioClient.java:1339) ~[minio-6.0.13.jar!/:6.0.13]
at io.minio.MinioClient.getObject(MinioClient.java:1854) ~[minio-6.0.13.jar!/:6.0.13]
at io.minio.MinioClient.getObject(MinioClient.java:1647) ~[minio-6.0.13.jar!/:6.0.13]
at com.epam.ta.reportportal.filesystem.distributed.minio.MinioDataStore.load(MinioDataStore.java:83) ~[commons-dao-5.7.0.jar!/:na]
at com.epam.ta.reportportal.config.EncryptConfiguration.loadOrGenerateIntegrationSalt(EncryptConfiguration.java:93) ~[commons-dao-5.7.0.jar!/:na]
at com.epam.ta.reportportal.config.EncryptConfiguration.afterPropertiesSet(EncryptConfiguration.java:88) ~[commons-dao-5.7.0.jar!/:na]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at com.epam.reportportal.auth.AuthServerApplication.main(AuthServerApplication.java:41) ~[classes!/:na]
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[service-authorization-5.7.0-exec.jar:na]
at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[service-authorization-5.7.0-exec.jar:na]
at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[service-authorization-5.7.0-exec.jar:na]
at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[service-authorization-5.7.0-exec.jar:na]
2022-11-10 20:37:17.042 ERROR 1 --- [ main] c.e.t.r.f.d.minio.MinioDataStore : Unable to save file 'keystore/secret-integration-salt'
io.minio.errors.InvalidResponseException: Non-XML response from server
at io.minio.MinioClient.executeReq(MinioClient.java:1155) ~[minio-6.0.13.jar!/:6.0.13]
at io.minio.MinioClient.execute(MinioClient.java:1082) ~[minio-6.0.13.jar!/:6.0.13]
at io.minio.MinioClient.updateRegionCache(MinioClient.java:1235) ~[minio-6.0.13.jar!/:6.0.13]
at io.minio.MinioClient.getRegion(MinioClient.java:1280) ~[minio-6.0.13.jar!/:6.0.13]
at io.minio.MinioClient.executeHead(MinioClient.java:1353) ~[minio-6.0.13.jar!/:6.0.13]
at io.minio.MinioClient.bucketExists(MinioClient.java:3613) ~[minio-6.0.13.jar!/:6.0.13]
at com.epam.ta.reportportal.filesystem.distributed.minio.MinioDataStore.save(MinioDataStore.java:60) ~[commons-dao-5.7.0.jar!/:na]
at com.epam.ta.reportportal.config.EncryptConfiguration.loadOrGenerateIntegrationSalt(EncryptConfiguration.java:99) ~[commons-dao-5.7.0.jar!/:na]
at com.epam.ta.reportportal.config.EncryptConfiguration.afterPropertiesSet(EncryptConfiguration.java:88) ~[commons-dao-5.7.0.jar!/:na]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at com.epam.reportportal.auth.AuthServerApplication.main(AuthServerApplication.java:41) ~[classes!/:na]
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[service-authorization-5.7.0-exec.jar:na]
at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[service-authorization-5.7.0-exec.jar:na]
at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[service-authorization-5.7.0-exec.jar:na]
at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[service-authorization-5.7.0-exec.jar:na]
2022-11-10 20:37:17.043 WARN 1 --- [ main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'encryptConfiguration' defined in URL [jar:file:/service-authorization-5.7.0-exec.jar!/BOOT-INF/lib/commons-dao-5.7.0.jar!/com/epam/ta/reportportal/config/EncryptConfiguration.class]: Invocation of init method failed; nested exception is com.epam.ta.reportportal.exception.ReportPortalException: Incorrect Request. Unable to save file
2022-11-10 20:37:17.085 INFO 1 --- [ main] com.zaxxer.hikari.HikariDataSource : HikariPool-1 - Shutdown initiated...
2022-11-10 20:37:17.425 INFO 1 --- [ main] com.zaxxer.hikari.HikariDataSource : HikariPool-1 - Shutdown completed.
2022-11-10 20:37:17.427 INFO 1 --- [ main] o.apache.catalina.core.StandardService : Stopping service [Tomcat]
2022-11-10 20:37:17.440 INFO 1 --- [ main] ConditionEvaluationReportLoggingListener :
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-11-10 20:37:17.441 ERROR 1 --- [ main] o.s.boot.SpringApplication : Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'encryptConfiguration' defined in URL [jar:file:/service-authorization-5.7.0-exec.jar!/BOOT-INF/lib/commons-dao-5.7.0.jar!/com/epam/ta/reportportal/config/EncryptConfiguration.class]: Invocation of init method failed; nested exception is com.epam.ta.reportportal.exception.ReportPortalException: Incorrect Request. Unable to save file
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at com.epam.reportportal.auth.AuthServerApplication.main(AuthServerApplication.java:41) ~[classes!/:na]
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[service-authorization-5.7.0-exec.jar:na]
at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[service-authorization-5.7.0-exec.jar:na]
at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[service-authorization-5.7.0-exec.jar:na]
at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[service-authorization-5.7.0-exec.jar:na]
Caused by: com.epam.ta.reportportal.exception.ReportPortalException: Incorrect Request. Unable to save file
at com.epam.ta.reportportal.filesystem.distributed.minio.MinioDataStore.save(MinioDataStore.java:75) ~[commons-dao-5.7.0.jar!/:na]
at com.epam.ta.reportportal.config.EncryptConfiguration.loadOrGenerateIntegrationSalt(EncryptConfiguration.java:99) ~[commons-dao-5.7.0.jar!/:na]
at com.epam.ta.reportportal.config.EncryptConfiguration.afterPropertiesSet(EncryptConfiguration.java:88) ~[commons-dao-5.7.0.jar!/:na]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
... 24 common frames omitted
```

**Comment by imigu17** [comment]
Any chance for a feedback?

**Comment by raikbitters** [comment]
`Unable to find file 'keystore/secret-integration-salt' io.minio.errors.InvalidResponseException: Non-XML response from server`
It's not an SSO error. It's an error for a cold start. After it, UAT creates secret-integration-salt. 
Looks like you have some connectivity issues depending on your infrastructure configuration.

**Comment by raikbitters** [comment]
Moreover, you can check this issues:
https://github.com/reportportal/reportportal/issues/2144
