### ISSUE TITLE
Can't deploy rpt with kubernetes when i try to set the value of signed-request=true

### ISSUE THREAD

**Issue by hamzarezgui** [reportportal/reportportal#1908]
**Describe the bug**
I am trying to integrate rpt with sso, and our system needs to sign the request in rpt
When i had a look at the source code, i tried to override the env var signed-request by declaring it in values chart of uat:

I did it in this way:

--
uat:
  repository: reportportal/service-authorization
  name: uat
  tag: 5.7.0
  pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 2048Mi
  sessionLiveTime: 86400
  podAnnotations: {}
  ## jvmArgs
  ## If you need to use a custom java keystore you can use it through jvmArgs
  ## eg. : -Djavax.net.ssl.trustStore=/etc/secret-volume/custom-pki.jks
  jvmArgs: "-Djava.security.egd=file:/dev/./urandom -XX:MinRAMPercentage=60.0 -XX:MaxRAMPercentage=90.0"
  ## External environment variables
  ##
  extraEnvs:
   - name: RP_AUTH_SAML_SIGNED-REQUESTS
     value: "true"
   - name: RP_AUTH_SAML_KEY_ALIAS
     value: "report-portal-sp"
   - name: RP_AUTH_SAML_KEY-STORE-PASSWORD
     value: "password"
   - name: RP_AUTH_SAML_KEY-STORE
     value: "/etc/secret-volume/custom-pki.jks"
    # - name: EXTRA_ENV_SECRET
    #   valueFrom:
    #     secretKeyRef:
  #       name: "additional-credentials"
  #       key: username
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  ## Define which Nodes the Pods are scheduled on.
  ## ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}
  #  disktype: ssd
  serviceAccountName: ""
  ## Provide a secret containing sensitives data
  ## eg. : provide a custom java keystore used in jvmArgs
  ##
  ## keytool -genkeypair -storetype jks -alias todelete -keypass changeit -storepass changeit -keystore custom-pki.jks -dname "CN=Developer, OU=Department, O=Company, L=City, ST=State, C=CA"
  ## keytool -delete -alias todelete -storepass changeit -keystore custom-pki.jks
  ## keytool -list -keystore custom-pki.jks -storepass changeit
  ##
  ## Generate base64 data and paste it in your values.yaml :
  ## cat custom-pki.jks | base64 -w
  secret:
    enabled: true
    mountPath: /etc/secret-volume
    readOnly: true
    data:
      custom-pki.jks: ***********************************************************************************
  service:
    portName: ""

--
    
When i deploy it i have the following error message 
--
                Authorization Service: 5.7.0
                Built with ♡ by EPAM Systems
                Spring Boot  (v2.2.5.RELEASE)

2022-12-23 11:18:01.403  INFO 1 --- [           main] c.e.r.auth.AuthServerApplication         : Starting AuthServerApplication on rpt-reportportal-uat-859867c8bc-lzb5t with PID 1 (/service-authorization-5.7.0-exec.jar started by ? in /)
2022-12-23 11:18:01.407  INFO 1 --- [           main] c.e.r.auth.AuthServerApplication         : The following profiles are active: default
2022-12-23 11:18:08.414  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2022-12-23 11:18:09.701  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 1201ms. Found 32 JPA repository interfaces.
2022-12-23 11:18:18.412  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9999 (http)
2022-12-23 11:18:18.510  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-12-23 11:18:18.510  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.37]
2022-12-23 11:18:18.802  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-12-23 11:18:18.802  INFO 1 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 16998 ms
2022-12-23 11:18:19.496  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2022-12-23 11:18:21.012  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2022-12-23 11:18:24.408  INFO 1 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2022-12-23 11:18:25.003  INFO 1 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.4.18.Final
2022-12-23 11:18:26.811  INFO 1 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
2022-12-23 11:18:29.521  INFO 1 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: com.epam.ta.reportportal.commons.JsonbAwarePostgresDialect
2022-12-23 11:18:40.399  INFO 1 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2022-12-23 11:18:40.409  INFO 1 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2022-12-23 11:18:45.506  WARN 1 --- [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2022-12-23 11:18:50.702  WARN 1 --- [ ConnectionPool] okhttp3.OkHttpClient                     : A connection to https://reportportal.s3.eu-west-3.amazonaws.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.security.saml.saml2.metadata.NameIdFormat (jar:file:/service-authorization-5.7.0-exec.jar!/BOOT-INF/lib/spring-security-saml2-core-2.0.0.M31.jar!/) to field java.lang.Enum.name
WARNING: Please consider reporting this to the maintainers of org.springframework.security.saml.saml2.metadata.NameIdFormat
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2022-12-23 11:18:51.007  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'samlServiceProviderBeanConfiguration' defined in URL [jar:file:/service-authorization-5.7.0-exec.jar!/BOOT-INF/classes!/com/epam/reportportal/auth/config/saml/SamlServiceProviderBeanConfiguration.class]: Unsatisfied dependency expressed through constructor parameter 4; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spConfiguration' defined in class path resource [com/epam/reportportal/auth/config/saml/SamlServiceProviderConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.saml.provider.SamlServerConfiguration]: Factory method 'samlServerConfiguration' threw exception; nested exception is java.lang.NullPointerException
2022-12-23 11:18:51.096  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2022-12-23 11:18:51.103  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2022-12-23 11:18:51.105  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2022-12-23 11:18:51.201  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-12-23 11:18:51.207 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'samlServiceProviderBeanConfiguration' defined in URL [jar:file:/service-authorization-5.7.0-exec.jar!/BOOT-INF/classes!/com/epam/reportportal/auth/config/saml/SamlServiceProviderBeanConfiguration.class]: Unsatisfied dependency expressed through constructor parameter 4; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spConfiguration' defined in class path resource [com/epam/reportportal/auth/config/saml/SamlServiceProviderConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.saml.provider.SamlServerConfiguration]: Factory method 'samlServerConfiguration' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:228) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at com.epam.reportportal.auth.AuthServerApplication.main(AuthServerApplication.java:41) ~[classes!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[service-authorization-5.7.0-exec.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[service-authorization-5.7.0-exec.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[service-authorization-5.7.0-exec.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[service-authorization-5.7.0-exec.jar:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spConfiguration' defined in class path resource [com/epam/reportportal/auth/config/saml/SamlServiceProviderConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.saml.provider.SamlServerConfiguration]: Factory method 'samlServerConfiguration' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:656) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:484) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	... 27 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.saml.provider.SamlServerConfiguration]: Factory method 'samlServerConfiguration' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	... 41 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.epam.reportportal.auth.util.CertificationUtil.getCertificateByName(CertificationUtil.java:38) ~[classes!/:na]
	at com.epam.reportportal.auth.config.saml.SamlServiceProviderConfiguration.activeKey(SamlServiceProviderConfiguration.java:161) ~[classes!/:na]
	at com.epam.reportportal.auth.config.saml.SamlServiceProviderConfiguration.rotatingKeys(SamlServiceProviderConfiguration.java:151) ~[classes!/:na]
	at com.epam.reportportal.auth.config.saml.SamlServiceProviderConfiguration.serviceProviderConfiguration(SamlServiceProviderConfiguration.java:129) ~[classes!/:na]
	at com.epam.reportportal.auth.config.saml.SamlServiceProviderConfiguration.samlServerConfiguration(SamlServiceProviderConfiguration.java:111) ~[classes!/:na]
	at com.epam.reportportal.auth.config.saml.SamlServiceProviderConfiguration$$EnhancerBySpringCGLIB$$de764455.CGLIB$samlServerConfiguration$0(<generated>) ~[classes!/:na]
	at com.epam.reportportal.auth.config.saml.SamlServiceProviderConfiguration$$EnhancerBySpringCGLIB$$de764455$$FastClassBySpringCGLIB$$f6e091c5.invoke(<generated>) ~[classes!/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at com.epam.reportportal.auth.config.saml.SamlServiceProvid--erConfiguration$$EnhancerBySpringCGLIB$$de764455.samlServerConfiguration(<generated>) ~[classes!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	... 42 common frames omitted

**Expected behavior**
deploy rpt and env var signed-request= true

**Screenshots**
If applicable

**Versions:** 
uat 5.7.0

Can you please help me to resolve this issue ?

Thnak you in advance

**Comment by MaryiaRymarchyk** [comment]
Hello @hamzarezgui , sorry for the silence.
Is the issue still relevant for you?
Could you please try the latest RP version  and check our recommendations/guides from here: https://github.com/reportportal/kubernetes

In case issue still relevant - let us know with recent details logs.

**Comment by MaryiaRymarchyk** [comment]
Hi @hamzarezgui , As we haven't received a reply from you, we'll close the issue for now.
If  the issue still relevant, just get in touch

**Comment by shaburov** [comment]
image: reportportal/service-authorization:5.11.0

![image](https://github.com/reportportal/reportportal/assets/15269131/678c2c8f-7263-4191-835b-ab5592623ced)

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.saml.provider.SamlServerConfiguration]: Factory method 'samlServerConfiguration' threw exception; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.20.jar!/:5.3.20]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.20.jar!/:5.3.20]
        ... 41 common frames omitted
Caused by: java.lang.NullPointerException: null
        at com.epam.reportportal.auth.util.CertificationUtil.getCertificateByName(CertificationUtil.java:47) ~[classes!/:na]
        at com.epam.reportportal.auth.config.saml.SamlServiceProviderConfiguration.getActiveKey(SamlServiceProviderConfiguration.java:165) ~[classes!/:na]
        at com.epam.reportportal.auth.config.saml.SamlServiceProviderConfiguration.rotatingKeys(SamlServiceProviderConfiguration.java:155) ~[classes!/:na]
        at com.epam.reportportal.auth.config.saml.SamlServiceProviderConfiguration.serviceProviderConfiguration(SamlServiceProviderConfiguration.java:133) ~[classes!/:na]
        at com.epam.reportportal.auth.config.saml.SamlServiceProviderConfiguration.samlServerConfiguration(SamlServiceProviderConfiguration.java:115) ~[classes!/:na]
        at com.epam.reportportal.auth.config.saml.SamlServiceProviderConfiguration$$EnhancerBySpringCGLIB$$d6000c54.CGLIB$samlServerConfiguration$0(<generated>) ~[classes!/:na]
        at com.epam.reportportal.auth.config.saml.SamlServiceProviderConfiguration$$EnhancerBySpringCGLIB$$d6000c54$$FastClassBySpringCGLIB$$34541669.invoke(<generated>) ~[classes!/:na]
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.30.jar!/:5.3.30]
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.20.jar!/:5.3.20]
        at com.epam.reportportal.auth.config.saml.SamlServiceProviderConfiguration$$EnhancerBySpringCGLIB$$d6000c54.samlServerConfiguration(<generated>) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]

```
