### ISSUE TITLE
Unexpected end of stream on

### ISSUE THREAD

**Issue by oleksandrsemak** [reportportal/reportportal#1952]
**Describe the bug**
Reportportal installed to kubernetes version 5.7.0 and access to RP URL over VPN 
We can't upload images for failed test

**Expected behavior**
Upload images for failed test in RP project

**Actual behavior**
```
2023-03-10 11:22:29 ERROR Launch:46 - [25] ReportPortal execution error
    java.io.IOException: unexpected end of stream on https://reportportal.****/...
    	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:236)
    	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
    	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
    	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
    	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
    	at com.epam.reportportal.service.PathParamInterceptor.intercept(PathParamInterceptor.java:55)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
    	at com.epam.reportportal.service.BearerAuthInterceptor.intercept(BearerAuthInterceptor.java:39)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
    	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
    	at okhttp3.RealCall.execute(RealCall.java:81)
    	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
    	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:46)
    	at io.reactivex.Observable.subscribe(Observable.java:12267)
    	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
    	at io.reactivex.Observable.subscribe(Observable.java:12267)
    	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
    	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
    	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
    	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:[113](https://git.*****.com/foundation/widgets-test-automation/-/jobs/16023368#L113)6)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    	at java.base/java.lang.Thread.run(Thread.java:833)
    Caused by: java.io.EOFException: \n not found: limit=0 content=?
    	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:240)
    	at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242)
    	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213)
    	... 34 more
    2023-03-10 11:22:29 ERROR Launch:46 - [25] ReportPortal execution error
    java.io.IOException: unexpected end of stream on https://reportportal.****/...
    	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:236)
    	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:[115](https://git.*****.com/foundation/widgets-test-automation/-/jobs/16023368#L115))
    	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:[117](https://git.*****.com/foundation/widgets-test-automation/-/jobs/16023368#L117))
    	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
    	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
    	at com.epam.reportportal.service.PathParamInterceptor.intercept(PathParamInterceptor.java:55)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
    	at com.epam.reportportal.service.BearerAuthInterceptor.intercept(BearerAuthInterceptor.java:39)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
    	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
    	at okhttp3.RealCall.execute(RealCall.java:81)
    	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
    	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:46)
    	at io.reactivex.Observable.subscribe(Observable.java:[122](https://git.*****.com/foundation/widgets-test-automation/-/jobs/16023368#L122)67)
    	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
    	at io.reactivex.Observable.subscribe(Observable.java:12267)
    	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
    	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
    	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
    	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1[136](https://git.*****.com/foundation/widgets-test-automation/-/jobs/16023368#L136))
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    	at java.base/java.lang.Thread.run(Thread.java:833)
    Caused by: java.io.EOFException: \n not found: limit=0 content=?
    	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:240)
    	at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242)
    	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213)
    	... 34 more
```

**Dependency versions**
`com.epam.reportportal:client-java:5.1.11`
`com.epam.reportportal:agent-java-junit5:5.1.5`

**Comment by HardNorth** [comment]
@alexandrsemak This issue is nothing to do with JUnit 5 agent or client code per se. You need to check your firewall / load balancer rules and allow binary data transfer of at least 64 MB per request (standard RP log batch).

**Comment by MaryiaRymarchyk** [comment]
Hi @alexandrsemak any updates from your side? did the comment above help you?

**Comment by HardNorth** [comment]
Abandoned
