### ISSUE TITLE
The report portal agent cannot send a request to the ReportPortal API service

### ISSUE THREAD

**Issue by Artem-Zahumonnyi** [reportportal/reportportal#1959]
We deployed ReportPortal v5.7.4 on our test cluster. And this version works as expected.

Then we tried to deploy the same version of ReportPortal to our main cluster, but we faced some errors when sending statuses and logs to ReportPortal.

After starting the test suites, ReportPortal catches statuses from 2-3 test suites and then we see the following errors from the java-agent

Versions:
```
    implementation group: 'com.epam.reportportal', name: 'agent-java-cucumber4', version: '5.1.2'
    implementation group: 'com.epam.reportportal', name: 'logger-java-logback', version: '5.1.3'
    implementation group: 'ch.qos.logback', name: 'logback-classic', version: '1.2.11'
    implementation group: 'com.epam.reportportal', name: 'logger-java-log4j', version: '5.1.5'
```
Logs from the console
```
2023-03-17 10:06:27.518 ERROR 93993 --- [       rp-io-91] com.epam.reportportal.service.Launch     : [201] ReportPortal execution error

retrofit2.adapter.rxjava2.HttpException: HTTP 400 
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57) ~[adapter-rxjava2-2.9.0.jar:na]
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38) ~[adapter-rxjava2-2.9.0.jar:na]
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48) ~[adapter-rxjava2-2.9.0.jar:na]
        at io.reactivex.Observable.subscribe(Observable.java:12284) ~[rxjava-2.2.19.jar:na]
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35) ~[adapter-rxjava2-2.9.0.jar:na]
        at io.reactivex.Observable.subscribe(Observable.java:12284) ~[rxjava-2.2.19.jar:na]
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96) ~[rxjava-2.2.19.jar:na]
        at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38) ~[rxjava-2.2.19.jar:na]
        at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26) ~[rxjava-2.2.19.jar:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

2023-03-17 10:06:27.518 ERROR 93993 --- [       rp-io-91] c.e.r.utils.SubscriptionUtils            : [201] ReportPortal Finish test item execution error

retrofit2.adapter.rxjava2.HttpException: HTTP 400 
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57) ~[adapter-rxjava2-2.9.0.jar:na]
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38) ~[adapter-rxjava2-2.9.0.jar:na]
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48) ~[adapter-rxjava2-2.9.0.jar:na]
        at io.reactivex.Observable.subscribe(Observable.java:12284) ~[rxjava-2.2.19.jar:na]
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35) ~[adapter-rxjava2-2.9.0.jar:na]
        at io.reactivex.Observable.subscribe(Observable.java:12284) ~[rxjava-2.2.19.jar:na]
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96) ~[rxjava-2.2.19.jar:na]
        at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38) ~[rxjava-2.2.19.jar:na]
        at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26) ~[rxjava-2.2.19.jar:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

2023-03-17 10:06:27.618 ERROR 93993 --- [       rp-io-92] com.epam.reportportal.service.Launch     : [202] ReportPortal execution error

retrofit2.adapter.rxjava2.HttpException: HTTP 400 
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57) ~[adapter-rxjava2-2.9.0.jar:na]
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38) ~[adapter-rxjava2-2.9.0.jar:na]
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48) ~[adapter-rxjava2-2.9.0.jar:na]
        at io.reactivex.Observable.subscribe(Observable.java:12284) ~[rxjava-2.2.19.jar:na]
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35) ~[adapter-rxjava2-2.9.0.jar:na]
        at io.reactivex.Observable.subscribe(Observable.java:12284) ~[rxjava-2.2.19.jar:na]
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96) ~[rxjava-2.2.19.jar:na]
        at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38) ~[rxjava-2.2.19.jar:na]
        at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26) ~[rxjava-2.2.19.jar:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

2023-03-17 10:06:27.620 ERROR 93993 --- [           main] com.epam.reportportal.service.Launch     : Unable to finish launch in ReportPortal

retrofit2.adapter.rxjava2.HttpException: HTTP 400 
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57) ~[adapter-rxjava2-2.9.0.jar:na]
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38) ~[adapter-rxjava2-2.9.0.jar:na]
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48) ~[adapter-rxjava2-2.9.0.jar:na]
        at io.reactivex.Observable.subscribe(Observable.java:12284) ~[rxjava-2.2.19.jar:na]
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35) ~[adapter-rxjava2-2.9.0.jar:na]
        at io.reactivex.Observable.subscribe(Observable.java:12284) ~[rxjava-2.2.19.jar:na]
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96) ~[rxjava-2.2.19.jar:na]
        at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38) ~[rxjava-2.2.19.jar:na]
        at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26) ~[rxjava-2.2.19.jar:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

```

At the same time, the api service gets the following error

![logs](https://user-images.githubusercontent.com/51204821/226172546-30731154-d453-43f8-9e41-57db72ef4893.png)

**Comment by irynakozak2** [comment]
@Artem-Zahumonnyi Hi! 
Could you please share the logs of the ReportPortal service-API container while receiving the error?

**Comment by Artem-Zahumonnyi** [comment]
Hi, 
Unfortunately I did not save the logs from the API container. All services except API worked without errors while pushing logs from tests.

**Comment by mchundi** [comment]
Hi I am facing the same issue. 
I see the below error in service-api
```
2023-04-05 19:40:11.239  INFO 1 --- [stener-exec1539] c.e.t.r.c.a.a.indexer.BatchLogIndexer    : Indexing of 3 logs is finished for 1 items.
2023-04-05 19:40:11.244  INFO 1 --- [stener-exec1539] c.e.t.r.c.a.a.impl.AnalyzerServiceImpl   : Start analysis of '1' items for launch with id '166614'
2023-04-05 19:40:11.397  INFO 1 --- [stener-exec1539] c.e.t.r.c.a.a.indexer.BatchLogIndexer    : Indexing started for 1 items.
2023-04-05 19:40:11.507  INFO 1 --- [stener-exec1539] c.e.t.r.c.a.a.indexer.BatchLogIndexer    : Indexing of 3 logs is finished for 1 items.
2023-04-05 19:40:45.894  INFO 1 --- [stener-exec1540] c.e.t.r.c.a.a.indexer.BatchLogIndexer    : Indexing started for 18 items.
2023-04-05 19:40:46.214  INFO 1 --- [stener-exec1540] c.e.t.r.c.a.a.indexer.BatchLogIndexer    : Indexing of 36 logs is finished for 18 items.
2023-04-05 19:40:46.218  INFO 1 --- [stener-exec1540] c.e.t.r.c.a.a.impl.AnalyzerServiceImpl   : Start analysis of '18' items for launch with id '166615'
2023-04-05 19:40:46.684  INFO 1 --- [stener-exec1540] c.e.t.r.c.a.a.indexer.BatchLogIndexer    : Indexing started for 18 items.
2023-04-05 19:40:46.995  INFO 1 --- [stener-exec1540] c.e.t.r.c.a.a.indexer.BatchLogIndexer    : Indexing of 36 logs is finished for 18 items.
2023-04-05 19:49:28.389  INFO 1 --- [portal_Worker-1] c.e.t.r.job.InterruptBrokenLaunchesJob   : Interrupt broken launches job has been started
2023-04-05 19:49:28.503  INFO 1 --- [portal_Worker-1] c.e.t.r.job.CleanExpiredCreationBidsJob  : Cleaning expired user creation bids finished. Deleted 0 bids
2023-04-05 20:33:29.725 ERROR 1 --- [-8585-exec-6505] c.e.t.r.c.e.rest.RestExceptionHandler    : Handled error: 

com.epam.ta.reportportal.exception.ReportPortalException: Finish launch is not allowed. Launch '166510' already finished with status 'INTERRUPTED'
	at com.epam.ta.reportportal.commons.validation.ErrorTypeBasedRuleValidator.verify(ErrorTypeBasedRuleValidator.java:32)
	at com.epam.ta.reportportal.core.launch.util.LaunchValidator.validate(LaunchValidator.java:55)
	at com.epam.ta.reportportal.core.launch.impl.FinishLaunchHandlerImpl.finishLaunch(FinishLaunchHandlerImpl.java:75)
	at com.epam.ta.reportportal.core.launch.impl.FinishLaunchHandlerImpl$$FastClassBySpringCGLIB$$ec54b939.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.epam.ta.reportportal.core.launch.impl.FinishLaunchHandlerImpl$$EnhancerBySpringCGLIB$$b9ca69eb.finishLaunch(<generated>)
	at com.epam.ta.reportportal.ws.controller.LaunchController.finishLaunch(LaunchController.java:126)
	at com.epam.ta.reportportal.ws.controller.LaunchController$$FastClassBySpringCGLIB$$702dfa6.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.epam.ta.reportportal.ws.controller.LaunchController$$EnhancerBySpringCGLIB$$4479b26e.finishLaunch(<generated>)
	at jdk.internal.reflect.GeneratedMethodAccessor468.invoke(Unknown Source)

```

How can I resolve this?

**Comment by HardNorth** [comment]
@mchundi No, this is unrelated. The stack trace is different, the root cause too. Please don't post unrelated comments.

**Comment by DzmitryHumianiuk** [comment]
Closing this issue due to inactivity. 

If this still remains a concern or if there are new developments, please feel free to reopen or create a new issue. 

Thank you for your understanding and contributions to the project!

**Comment by anwaarah** [comment]
@Artem-Zahumonnyi, did you find a solution for this issue?
