### ISSUE TITLE
Timeout exceeded on method POST

### ISSUE THREAD

**Issue by ssfxate** [reportportal/reportportal#1978]
From time to time posting test results shows the error.
We have around 280 tests and 1-2 can fail this POST timeout error. Hereinbelow, you'll find the screenshot that shows how often it's happening. All red were stopped automatically after 1h of timeout.
It doesn't matter, had the tests run overnight or during the day.
The longer run, the more chances to fail the run in RP.
```
Error: timeout of 30000ms exceeded
URL: https://reportportal.epam.com/api/v1/burb-unic/item/cfaa85e5-6e45-420a-87dc-8d865db81026
method: POST
```
Thus the test run can't be finished properly.
![image](https://user-images.githubusercontent.com/18144023/231131584-21801800-4c1a-4733-ac21-8b666226e789.png)

Current version:API Service: 5.7.4;Index Service: 5.7.3;Jobs Service: 5.7.4;EPAM Authorization Service: 5.7.4;Service UI: 5.7.4;

**Comment by shwarcu** [comment]
Hi, I have setup Report Portal with docker recently and I have the same issue. I am sending test results from unit tests written in Jest, using official client https://github.com/reportportal/agent-js-jest
Some results are send to RP but a lot of them error with message `Error: timeout of 30000ms exceeded`

**Comment by ladislav-wandera** [comment]
We are facing same problem after upgrading to API Service: 5.7.3;API Service: 5.7.3;Authorization Service: 5.7.3;Service UI: 5.7.3;

**Comment by duduc** [comment]
Same, using playwright client. It seems that after the first timeout, any further request to Report Portal will timeout, or will fail because of ambiguous status:

```
02:33:46  method: PUT
Error: timeout of 30000ms exceeded
```

```
method: PUT
Error: Request failed with status code 400: {"errorCode":40019,"message":"Test item status is ambiguous. There is no status provided from request and there are no descendants to check statistics for test item id '2848591'"}
```

I checked some logs in the API service but since the problem is not always happening it's a bit hard to extract the data, but here is a small sample:
```
ERROR 1 --- [-8585-exec-9223] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: deadlock detected
ERROR 1 --- [-8585-exec-9223] c.e.t.r.c.e.rest.RestExceptionHandler    : Handled error:
Caused by: org.postgresql.util.PSQLException: ERROR: deadlock detected
ERROR 1 --- [-8585-exec-9223] .t.r.c.e.r.ReportPortalExceptionResolver : ReportPortalExceptionResolver > could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.LockAcquisitionException: could not execute statement
ERROR 1 --- [-8585-exec-9240] c.e.t.r.c.e.rest.RestExceptionHandler    : Handled error:
ERROR 1 --- [-8585-exec-9240] .t.r.c.e.r.ReportPortalExceptionResolver : ReportPortalExceptionResolver > java.io.IOException: Broken pipe
ERROR 1 --- [-8585-exec-9240] c.e.t.r.c.e.rest.DefaultErrorResolver    : java.io.IOException: Broken pipe
ERROR 1 --- [stener-exec1857] c.e.t.r.c.l.c.UniqueErrorGeneratorAsync  : SQL [insert into "public"."item_attribute" ("key", "value", "launch_id", "system") values (?, ?, ?, ?)]; ERROR: insert or update on table "item_attribute" violates foreign key constraint "item_attribute_launch_id_fkey"
org.jooq.exception.DataAccessException: SQL [insert into "public"."item_attribute" ("key", "value", "launch_id", "system") values (?, ?, ?, ?)]; ERROR: insert or update on table "item_attribute" violates foreign key constraint "item_attribute_launch_id_fkey"
Exception in thread "logs-task-exec6544" java.lang.NullPointerException
Exception in thread "logs-task-exec6537" java.lang.NullPointerException
Exception in thread "logs-task-exec6548" java.lang.NullPointerException
Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "item_attribute" violates foreign key constraint "item_attribute_launch_id_fkey"
```

**Comment by viktor-maksymenko** [comment]
Same for us, we're using `@reportportal/agent-js-playwright` with the ReportPortal on GCP (the version 5.10.0 from MarketPlace), and some results are missing. We also receive timeout errors like this:
```
Failed to start nested step. Error: timeout of 30000ms exceeded
URL: *******************************/item/bc7d614f-03ed-4f18-91ed-5f7b1405ad66
method: POST
    at /app/node_modules/@reportportal/client-javascript/lib/rest.js:43:15
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at processTimers (node:internal/timers:514:7)
```
Any assistance with the issue is welcomed.

**Comment by AmsterGet** [comment]
Hi guys!
The issue seems to be related to processing requests to the API service.
30s is the standard HTTP request processing timeout set by the JS client.
Without diving deep into possible slowdowns on the API service side, which requires additional investigation of its load, I would suggest two options:
1. Try using the higher performance asynchronous `api/v2` endpoint instead of the synchronous `api/v1` endpoint.
2. In case the problem still exists, try increasing the timeout value using the agent option [restClientConfig.timeout](https://github.com/reportportal/agent-js-playwright?tab=readme-ov-file#configuration:~:text=be%20finished%20separately.-,restClientConfig,-Optional).

@irynakozak2 Can you suggest anything regarding API service load issues?

**Comment by viktor-maksymenko** [comment]
Thanks, I will try to use `api/v2`. Also, I haven't seen errors in API service logs and it does not looked overloaded. Any hint on what to look at?

**Comment by AmsterGet** [comment]
@viktor-maksymenko If the API load is fine, I assume it could be due to network slowdowns, for example in case requests are going through VPNs, proxies, etc. So you could try to figure out possible delays there, if applicable.

**Comment by irynakozak2** [comment]
@duduc Hi! What version of the ReportPortal are you using? I see the constraint error in the API logs so it might be the issue during deployment, so the migration service isn't rolled out properly or something on the PostgreSQL database side.
Could you please share the ReportPortal container statuses?

**Comment by toduyemi** [comment]
Hi using `@reportportal/agent-js-playwright` and also experiencing this timeout error. 

```
Failed to finish nested step. Error: timeout of 60000ms exceeded
URL: http://localhost:8080/api/v2/superadmin_personal/item/f38c715e-45f7-48c1-9bea-c260ea80e18b
method: POST
    at /Users/temi/work/spire-web-tests-playwright/node_modules/@reportportal/client-javascript/lib/rest.js:56:15
Failed to start nested step. Error: timeout of 60000ms exceeded
URL: http://localhost:8080/api/v2/superadmin_personal/item/f38c715e-45f7-48c1-9bea-c260ea80e18b
method: POST
    at /Users/temi/work/spire-web-tests-playwright/node_modules/@reportportal/client-javascript/lib/rest.js:56:15```
   
I did what @AmsterGet suggested and changed the timeout in the settings (first to 60000 which made no difference) to 0 to disable timeout. Then I got this instead:

<img width="531" alt="Screenshot 2024-11-07 at 3 03 00 PM" src="https://github.com/user-attachments/assets/cbe2835c-385d-4bb1-824a-97ff99536a0d">


  I'd appreciate some help resolving this.

**Comment by toduyemi** [comment]
Thank you for replying! What entry am I looking for in the api/DB logs? A file uploadbase exception?

**Comment by viktor-maksymenko** [comment]
We have something like this in the `api-service` logs:

```
javax.persistence.OptimisticLockException: org.hibernate.exception.LockAcquisitionException: could not execute statement
	at org.hibernate.internal.ExceptionConverterImpl.wrapLockException(ExceptionConverterImpl.java:277)
	... 
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1362)
	... 162 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: deadlock detected
```

**Comment by toduyemi** [comment]
I attempted to redeploy the application with docker and received a:
`dependency failed to start: container postgres is unhealthy` response.

I think the database is to blame here. But I haven't been able to find that exception.
