### ISSUE TITLE
Error while importing the file for input string : \"3,000.457\"'

### ISSUE THREAD

**Issue by rujutashinde** [reportportal/reportportal#2008]
**Describe the bug**
I am using Reportportal version Build: 5.7.2

I see a 400 error when  i use the `launch/import api`
`https://<instance>/api/v1/<project>/launch/import`

error:
```

{
  "errorCode": 40035,
  "message": "Error while importing the file. 'For input string: \"3,000.457\"'"
}

```
this is the  snippet from my xml which is causing the issue
```
<testcase name="testNotification" classname="io.debezium.connector.oracle.IncrementalSnapshotCaseSensitiveIT" time="3,000.457">
<error message="Index 868 out of bounds for length 868" type="java.lang.IndexOutOfBoundsException">
<![CDATA[ java.lang.IndexOutOfBoundsException: Index 868 out of bounds for length 868 at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) at java.base/java.util.Objects.checkIndex(Objects.java:359) at java.base/java.util.ArrayList.get(ArrayList.java:427) at io.debezium.pipeline.source.snapshot.incremental.AbstractIncrementalSnapshotTest.testNotification(AbstractIncrementalSnapshotTest.java:1144) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61) at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) at org.junit.runners.ParentRunner.run(ParentRunner.java:413) at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:377) at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:284) at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:248) at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:167) at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456) at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169) at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595) at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581) ]]>
</error>
<system-out>
...
</system-out>
```
The launch is seen on the RP instance as forever waiting, and it has to be forcefully ended.

Is there a documentation on what is the format that is expected for the time field int he xunit file?

Error as seen on the RP log:

```
t java.base/java.lang.Thread.run(Unknown Source)
2023-05-19 14:33:26.337 ERROR 7 --- [o-8585-exec-251] .t.r.c.e.r.ReportPortalExceptionResolver : ReportPortalExceptionResolver > Error while importing the file. 'For input string: "3,000.457"'
com.epam.ta.reportportal.exception.ReportPortalException: Error while importing the file. 'For input string: "3,000.457"'
at com.epam.ta.reportportal.core.imprt.impl.ZipImportStrategy.processZipFile(ZipImportStrategy.java:78)
at com.epam.ta.reportportal.core.imprt.impl.ZipImportStrategy.importLaunch(ZipImportStrategy.java:52)
at com.epam.ta.reportportal.core.imprt.ImportLaunchHandlerImpl.importLaunch(ImportLaunchHandlerImpl.java:69)
at com.epam.ta.reportportal.ws.controller.LaunchController.importLaunch(LaunchController.java:377)
at com.epam.ta.reportportal.ws.controller.LaunchController$$FastClassBySpringCGLIB$$702dfa6.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
at com.epam.ta.reportportal.ws.controller.LaunchController$$EnhancerBySpringCGLIB$$1644290b.importLaunch(<generated>)
at jdk.internal.reflect.GeneratedMethodAccessor431.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
```

**Screenshots**
![image](https://github.com/reportportal/reportportal/assets/26877311/f0231208-5079-40d0-b917-108a42c12b17)

**Versions:**
I am using Reportportal version Build: 5.7.2

**Comment by MaryiaRymarchyk** [comment]
Hi @rujutashinde,  unfortunately, there is no such documentation so far.
The 'time'  field supports only numbers and single point, other symbols will lead to error.
So, according to your example, valid value will be = 3000.457.
Could you please try it?

**Comment by rujutashinde** [comment]
@MaryiaRymarchyk  Thank you for the response, i was able to get the import done by removing the `,` from the time attribute value

**Comment by MaryiaRymarchyk** [comment]
@rujutashinde  as you have resolved the problem, i will close the issue, hope you don't mind.
