### ISSUE TITLE
UAT couldn't start on 5.8.0 version

### ISSUE THREAD

**Issue by Kanaduchi** [reportportal/reportportal#2023]
**Describe the bug**
We use RP with SAML auth config (Okta provider)

I am trying to upgrade from 5.7.4 to 5.8 but got a problem with UAT. It cannot start due to error:
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'OAuthConfigurationEndpoint' defined in URL [jar:file:/service-authorization-5.8.0-exec.jar!/BOOT-INF/classes!/com/epam/reportportal/auth/endpoint/OAuthConfigurationEndpoint.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'createAuthIntegrationHandlerImpl' defined in URL [jar:file:/service-authorization-5.8.0-exec.jar!/BOOT-INF/classes!/com/epam/reportportal/auth/integration/handler/impl/CreateAuthIntegrationHandlerImpl.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'authIntegrationStrategyProvider' defined in class path resource [com/epam/reportportal/auth/config/AuthIntegrationConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.epam.reportportal.auth.integration.provider.AuthIntegrationStrategyProvider]: Factory method 'authIntegrationStrategyProvider' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'samlIntegrationStrategy' defined in URL [jar:file:/service-authorization-5.8.0-exec.jar!/BOOT-INF/classes!/com/epam/reportportal/auth/integration/handler/impl/strategy/SamlIntegrationStrategy.class]: Unsatisfied dependency expressed through constructor parameter 3; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'samlServiceProviderProvisioning' defined in class path resource [com/epam/reportportal/auth/config/saml/SamlServiceProviderBeanConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.saml.provider.provisioning.SamlProviderProvisioning]: Factory method 'getSamlProvisioning' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'samlValidator' defined in class path resource [com/epam/reportportal/auth/config/saml/SamlServiceProviderBeanConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.saml.SamlValidator]: Factory method 'samlValidator' threw exception; nested exception is java.lang.ArithmeticException: integer overflow
```

I tried to roll back to 5.7.4 and recreate SAML config but it doesn't help.
Also after roll back to 5.7.4  starts working incorrectly due to errors like:
```
Caused by: org.postgresql.util.PSQLException: ERROR: relation "shareable_entity" does not exist
1 --- [nio-8585-exec-5] c.e.t.r.c.e.rest.DefaultErrorResolver    : could not extract ResultSet
May 31 15:09:52 a51bd06fabc9 api org.hibernate.exception.SQLGrammarException: could not extract ResultSet
May 31 15:09:52 a51bd06fabc9 api 	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:103)
May 31 15:09:52 a51bd06fabc9 api 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
May 31 15:09:52 a51bd06fabc9 api 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
May 31 15:09:52 a51bd06fabc9 api 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
May 31 15:09:52 a51bd06fabc9 api 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:67)
```

**Expected behavior**
UAT should work without issues

**Versions:**
 - 5.8.0

**Comment by IvanKustau** [comment]
Hi @Kanaduchi.
Can you please tell me if you provided rp.auth.saml.session-live value in environment variables. If you did can tell me what value do you have?

**Comment by Kanaduchi** [comment]
Hi @IvanKustau 
I specified the same value as RP_SESSION_LIVE:
RP_SAML_SESSION-LIVE: 86400

**Comment by IvanKustau** [comment]
@Kanaduchi The value should be different as RP_SAML_SESSION_LIVE is containing minutes, no seconds.
I can suggest you to use default value for it: 
RP_SAML_SESSION_LIVE : 4320

**Comment by Kanaduchi** [comment]
I will try, thank you

**Comment by Kanaduchi** [comment]
It works, thank you!

**Comment by MeirsPortal** [comment]
Hi,

We would like to use this env to set a different value from the default - I thought that was the whole point of of this feature.
How can we use it?
