### ISSUE TITLE
Heap space error in job microservice

### ISSUE THREAD

**Issue by Kanaduchi** [reportportal/reportportal#2026]
**Describe the bug**
```
Jun 2 17:26:16 9a37b2677c18 jobs ERROR 1 --- [pool-2-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
Jun 2 17:26:16 9a37b2677c18 jobs java.lang.OutOfMemoryError: Java heap space
Jun 2 17:26:16 9a37b2677c18 jobs 	at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:133) ~[na:na]
Jun 2 17:26:16 9a37b2677c18 jobs 	at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:226) ~[na:na]
Jun 2 17:26:16 9a37b2677c18 jobs 	at java.base/java.io.Writer.write(Writer.java:249) ~[na:na]
Jun 2 17:26:16 9a37b2677c18 jobs 	at org.springframework.util.StreamUtils.copy(StreamUtils.java:147) ~[spring-core-5.3.20.jar!/:5.3.20]
Jun 2 17:26:16 9a37b2677c18 jobs 	at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:126) ~[spring-web-5.3.20.jar!/:5.3.20]
Jun 2 17:26:16 9a37b2677c18 jobs 	at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:44) ~[spring-web-5.3.20.jar!/:5.3.20]
Jun 2 17:26:16 9a37b2677c18 jobs 	at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:227) ~[spring-web-5.3.20.jar!/:5.3.20]
Jun 2 17:26:16 9a37b2677c18 jobs 	at org.springframework.web.client.RestTemplate$HttpEntityRequestCallback.doWithRequest(RestTemplate.java:991) ~[spring-web-5.3.20.jar!/:5.3.20]
Jun 2 17:26:16 9a37b2677c18 jobs 	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:774) ~[spring-web-5.3.20.jar!/:5.3.20]
Jun 2 17:26:16 9a37b2677c18 jobs 	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711) ~[spring-web-5.3.20.jar!/:5.3.20]
Jun 2 17:26:16 9a37b2677c18 jobs 	at org.springframework.web.client.RestTemplate.put(RestTemplate.java:497) ~[spring-web-5.3.20.jar!/:5.3.20]
Jun 2 17:26:16 9a37b2677c18 jobs 	at com.epam.reportportal.elastic.SimpleElasticSearchClient.lambda$save$1(SimpleElasticSearchClient.java:64) ~[classes!/:na]
Jun 2 17:26:16 9a37b2677c18 jobs 	at com.epam.reportportal.elastic.SimpleElasticSearchClient$$Lambda$1080/0x000000010086d040.accept(Unknown Source) ~[na:na]
Jun 2 17:26:16 9a37b2677c18 jobs 	at java.base/java.util.HashMap.forEach(HashMap.java:1337) ~[na:na]
Jun 2 17:26:16 9a37b2677c18 jobs 	at com.epam.reportportal.elastic.SimpleElasticSearchClient.save(SimpleElasticSearchClient.java:63) ~[classes!/:na]
Jun 2 17:26:16 9a37b2677c18 jobs 	at com.epam.reportportal.log.LogProcessing.process(LogProcessing.java:33) ~[classes!/:na]
Jun 2 17:26:16 9a37b2677c18 jobs 	at com.epam.reportportal.calculation.BatchProcessing.processAndSchedule(BatchProcessing.java:54) ~[classes!/:na]
Jun 2 17:26:16 9a37b2677c18 jobs 	at com.epam.reportportal.calculation.BatchProcessing$$Lambda$735/0x000000010058d040.run(Unknown Source) ~[na:na]
Jun 2 17:26:16 9a37b2677c18 jobs 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.20.jar!/:5.3.20]
Jun 2 17:26:16 9a37b2677c18 jobs 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
Jun 2 17:26:16 9a37b2677c18 jobs 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
Jun 2 17:26:16 9a37b2677c18 jobs 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
Jun 2 17:26:16 9a37b2677c18 jobs 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
Jun 2 17:26:16 9a37b2677c18 jobs 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
Jun 2 17:26:16 9a37b2677c18 jobs 	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```
```
Jun 2 17:26:51 9a37b2677c18 jobs ERROR 1 --- [ntContainer#0-1] o.s.a.r.l.SimpleMessageListenerContainer : Consumer thread error, thread abort.
Jun 2 17:26:51 9a37b2677c18 jobs java.lang.OutOfMemoryError: Java heap space
Jun 2 17:26:51 9a37b2677c18 jobs 	at java.base/jdk.internal.misc.Unsafe.allocateUninitializedArray(Unsafe.java:1269) ~[na:na]
Jun 2 17:26:51 9a37b2677c18 jobs 	at java.base/java.lang.invoke.StringConcatFactory$MethodHandleInlineCopyStrategy.newArray(StringConcatFactory.java:1633) ~[na:na]
Jun 2 17:26:51 9a37b2677c18 jobs 	at java.base/java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(DirectMethodHandle$Holder) ~[na:na]
Jun 2 17:26:51 9a37b2677c18 jobs 	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000100849440.invoke(LambdaForm$MH) ~[na:na]
Jun 2 17:26:51 9a37b2677c18 jobs 	at java.base/java.lang.invoke.Invokers$Holder.linkToTargetMethod(Invokers$Holder) ~[na:na]
Jun 2 17:26:51 9a37b2677c18 jobs 	at com.epam.reportportal.elastic.SimpleElasticSearchClient.lambda$save$0(SimpleElasticSearchClient.java:57) ~[classes!/:na]
Jun 2 17:26:51 9a37b2677c18 jobs 	at com.epam.reportportal.elastic.SimpleElasticSearchClient$$Lambda$1079/0x0000000100869840.accept(Unknown Source) ~[na:na]
Jun 2 17:26:51 9a37b2677c18 jobs 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) ~[na:na]
Jun 2 17:26:51 9a37b2677c18 jobs 	at com.epam.reportportal.elastic.SimpleElasticSearchClient.save(SimpleElasticSearchClient.java:52) ~[classes!/:na]
Jun 2 17:26:51 9a37b2677c18 jobs 	at com.epam.reportportal.log.LogProcessing.process(LogProcessing.java:33) ~[classes!/:na]
Jun 2 17:26:51 9a37b2677c18 jobs 	at com.epam.reportportal.calculation.BatchProcessing.processAndSchedule(BatchProcessing.java:54) ~[classes!/:na]
Jun 2 17:26:51 9a37b2677c18 jobs 	at com.epam.reportportal.calculation.BatchProcessing.add(BatchProcessing.java:41) ~[classes!/:na]
Jun 2 17:26:51 9a37b2677c18 jobs 	at com.epam.reportportal.jobs.processing.SaveLogMessageJob.execute(SaveLogMessageJob.java:30) ~[classes!/:na]
Jun 2 17:26:51 9a37b2677c18 jobs 	at jdk.internal.reflect.GeneratedMethodAccessor45.invoke(Unknown Source) ~[na:na]
Jun 2 17:26:51 9a37b2677c18 jobs 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
Jun 2 17:26:51 9a37b2677c18 jobs 	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
Jun 2 17:26:51 9a37b2677c18 jobs 	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169) ~[spring-messaging-5.3.20.jar!/:5.3.20]
Jun 2 17:26:51 9a37b2677c18 jobs 	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119) ~[spring-messaging-5.3.20.jar!/:5.3.20]
Jun 2 17:26:51 9a37b2677c18 jobs 	at org.springframework.amqp.rabbit.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:75) ~[spring-rabbit-2.4.5.jar!/:2.4.5]
Jun 2 17:26:51 9a37b2677c18 jobs 	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:262) ~[spring-rabbit-2.4.5.jar!/:2.4.5]
Jun 2 17:26:51 9a37b2677c18 jobs 	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.invokeHandlerAndProcessResult(MessagingMessageListenerAdapter.java:208) ~[spring-rabbit-2.4.5.jar!/:2.4.5]
Jun 2 17:26:51 9a37b2677c18 jobs 	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:147) ~[spring-rabbit-2.4.5.jar!/:2.4.5]
Jun 2 17:26:51 9a37b2677c18 jobs 	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1657) ~[spring-rabbit-2.4.5.jar!/:2.4.5]
Jun 2 17:26:51 9a37b2677c18 jobs 	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1576) ~[spring-rabbit-2.4.5.jar!/:2.4.5]
Jun 2 17:26:51 9a37b2677c18 jobs 	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer$$Lambda$971/0x00000001007d4440.invokeListener(Unknown Source) ~[na:na]
Jun 2 17:26:51 9a37b2677c18 jobs 	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1564) ~[spring-rabbit-2.4.5.jar!/:2.4.5]
Jun 2 17:26:51 9a37b2677c18 jobs 	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1555) ~[spring-rabbit-2.4.5.jar!/:2.4.5]
Jun 2 17:26:51 9a37b2677c18 jobs 	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1499) ~[spring-rabbit-2.4.5.jar!/:2.4.5]
Jun 2 17:26:51 9a37b2677c18 jobs 	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:992) ~[spring-rabbit-2.4.5.jar!/:2.4.5]
Jun 2 17:26:51 9a37b2677c18 jobs 	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:939) ~[spring-rabbit-2.4.5.jar!/:2.4.5]
Jun 2 17:26:51 9a37b2677c18 jobs 	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:84) ~[spring-rabbit-2.4.5.jar!/:2.4.5]
Jun 2 17:26:51 9a37b2677c18 jobs 	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1316) ~[spring-rabbit-2.4.5.jar!/:2.4.5]
```
**Versions:**
 - OS, Browser
 - Version of RP: 5.8

**Comment by MaryiaRymarchyk** [comment]
Hi @Kanaduchi, could you please provide more details? What actions lead to this error logs?

**Comment by Kanaduchi** [comment]
@MaryiaRymarchyk I don't perform any special set of actions. Just write results by agent-java-testng. This error appears in the log every day.

**Comment by irynakozak2** [comment]
@Kanaduchi Hi, could you please provide the following essential details regarding your ReportPortal usage:

1. Did you face such issues on the previous ReportPortal versions?
2. Did your logs with stack traces have more than 500 symbols?
3. Installation details: CPU and RAM size for the ReportPortal installation and the service-jobs container JAVA_OPTS value.

Thank you and waiting for your reply.

**Comment by Kanaduchi** [comment]
@irynakozak2 
1. I haven't checked logs before. I found these errors by checking logs after migration to 5.8
2. We have big stack traces, for example, Cassandra Datastax client generates stack traces with more than 10000 symbols
3. I don't specify any custom JAVA_OPTS for service-jobs container. Instance is t2.xlarge

**Comment by irynakozak2** [comment]
@Kanaduchi Hi! Thank you for the information. We confirm that currently is a known issue with the Java Memory utilization for the service jobs while large stack traces are reported to the ReportPortal. Besides, we have profiled JVM for our service jobs to identify the optimal and stable configuration and reduce the restarts. 
The performance testing isn't finished yet, these values should pass the additional performance checks, but I can share our JAVA_OPTS which were stabilized service jobs in our infrastructure:

`-Djava.security.egd=file:/dev/./urandom -XX:+UseG1GC -XX:G1HeapRegionSize=32m -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=70 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp`

If you have a possibility, please test it on the non-prod environment.
Hope it helps.

Waiting for your reply!

**Comment by irynakozak2** [comment]
@Kanaduchi Hi! Did you have a chance to apply the proposed env variables for the jobs service?

**Comment by Kanaduchi** [comment]
@irynakozak2 Hi Iryna! Yes, I've applied JAVA_OPTS recommended by you. I am waiting for our regression tests to verify this error is fixed. Once I get the statistics I will share it here

**Comment by irynakozak2** [comment]
@Kanaduchi Perfect, waiting for your updates!

**Comment by Kanaduchi** [comment]
This error still exists.

<img width="497" alt="image" src="https://github.com/reportportal/reportportal/assets/7042994/084369fa-b845-4004-b10e-646f7bbe67dc">

It appears today after our regression tests have started writing the results.

**Comment by irynakozak2** [comment]
Okay, thank you for the updates. Since the 5.7.4 version of the service-jobs is handled more load (logs double-entry in added to write the test logs to the PostgreSQL database and Elasticsearch), the instance shape should be scaled up. Based on the size of your logs, I think the issue can be with the insufficient CPU and RAM count. My suggestion to you is to scale up your ReportPortal instance and/or allocate for the jobs service at least 0.5 CPU and 1 Gb RAM.

**Comment by irynakozak2** [comment]
Could you please share your RP deployment for checking the service requests and limits? Do you use docker-compose or Kubernetes?

**Comment by irynakozak2** [comment]
@Kanaduchi Hi! Seems like the current shape isn't suitable for your workload anymore. 
My suggestions could be:

- [ ] Check the CPU and RAM utilization of the docker machine where the RP is hosted. 
- [ ] Check CPU and RAM utilization per each docker container. Please use docker stats or install the basic monitoring.
- [ ] Identify whether CPU or RAM resources aren't enough to handle your workload and scale up the RP machine.

**Comment by DzmitryHumianiuk** [comment]
Closing this issue due to inactivity. 

If this still remains a concern or if there are new developments, please feel free to reopen or create a new issue. 

Thank you for your understanding and contributions to the project!
