### ISSUE TITLE
API Server is not able to connect to Minio after Changing Persistance Volume Size

### ISSUE THREAD

**Issue by samagarw** [reportportal/reportportal#2032]
Scaled down the pod to 0 for minio . 
Increased the pv size .
Scaled the pod again using deployment on kubernetes . 
Getting below error in api server as it is not able to connect to Minio . 
```
java.net.ConnectException: Failed to connect to minio.reportportal.svc.cluster.local/x.x.x.x:9000
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at io.minio.MinioClient.executeReq(MinioClient.java:1123)
	at io.minio.MinioClient.execute(MinioClient.java:1082)
	at io.minio.MinioClient.executeHead(MinioClient.java:1353)
	at io.minio.MinioClient.bucketExists(MinioClient.java:3613)	
at com.epam.ta.reportportal.filesystem.distributed.minio.MinioDataStore.save(MinioDataStore.java:60)
	at com.epam.ta.reportportal.binary.impl.CommonDataStoreService.save(CommonDataStoreService.java:44)
	at com.epam.ta.reportportal.binary.impl.AttachmentBinaryDataServiceImpl.saveAttachment(AttachmentBinaryDataServiceImpl.java:92)
	at com.epam.ta.reportportal.core.log.impl.SaveLogBinaryDataTaskAsync.get(SaveLogBinaryDataTaskAsync.java:55)
	at com.epam.ta.reportportal.core.log.impl.SaveLogBinaryDataTaskAsync.get(SaveLogBinaryDataTaskAsync.java:40)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
	... 31 common frames omitted
```

**Comment by MaryiaRymarchyk** [comment]
Hi @samagarw  if the issue still actual, let us know which version of RP do you use.
