### ISSUE TITLE
Error while initializing logger: logger://ReportPortal

### ISSUE THREAD

**Issue by iamkrk** [reportportal/reportportal#2039]
Hi Team,

Good Day!

I am trying to configure and use ReportPortal through Docker Desktop for windows. 

In my automation framework, installed the required package "ReportPortal.VSTest.TestLogger" and am trying to launch the test with the below command:

`dotnet vstest Tests.dll /TestCaseFilter:"(TestCategory=Test ID)" --logger:ReportPortal`

Am running into below error:

`Microsoft (R) Test Execution Command Line Tool Version 16.11.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Unexpected exception in Initialize: System.IO.FileLoadException: Could not load file or assembly 'System.Text.Json, Version=6.0.0.6, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)
File name: 'System.Text.Json, Version=6.0.0.6, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at ReportPortal.Shared.Configuration.Providers.JsonFileConfigurationProvider.GetFlattenProperties(String json)
   at ReportPortal.Shared.Configuration.Providers.JsonFileConfigurationProvider.Load()
   at ReportPortal.Shared.Configuration.ConfigurationBuilder.Build()
   at ReportPortal.VSTest.TestLogger.ReportPortalLogger.Initialize(TestLoggerEvents events, String testRunDirectory) in C:\projects\agent-net-vstest\src\ReportPortal.VSTest.TestLogger\ReportPortalLogger.cs:line 66
Unexpected exception in Initialize: System.IO.FileLoadException: Could not load file or assembly 'System.Text.Json, Version=6.0.0.6, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)
File name: 'System.Text.Json, Version=6.0.0.6, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at ReportPortal.Shared.Configuration.Providers.JsonFileConfigurationProvider.GetFlattenProperties(String json)
   at ReportPortal.Shared.Configuration.Providers.JsonFileConfigurationProvider.Load()
   at ReportPortal.Shared.Configuration.ConfigurationBuilder.Build()
   at ReportPortal.VSTest.TestLogger.ReportPortalLogger.Initialize(TestLoggerEvents events, String testRunDirectory) in C:\projects\agent-net-vstest\src\ReportPortal.VSTest.TestLogger\ReportPortalLogger.cs:line 66
   at ReportPortal.VSTest.TestLogger.ReportPortalLogger.Initialize(TestLoggerEvents events, Dictionary`2 parameters) in C:\projects\agent-net-vstest\src\ReportPortal.VSTest.TestLogger\ReportPortalLogger.cs:line 95
Error while initializing logger: logger://ReportPortal, Exception details: Could not load file or assembly 'System.Text.Json, Version=6.0.0.6, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)`

Not sure where I am going wrong here. Tried to fix but no luck.

Need your support here to fix this issue. Thanks in advance.

Thanks,
Karthik K R

**Comment by nvborisenko** [comment]
Hi @iamkrk , can you please add `--Diag RPDiag.txt` argument for command to execute tests, and share `RPDiag.file`?

**Comment by iamkrk** [comment]
Hi @nvborisenko ,

PFA the Diagnostic Information file.

Thanks,
Karthik K R
[RPDiag.txt](https://github.com/reportportal/reportportal/files/11883194/RPDiag.txt)

**Comment by nvborisenko** [comment]
Short suggestion just use .NET SDK 6 - https://dotnet.microsoft.com/en-us/download/dotnet

**Comment by iamkrk** [comment]
Hi @nvborisenko ,

Still running into same issue with .NET SDK 6 as well.

Thanks
Karthik K R
[RPDiag.txt](https://github.com/reportportal/reportportal/files/11884603/RPDiag.txt)

**Comment by nvborisenko** [comment]
I was able to reproduce the issue. Looks like your tests target framework is 4.8? If yes, then use .NET SDK 7 :)

**Comment by nvborisenko** [comment]
If not, I would ask to share your csproj file.

**Comment by iamkrk** [comment]
Currently I am using VS 2019 which doesn't support .NET 6 or above. Seems like I need to upgrade the VS to 2022.

Does ReportPortal work only with .NET 6 and above?

**Comment by nvborisenko** [comment]
You can stay on .net framework 4.8. It allows you to use VS 2019 as IDE. But to execute tests, it's required to use .NET SDK 7 (just download and install).

**Comment by iamkrk** [comment]
You are right @nvborisenko . Execution with dotnet command worked after installing .NET SDK 7

`dotnet vstest Tests.dll /TestCaseFilter:"(TestCategory=Test ID)" --logger:ReportPortal`
