### ISSUE TITLE
Newtonsoft.Json dependancy issue when use reportportal for nunit 3

### ISSUE THREAD

**Issue by KursLabIgor** [reportportal/reportportal#204]
In case if your project use Newtonsoft.Json version >9 and nunit 3 run tests failed with following error. 
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'ReportPortal.NUnitExtension.ReportPortalListener' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
   at ReportPortal.NUnitExtension.ReportPortalListener..cctor()
   --- End of inner exception stack trace ---
   at ReportPortal.NUnitExtension.ReportPortalListener..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at NUnit.Engine.Extensibility.ExtensionNode.CreateExtensionObject(Object[] args)
   at NUnit.Engine.Extensibility.ExtensionNode.get_ExtensionObject()
   at NUnit.Engine.Services.ExtensionService.<GetExtensions>d__19`1.MoveNext()
   at NUnit.Engine.Runners.MasterTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
   at NUnit.ConsoleRunner.Program.Main(String[] args)
```

**Comment by KursLabIgor** [comment]
after installing NewtonSoft.Json version 9.01 following error occurs:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'ReportPortal.NUnitExtension.ReportPortalListener' threw an exception. ---> System.TypeInitializationException: The type initializer for 'ReportPortal.Shared.Bridge' threw an exception. ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at ReportPortal.Shared.Bridge..cctor()
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Bridge.set_Service(Service value)
   at ReportPortal.NUnitExtension.ReportPortalListener..cctor()
   --- End of inner exception stack trace ---
   at ReportPortal.NUnitExtension.ReportPortalListener..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at NUnit.Engine.Extensibility.ExtensionNode.CreateExtensionObject(Object[] args)
   at NUnit.Engine.Extensibility.ExtensionNode.get_ExtensionObject()
   at NUnit.Engine.Services.ExtensionService.<GetExtensions>d__19`1.MoveNext()
   at NUnit.Engine.Runners.MasterTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
   at NUnit.ConsoleRunner.Program.Main(String[] args)

**Comment by nvborisenko** [comment]
@KursLabIgor please use newtonsoft.json 9.0.1 and the latest ReportPortal.Shared beta version.

**Comment by KursLabIgor** [comment]
ok. will check

**Comment by DzmitryHumianiuk** [comment]
@KursLabIgor it works?

**Comment by KursLabIgor** [comment]
sorry, didnt have time handle this. i'm going to check next week

**Comment by KursLabIgor** [comment]
updates:
install latest beta ReportPortal.Shared and use NewtonSoft.Json version 9.01 Now result:
in case if install 10, back to previous error.
ReportPortal exception was thrown.
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
   at ReportPortal.Client.Service.StartLaunch(StartLaunchRequest model)
   at ReportPortal.Shared.LaunchReporter.<>c__DisplayClass4_0.<Start>b__0()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at ReportPortal.Shared.LaunchReporter.<>c__DisplayClass6_0.<Finish>b__0()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at ReportPortal.NUnitExtension.ReportPortalListener.FinishRun(XmlDocument xmlDoc)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
   at ReportPortal.Client.Service.StartLaunch(StartLaunchRequest model)
   at ReportPortal.Shared.LaunchReporter.<>c__DisplayClass4_0.<Start>b__0()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at ReportPortal.Shared.LaunchReporter.<>c__DisplayClass6_0.<Finish>b__0()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at ReportPortal.Client.Service.StartLaunch(StartLaunchRequest model)
   at ReportPortal.Shared.LaunchReporter.<>c__DisplayClass4_0.<Start>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by nvborisenko** [comment]
This is will be resolved in scope of https://github.com/reportportal/client-net/issues/3

**Comment by nvborisenko** [comment]
Fixed in 3.3.0-beta1

**Comment by KursLabIgor** [comment]
guys, how i can get code with fixes?

**Comment by DzmitryHumianiuk** [comment]
@nvborisenko ^

**Comment by KursLabIgor** [comment]
guys question is still relevant. I dont see 3.3.0-beta1 branch in list

**Comment by nvborisenko** [comment]
@KursLabIgor it's not a branch, this is version of nuget package. This package doesn't require newtonsoft.json at all.

**Comment by KursLabIgor** [comment]
@nvborisenko thanks, now is clear

**Comment by KursLabIgor** [comment]
I installed version below and got error again. 
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'ReportPortal.NUnitExtension.ReportPortalListener' threw an exception. ---> System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type ReportPortal.NUnitExtension.Configuration.Config. Encountered unexpected character '/'. ---> System.Xml.XmlException: Encountered unexpected character '/'.
   at System.Xml.XmlExceptionHelper.ThrowXmlException(XmlDictionaryReader reader, XmlException exception)
   at System.Runtime.Serialization.Json.XmlJsonReader.Read()
   at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at ReadServerFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at ReadConfigFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   --- End of inner exception stack trace ---
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at ReportPortal.Client.Converters.ModelSerializer.Deserialize[T](String json)
   at ReportPortal.NUnitExtension.ReportPortalListener..cctor()
   --- End of inner exception stack trace ---
   at ReportPortal.NUnitExtension.ReportPortalListener..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at NUnit.Engine.Extensibility.ExtensionNode.CreateExtensionObject(Object[] args)
   at NUnit.Engine.Extensibility.ExtensionNode.get_ExtensionObject()
   at NUnit.Engine.Services.ExtensionService.<GetExtensions>d__19`1.MoveNext()
   at NUnit.Engine.Runners.MasterTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
   at NUnit.ConsoleRunner.Program.Main(String[] args)

**Comment by nvborisenko** [comment]
It seems configuration file has incorrect content. Could you please remove all commented lines in `ReportPortal.conf` and execute tests again?

**Comment by KursLabIgor** [comment]
{
  "enabled": true,
  "server": {
    "url": "https://localhost/api/v1/",
    "project": "default_project",
    "authentication": {
      "uuid": "f4b62e41-9575-4318-bd5d-3bdac5eadd03"
    },

  },
  "launch": {
    "name": "NUnit 3 Demo Launch",
    "description": "this is description",
    "debugMode": true,
    "tags": [ "t1", "t2" ]
  }
}
Now error like:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'ReportPortal.NUnitExtension.ReportPortalListener' threw an exception. ---> System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type ReportPortal.NUnitExtension.Configuration.Config. There are multiple root elements. ---> System.Xml.XmlException: There are multiple root elements.

**Comment by nvborisenko** [comment]
Example of config file: https://github.com/reportportal/example-net-nunit/blob/master/src/Example/ReportPortal.conf

**Comment by KursLabIgor** [comment]
ok, thanks found the problem. now works
