### ISSUE TITLE
Exported reports from report portal is blank

### ISSUE THREAD

**Issue by mkothuru** [reportportal/reportportal#2040]
When exporting a launch in pdf, html, xls formats, report generated is blank.

Expected behavior:
Report should be generated with information about the launch

**Comment by APiankouski** [comment]
Hi @mkothuru, we reuploaded service-api images to docker hub with fix this issue.
You can redeploy with new image reportportal/service-api:5.8.0

**Comment by mkothuru** [comment]
Hi @APiankouski , I have deployed the latest version of report portal i.e, the service-api is 5.8.0. The issue is still reproducible.

**Comment by APiankouski** [comment]
Kubernetes can cache old 5.8.0 image. Make sure that new image was downloaded. They both have 5.8.0 tag.

**Comment by mkothuru** [comment]
redeployed reportportal/service-api:5.8.0, reports still seem to be blank

**Comment by DzmitryHumianiuk** [comment]
@arunkumar832 @mkothuru is it still actual?
it works for me on 5.8.0 API.

**Comment by schneider-technology** [comment]
same for me, double checked docker image as well: 5.8.0

**Comment by DzmitryHumianiuk** [comment]
@schneider-technology does your launch contain test cases? 
Are they reported as individual test cases or as a test classes?

Please share the screenshots, with the masked data on them, so we can verify if it's still being reported properly.

Another thing to check in the background: please see what's in the `service-api` logs at this moment. Thank you!

**Comment by schneider-technology** [comment]
My launch contains test cases, although i'm not too sure what you mean by "test classes".
For safety i just generated Demo Data through the project settings and the same thing happens: empty *.pdf/*.xls and .html are downloaded.

My log:

```
2023-08-02 10:33:30.132 ERROR 1 --- [nio-8585-exec-6] c.e.t.r.c.e.rest.DefaultErrorResolver    : Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class net.sf.jasperreports.engine.util.JRStyledTextParser

org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class net.sf.jasperreports.engine.util.JRStyledTextParser
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1082)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:670)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.multipart.support.MultipartFilter.doFilterInternal(MultipartFilter.java:125)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:121)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:182)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.sf.jasperreports.engine.util.JRStyledTextParser
        at net.sf.jasperreports.engine.fill.JRBaseFiller.<init>(JRBaseFiller.java:116)
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.<init>(JRVerticalFiller.java:79)
        at net.sf.jasperreports.engine.fill.JRFiller.createBandReportFiller(JRFiller.java:251)
        at net.sf.jasperreports.engine.fill.JRFiller.createReportFiller(JRFiller.java:272)
        at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:156)
        at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:145)
        at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:758)
        at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:1074)
        at com.epam.ta.reportportal.core.jasper.JasperReportRender.generateReportPrint(JasperReportRender.java:81)
        at com.epam.ta.reportportal.core.jasper.impl.LaunchJasperReportHandler.getJasperPrint(LaunchJasperReportHandler.java:64)
        at com.epam.ta.reportportal.core.launch.impl.GetLaunchHandlerImpl.exportLaunch(GetLaunchHandlerImpl.java:313)
        at com.epam.ta.reportportal.core.launch.impl.GetLaunchHandlerImpl$$FastClassBySpringCGLIB$$21f6db8c.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
        at com.epam.ta.reportportal.core.launch.impl.GetLaunchHandlerImpl$$EnhancerBySpringCGLIB$$4749ac71.exportLaunch(<generated>)
        at com.epam.ta.reportportal.ws.controller.LaunchController.getLaunchReport(LaunchController.java:356)
        at com.epam.ta.reportportal.ws.controller.LaunchController$$FastClassBySpringCGLIB$$702dfa6.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
        at com.epam.ta.reportportal.ws.controller.LaunchController$$EnhancerBySpringCGLIB$$e8d379ef.getLaunchReport(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
        ... 84 common frames omitted

```

**Comment by subha0990** [comment]
Hi Team, 

I am also facing same issue. I am using   api: image: reportportal/service-api:5.8.0 version. 
I noticed Export with (PDF, XLS, HTML) generating blank records.

Kindly help!
Thanks in Advance!

**Comment by DzmitryHumianiuk** [comment]
@subha0990 @schneider-technology @arunkumar832 @mkothuru 
### Resolutions: fixed
released in the patched `service-api` with a tag `5.8.0-exportFix`

Please update your version of the service-api in docker compose from `5.8.0` to `5.8.0-exportFix`

Docker image:
https://hub.docker.com/layers/reportportal/service-api/5.8.0-exportFix/images/sha256-7553e46a27894148a30ab539f7a0aa5cfa8cac2041bec0dcb54c05caadc36be5?context=explore


```yml
  api:
📍  image: reportportal/service-api:5.8.0-exportFix
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      ## Double entry moves test logs from PostgreSQL to Elastic-type engines
      ## Ref: https://reportportal.io/blog/double-entry-in-5.7.2
      RP_ELASTICSEARCHLOGMESSAGE_HOST: "true"
      RP_DB_HOST: postgres
      RP_DB_USER: rpuser
      RP_DB_PASS: rppass
      RP_DB_NAME: reportportal
      RP_AMQP_USER: rabbitmq
      RP_AMQP_PASS: rabbitmq
      RP_AMQP_APIUSER: rabbitmq
      RP_AMQP_APIPASS: rabbitmq
      RP_AMQP_ANALYZER-VHOST: analyzer
      RP_BINARYSTORE_TYPE: minio
      RP_BINARYSTORE_MINIO_ENDPOINT: http://minio:9000
      RP_BINARYSTORE_MINIO_ACCESSKEY: minio
      RP_BINARYSTORE_MINIO_SECRETKEY: minio123
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: info
      RP_REQUESTLOGGING: "false"
      MANAGEMENT_HEALTH_ELASTICSEARCH_ENABLED: "false"
      JAVA_OPTS: -Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp  -Dcom.sun.management.jmxremote.rmi.port=12349 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false  -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=0.0.0.0
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://0.0.0.0:8585/health || exit 1
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 60s
    labels:
      - "traefik.http.middlewares.api-strip-prefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.api.middlewares=api-strip-prefix@docker"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.api.service=api"
      - "traefik.http.services.api.loadbalancer.server.port=8585"
      - "traefik.http.services.api.loadbalancer.server.scheme=http"
      - "traefik.expose=true"
    restart: always
```

**Comment by pkolomytsev** [comment]
Failed to load UI after updating to 5.8.0-exportFix. I see `Loading...` and an error in the browser console: `TypeError: Cannot convert undefined or null to object`. This is a fresh deployment using the `docker-compose.yml` example and WSL 2 as a docker backend.

**Comment by heilwood** [comment]
> Failed to load UI after updating to 5.8.0-exportFix. I see `Loading...` and an error in the browser console: `TypeError: Cannot convert undefined or null to object`. This is a fresh deployment using the `docker-compose.yml` example and WSL 2 as a docker backend.

same, api service unable to start

**Comment by DzmitryHumianiuk** [comment]
@heilwood @pkolomytsev anything special in the `service-api` logs?

**Comment by pkolomytsev** [comment]
@DzmitryHumianiuk

> make sure that the other services are in accordance with 23.1 release.

I am using this compose file - https://github.com/reportportal/reportportal/blob/master/docker-compose.yml, just changed `reportportal/service-api:5.8.0` to `reportportal/service-api:5.8.0-exportFix`.

> and please restart the whole application via docker-compose.

The application was completely removed (containers, volumes, data folder, images) and recreated.

> anything special in the `service-api` logs?

I don't see any significant difference between the two logs, I've attached them.

[api-log.txt](https://github.com/reportportal/reportportal/files/12261831/api-log.txt)
[api-fix-log.txt](https://github.com/reportportal/reportportal/files/12261829/api-fix-log.txt)

**Comment by DzmitryHumianiuk** [comment]
@pkolomytsev nothing special in logs.

could you please check what `https://SERVER/composite/info` returns you?

**Comment by pkolomytsev** [comment]
@DzmitryHumianiuk 

> could you please check what https://SERVER/composite/info returns you?

```
{
  "index": {
    "build": {
      "branch": "3e92619",
      "build_date": "2023-06-01T16:13:32+0000",
      "name": "Index Service",
      "repo": "reportportal/service-index",
      "version": "5.8.0"
    }
  },
  "jobs": {
    "build": {
      "branch": "master-1da3d20f328acc968557d79c9ac2368a739b2226",
      "description": "ReportPortal Jobs Service",
      "name": "Jobs Service",
      "repo": "reportportal/service-jobs",
      "version": "5.8.0"
    }
  },
  "uat": {
    "authExtensions": {},
    "build": {
      "branch": "master-8dbe2cc28e06b6372887a62d16c795c61066d0b0",
      "description": "Unified Authorization Trap for all ReportPortal's Services",
      "name": "Authorization Service",
      "repo": "reportportal/service-authorization",
      "version": "5.8.0"
    },
    "metadata": {
      "project_roles": ["OPERATOR", "CUSTOMER", "MEMBER", "PROJECT_MANAGER"]
    }
  },
  "ui": {
    "build": {
      "branch": "hotfix/5.8.0-91b9e05926024569f773f953fd99b8106a3e7100",
      "build_date": "2023-04-21T12:14:15+0000",
      "name": "Service UI",
      "repo": "reportportal/service-ui",
      "version": "5.8.0"
    }
  }
}

```

**Comment by DzmitryHumianiuk** [comment]
@pkolomytsev you are missing API service registered in the system.
here is how it looks for me.

try to restart with --force-recreate flag for docker compose.


```json
{
  "api": {
    "build": {
      "branch": "HEAD-7bae8829bda5c4dc8ab6538b5145443e47a34836",
      "description": "ReportPortal API Service",
      "name": "API Service",
      "repo": "reportportal/service-api",
      "version": "5.8.0"
    },
    "environment": {},
    "extensions": {
      "analyzers": [
        {
          "analyzer": "analyzer-default",
          "analyzer_cluster": true,
          "analyzer_index": true,
          "analyzer_log_search": true,
          "analyzer_priority": 1,
          "analyzer_suggest": true,
          "version": "5.7.5-RC-13"
        }
      ],
      "extension": [
        "JIRA Cloud",
        "quality gate",
        "saucelabs",
        "rally",
        "Azure DevOps",
        "jira",
        "billing"
      ],
      "result": {
        "server.analytics.all": "true"
      }
    },
    "jobs": {
      "cleanExpiredCreationBidsTrigger": {
        "triggersIn": 229559
      },
      "interruptLaunchesTrigger": {
        "triggersIn": 229546
      },
      "qgResultTimeoutTrigger": {
        "triggersIn": 109022
      }
    },
    "metadata": {
      "activityAction": [
        "createDashboard",
        "updateDashboard",
        "deleteDashboard",
        "createWidget",
        "updateWidget",
        "deleteWidget",
        "createFilter",
        "updateFilter",
        "deleteFilter",
        "analyzeItem",
        "createDefect",
        "updateDefect",
        "deleteDefect",
        "createIntegration",
        "updateIntegration",
        "deleteIntegration",
        "startLaunch",
        "finishLaunch",
        "deleteLaunch",
        "updateProject",
        "updateAnalyzer",
        "postIssue",
        "linkIssue",
        "linkIssueAa",
        "unlinkIssue",
        "updateItem",
        "createUser",
        "deleteIndex",
        "generateIndex",
        "startImport",
        "finishImport",
        "createPattern",
        "updatePattern",
        "deletePattern",
        "patternMatched"
      ],
      "activityEntityType": [
        "launch",
        "item",
        "dashboard",
        "defectType",
        "emailConfig",
        "filter",
        "import",
        "integration",
        "itemIssue",
        "project",
        "sharing",
        "ticket",
        "user",
        "widget",
        "pattern"
      ]
    }
  },
  "index": {
    "build": {
      "branch": "3e92619",
      "build_date": "2023-06-01T16:13:32+0000",
      "name": "Index Service",
      "repo": "reportportal/service-index",
      "version": "5.8.0"
    }
  },
  "uat": {
    "authExtensions": {},
    "build": {
      "branch": "master-8dbe2cc28e06b6372887a62d16c795c61066d0b0",
      "description": "Unified Authorization Trap for all ReportPortal's Services",
      "name": "Authorization Service",
      "repo": "reportportal/service-authorization",
      "version": "5.8.0"
    },
    "metadata": {
      "project_roles": [
        "OPERATOR",
        "CUSTOMER",
        "MEMBER",
        "PROJECT_MANAGER"
      ]
    }
  },
  "ui": {
    "build": {
      "branch": "hotfix/5.8.0-91b9e05926024569f773f953fd99b8106a3e7100",
      "build_date": "2023-04-21T12:14:15+0000",
      "name": "Service UI",
      "repo": "reportportal/service-ui",
      "version": "5.8.0"
    }
  }
}
```

**Comment by pkolomytsev** [comment]
@DzmitryHumianiuk 

> try to restart with --force-recreate flag for docker compose.

Same result. Latest log messages:
```
INFO 1 --- [           main] c.e.h.IntegrationSecretsMigrationHandler : Secrets migration is not needed
INFO 1 --- [_ClusterManager] o.s.s.quartz.LocalDataSourceJobStore     : ClusterManager: detected 1 failed or restarted instances.
INFO 1 --- [_ClusterManager] o.s.s.quartz.LocalDataSourceJobStore     : ClusterManager: Scanning for instance "api:0edf21f7e19ed83cf150781a9e212954"'s failed in-progress jobs.
```
