### ISSUE TITLE
service-api:5.8.0 is getting unhealthy intermittently after upgrading report portal 5.6.3 to 5.8.0(23.1)

### ISSUE THREAD

**Issue by nitin-vhanakaware** [reportportal/reportportal#2054]
**Describe the bug**
After upgrading report portal 5.6.3 to 5.8.0(23.1) service-api:5.8.0 is becoming unhealthy intermittently and reporportal is going down after that. 

Also updated the user access tokens as suggested here https://github.com/reportportal/reportportal/issues/1970 but issue is still persist

**Expected behavior**
report portal should work as expected without any error with all the container healthy after upgradation to 23.1

**Showing below exceptions in logs**
- java.io.InvalidClassException: Overriding serialized class version mismatch: local serialVersionUID = 550 stream serialVersionUID = com.epam.ta.reportportal.auth.util.AuthUtils$SerialUidReplacingInputStream.readClassDescriptor(AuthUtils.java:105)

- org.springframework.amqp.AmqpIOException: com.rabbitmq.client.ChannelContinuationTimeoutException
-  com.epam.ta.reportportal.exception.ReportPortalException: com.rabbitmq.client.ChannelContinuationTimeoutException: Continuation call for method #method<channel.open>(out-of-band=) on channel AMQChannel

**Versions:**
 5.8.0(23.1)

**Stack trace -** 

**java.io.InvalidClassException**: Overriding serialized class version mismatch: local serialVersionUID = 550 stream serialVersionUID = 520
at com.epam.ta.reportportal.auth.util.AuthUtils$SerialUidReplacingInputStream.readClassDescriptor(AuthUtils.java:105)
at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1992)
at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1870)
at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2201)
at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1687)
at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:489)
at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:447)
at java.base/java.util.ArrayList.readObject(ArrayList.java:929)
at java.base/jdk.internal.reflect.GeneratedMethodAccessor237.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1046)

**com.epam.ta.reportportal.exception.ReportPortalException**: com.rabbitmq.client.ChannelContinuationTimeoutException: Continuation call for method #method<channel.open>(out-of-band=) on channel AMQChannel  timed out
at com.epam.ta.reportportal.core.analyzer.auto.impl.LogIndexerService.indexLaunchLogs(LogIndexerService.java:109)
at com.epam.ta.reportportal.core.analyzer.auto.impl.LogIndexerService$$FastClassBySpringCGLIB$$f53c9b3b.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)

**org.springframework.amqp.AmqpIOException**: com.rabbitmq.client.ChannelContinuationTimeoutException: Continuation call for method #method<channel.open>(out-of-band=) on channel AMQChannel  timed out
at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:70)
at org.springframework.amqp.rabbit.connection.SimpleConnection.createChannel(SimpleConnection.java:69)
at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$ChannelCachingConnectionProxy.createBareChannel(CachingConnectionFactory.java:1408)
at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$ChannelCachingConnectionProxy.access$200(CachingConnectionFactory.java:1394)
at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.doCreateBareChannel(CachingConnectionFactory.java:696)
at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createBareChannel(CachingConnectionFactory.java:679)
at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.getCachedChannelProxy(CachingConnectionFactory.java:649)
at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.getChannel(CachingConnectionFactory.java:539)
at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.access$1600(CachingConnectionFactory.java:99)
at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$ChannelCachingConnectionProxy.createChannel(CachingConnectionFactory.java:1413)

WARN 1 --- [MI TCP Accept-0] sun.rmi.transport.tcp                    : RMI TCP Accept-0: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=43488] throws
**java.net.SocketTimeoutException**: Accept timed out
at java.base/java.net.PlainSocketImpl.socketAccept(Native Method)
at java.base/java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:474)
at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:565)
at java.base/java.net.ServerSocket.accept(ServerSocket.java:533)
at java.rmi/sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:394)
at java.rmi/sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:366)
at java.base/java.lang.Thread.run(Thread.java:829)

WARN 1 --- [CP Accept-12349] sun.rmi.transport.tcp                    : RMI TCP Accept-12349: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=12349] throws
**java.net.SocketTimeoutException**: Accept timed out
at java.base/java.net.PlainSocketImpl.socketAccept(Native Method)
at java.base/java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:474)
at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:565)
at java.base/java.net.ServerSocket.accept(ServerSocket.java:533)
at java.rmi/sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:394)
at java.rmi/sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:366)
at java.base/java.lang.Thread.run(Thread.java:829)

WARN 1 --- [TCP Accept-9010] sun.rmi.transport.tcp                    : RMI TCP Accept-9010: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=9010] throws
**java.net.SocketTimeoutException**: Accept timed out
at java.base/java.net.PlainSocketImpl.socketAccept(Native Method)
at java.base/java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:474)
at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:565)
at java.base/java.net.ServerSocket.accept(ServerSocket.java:533)
at java.rmi/sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:394)
at java.rmi/sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:366)
at java.base/java.lang.Thread.run(Thread.java:829)

ERROR 1 --- [nio-8585-exec-2] .t.r.c.e.r.ReportPortalExceptionResolver : ReportPortalExceptionResolver > java.io.IOException: Broken pipe

**org.apache.catalina.connector.ClientAbortException**: java.io.IOException: Broken pipe
at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:353)
at org.apache.catalina.connector.OutputBuffer.flushByteBuffer(OutputBuffer.java:784)
at org.apache.catalina.connector.OutputBuffer.append(OutputBuffer.java:689)
at org.apache.catalina.connector.OutputBuffer.writeBytes(OutputBuffer.java:388)
at org.apache.catalina.connector.OutputBuffer.write(OutputBuffer.java:366)

CC: 
@anandbagmar
@shubhangiBajpai
@grover-ankit11

**Comment by HardNorth** [comment]
Duplicates https://github.com/reportportal/reportportal/issues/1970
