### ISSUE TITLE
HTTP 403 Forbidden while connecting to report Portal

### ISSUE THREAD

**Issue by JavedAkramGit** [reportportal/reportportal#2060]
Hi ,

I have been trying to connect to Report Portal via localhost:8080 and it has been configured.But while trying to run my selenium suite via testng,i have been getting the same 403 forbidden error incessantly multiple times ever since i completed the setup.

For reference, steps followed so far:
1. Deployed Report portal via Docker Compose through docker ( Also added folders as per official site instruction ->Data, elastic search etc )
2. Created a test suite in selenium and configured report portal by adding the respective dependencies( agent-java-testng,log4j etc) in pom.xml
3. Added the Reporttestng listener in the testng.xml file
 I have also tried adding the listener as a property on pom.xml as tried running from cmd line but the same 403 forbidden issue persists.

Original log trace of  the error:
```
7550 [rp-io-2] ERROR com.epam.reportportal.service.Launch - [20] ReportPortal execution error
retrofit2.adapter.rxjava2.HttpException: HTTP 403 Forbidden
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

I have been running this on mac, JRE 17,Latest report portal version,Selenium 4.9.1, testng 7.4.0,agent-java-testng 5.3.0, logger-java-log4j 5.1.4.
 Owing to this issue, i am unable to view none of the launches on report portal UI.
Currently, in dire need of help. I have literally got migraine headache due to this issue

**Comment by DzmitryHumianiuk** [comment]
@JavedAkramGit both ReportPortal and Selenium tests are run on the same laptop?
try to regenerate the UUID (API token starting version 23.1++) for data reporting

**Comment by DzmitryHumianiuk** [comment]
Closing this issue due to inactivity. 

If this still remains a concern or if there are new developments, please feel free to create a new issue. 

Thank you for your understanding and contributions to the project!

**Comment by gokulsukumar** [comment]
> @JavedAkramGit both ReportPortal and Selenium tests are run on the same laptop? try to regenerate the UUID (API token starting version 23.1++) for data reporting

I have the same issue. UUID is regenerated but no solving the problem. Please could you help?

**Comment by DzmitryHumianiuk** [comment]
@gokulsukumar what's you version of ReportPortal?
it should be API-KEY instead of the UUID now for the reporting purposes (in property file).
