### ISSUE TITLE
Two pods failing to start following tutorial

### ISSUE THREAD

**Issue by AlexandruCh** [reportportal/reportportal#2109]
**Describe the bug**

Attempting to spin up the env on GCloud following tutorial https://github.com/reportportal/kubernetes/tree/develop/reportportal

Getting 
"Error creating bean with name ..."
2 pods are failing with similar errors

**report-portal-reportportal-api** 
`Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.health.HealthContributorRegistry]: Factory method 'healthContributorRegistry' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'rabbitHealthContributor' defined in class path resource [org/springframework/boot/actuate/autoconfigure/amqp/RabbitHealthContributorAutoConfiguration.class]: Unsatisfied dependency expressed through method 'rabbitHealthContributor' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'rabbitTemplate' defined in class path resource [com/epam/ta/reportportal/core/configs/rabbit/RabbitMqConfiguration.class]: Unsatisfied dependency expressed through method 'rabbitTemplate' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'connectionFactory' defined in class path resource [com/epam/ta/reportportal/core/configs/rabbit/RabbitMqConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.amqp.rabbit.connection.ConnectionFactory]: Factory method 'connectionFactory' threw exception; nested exception is com.epam.ta.reportportal.exception.ReportPortalException: Unclassified Report Portal Error
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'rabbitHealthContributor' defined in class path resource [org/springframework/boot/actuate/autoconfigure/amqp/RabbitHealthContributorAutoConfiguration.class]: Unsatisfied dependency expressed through method 'rabbitHealthContributor' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'rabbitTemplate' defined in class path resource [com/epam/ta/reportportal/core/configs/rabbit/RabbitMqConfiguration.class]: Unsatisfied dependency expressed through method 'rabbitTemplate' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'connectionFactory' defined in class path resource [com/epam/ta/reportportal/core/configs/rabbit/RabbitMqConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.amqp.rabbit.connection.ConnectionFactory]: Factory method 'connectionFactory' threw exception; nested exception is com.epam.ta.reportportal.exception.ReportPortalException: Unclassified Report Portal Error
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'rabbitTemplate' defined in class path resource [com/epam/ta/reportportal/core/configs/rabbit/RabbitMqConfiguration.class]: Unsatisfied dependency expressed through method 'rabbitTemplate' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'connectionFactory' defined in class path resource [com/epam/ta/reportportal/core/configs/rabbit/RabbitMqConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.amqp.rabbit.connection.ConnectionFactory]: Factory method 'connectionFactory' threw exception; nested exception is com.epam.ta.reportportal.exception.ReportPortalException: Unclassified Report Portal Error
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'connectionFactory' defined in class path resource [com/epam/ta/reportportal/core/configs/rabbit/RabbitMqConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.amqp.rabbit.connection.ConnectionFactory]: Factory method 'connectionFactory' threw exception; nested exception is com.epam.ta.reportportal.exception.ReportPortalException: Unclassified Report Portal Error
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.amqp.rabbit.connection.ConnectionFactory]: Factory method 'connectionFactory' threw exception; nested exception is com.epam.ta.reportportal.exception.ReportPortalException: Unclassified Report Portal Error
Caused by: com.epam.ta.reportportal.exception.ReportPortalException: Unclassified Report Portal Error `

**report-portal-reportportal-jobs**
`Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'managementTemplate' defined in class path resource [com/epam/reportportal/config/rabbit/AnalyzerRabbitMqConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.epam.reportportal.analyzer.RabbitMqManagementClient]: Factory method 'managementTemplate' threw exception; nested exception is org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 Unauthorized: [{"error":"not_authorised","reason":"Login failed"}]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.epam.reportportal.analyzer.RabbitMqManagementClient]: Factory method 'managementTemplate' threw exception; nested exception is org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 Unauthorized: [{"error":"not_authorised","reason":"Login failed"}]
Caused by: org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 Unauthorized: [{"error":"not_authorised","reason":"Login failed"}] `
...

**Expected behavior**
- To spin up with no issues

**Screenshots**
![image](https://github.com/reportportal/reportportal/assets/34208988/2acaf5da-14cd-422a-8c0f-19dea413e895)

**Versions:**
 - Latest

**Comment by AlexandruCh** [comment]
mm, anyone?

**Comment by irynakozak2** [comment]
@AlexandruCh Hi! I want to kindly ask you to update your ReportPortal from the master branch (the latest officially released version), not from develop, and double-check the issue:
https://github.com/reportportal/kubernetes/tree/reportportal-5.10.0/reportportal

Waiting for your reply.

**Comment by AlexandruCh** [comment]
problem is still in place with the latest version 5.10.0

Issue on the reportportal-api


`//
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'connectionFactory' defined in class path resource [com/epam/ta/reportportal/core/configs/rabbit/RabbitMqConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.amqp.rabbit.connection.ConnectionFactory]: Factory method 'connectionFactory' threw exception; nested exception is com.epam.ta.reportportal.exception.ReportPortalException: Unclassified Report Portal Error         at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:656)         at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636)         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)         at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)         at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287)         at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)         at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885)         at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789)         ... 132 common frames omitted Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.amqp.rabbit.connection.ConnectionFactory]: Factory method 'connectionFactory' threw exception; nested exception is com.epam.ta.reportportal.exception.ReportPortalException: Unclassified Report Portal Error         at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)         at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651)         ... 146 common frames omitted Caused by: com.epam.ta.reportportal.exception.ReportPortalException: Unclassified Report Portal Error         at com.epam.ta.reportportal.core.configs.rabbit.RabbitMqConfiguration.connectionFactory(RabbitMqConfiguration.java:67)         at com.epam.ta.reportportal.core.configs.rabbit.RabbitMqConfiguration$$EnhancerBySpringCGLIB$$9e3a68dc.CGLIB$connectionFactory$4(<generated>)         at com.epam.ta.reportportal.core.configs.rabbit.RabbitMqConfiguration$$EnhancerBySpringCGLIB$$9e3a68dc$$FastClassBySpringCGLIB$$b4cf749b.invoke(<generated>)         at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)         at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)         at com.epam.ta.reportportal.core.configs.rabbit.RabbitMqConfiguration$$EnhancerBySpringCGLIB$$9e3a68dc.connectionFactory(<generated>)         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)         at java.base/java.lang.reflect.Method.invoke(Method.java:566)         at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)         ... 147 common frames omitted`

**Comment by MaryiaRymarchyk** [comment]
Hi @AlexandruCh check   rp.amqp.api-address  value, problem may be there.

**Comment by irynakozak2** [comment]
@AlexandruCh Hi! Did you have a chance to review the rp.amqp.api-address value?

**Comment by AlexandruCh** [comment]
@irynakozak2 sorry, very busy period but will give it a go following days, thank you

**Comment by irynakozak2** [comment]
@AlexandruCh Hi! Are there any updates from your side? Has the problem been resolved following the recommendations?

**Comment by irynakozak2** [comment]
@AlexandruCh Hi! Could you please confirm that the issue is still relevant to you?

**Comment by AlexandruCh** [comment]
@irynakozak2 - Hi, issue is no longer relevant to me, can be closed

**Comment by abdul-050** [comment]
@AlexandruCh @irynakozak2 
Can you guys can mention the resolution here, we are having the same issue while the deployment of reportportal using helm on EKS.
