### ISSUE TITLE
API service appears "Unhealthy" from time to time

### ISSUE THREAD

**Issue by petprojectdevelop** [reportportal/reportportal#2137]
**Describe the bug**
After some period of time Report Portal stops to load in browser.
No issues in browser's console, however - when doing analysis of ReportPortal components (containers that being launched after yaml file was executed) it can be seen that "service-api" container is being unhealthy.
When doing analysis of logs for corresponding container, seeing things like that:

Caused by: java.util.concurrent.TimeoutException: null
	at com.rabbitmq.utility.BlockingCell.get(BlockingCell.java:77)
	at com.rabbitmq.utility.BlockingCell.uninterruptibleGet(BlockingCell.java:120)
	
Caused by: com.rabbitmq.client.ChannelContinuationTimeoutException: Continuation call for method #method<channel.open>(out-of-band=) on channel AMQChannel(amqp://rabbitmq@192.168.16.2:5672/analyzer,17) (#17) timed out

WARN 1 --- [o-8585-exec-106] o.s.b.a.amqp.RabbitHealthIndicator       : Rabbit health check failed

Things are being re-appear continuously.

As per last issue from API service, we've also tried to analyze what's going on inside RabbitMQ container and this is what can be seen:
[warning] <0.4951.0> closing AMQP connection <0.4951.0> (192.168.16.9:38054 -> 192.168.16.2:5672, vhost: 'analyzer', user: 'rabbitmq'):
[warning] <0.4951.0> client unexpectedly closed TCP connection

Rest of service remain healthy.

**Screenshots**
No screenshots can be attached in this particular case.

**Versions:**
 - Linux, Chrome.
API Service: 5.9.2;Index Service: 5.8.0;Jobs Service: 5.8.2;Authorization Service: 5.8.2;Service UI: 5.9.0;

**Comment by evgeny-grushko** [comment]
2023-09-27 10:47:02.099 ERROR 1 --- [-listener-exec2] c.e.t.r.c.a.auto.impl.LogIndexerService  : com.rabbitmq.client.ChannelContinuationTimeoutException: Continuation call for method #method<queue.declare>(ticket=0, queue=amq.rabbitmq.reply-to, passive=true, durable=false, exclusive=true, auto-delete=true, nowait=false, arguments=null) on channel AMQChannel(amqp://rabbitmq@192.168.64.2:5672/analyzer,1) (#1) timed out

org.springframework.amqp.AmqpIOException: com.rabbitmq.client.ChannelContinuationTimeoutException: Continuation call for method #method<queue.declare>(ticket=0, queue=amq.rabbitmq.reply-to, passive=true, durable=false, exclusive=true, auto-delete=true, nowait=false, arguments=null) on channel AMQChannel(amqp://rabbitmq@192.168.64.2:5672/analyzer,1) (#1) timed out
	at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:70)
	at org.springframework.amqp.rabbit.connection.RabbitAccessor.convertRabbitAccessException(RabbitAccessor.java:113)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:2202)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:2148)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:2128)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.useDirectReplyTo(RabbitTemplate.java:1018)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.evaluateFastReplyTo(RabbitTemplate.java:990)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.doSendAndReceive(RabbitTemplate.java:1844)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.convertSendAndReceiveRaw(RabbitTemplate.java:1818)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.convertSendAndReceiveAsType(RabbitTemplate.java:1788)
	at org.springframework.amqp.rabbit.core.RabbitOperations.convertSendAndReceiveAsType(RabbitOperations.java:371)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.convertSendAndReceiveAsType(RabbitTemplate.java:1730)
	at com.epam.ta.reportportal.core.analyzer.auto.client.impl.IndexerServiceClientImpl.lambda$index$0(IndexerServiceClientImpl.java:72)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.LongPipeline.reduce(LongPipeline.java:474)
	at java.base/java.util.stream.LongPipeline.sum(LongPipeline.java:432)
	at com.epam.ta.reportportal.core.analyzer.auto.client.impl.IndexerServiceClientImpl.index(IndexerServiceClientImpl.java:83)
	at com.epam.ta.reportportal.core.analyzer.auto.indexer.BatchLogIndexer.lambda$indexPartition$1(BatchLogIndexer.java:83)
	at java.base/java.util.Optional.map(Optional.java:265)
	at com.epam.ta.reportportal.core.analyzer.auto.indexer.BatchLogIndexer.indexPartition(BatchLogIndexer.java:83)
	at com.epam.ta.reportportal.core.analyzer.auto.indexer.BatchLogIndexer.lambda$index$0(BatchLogIndexer.java:76)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.epam.ta.reportportal.core.analyzer.auto.indexer.BatchLogIndexer.index(BatchLogIndexer.java:76)
	at com.epam.ta.reportportal.core.analyzer.auto.indexer.BatchLogIndexer$$FastClassBySpringCGLIB$$fc22a037.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at com.epam.ta.reportportal.core.analyzer.auto.indexer.BatchLogIndexer$$EnhancerBySpringCGLIB$$c79c4b5f.index(<generated>)
	at com.epam.ta.reportportal.core.analyzer.auto.impl.LogIndexerService.indexLaunchLogs(LogIndexerService.java:106)
	at com.epam.ta.reportportal.core.analyzer.auto.impl.LogIndexerService$$FastClassBySpringCGLIB$$f53c9b3b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at com.epam.ta.reportportal.core.analyzer.auto.impl.LogIndexerService$$EnhancerBySpringCGLIB$$77ed3eeb.indexLaunchLogs(<generated>)
	at com.epam.ta.reportportal.core.analyzer.auto.starter.decorator.IndexingAutoAnalysisStarter.start(IndexingAutoAnalysisStarter.java:46)
	at com.epam.ta.reportportal.core.analyzer.auto.starter.decorator.IndexingAutoAnalysisStarter$$FastClassBySpringCGLIB$$6c5f0b93.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at com.epam.ta.reportportal.core.analyzer.auto.starter.decorator.IndexingAutoAnalysisStarter$$EnhancerBySpringCGLIB$$2bd186f3.start(<generated>)
	at com.epam.ta.reportportal.core.analyzer.auto.starter.decorator.ExistingAnalyzerStarter.start(ExistingAnalyzerStarter.java:46)
	at com.epam.ta.reportportal.core.events.handler.launch.LaunchAutoAnalysisRunner.handle(LaunchAutoAnalysisRunner.java:51)
	at com.epam.ta.reportportal.core.events.handler.launch.LaunchAutoAnalysisRunner.handle(LaunchAutoAnalysisRunner.java:34)
	at com.epam.ta.reportportal.core.events.subscriber.impl.delegate.ProjectConfigDelegatingSubscriber.lambda$handleEvent$0(ProjectConfigDelegatingSubscriber.java:44)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.epam.ta.reportportal.core.events.subscriber.impl.delegate.ProjectConfigDelegatingSubscriber.handleEvent(ProjectConfigDelegatingSubscriber.java:44)
	at com.epam.ta.reportportal.core.events.subscriber.impl.delegate.ProjectConfigDelegatingSubscriber.handleEvent(ProjectConfigDelegatingSubscriber.java:30)
	at com.epam.ta.reportportal.core.events.listener.LaunchFinishedEventListener.lambda$onApplicationEvent$0(LaunchFinishedEventListener.java:45)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.epam.ta.reportportal.core.events.listener.LaunchFinishedEventListener.onApplicationEvent(LaunchFinishedEventListener.java:45)
	at com.epam.ta.reportportal.core.events.listener.LaunchFinishedEventListener$$FastClassBySpringCGLIB$$81f8adcc.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.rabbitmq.client.ChannelContinuationTimeoutException: Continuation call for method #method<queue.declare>(ticket=0, queue=amq.rabbitmq.reply-to, passive=true, durable=false, exclusive=true, auto-delete=true, nowait=false, arguments=null) on channel AMQChannel(amqp://rabbitmq@192.168.64.2:5672/analyzer,1) (#1) timed out
	at com.rabbitmq.client.impl.AMQChannel.wrapTimeoutException(AMQChannel.java:313)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:295)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:141)
	at com.rabbitmq.client.impl.ChannelN.queueDeclarePassive(ChannelN.java:1012)
	at com.rabbitmq.client.impl.ChannelN.queueDeclarePassive(ChannelN.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(CachingConnectionFactory.java:1157)
	at com.sun.proxy.$Proxy305.queueDeclarePassive(Unknown Source)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.lambda$useDirectReplyTo$2(RabbitTemplate.java:1019)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.invokeAction(RabbitTemplate.java:2237)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:2196)
	... 84 common frames omitted
Caused by: java.util.concurrent.TimeoutException: null
	at com.rabbitmq.utility.BlockingCell.get(BlockingCell.java:77)
	at com.rabbitmq.utility.BlockingCell.uninterruptibleGet(BlockingCell.java:120)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:502)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:293)
	... 96 common frames omitted

2023-09-27 10:47:02.102 ERROR 1 --- [-listener-exec2] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method: public void com.epam.ta.reportportal.core.events.listener.LaunchFinishedEventListener.onApplicationEvent(com.epam.ta.reportportal.core.events.activity.LaunchFinishedEvent)

com.epam.ta.reportportal.exception.ReportPortalException: com.rabbitmq.client.ChannelContinuationTimeoutException: Continuation call for method #method<queue.declare>(ticket=0, queue=amq.rabbitmq.reply-to, passive=true, durable=false, exclusive=true, auto-delete=true, nowait=false, arguments=null) on channel AMQChannel(amqp://rabbitmq@192.168.64.2:5672/analyzer,1) (#1) timed out
	at com.epam.ta.reportportal.core.analyzer.auto.impl.LogIndexerService.indexLaunchLogs(LogIndexerService.java:109)
	at com.epam.ta.reportportal.core.analyzer.auto.impl.LogIndexerService$$FastClassBySpringCGLIB$$f53c9b3b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at com.epam.ta.reportportal.core.analyzer.auto.impl.LogIndexerService$$EnhancerBySpringCGLIB$$77ed3eeb.indexLaunchLogs(<generated>)
	at com.epam.ta.reportportal.core.analyzer.auto.starter.decorator.IndexingAutoAnalysisStarter.start(IndexingAutoAnalysisStarter.java:46)
	at com.epam.ta.reportportal.core.analyzer.auto.starter.decorator.IndexingAutoAnalysisStarter$$FastClassBySpringCGLIB$$6c5f0b93.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at com.epam.ta.reportportal.core.analyzer.auto.starter.decorator.IndexingAutoAnalysisStarter$$EnhancerBySpringCGLIB$$2bd186f3.start(<generated>)
	at com.epam.ta.reportportal.core.analyzer.auto.starter.decorator.ExistingAnalyzerStarter.start(ExistingAnalyzerStarter.java:46)
	at com.epam.ta.reportportal.core.events.handler.launch.LaunchAutoAnalysisRunner.handle(LaunchAutoAnalysisRunner.java:51)
	at com.epam.ta.reportportal.core.events.handler.launch.LaunchAutoAnalysisRunner.handle(LaunchAutoAnalysisRunner.java:34)
	at com.epam.ta.reportportal.core.events.subscriber.impl.delegate.ProjectConfigDelegatingSubscriber.lambda$handleEvent$0(ProjectConfigDelegatingSubscriber.java:44)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.epam.ta.reportportal.core.events.subscriber.impl.delegate.ProjectConfigDelegatingSubscriber.handleEvent(ProjectConfigDelegatingSubscriber.java:44)
	at com.epam.ta.reportportal.core.events.subscriber.impl.delegate.ProjectConfigDelegatingSubscriber.handleEvent(ProjectConfigDelegatingSubscriber.java:30)
	at com.epam.ta.reportportal.core.events.listener.LaunchFinishedEventListener.lambda$onApplicationEvent$0(LaunchFinishedEventListener.java:45)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.epam.ta.reportportal.core.events.listener.LaunchFinishedEventListener.onApplicationEvent(LaunchFinishedEventListener.java:45)
	at com.epam.ta.reportportal.core.events.listener.LaunchFinishedEventListener$$FastClassBySpringCGLIB$$81f8adcc.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by evgeny-grushko** [comment]
![image](https://github.com/reportportal/reportportal/assets/14168961/609a4b41-da78-46ea-843a-66c29b0946bb)

**Comment by petprojectdevelop** [comment]
Closed since issue is not valid.
It was detected and found out that issue is on host side.

**Comment by godseaishwarya** [comment]
@petprojectdevelop : Hey we are facing the same issue, any steps that we should follow to resolve this?
