### ISSUE TITLE
Auto-Analysis not marking defects on some projects

### ISSUE THREAD

**Issue by dstewart25** [reportportal/reportportal#2154]
I have 3 projects created in ReportPortal. 1 of those is working with the auto-analysis, however, 2 of the projects seem to run auto-analysis after a test run but they do not get defects marked as determined from previous test runs. I have tried generating a new index in both projects multiple times to no avail. After looking through the logs of different ReportPortal pods running in k8s. I have found these two errors that seem to pop up pretty regularly:

In `reportportal-analyzer-train-0`:
```
2023-10-09 13:44:24,241 - analyzerApp.trainingDefectTypeModel - ERROR - The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.
```
```
2023-10-09 13:44:25,544 - analyzerApp.minioClient - DEBUG - Saved into bucket 'prj-3' with name 'defect_type_trigger_info': {'gathered_metric_total': 228, 'gathered_metric_since_training': 0}
2023-10-09 13:44:25,544 - analyzerApp.retrainingService - DEBUG - {'ab': {'method': 'training', 'sub_model_type': 'ab', 'model_type': 'defect_type', 'baseline_model': ['global_defect_type_model_12.03.23'], 'new_model': ['defect_type_model_09.10.23'], 'project_id': '3', 'model_saved': 0, 'p_value': 0.20262989151119273, 'data_proportion': 0.0, 'baseline_mean_metric': 0.10666666666666666, 'new_model_mean_metric': 0.3, 'bad_data_proportion': 0, 'metric_name': 'F1', 'errors': [], 'errors_count': 0, 'time_spent': 11.754669666290283, 'data_size': 20, 'gather_date': '2023-10-09 13:44:25', 'module_version': ['5.7.5-RC-13']}, 'pb': {'method': 'training', 'sub_model_type': 'pb', 'model_type': 'defect_type', 'baseline_model': ['global_defect_type_model_12.03.23'], 'new_model': ['defect_type_model_09.10.23'], 'project_id': '3', 'model_saved': 1, 'p_value': 0.0006324312696901084, 'data_proportion': 0.469, 'baseline_mean_metric': 0.0, 'new_model_mean_metric': 0.42333333333333334, 'bad_data_proportion': 0, 'metric_name': 'F1', 'errors': [], 'errors_count': 0, 'time_spent': 13.162737607955933, 'data_size': 146, 'gather_date': '2023-10-09 13:44:25', 'module_version': ['5.7.5-RC-13']}, 'si': {'method': 'training', 'sub_model_type': 'si', 'model_type': 'defect_type', 'baseline_model': ['global_defect_type_model_12.03.23'], 'new_model': ['defect_type_model_09.10.23'], 'project_id': '3', 'model_saved': 0, 'p_value': 0.3175685177798147, 'data_proportion': 0.0, 'baseline_mean_metric': 0.3466666666666666, 'new_model_mean_metric': 0.4904761904761904, 'bad_data_proportion': 0, 'metric_name': 'F1', 'errors': [], 'errors_count': 0, 'time_spent': 12.496672868728638, 'data_size': 62, 'gather_date': '2023-10-09 13:44:25', 'module_version': ['5.7.5-RC-13']}, 'ab_1jelhfnw7qvl0': {'method': 'training', 'sub_model_type': 'ab_1jelhfnw7qvl0', 'model_type': 'defect_type', 'baseline_model': ['global_defect_type_model_12.03.23'], 'new_model': ['defect_type_model_09.10.23'], 'project_id': '3', 'model_saved': 0, 'p_value': 1.0, 'data_proportion': 0.0, 'baseline_mean_metric': 0.0, 'new_model_mean_metric': 0.0, 'bad_data_proportion': 1, 'metric_name': 'F1', 'errors': [], 'errors_count': 0, 'time_spent': 0.0700526237487793, 'data_size': 3, 'gather_date': '2023-10-09 13:44:25', 'module_version': ['5.7.5-RC-13']}, 'ab_qxw3re18p5bm': {'method': 'training', 'sub_model_type': 'ab_qxw3re18p5bm', 'model_type': 'defect_type', 'baseline_model': ['global_defect_type_model_12.03.23'], 'new_model': ['defect_type_model_09.10.23'], 'project_id': '3', 'model_saved': 0, 'p_value': 0.0, 'data_proportion': 0.0, 'baseline_mean_metric': 0.0010000000000000002, 'new_model_mean_metric': 0.0, 'bad_data_proportion': 0, 'metric_name': 'F1', 'errors': [], 'errors_count': 0, 'time_spent': 7.606382608413696, 'data_size': 8, 'gather_date': '2023-10-09 13:44:25', 'module_version': ['5.7.5-RC-13']}, 'si_tnzj94efa9m8': {'method': 'training', 'sub_model_type': 'si_tnzj94efa9m8', 'model_type': 'defect_type', 'baseline_model': ['global_defect_type_model_12.03.23'], 'new_model': ['defect_type_model_09.10.23'], 'project_id': '3', 'model_saved': 0, 'p_value': 0.08101585200212401, 'data_proportion': 0.0, 'baseline_mean_metric': 0.0010000000000000002, 'new_model_mean_metric': 0.21666666666666665, 'bad_data_proportion': 0, 'metric_name': 'F1', 'errors': [], 'errors_count': 0, 'time_spent': 8.017140626907349, 'data_size': 20, 'gather_date': '2023-10-09 13:44:25', 'module_version': ['5.7.5-RC-13']}, 'si_t81tljj2g6ec': {'method': 'training', 'sub_model_type': 'si_t81tljj2g6ec', 'model_type': 'defect_type', 'baseline_model': ['global_defect_type_model_12.03.23'], 'new_model': ['defect_type_model_09.10.23'], 'project_id': '3', 'model_saved': 0, 'p_value': 1.0, 'data_proportion': 0.0, 'baseline_mean_metric': 0.0, 'new_model_mean_metric': 0.0, 'bad_data_proportion': 0, 'metric_name': 'F1', 'errors': ['ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.\n'], 'errors_count': 1, 'time_spent': 0.010916948318481445, 'data_size': 1, 'gather_date': '2023-10-09 13:44:25', 'module_version': ['5.7.5-RC-13']}, 'si_toohzrj7ld2d': {'method': 'training', 'sub_model_type': 'si_toohzrj7ld2d', 'model_type': 'defect_type', 'baseline_model': ['global_defect_type_model_12.03.23'], 'new_model': ['defect_type_model_09.10.23'], 'project_id': '3', 'model_saved': 0, 'p_value': 1.0, 'data_proportion': 0.0, 'baseline_mean_metric': 0.0, 'new_model_mean_metric': 0.0, 'bad_data_proportion': 1, 'metric_name': 'F1', 'errors': [], 'errors_count': 0, 'time_spent': 0.11278200149536133, 'data_size': 1, 'gather_date': '2023-10-09 13:44:25', 'module_version': ['5.7.5-RC-13']}, 'all': {'method': 'training', 'sub_model_type': 'all', 'model_type': 'defect_type', 'baseline_model': ['global_defect_type_model_12.03.23'], 'new_model': ['defect_type_model_09.10.23'], 'project_id': '3', 'model_saved': 1, 'p_value': 0.0006324312696901084, 'data_proportion': 0.469, 'baseline_mean_metric': 0.09106666666666666, 'new_model_mean_metric': 0.17573333333333335, 'bad_data_proportion': 0, 'metric_name': 'F1', 'errors': ['ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.\n'], 'errors_count': 1, 'time_spent': 54.367751359939575, 'data_size': 228, 'gather_date': '2023-10-09 13:44:25', 'module_version': ['5.7.5-RC-13']}}
```

In `reportportal-api-74cd659b8d-tbhvl`:
```
java.lang.NullPointerException: null
        at com.epam.ta.reportportal.core.analyzer.auto.impl.SuggestItemService.getSuggestedItems(SuggestItemService.java:153)
        at com.epam.ta.reportportal.core.analyzer.auto.impl.SuggestItemService.suggestItems(SuggestItemService.java:98)
        at com.epam.ta.reportportal.core.analyzer.auto.impl.SuggestItemService$$FastClassBySpringCGLIB$$2b73cffd.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
        at com.epam.ta.reportportal.core.analyzer.auto.impl.SuggestItemService$$EnhancerBySpringCGLIB$$ef36c571.suggestItems(<generated>)
        at com.epam.ta.reportportal.ws.controller.TestItemController.getSuggestedItems(TestItemController.java:168)
        at com.epam.ta.reportportal.ws.controller.TestItemController$$FastClassBySpringCGLIB$$b0260678.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:61)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
        at com.epam.ta.reportportal.ws.controller.TestItemController$$EnhancerBySpringCGLIB$$96a7fc76.getSuggestedItems(<generated>)
        at jdk.internal.reflect.GeneratedMethodAccessor555.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:670)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.multipart.support.MultipartFilter.doFilterInternal(MultipartFilter.java:125)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:121)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:182)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Any help with this will be greatly appreciated.

**Comment by HardNorth** [comment]
@dstewart25 Looks like you have too few defect classes in these projects, E.G only product bugs. Could you try assigning different defect types, and try again?

**Comment by HardNorth** [comment]
@dstewart25 Most likely you don't have enough resources for the analyzer to work. What is machine/resource limit you give for Analyzer and Elastic Search instnces?

**Comment by MaryiaRymarchyk** [comment]
@irynakozak2 please you review the values above and comment.

**Comment by irynakozak2** [comment]
@dstewart25 Hi! Sorry for reaching out after some time. Could you please check if this issue is still reproducible in the latest live release?
