### ISSUE TITLE
ReportPortal execution error - retrofit2.adapter.rxjava2.HttpException: HTTP 403 Forbidden

### ISSUE THREAD

**Issue by gokulsukumar** [reportportal/reportportal#2173]
Hi,  I am using reportPortal version API Service: 5.10.1;Index Service: 5.10.0;Jobs Service: 5.10.0;Authorization Service: 5.10.0;Service UI: 5.10.0.

While trying to run my tests I receive a HTTP 403 forbidden error. 

`14:57:11.108 ERROR c.e.r.s.Launch - rp-io-2 - [27] ReportPortal execution error
retrofit2.adapter.rxjava2.HttpException: HTTP 403 Forbidden
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
14:57:11.119 ERROR c.e.r.s.Launch - rp-io-2 - [27] ReportPortal execution error
retrofit2.adapter.rxjava2.HttpException: HTTP 403 Forbidden
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

I have already verified the API key set in the reportportal.properties file.
I am using MacOS Ventura and no firewall is enabled.

Please could you let me know what is wrong in my configuration?

**Comment by babantax** [comment]
I had some similar issue related to self-signed certificates.
Problem was that:
- I had self-signed ssl certs (signed by my company)
- Some Java libraries do not recognize the certs

Final solution was install other kind of certs.

Not sure if is your case

**Comment by alena-babrova** [comment]
Hello @gokulsukumar,

Could you tell me please if the issue is still relevant?

**Comment by alena-babrova** [comment]
Dear @gokulsukumar,

As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.
