### ISSUE TITLE
Can't login to reportportal using LDAPS after upgrade to UAT 5.8.2

### ISSUE THREAD

**Issue by heilwood** [reportportal/reportportal#2183]
After upgrade to latest version can't login to reportportal using LDAPS.

We are adding certificate to our UAT service with custom script using keytool (command added to docker compose file).

This issue appears in 5.8.2 and 5.10.0,  version 5.7.4 working fine without problems. 

We are getting next exception in authorization containers when we trying to login:

`org.jasypt.exceptions.EncryptionOperationNotPossibleException: null 
        at org.jasypt.encryption.pbe.StandardPBEByteEncryptor.decrypt(StandardPBEByteEncryptor.java:1169) ~[jasypt-1.9.3.jar!/:na] 
        at org.jasypt.encryption.pbe.StandardPBEStringEncryptor.decrypt(StandardPBEStringEncryptor.java:738) ~[jasypt-1.9.3.jar!/:na] 
        at org.jasypt.util.text.BasicTextEncryptor.decrypt(BasicTextEncryptor.java:112) ~[jasypt-1.9.3.jar!/:na] 
        at com.epam.reportportal.auth.integration.ldap.LdapAuthProvider.lambda$getDelegate$1(LdapAuthProvider.java:72) ~[classes!/:na] 
        at java.base/java.util.Optional.ifPresent(Optional.java:183) ~[na:na] 
        at com.epam.reportportal.auth.integration.ldap.LdapAuthProvider.getDelegate(LdapAuthProvider.java:72) ~[classes!/:na] 
        at com.epam.reportportal.auth.EnableableAuthProvider.supports(EnableableAuthProvider.java:59) ~[classes!/:na] 
        at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:174) ~[spring-security-core-5.5.8.jar!/:5.5.8] 
        at org.springframework.security.oauth2.provider.password.ResourceOwnerPasswordTokenGranter.getOAuth2Authentication(ResourceOwnerPasswordTokenGranter.java:76) ~[spring-security-oauth2-2.5.2.RELEASE.jar!/:na] 
        at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.getAccessToken(AbstractTokenGranter.java:76) ~[spring-security-oauth2-2.5.2.RELEASE.jar!/:na] 
        at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.grant(AbstractTokenGranter.java:71) ~[spring-security-oauth2-2.5.2.RELEASE.jar!/:na] 
        at org.springframework.security.oauth2.provider.CompositeTokenGranter.grant(CompositeTokenGranter.java:42) ~[spring-security-oauth2-2.5.2.RELEASE.jar!/:na] 
        at org.springframework.security.oauth2.config.annotation.web.configurers.AuthorizationServerEndpointsConfigurer$4.grant(AuthorizationServerEndpointsConfigurer.java:587) ~[spring-security-oauth2-2.5.2.RELEASE.jar!/:na] 
        at org.springframework.security.oauth2.provider.endpoint.TokenEndpoint.postAccessToken(TokenEndpoint.java:137) ~[spring-security-oauth2-2.5.2.RELEASE.jar!/:na] 
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na] 
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na] 
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na] 
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na] 
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.20.jar!/:5.3.20] 
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.20.jar!/:5.3.20] 
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.20.jar!/:5.3.20] 
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.20.jar!/:5.3.20] 
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.20.jar!/:5.3.20] 
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.20.jar!/:5.3.20] 
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) ~[spring-webmvc-5.3.20.jar!/:5.3.20] 
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.20.jar!/:5.3.20] 
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.20.jar!/:5.3.20] 
        at`

**Expected behavior**
Should login with LDAPS credentials

**Versions:**
 - Ubuntu, Any
 - 23.2

**Comment by heilwood** [comment]
fixed by adjusting keytool command
