### ISSUE TITLE
service-api logs kill log collector

### ISSUE THREAD

**Issue by cirrusnative** [reportportal/reportportal#2238]
Hello Team, 👋 
I have installed Report portal from helmchart (5.10.0), using AWS rabbitmq (3.11.20) and AWS RDS(12.18).
I have taken a db backup from previous instance which was running on docker-compose (same version of app) and restored it in the k8s env.
The portal seems to work fine but the service-api throws an excessive amount of logs and errors. 😿 

I checked existing issues, but could not find anything with similar exception.
The logs are produced at volumes of millions per day, which is causing issues with my log collector. 💣 
Thank you for your help in advance. 

`
2024-02-29 10:52:26.985 ERROR 1 --- [a.Spring.bean-2] c.e.t.r.w.rabbit.AsyncReportingListener  : exception : java.lang.NullPointerException, message : null,  cause :
2024-02-29 10:52:26.985  WARN 1 --- [a.Spring.bean-2] s.a.r.l.ConditionalRejectingErrorHandler : Execution of Rabbit message listener failed.

org.springframework.amqp.rabbit.support.ListenerExecutionFailedException: Listener threw exception
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.wrapToListenerExecutionFailedExceptionIfNeeded(AbstractMessageListenerContainer.java:1778)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1724)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1594)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1571)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1562)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1506)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:967)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:914)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:83)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1291)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1197)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.springframework.amqp.AmqpRejectAndDontRequeueException: null
	at com.epam.ta.reportportal.ws.rabbit.AsyncReportingListener.onMessage(AsyncReportingListener.java:186)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1720)
	... 10 common frames omitted
Caused by: java.lang.NullPointerException: null
`

**Comment by Pink-Bumblebee** [comment]
@cirrusnative , please read last comments in this thread: https://github.com/reportportal/service-api/issues/1404. I hope it will be helpful.

**Comment by cirrusnative** [comment]
I updated service-api image to 5.10.1 and it cleaned some logs. However now I still have lot of messages as below. Do you know what is causing these messages?
I would prefer to fix it than just suppress the logs.

`2024-03-01 06:43:47.559 ERROR 1 --- [a.Spring.bean-5] c.e.t.r.w.rabbit.AsyncReportingListener  : Dropping on maximum retry limit request of type = LOG, for target id = e006a4ff-5561-403d-bb98-202a96275ff62024-03-01 06:43:47.559 ERROR 1 --- [a.Spring.bean-5] c.e.t.r.w.rabbit.AsyncReportingListener  : Dropping on maximum retry limit request of type = LOG, for target id = 6166fd89-24a1-4860-a336-d4fabba948c42024-03-01 06:43:47.559 ERROR 1 --- [a.Spring.bean-5] c.e.t.r.w.rabbit.AsyncReportingListener  : Dropping on maximum retry limit request of type = LOG, for target id = f1f671c3-7ed3-4fe1-965d-fe93cdef4d212024-03-01 06:43:47.572 ERROR 1 --- [a.Spring.bean-5] c.e.t.r.w.rabbit.AsyncReportingListener  : Dropping on maximum retry limit request of type = LOG, for target id = 8fd38dd4-16bc-49b6-94aa-94b4c81a0a302`

**Comment by cirrusnative** [comment]
When the errors persisted, it was also feeling up rabbit queue and as well adding 20 GB to database daily. After updating of service-api image from 5.10.0 to 5.10.1 error logs stopped and also rabbit queue and RDS database stopped growing at such fast rate. Now database barely grows by some MBs daily.
Can you suggest what should I clean from the database after such bug?

**Comment by Pink-Bumblebee** [comment]
Not sure whether it is possible in few clicks. Only manual cleaning in database, sorry.
