### ISSUE TITLE
[API][MINIO] IllegalArgumentException: Empty key

### ISSUE THREAD

**Issue by shaburov** [reportportal/reportportal#2248]
image: reportportal/service-api:5.11.0

![image](https://github.com/reportportal/reportportal/assets/15269131/43979d67-bb1b-4a7d-b672-2710bb9fd317)

[Code link](https://github.com/reportportal/commons-dao/blob/b2c73acfdbd0dd07bcd5f790f1e1bb61eeaa7dc3/src/main/java/com/epam/ta/reportportal/config/DataStoreConfiguration.java#L175) to problem `@Bean`

```
Caused by: java.lang.IllegalArgumentException: Empty key
        at java.base/javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:107)
        at org.jclouds.encryption.internal.JCECrypto.hmac(JCECrypto.java:73)
        at org.jclouds.encryption.internal.JCECrypto.hmacSHA1(JCECrypto.java:90)
        at org.jclouds.s3.filters.RequestAuthorizeSignatureV2.sign(RequestAuthorizeSignatureV2.java:181)
        at org.jclouds.s3.filters.RequestAuthorizeSignatureV2.calculateSignature(RequestAuthorizeSignatureV2.java:171)
        at org.jclouds.s3.filters.RequestAuthorizeSignatureV2.filter(RequestAuthorizeSignatureV2.java:125)
        at org.jclouds.http.internal.BaseHttpCommandExecutorService.invoke(BaseHttpCommandExecutorService.java:90)
        at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:91)
        at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:74)
        at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:45)
        at org.jclouds.rest.internal.DelegatesToInvocationFunction.handle(DelegatesToInvocationFunction.java:156)
        at org.jclouds.rest.internal.DelegatesToInvocationFunction.invoke(DelegatesToInvocationFunction.java:123)
        at jdk.proxy2/jdk.proxy2.$Proxy228.objectExists(Unknown Source)
        at org.jclouds.s3.blobstore.S3BlobStore.blobExists(S3BlobStore.java:208)
        at com.epam.ta.reportportal.filesystem.distributed.s3.S3DataStore.exists(S3DataStore.java:132)
        at com.epam.ta.reportportal.config.EncryptConfiguration.loadOrGenerateEncryptorPassword(EncryptConfiguration.java:127)
        at com.epam.ta.reportportal.config.EncryptConfiguration.afterPropertiesSet(EncryptConfiguration.java:110)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
        ... 45 common frames omitted

```

**Comment by Pink-Bumblebee** [comment]
@shaburov , actually in latest release 24.1 we decided to deprecate minio.
In release v23.1 we provided 3 different options for storing data: https://reportportal.io/docs/installation-steps/ReportPortal23.1FileStorageOptions

**Comment by shaburov** [comment]
@Pink-Bumblebee But what about those teams that use an internal deployed minio in the company?
