### ISSUE TITLE
Java Outof memory exception when uploading log file to reportportal

### ISSUE THREAD

**Issue by badrinrs** [reportportal/reportportal#2251]
**Describe the bug**
When uploading a file to reportportal I am on some mobile devices getting an out of memory exception.

**Stacktrace**
`java.lang.OutOfMemoryError: Failed to allocate a 140497984 byte allocation with 25165824 free bytes and 86MB until OOM, target footprint 470957488, growth limit 536870912
        at java.util.Arrays.copyOf(Arrays.java:3161)
        at com.google.common.io.ByteStreams.combineBuffers(ByteStreams.java:218)
        at com.google.common.io.ByteStreams.toByteArrayInternal(ByteStreams.java:193)
        at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:238)
        at com.google.common.io.ByteSource.read(ByteSource.java:300)
        at com.epam.reportportal.logback.appender.ReportPortalAppender.lambda$append$0$com-epam-reportportal-logback-appender-ReportPortalAppender(ReportPortalAppender.java:68)
        at com.epam.reportportal.logback.appender.ReportPortalAppender$$ExternalSyntheticLambda0.apply(Unknown Source:6)
        at com.epam.reportportal.service.LoggingContext.prepareRequest(LoggingContext.java:215)
        at com.epam.reportportal.service.LoggingContext.lambda$emit$2$com-epam-reportportal-service-LoggingContext(LoggingContext.java:232)
        at com.epam.reportportal.service.LoggingContext$$ExternalSyntheticLambda0.apply(Unknown Source:8)
        at io.reactivex.internal.functions.Functions$Array2Func.apply(Functions.java:529)
        at io.reactivex.internal.functions.Functions$Array2Func.apply(Functions.java:516)
        at io.reactivex.internal.operators.maybe.MaybeZipArray$ZipCoordinator.innerSuccess(MaybeZipArray.java:111)
        at io.reactivex.internal.operators.maybe.MaybeZipArray$ZipMaybeObserver.onSuccess(MaybeZipArray.java:176)
        at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:66)
        at io.reactivex.Maybe.subscribe(Maybe.java:4290)
        at io.reactivex.internal.operators.maybe.MaybeZipArray.subscribeActual(MaybeZipArray.java:62)
        at io.reactivex.Maybe.subscribe(Maybe.java:4290)
        at io.reactivex.internal.operators.maybe.MaybeToFlowable.subscribeActual(MaybeToFlowable.java:45)
        at io.reactivex.Flowable.subscribe(Flowable.java:14935)
        at io.reactivex.Flowable.subscribe(Flowable.java:14882)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
        at io.reactivex.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.onNext(FlowableFromObservable.java:54)
        at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:308)
        at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:228)
        at com.epam.reportportal.service.LoggingContext.emit(LoggingContext.java:232)
        at com.epam.reportportal.service.ReportPortal.emitLog(ReportPortal.java:216)
        at com.epam.reportportal.logback.appender.ReportPortalAppender.append(ReportPortalAppender.java:53)
        at com.epam.reportportal.logback.appender.ReportPortalAppender.append(ReportPortalAppender.java:37)
        at ch.qos.logback.core.AppenderBase.doAppend(AppenderBase.java:82)
        at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
        at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
        at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
        at ch.qos.logback.classic.Logger.filterAndLog_2(Logger.java:414)
        at ch.qos.logback.classic.Logger.debug(Logger.java:490)`

**Versions:**
 - Android OS - 10
 - Current version of RP:API Service: 5.10.0;Index Service: 5.10.0;Jobs Service: 5.10.0;Authorization Service: 5.10.0;Service UI: 5.10.0;

**Comment by Pink-Bumblebee** [comment]
@badrinrs , not sure whether it will help, but RP-team released fixed version of api-service : 5.10.1. It is important fix, please update your instance.

**Comment by badrinrs** [comment]
I updated the reportportal instance to the latest 24.1 version but am still facing the issue.
![Screenshot 2024-03-26 at 12 23 56 PM](https://github.com/reportportal/reportportal/assets/6345184/08dd80a6-1070-4a56-97a7-a654465de0a4)

**Comment by Pink-Bumblebee** [comment]
@badrinrs,  could you please share sample log file with us? Also sometimes people are uploading log files to demo.reportportal.io and checking results.
By the way, you said that only some devices meets this problem. How about other devices? What is the difference between them?

**Comment by badrinrs** [comment]
We run tests on a range of android devices. These have os versions from Android 8 to the latest one. The newer devices work fine, but on older devices from android 8, 9, 10 we this issue.

**Comment by Pink-Bumblebee** [comment]
I think, that this is not related to ReportPortal. Please try to find solution for java.lang.OutOfMemoryError and how to avoid it in another sources.
