### ISSUE TITLE
Missing items in "Similar launches" secrtion in UI after uprgade to 24.1.0

### ISSUE THREAD

**Issue by ifurs** [reportportal/reportportal#2255]
**Describe the bug**
After upgrade from chart 5.10.0 to  24.1.0 I got issue, that in UI missing Items `Similar "case type"` even in "Similar to 10 launches & current launch" but analyzer works and return sugesstions.

I've checked firstly analyzer logs, and it doesn't have any exceptions, then I've cheked  service jobs pod logs, and found interesting error:
```java
# started job
2024-04-08 06:57:22.625  INFO 1 --- [           main] c.e.reportportal.ServiceJobApplication   : Starting ServiceJobApplication using Java 21.0.1 on reportportal-jobs-57485jdws-cmdfklti with PID 1 (/usr/app/service-jobs-5.11.0-exec.jar started by root in /usr/app)
# ...
# error
2024-04-08 07:03:23.189 ERROR 1 --- [pool-4-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

org.springframework.web.client.ResourceAccessException: I/O error on PUT request for "https://opensearch.my.domain:9200/logs-reportportal-1/_bulk": Remote host terminated the handshake; nested exception is javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:791) ~[spring-web-5.3.30.jar!/:5.3.30]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:717) ~[spring-web-5.3.30.jar!/:5.3.30]
        at org.springframework.web.client.RestTemplate.put(RestTemplate.java:503) ~[spring-web-5.3.30.jar!/:5.3.30]
        at com.epam.reportportal.elastic.SimpleElasticSearchClient.lambda$save$1(SimpleElasticSearchClient.java:69) ~[classes!/:na]
        at java.base/java.util.HashMap.forEach(HashMap.java:1429) ~[na:na]
        at com.epam.reportportal.elastic.SimpleElasticSearchClient.save(SimpleElasticSearchClient.java:68) ~[classes!/:na]
        at com.epam.reportportal.log.LogProcessing.process(LogProcessing.java:33) ~[classes!/:na]
        at com.epam.reportportal.calculation.BatchProcessing.processAndSchedule(BatchProcessing.java:55) ~[classes!/:na]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.30.jar!/:5.3.30]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1714) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1514) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426) ~[na:na]
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:586) ~[na:na]
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187) ~[na:na]
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:141) ~[na:na]
        at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:76) ~[spring-web-5.3.30.jar!/:5.3.30]
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-5.3.30.jar!/:5.3.30]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66) ~[spring-web-5.3.30.jar!/:5.3.30]
        at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:109) ~[spring-web-5.3.30.jar!/:5.3.30]
        at org.springframework.http.client.support.BasicAuthenticationInterceptor.intercept(BasicAuthenticationInterceptor.java:79) ~[spring-web-5.3.30.jar!/:5.3.30]
        at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:93) ~[spring-web-5.3.30.jar!/:5.3.30]
        at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:77) ~[spring-web-5.3.30.jar!/:5.3.30]
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-5.3.30.jar!/:5.3.30]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66) ~[spring-web-5.3.30.jar!/:5.3.30]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:782) ~[spring-web-5.3.30.jar!/:5.3.30]
        ... 14 common frames omitted
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:494) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:483) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160) ~[na:na]
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506) ~[na:na]
        ... 30 common frames omitted
```
Also I've checked logs in service-api:

```java
# Error I've got
2024-04-07 21:15:15.023 ERROR 1 --- [istener-exec117] c.e.t.r.dao.custom.ElasticSearchClient   : Search error logs-reportportal-1 Terms: {"id":[12345, 23456, 34567]} Message: 401 Unauthorized: [no body]
# ...

# Another one
2024-04-08 08:28:56.961 DEBUG 1 --- [a.Spring.bean-5] c.e.t.r.w.rabbit.AsyncReportingListener  : exception : com.epam.ta.reportportal.exception.ReportPortalException, message : Test Item 'a0b2c3-d4e5f6-6f65js-fgd435' not found. Did you use correct Test Item ID?,  cause :
2024-04-08 08:28:56.961  WARN 1 --- [a.Spring.bean-5] s.a.r.l.ConditionalRejectingErrorHandler : Execution of Rabbit message listener failed.

org.springframework.amqp.rabbit.support.ListenerExecutionFailedException: Listener threw exception
        at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.wrapToListenerExecutionFailedExceptionIfNeeded(AbstractMessageListenerContainer.java:1770)
        at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1716)
        at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1586)
        at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1563)
        at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1554)
        at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1498)
        at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:992)
        at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:939)
        at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:84)
        at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1316)
        at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1222)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.springframework.amqp.AmqpRejectAndDontRequeueException: null
        at com.epam.ta.reportportal.ws.rabbit.AsyncReportingListener.onMessage(AsyncReportingListener.java:190)
        at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1712)
        ... 10 common frames omitted
Caused by: com.epam.ta.reportportal.exception.ReportPortalException: Test Item 'a0b2c3-d4e5f6-6f65js-fgd435' not found. Did you use correct Test Item ID?
        at com.epam.ta.reportportal.ws.rabbit.AsyncReportingListener.onLogCreate(AsyncReportingListener.java:239)
        at com.epam.ta.reportportal.ws.rabbit.AsyncReportingListener.onMessage(AsyncReportingListener.java:167)
        ... 11 common frames omitted
```

Index "logs-reportportal-1" is exist in OpenSearch, also I tried to regenerate index for project from UI, but it does'nt helped me, same as creating new project.

All dependecies I use managed outide helm chart, versions you can find below.
For OpenSearch ReportPortal uses role with full permissions for indexes by patterns and rp_aa_stats, rp_done_tasks, etc.

**Expected behavior**
Must be Items in  "similar launhes" section in UI

**Screenshots**
-

**Versions:**
 - In K8s, chart - 24.1.0
 - OpenSearch - 2.10.0 has tls and user/pass auth
 - RabbitMQ  - 3.12.11
 - Minio -  2023.12.23
 - Postges - 11.14.0

**Additional envs added:**
- serviceapi - RP_JOBS_BASEURL(cause we have custom cluster domain, so default vault not works)
- servicejobs - ES_PROJECT_INDEX_PREFIX
- serviceanalyzer - ES_PROJECT_INDEX_PREFIX, MINIO_USE_TLS

**Comment by ifurs** [comment]
For issue with service-api trying connect to OpenSearch is my bad, cause there is doubleEntry enabled and need to set env vars:
- RP_ELASTICSEARCH_USERNAME
- RP_ELASTICSEARCH_PASSWORD
That is automaticly added to service jobs, but not api.

Also service-api trying connect to binded dns for service-jobs, using var
- RP_JOBS_BASEURL
The problem is that this var has almost static value:
```yaml
{{ ternary "https" "http" .Values.k8s.networking.ssl }}://{{ include "reportportal.fullname" . }}-jobs{{ printf ".%s.svc.cluster.local" .Release.Namespace }}:8686/jobs
```
But most production clusters use other domain than `.svc.cluster.local`
That could be fixed on Chart level, I will send PR.

After changes I got new errors from service-api:
```java
2024-04-08 09:53:17.172 ERROR 1 --- [a.Spring.bean-9] c.e.t.r.w.rabbit.AsyncReportingListener  : exception : javax.persistence.PersistenceException, message : org.hibernate.exception.ConstraintViolationException: could not execute statement,  cause : could not execute statement
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "test_item_uuid_key"
2024-04-08 09:54:17.490 ERROR 1 --- [a.Spring.bean-9] c.e.t.r.w.rabbit.AsyncReportingListener  : Dropping on maximum retry limit request of type = START_TEST, for target id = jfud7re-5054-fvfm54-aaa4-38108cb11bc6
2024-04-08 10:02:50.612 ERROR 1 --- [nio-8585-exec-3] o.s.t.i.TransactionInterceptor           : Application exception overridden by rollback exception
2024-04-08 10:02:50.615 ERROR 1 --- [nio-8585-exec-3] c.e.t.r.c.e.rest.RestExceptionHandler    : Handled error:
2024-04-08 10:02:50.616 ERROR 1 --- [nio-8585-exec-3] .t.r.c.e.r.ReportPortalExceptionResolver : ReportPortalExceptionResolver > Could not roll back JPA transaction; nested exception is org.hibernate.TransactionException: Unable to rollback against JDBC Connection
2024-04-08 10:02:50.617 ERROR 1 --- [nio-8585-exec-3] c.e.t.r.c.e.rest.Default
```
and
```java
2024-04-08 10:02:50.612 ERROR 1 --- [nio-8585-exec-3] o.s.t.i.TransactionInterceptor           : Application exception overridden by rollback exception
2024-04-08 10:02:50.615 ERROR 1 --- [nio-8585-exec-3] c.e.t.r.c.e.rest.RestExceptionHandler    : Handled error:
2024-04-08 10:02:50.616 ERROR 1 --- [nio-8585-exec-3] .t.r.c.e.r.ReportPortalExceptionResolver : ReportPortalExceptionResolver > Could not roll back JPA transaction; nested exception is org.hibernate.TransactionException: Unable to rollback against JDBC Connection
2024-04-08 10:02:50.617 ERROR 1 --- [nio-8585-exec-3] c.e.t.r.c.e.rest.DefaultErrorResolver    : Could not roll back JPA transaction; nested exception is org.hibernate.TransactionException: Unable to rollback against JDBC Connection
```

**Comment by ifurs** [comment]
I've added PR that would fix issues with env variables, still problem need attention

**Comment by ifurs** [comment]
After recreating job migration, logs from service-api is normal now

**Comment by alena-babrova** [comment]
Hello @ifurs,

If I understood correctly, we are waiting for the PR updates according to the comments there in order to apply your changes.

**Comment by alena-babrova** [comment]
Dear @ifurs,

Closing this due to inactivity. 
Please feel free to reopen it if the issue persists.
