### ISSUE TITLE
Socket timeout error / com.rabbitmq.client.ChannelContinuationTimeoutException: Continuation call for method 

### ISSUE THREAD

**Issue by yarynafd** [reportportal/reportportal#2273]
Report Portal used to work fine for five months. However, after updating the Jenkins machine, where Report Portal is also running, Report Portal stopped working. When running tests, there is an error message:

`[rp-io-2] ERROR c.epam.reportportal.service.Launch - [23] ReportPortal execution error
java.net.SocketTimeoutException: timeout
	at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:146)
	at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:161)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:339)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:430)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:323)
	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:180)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.epam.reportportal.service.PathParamInterceptor.intercept(PathParamInterceptor.java:55)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.epam.reportportal.service.BearerAuthInterceptor.intercept(BearerAuthInterceptor.java:40)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:46)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.net.SocketException: Socket closed
	at java.base/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:253)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:332)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
	at okio.InputStreamSource.read(JvmOkio.kt:93)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:128)
	... 33 common frames omitted
[rp-io-2] ERROR c.epam.reportportal.service.Launch - [23] ReportPortal execution error
java.net.SocketTimeoutException: timeout
	at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:146)
	at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:161)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:339)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:430)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:323)
	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:180)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.epam.reportportal.service.PathParamInterceptor.intercept(PathParamInterceptor.java:55)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.epam.reportportal.service.BearerAuthInterceptor.intercept(BearerAuthInterceptor.java:40)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:46)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.net.SocketException: Socket closed
	at java.base/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:253)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:332)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
	at okio.InputStreamSource.read(JvmOkio.kt:93)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:128)
	... 33 common frames omitted`

Docker compose logs
[logstxt.txt](https://github.com/reportportal/reportportal/files/15329335/logstxt.txt)

docker-compose.xml
[docke-compose.txt](https://github.com/reportportal/reportportal/files/15329337/docke-compose.txt)

I deleted all images, containers, volume, it didn't help.
<img width="1390" alt="Screenshot 2024-05-15 at 11 26 50 PM" src="https://github.com/reportportal/reportportal/assets/111346500/b01fd5bc-9153-4a40-827d-4451319891a3">

**Comment by carellevbt** [comment]
Same issue experienced on my end as well. Except I'm still on 5.10. It was working fine and then stopped 3 wks ago. We started from scratch with 5.11 and still have the same issue

**Comment by carellevbt** [comment]
Hi @yarynafd, we had made some clients version upgrade. Once we downgraded them we could see results on the portal again.

**Comment by carellevbt** [comment]
we downgraded the client libraries and the results populated on reportportal (both v5.10 and v5.11). When we upgrade the client libraries, it fails and we run into timeout errors.

**Comment by olmmarbury** [comment]
@yarynafd I've installed for the first time (v5.11) and am seeing this too. What version were you on before you upgraded?

**Comment by akuiz** [comment]
Can someone please help to troubleshoot this issue or advise on how to debug it on the Report Portal instance?
We're facing this problem with all the following Report Portal agents:
TestNG, Junit5, Junit4 
Also timeout is reproducible manually by sending a request to Report Portal instance to initiate a launch (taken from the JUNIT5 agent http logs)

`curl --location 'http://host:8080/api/v2/<user>_personal/launch' \
--header 'Authorization: Bearer <api-token>' \
--header 'Content-Type: application/json; charset=UTF-8' \
--data '{"startTime":"2024-07-11T14:49:17.998+0300","name":"Test Launch","attributes":[{"key":"skippedIssue","value":"true","system":true},{"key":"agent","value":"agent-java-junit5|5.3.1","system":true},{"key":"os","value":"Mac OS X|x86_64|12.7.5","system":true},{"key":"jvm","value":"OpenJDK 64-Bit Server VM|21.0.2|65.0","system":true}],"uuid":"<uuid>","mode":"DEFAULT","rerun":false}
'`

**Comment by pankajrawat1996** [comment]
@olmmarbury   @yarynafd [yarynafd](https://github.com/yarynafd) facing same issue.. Which version should we use?

**Comment by akshayamaldhure** [comment]
We are seeing this intermittently and frequently too recently.

```
com.epam.ta.reportportal.exception.ReportPortalException: com.rabbitmq.client.ChannelContinuationTimeoutException: Continuation call for method #method<channel.open>(out-of-band=) on channel AMQChannel(amqp://rabbitmq@172.21.0.2:5672/analyzer,41) (#41) timed out
	at com.epam.ta.reportportal.core.analyzer.auto.impl.LogIndexerService.indexLaunchLogs(LogIndexerService.java:111)
	at com.epam.ta.reportportal.core.analyzer.auto.impl.LogIndexerService$$FastClassBySpringCGLIB$$f53c9b3b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
```

Attaching the `docker-compose.yml` we are using.
[docker-compose.zip](https://github.com/user-attachments/files/17199223/docker-compose.zip)

**Comment by DzmitryHumianiuk** [comment]
@akshayamaldhure plz keep us posted if this still relevant for 24.2

**Comment by akshayamaldhure** [comment]
Yes, still observed on the 24.2 version. Attaching the logs.
[service-api-log-ChannelContinuationTimeoutException.zip](https://github.com/user-attachments/files/17238298/service-api-log-ChannelContinuationTimeoutException.zip)

**Comment by pankajrawat1996** [comment]
@DzmitryHumianiuk  Yes, I have also upgraded to the 24.2 version. and getting same error in logs

**Comment by DzmitryHumianiuk** [comment]
@pankajrawat1996 @akshayamaldhure thanks for the update. team will take a look

**Comment by ilonakozak2** [comment]
I faced with the same issue, reportportal/service-api:5.12.0 becomes unhealthy periodically.

**Comment by Pink-Bumblebee** [comment]
One of our end-users proposed to add this parameter to the rabbitmq settings :  RABBITMQ_DISK_FREE_ABSOLUTE_LIMIT: 50MB.
We added it to latest version of docker-compose.yml file. Maybe this setting will be helpful for you.
