### ISSUE TITLE
Getting connection timedout + closed issues in API + UAT service

### ISSUE THREAD

**Issue by mathew-jithin** [reportportal/reportportal#2287]
**Describe the bug**
There are two different issues:

1) 
```
2024-06-03 14:26:27.061  WARN 1 --- [s-task-exec2592] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: null
2024-06-03 14:26:27.061 ERROR 1 --- [s-task-exec2592] o.h.engine.jdbc.spi.SqlExceptionHelper   : HikariPool-1 - Connection is not available, request timed out after 30000ms.
2024-06-03 14:26:27.061 ERROR 1 --- [s-task-exec2592] c.e.t.r.c.log.impl.CreateLogHandlerImpl  : Failed to save log with attachments

java.util.concurrent.CompletionException: org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
```

2) 
```
2024-06-05 18:06:21.404  WARN 1 --- [nio-8585-exec-5] c.e.t.r.c.e.rest.RestExceptionHandler    : Resolved [javax.persistence.OptimisticLockException: org.hibernate.exception.LockAcquisitionException: could not execute statement]
2024-06-05 18:09:23.044  WARN 1 --- [io-8585-exec-40] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Failed to validate connection org.postgresql.jdbc.PgConnection@6720ee48 (This connection has been closed.). Possibly consider using a shorter maxLifetime value.
```

**Considerations:**
- We used the default connection limits initially (internally given for the services). Now we are on 70 connections per pod (3 pods) for `serviceapi` and 150 connections for `uat`. Issues are found to occur in both the cases (we did change connection limits due to the issue in the first place).
- This was working fine with ReportPortal 5.7.2 and issues started happening after we migrated to 24.1.0, as well as in 24.1.1. We did a fresh installation, so this is not a migration issue.
- We are on AWS RDS (Engine Ver: 14.11) with 2 vCPU & 4GB ram. We used to use the same on ReportPortal v5.7.2. So we continued with the same config.

...

**Expected behavior**
Connections to work similar to 5.7.2, which we were using earlier, from which we did a fresh installation with a new DB and other resources for ReportPortal
...

**Screenshots**
If applicable

**Versions:**
 - OS, Browser
 - Version of RP: `24.1.1`

**Comment by Pink-Bumblebee** [comment]
@mathew-jithin , looks like the root cause of your problem is related with AWS RDS PSQL (Engine Ver: 14.11) - we never tested it in RP. Please try to rool back to RDS PSQL (Engine Ver: 12.12).

**Comment by mathew-jithin** [comment]
Sure @Pink-Bumblebee. Thanks for responding. Is 12.12 the last version which ReportPortal was tested or is there any higher versions where support is provided.

I am asking as I saw that with 24.1.1 in helm, there was an upgrade done to 16.x. Is this also tested?

**Comment by Pink-Bumblebee** [comment]
@mathew-jithin , as for now some users are experiencing issues when upgrading version of RP: https://github.com/reportportal/reportportal/issues/2288.
Anyway, Postgres 16.x  was tested. So you could try.

**Comment by mathew-jithin** [comment]
@Pink-Bumblebee Thanks for sharing the thread. Should we wait until 16.x is fully tested and any fixes are made (if there is any near future plans), or should we switch to 12.12 now? Any recommendation from you would be really great.

**Comment by Pink-Bumblebee** [comment]
@mathew-jithin , have you resolved your issue?

**Comment by mathew-jithin** [comment]
@Pink-Bumblebee Nope. We are yet to do the downgrade to 12.x. We might do it to 13.x once as 12.x is reaching AWS EOS by end of this year. I will update you here if we were able to properly fix the issues after the same 👍
