### ISSUE TITLE
Azure Entra ID SAML configuration seems to create an entity ID mismatch

### ISSUE THREAD

**Issue by leonkaucher-threedy** [reportportal/reportportal#2292]
**Describe the bug**
I have a Docker Compose project of the latest Reportportal (versions below) running on my machine.

I have configured Entra ID SAML according to the [guide](https://reportportal.io/docs/reportportal-configuration/authorization/SamlProviders/AzureSaml/).

After logging in with Azure I receive a 403 error from the configered callback URL. The SAML response  comes from the issuer:

```xml
<Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">
  https://sts.windows.net/AAAAAAAA-AAAA-4AAA-AAAA-AAAAAAAAAAAA/BBBBBBBB-BBBB-4BBB-BBBB-BBBBBBBBBBBB
</Issuer>
```

This issuer appears in the error message of the uat:

<details>
  <summary>[Full message]<pre>org.springframework.security.saml.SamlProviderNotFoundException: Provider for key 'remote provider entityId' with value 'https://sts.windows.net/AAAAAAAA-AAAA-4AAA-AAAA-AAAAAAAAAAAA/BBBBBBBB-BBBB-4BBB-BBBB-BBBBBBBBBBBB' not found.</pre></summary>

  ```
org.springframework.security.saml.SamlProviderNotFoundException: Provider for key 'remote provider entityId' with value 'https://sts.windows.net/AAAAAAAA-AAAA-4AAA-AAAA-AAAAAAAAAAAA/BBBBBBBB-BBBB-4BBB-BBBB-BBBBBBBBBBBB' not found.
2024-06-13T07:44:03.497254084Z 	at org.springframework.security.saml.provider.AbstractHostedProviderService.throwIfNull(AbstractHostedProviderService.java:114) ~[spring-security-saml2-core-2.0.0.M31.jar!/:2.0.0.M31]
2024-06-13T07:44:03.497257589Z 	at org.springframework.security.saml.provider.AbstractHostedProviderService.getRemoteProvider(AbstractHostedProviderService.java:206) ~[spring-security-saml2-core-2.0.0.M31.jar!/:2.0.0.M31]
2024-06-13T07:44:03.497260988Z 	at org.springframework.security.saml.provider.service.HostedServiceProviderService.getRemoteProvider(HostedServiceProviderService.java:131) ~[spring-security-saml2-core-2.0.0.M31.jar!/:2.0.0.M31]
2024-06-13T07:44:03.497264498Z 	at org.springframework.security.saml.provider.service.HostedServiceProviderService.getRemoteProvider(HostedServiceProviderService.java:105) ~[spring-security-saml2-core-2.0.0.M31.jar!/:2.0.0.M31]
2024-06-13T07:44:03.497291001Z 	at org.springframework.security.saml.provider.service.HostedServiceProviderService.getRemoteProvider(HostedServiceProviderService.java:53) ~[spring-security-saml2-core-2.0.0.M31.jar!/:2.0.0.M31]
2024-06-13T07:44:03.497294092Z 	at org.springframework.security.saml.provider.AbstractHostedProviderService.fromXml(AbstractHostedProviderService.java:315) ~[spring-security-saml2-core-2.0.0.M31.jar!/:2.0.0.M31]
2024-06-13T07:44:03.497297167Z 	at org.springframework.security.saml.provider.service.authentication.SamlAuthenticationResponseFilter.attemptAuthentication(SamlAuthenticationResponseFilter.java:80) ~[spring-security-saml2-core-2.0.0.M31.jar!/:2.0.0.M31]
2024-06-13T07:44:03.497300011Z 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:231) ~[spring-security-web-5.8.5.jar!/:5.8.5]
2024-06-13T07:44:03.497304308Z 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221) ~[spring-security-web-5.8.5.jar!/:5.8.5]
2024-06-13T07:44:03.497306879Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) ~[spring-security-web-5.8.5.jar!/:5.8.5]
2024-06-13T07:44:03.497309374Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:111) ~[spring-web-5.3.33.jar!/:5.3.33]
2024-06-13T07:44:03.497312435Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) ~[spring-security-web-5.8.5.jar!/:5.8.5]
2024-06-13T07:44:03.497315560Z 	at org.springframework.security.saml.provider.service.SamlAuthenticationRequestFilter.doFilterInternal(SamlAuthenticationRequestFilter.java:89) ~[spring-security-saml2-core-2.0.0.M31.jar!/:2.0.0.M31]
2024-06-13T07:44:03.497318305Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.33.jar!/:5.3.33]
2024-06-13T07:44:03.497321091Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) ~[spring-security-web-5.8.5.jar!/:5.8.5]
2024-06-13T07:44:03.497323576Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:111) ~[spring-web-5.3.33.jar!/:5.3.33]
2024-06-13T07:44:03.497326204Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) ~[spring-security-web-5.8.5.jar!/:5.8.5]
2024-06-13T07:44:03.497329088Z 	at org.springframework.security.saml.provider.SamlMetadataFilter.doFilterInternal(SamlMetadataFilter.java:75) ~[spring-security-saml2-core-2.0.0.M31.jar!/:2.0.0.M31]
2024-06-13T07:44:03.497331592Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.33.jar!/:5.3.33]
2024-06-13T07:44:03.497334280Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) ~[spring-security-web-5.8.5.jar!/:5.8.5]
2024-06-13T07:44:03.497336873Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:111) ~[spring-web-5.3.33.jar!/:5.3.33]
2024-06-13T07:44:03.497343359Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) ~[spring-security-web-5.8.5.jar!/:5.8.5]
2024-06-13T07:44:03.497346688Z 	at org.springframework.security.saml.provider.config.ThreadLocalSamlConfigurationFilter.doFilterInternal(ThreadLocalSamlConfigurationFilter.java:42) ~[spring-security-saml2-core-2.0.0.M31.jar!/:2.0.0.M31]
2024-06-13T07:44:03.497349728Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.33.jar!/:5.3.33]
2024-06-13T07:44:03.497353859Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) ~[spring-security-web-5.8.5.jar!/:5.8.5]
2024-06-13T07:44:03.497356361Z 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107) ~[spring-security-web-5.8.5.jar!/:5.8.5]
2024-06-13T07:44:03.497358985Z 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93) ~[spring-security-web-5.8.5.jar!/:5.8.5]
2024-06-13T07:44:03.497361484Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) ~[spring-security-web-5.8.5.jar!/:5.8.5]
2024-06-13T07:44:03.497363274Z 	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[spring-security-web-5.8.5.jar!/:5.8.5]
2024-06-13T07:44:03.497365089Z 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[spring-security-web-5.8.5.jar!/:5.8.5]
2024-06-13T07:44:03.497366824Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.33.jar!/:5.3.33]
2024-06-13T07:44:03.497368601Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) ~[spring-security-web-5.8.5.jar!/:5.8.5]
2024-06-13T07:44:03.497370324Z 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:117) ~[spring-security-web-5.8.5.jar!/:5.8.5]
2024-06-13T07:44:03.497372067Z 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87) ~[spring-security-web-5.8.5.jar!/:5.8.5]
2024-06-13T07:44:03.497373935Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) ~[spring-security-web-5.8.5.jar!/:5.8.5]
2024-06-13T07:44:03.497376068Z 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62) ~[spring-security-web-5.8.5.jar!/:5.8.5]
2024-06-13T07:44:03.497377908Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.33.jar!/:5.3.33]
2024-06-13T07:44:03.497379671Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) ~[spring-security-web-5.8.5.jar!/:5.8.5]
2024-06-13T07:44:03.497381387Z 	at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42) ~[spring-security-web-5.8.5.jar!/:5.8.5]
2024-06-13T07:44:03.497386587Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.33.jar!/:5.3.33]
2024-06-13T07:44:03.497388376Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) ~[spring-security-web-5.8.5.jar!/:5.8.5]
2024-06-13T07:44:03.497390091Z 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:225) ~[spring-security-web-5.8.5.jar!/:5.8.5]
2024-06-13T07:44:03.497391847Z 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:190) ~[spring-security-web-5.8.5.jar!/:5.8.5]
2024-06-13T07:44:03.497393592Z 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354) ~[spring-web-5.3.33.jar!/:5.3.33]
2024-06-13T07:44:03.497395249Z 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) ~[spring-web-5.3.33.jar!/:5.3.33]
2024-06-13T07:44:03.497397020Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497398751Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497400774Z 	at org.springframework.security.oauth2.client.filter.OAuth2ClientContextFilter.doFilter(OAuth2ClientContextFilter.java:64) ~[spring-security-oauth2-2.5.2.RELEASE.jar!/:na]
2024-06-13T07:44:03.497402607Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497405713Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497407394Z 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.33.jar!/:5.3.33]
2024-06-13T07:44:03.497409078Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.33.jar!/:5.3.33]
2024-06-13T07:44:03.497413046Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497414963Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497416714Z 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.33.jar!/:5.3.33]
2024-06-13T07:44:03.497418597Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.33.jar!/:5.3.33]
2024-06-13T07:44:03.497420367Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497422279Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497425167Z 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) ~[spring-boot-actuator-2.5.14.jar!/:2.5.14]
2024-06-13T07:44:03.497430375Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.33.jar!/:5.3.33]
2024-06-13T07:44:03.497432994Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497436204Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497438884Z 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.33.jar!/:5.3.33]
2024-06-13T07:44:03.497442430Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.33.jar!/:5.3.33]
2024-06-13T07:44:03.497445145Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497447647Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497450251Z 	at org.springframework.web.filter.ForwardedHeaderFilter.doFilterInternal(ForwardedHeaderFilter.java:156) ~[spring-web-5.3.33.jar!/:5.3.33]
2024-06-13T07:44:03.497452904Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.33.jar!/:5.3.33]
2024-06-13T07:44:03.497455387Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497457781Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497460042Z 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497462798Z 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497467119Z 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497469966Z 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497472755Z 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497476571Z 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497478929Z 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497481595Z 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497488377Z 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497491305Z 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497494205Z 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497496863Z 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497499420Z 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497502971Z 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497505459Z 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[tomcat-embed-core-9.0.86.jar!/:na]
2024-06-13T07:44:03.497508096Z 	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
  ```
</details>

To me it looks like the UAT has registered a SAML provider from the entity ID it looked up from the metadata endpoint `https://login.microsoftonline.com/AAAAAAAA-AAAA-4AAA-AAAA-AAAAAAAAAAAA/federationmetadata/2007-06/federationmetadata.xml?appid=BBBBBBBB-BBBB-4BBB-BBBB-BBBBBBBBBBBB`. There the entity ID is named `https://sts.windows.net/AAAAAAAA-AAAA-4AAA-AAAA-AAAAAAAAAAAA/`.
And now it rejects the SAML Response because the issuer in the SAML response has the Application ID added to the entity ID.

Is there another lookup algorithm? It seems that others had success in adding Entra ID as a SAML provider. For me I can solve this problem by manually downloading the Metadata XML from Azure, editing the Entity ID such that it matches the Issuer for the SAML Response and then host the changed XML as a new Metadata XML endpoint but of course this seems to be the wrong approach.

I would be glad if someone could give me a hint why Reportportal does not find a match between SAMLResponse and registered Provider.

 *Versions*:
- API, Index, UI, Jobs: 5.11.0
- UAT: 5.11.2

**Expected behavior**
The UAT matches the SAML response to the registered SAML provider for ENtra ID without having to modify the XML metadata.

**Screenshots**
Azure portal SAML configuration:
![grafik](https://github.com/reportportal/reportportal/assets/158047574/e221ca72-69f6-4b46-9cec-b6ddb8c82f81)

Report Portal configuration:
![grafik](https://github.com/reportportal/reportportal/assets/158047574/c11cfe3a-3b6e-47c3-a818-439d3ef0ac00)

**Versions:**
 - Debian GNU/Linux 12 (bookworm), Firefox 128.0b1 (64-Bit)
- API, Index, UI, Jobs: 5.11.0
- UAT: 5.11.2

**Comment by raikbitters** [comment]
Hello @leonkaucher-threedy. Could you check your connectivity and ensure all attributes are mapped correctly? It looks like you have an issue with the Azure SSO configuration.

**Comment by leonkaucher-threedy** [comment]
Hey, thank you!

Yes, the `entityID` attribute in the XML metadata is exactly the same as the field `Microsoft Entra Identifier` in the portal page of the application.
Reportportal also fills two properties `identityProviderUrl` and `identityProviderAlias` in the `params` column of the `integration` table with this entityID that must come from the metadata endpoint as it is not explicitly given in the form.

The surprising thing for me was to find the `Issuer` in the `SAMLResponse` to have an added segment that includes the application ID (which is not part of the entityID) and UAT tries to match that and does not find a provider as the Issuer != entityID. As soon as I manually edit the Metadata XML to match with the issuer in the `SAMLResponse` and give my modified XML to Reportportal it will register a "wrong" entityID but as it matches the Issuer, UAT finds the correct provider and provisions the user:

![grafik](https://github.com/reportportal/reportportal/assets/158047574/ca60ab36-d792-4ab1-9a36-51e7fce54084)

But modifying the Metadata to force another entityID is not a solution.

**Comment by raikbitters** [comment]
@leonkaucher-threedy  I made a test integration with Azure SSO. In my case, Issure has the same value without any additional postfix.
![image](https://github.com/reportportal/reportportal/assets/13565058/43dd0a5f-661f-434d-8e2e-4cfde4307b7b)

We use standard Spring security logic for parsing SAML meta information and claim attributes. 
I guess you can try to fix it here:
In "Attributes & Claims" go to Edit:
![image](https://github.com/reportportal/reportportal/assets/13565058/b540f8c9-e2d6-4f66-8f0d-7f0357e378e9)
Here find the "Advanced SAML claims options" menu:
![image](https://github.com/reportportal/reportportal/assets/13565058/07b80e78-b772-4fd5-b873-ad0bb2881dae)

And disable the "Append application ID to issuer" checkbox (by default it is disabled):
![image](https://github.com/reportportal/reportportal/assets/13565058/54733e1b-0ad3-47fc-82b6-383a493571d7)

You will get the Issuere attribute with the same EntityId value after that.

Right now we don't have plans to adjust the Service Athtirization to solve a case when an Issuer contains an Application ID.
