### ISSUE TITLE
report portal launch is failing to finish 

### ISSUE THREAD

**Issue by rutika89** [reportportal/reportportal#2318]
**Describe the bug**
... Getting below error when the test execution finishes.
/playwright/node_modules/@reportportal/client-javascript/lib/report-portal-client.js:589
        new Error(`Item with tempId "${itemTempId}" not found`),
        ^
Error: Item with tempId "undefined" not found
    at RPClient.finishTestItem (/builds/future-state/cov/ait/playwright/node_modules/@reportportal/client-javascript/lib/report-portal-client.js:589:9)
    at CucumberReportPortalFormatter.finishFeature (/builds/future-state/cov/ait/playwright/node_modules/@reportportal/agent-js-cucumber/modules/cucumber-reportportal-formatter.js:169:25)
    at /builds/future-state/cov/ait/playwright/node_modules/@reportportal/agent-js-cucumber/modules/cucumber-reportportal-formatter.js:631:14
    at Array.forEach (<anonymous>)
    at CucumberReportPortalFormatter.onTestRunFinishedEvent (/builds/future-state/cov/ait/playwright/node_modules/@reportportal/agent-js-cucumber/modules/cucumber-reportportal-formatter.js:630:19)
    at CucumberReportPortalFormatter.eventHandler (/builds/future-state/cov/ait/playwright/node_modules/@reportportal/agent-js-cucumber/modules/cucumber-reportportal-formatter.js:82:23)
    at EventEmitter.emit (node:events:531:35)
    at Coordinator.onWorkerProcessClose (/builds/future-state/cov/ait/playwright/node_modules/@cucumber/cucumber/lib/runtime/parallel/coordinator.js:120:35)
    at ChildProcess.<anonymous> (/builds/future-state/cov/ait/playwright/node_modules/@cucumber/cucumber/lib/runtime/parallel/coordinator.js:93:18)
    at ChildProcess.emit (node:events:519:28)

**Expected behavior**
... Should be able to finish launch successfully.

**Screenshots**
If applicable

**Versions:**
 - OS, Browser
 - Version of RP : API Service: 5.10.0;Index Service: 5.10.0;Jobs Service: 5.10.0;Authorization Service: 5.10.0;Service UI: 5.10.0;

**Comment by Pink-Bumblebee** [comment]
@rutika89 , may I ask you about versions of reportportal's client-javascript and it's config?
BTW, maybe this information will be helpful: https://medium.com/@reportportal.io/reportportal-integration-with-playwright-43f2e73401af

**Comment by rutika89** [comment]
@Pink-Bumblebee  using these versions 
reportportal/agent-js-cucumber: 5.4.0
reportportal-js-client: 2.2.1
