### ISSUE TITLE
Getting some errors when try to run scripts in chrome headless mode

### ISSUE THREAD

**Issue by shashika23** [reportportal/reportportal#2320]
Hi Guys,

I am getting the following error when I run the test in Chrome headless mode: My suite has 37 test suites, generating like after executing 15 test suites. Please assist in resolving this.

Package.json
"scripts": {   
    "AllContentBlocks": "cypress run --spec 'cypress/e2e/ContentBlocks/**/*.js' --reporter @reportportal/agent-js-cypress --browser chrome --headless",
}
"devDependencies": {
    "@reportportal/agent-js-cypress": "5.3.1",
  },

Running:  AllAddon/SCC_All_Addon.spec.js               
                                  (3 of 37)
Fail to finish test Error: Item with tempId "cyi48r8lz9kc43r" not found
    at RPClient.finishTestItem (D:\addon-agent_work\1\s\node_modules\@reportportal\client-javascript\lib\report-portal-client.js:589:9)
    at Reporter.testEnd (D:\addon-agent_work\1\s\node_modules\@reportportal\agent-js-cypress\lib\reporter.js:176:47)
    at Reporter.testPending (D:\addon-agent_work\1\s\node_modules\@reportportal\agent-js-cypress\lib\reporter.js:189:12)
    at process.<anonymous> (D:\addon-agent_work\1\s\node_modules\@reportportal\agent-js-cypress\lib\worker.js:70:16)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

  (Results)

**Comment by alena-babrova** [comment]
Hello @shashika23,

Could you please tell me if it is still relevant for you, or you have managed to resolve it?

**Comment by alena-babrova** [comment]
Dear @shashika23,

As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to reopen the ticket with details.
