### ISSUE TITLE
reportportal/service-authorization failed to start after superadmin account is deleted

### ISSUE THREAD

**Issue by chanyk-joseph** [reportportal/reportportal#2327]
**Describe the bug**
superadmin account is deleted once we have enabled oauth authentication. 
During maintenance, we have recreated the docker compose service using
`docker-compose -p reportportal up -d --force-recreate`

However, reportportal/service-authorization:5.11.1 failed to init with following exception in the docker log
`Caused by: javax.persistence.EntityNotFoundException: superadmin not found`
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-08-19 16:53:03.205 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:820) ~[spring-boot-2.5.14.jar!/:2.5.14]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:801) ~[spring-boot-2.5.14.jar!/:2.5.14]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:350) ~[spring-boot-2.5.14.jar!/:2.5.14]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1370) ~[spring-boot-2.5.14.jar!/:2.5.14]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1359) ~[spring-boot-2.5.14.jar!/:2.5.14]
        at com.epam.reportportal.auth.AuthServerApplication.main(AuthServerApplication.java:40) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[service-authorization-5.11.1-exec.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[service-authorization-5.11.1-exec.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[service-authorization-5.11.1-exec.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[service-authorization-5.11.1-exec.jar:na]
Caused by: javax.persistence.EntityNotFoundException: superadmin not found
        at com.epam.reportportal.auth.AdminPasswordInitializer.lambda$run$0(AdminPasswordInitializer.java:42) ~[classes!/:na]
        at java.base/java.util.Optional.orElseThrow(Optional.java:408) ~[na:na]
        at com.epam.reportportal.auth.AdminPasswordInitializer.run(AdminPasswordInitializer.java:42) ~[classes!/:na]
        at com.epam.reportportal.auth.AdminPasswordInitializer$$FastClassBySpringCGLIB$$ee8f261a.invoke(<generated>) ~[classes!/:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.30.jar!/:5.3.30]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.20.jar!/:5.3.20]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.20.jar!/:5.3.20]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.20.jar!/:5.3.20]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.20.jar!/:5.3.20]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.20.jar!/:5.3.20]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.20.jar!/:5.3.20]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.20.jar!/:5.3.20]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.20.jar!/:5.3.20]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.20.jar!/:5.3.20]
        at com.epam.reportportal.auth.AdminPasswordInitializer$$EnhancerBySpringCGLIB$$425922c3.run(<generated>) ~[classes!/:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:817) ~[spring-boot-2.5.14.jar!/:2.5.14]
        ... 13 common frames omitted

2024-08-19 16:53:03.242  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2024-08-19 16:53:03.254  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
```

When the auth service is down, following issues happen:
- On the login UI, oauth method disappears
- login with username and password will be failed with response: `Full authentication is required to access this resource`

To solve the issue, we manually added back the `superadmin` user to the postgres database 

**Expected behavior**
If the `superadmin` user is required to init the auth service, it should be protected and not allowing admin users to delete it

**Screenshots**
N/A

**Versions:**
v5.11.1

**Comment by Pink-Bumblebee** [comment]
Hello @chanyk-joseph , thank you for your highlight. We are already have this issue in our backlog. I requested to add note to installation documentation.
