### ISSUE TITLE
ReportPortalException: Log 'xxxxxx' not found. Did you use correct Log ID?

### ISSUE THREAD

**Issue by amalbaccar-hub** [reportportal/reportportal#2328]
Hello,

We faced this exception while executing few test runs (large test suites of almost 800 test cases) from our CI server: 

<img width="786" alt="image" src="https://github.com/user-attachments/assets/2ac0bfb3-043c-47ed-b1d5-78cc66b94e37">

I checked logs from service api:

```
 2024-08-05 11:59:10.253 ERROR 1 --- [gs-task-exec399] .t.r.b.i.AttachmentBinaryDataServiceImpl : Cannot save log to database, remove files

com.epam.ta.reportportal.exception.ReportPortalException: Log '567629' not found. Did you use correct Log ID?
        at com.epam.ta.reportportal.binary.CreateLogAttachmentService.lambda$create$0(CreateLogAttachmentService.java:43)
        at java.base/java.util.Optional.orElseThrow(Optional.java:408)
        at com.epam.ta.reportportal.binary.CreateLogAttachmentService.create(CreateLogAttachmentService.java:43)
        at com.epam.ta.reportportal.binary.CreateLogAttachmentService$$FastClassBySpringCGLIB$$ca097b40.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
        at com.epam.ta.reportportal.binary.CreateLogAttachmentService$$EnhancerBySpringCGLIB$$7d9b3e58.create(<generated>)
        at com.epam.ta.reportportal.binary.impl.AttachmentBinaryDataServiceImpl.attachToLog(AttachmentBinaryDataServiceImpl.java:134)
        at com.epam.ta.reportportal.binary.impl.AttachmentBinaryDataServiceImpl.lambda$saveFileAndAttachToLog$0(AttachmentBinaryDataServiceImpl.java:117)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at com.epam.ta.reportportal.binary.impl.AttachmentBinaryDataServiceImpl.saveFileAndAttachToLog(AttachmentBinaryDataServiceImpl.java:117)
        at com.epam.ta.reportportal.core.log.impl.SaveLogBinaryDataTask.run(SaveLogBinaryDataTask.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

ReportPortal Version we are using:

<img width="323" alt="image" src="https://github.com/user-attachments/assets/4a7629c2-7b9e-4485-8891-0de17baccc6f">

**Note:**
We are using minio as our binary storage (minio/minio:RELEASE.2020-10-27T04-03-55Z), actually just using default config for minio in docker-compose file.

Any help please @DzmitryHumianiuk @abotalov

**Comment by alena-babrova** [comment]
Hello @amalbaccar-hub,

Could you please tell me if it is still relevant for you, or you have managed to resolve it?

**Comment by alena-babrova** [comment]
Dear @amalbaccar-hub,

As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to reopen the ticket with details.
