### ISSUE TITLE
java.lang.IllegalArgumentException: Empty key got when trying to connect s3 Bucket configuration

### ISSUE THREAD

**Issue by ulrich-geraud** [reportportal/reportportal#2335]
**Describe the bug**
...

I want to use S3 buckets to configure (multi-buckets) my reportportal for tests automation. After trying to connect the s3 buckets, I got the below error  (Caused by: java.lang.IllegalArgumentException: Empty key) that I don't understand. 

* Anyone here can help me ?
* I wondering if my configuration is good ?

**Behavior**
...
On service-api:5.11.1, I have this configuration for envs vars

```
RP_BINARYSTORE_TYPE: s3
RP_BINARYSTORE_S3_REGION: eu-central-1
RP_BINARYSTORE_S3_BUCKETPREFIX: first-prefix
RP_BINARYSTORE_S3_DEFAULTBUCKETNAME: reportportal-all-logs
RP_BINARYSTORE_S3_ACCESSKEY: my-access-key
RP_BINARYSTORE_S3_SECRETKEY: my-secret-key
```

On reportportal/service-authorization:5.11.1, I have this configuration for envs vars

```
RP_BINARYSTORE_TYPE: s3
RP_BINARYSTORE_S3_BUCKETPREFIX: second-prefix
RP_BINARYSTORE_S3_REGION: eu-central-1
RP_BINARYSTORE_S3_DEFAULTBUCKETNAME: reportportal-all-logs
RP_BINARYSTORE_S3_ACCESSKEY: my-access-key
RP_BINARYSTORE_S3_SECRETKEY: my-secret-key
```

On reportportal/service-jobs:5.11.1, I have this configuration for envs vars

```
DATASTORE_TYPE: s3
DATASTORE_S3_REGION: eu-central-1
DATASTORE_S3_BUCKETPREFIX: third-prefix-
DATASTORE_S3_DEFAULTBUCKETNAME: reportportal-all-logs
DATASTORE_S3_ACCESSKEY: my-access-key
DATASTORE_S3_SECRETKEY: my-secret-key
```

**Screenshots**

For service-api, I got this error:

```
api-1               | 2024-09-03 14:00:42.710  INFO 1 --- [           main] o.s.s.quartz.LocalDataSourceJobStore     : JobStoreCMT initialized.
api-1               | 2024-09-03 14:00:42.711  INFO 1 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler meta-data: Quartz Scheduler (v2.3.2) 'reportportal' with instanceId 'api:15a2fe1e67369e6ab796a84e9662bf3a'
api-1               |   Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
api-1               |   NOT STARTED.
api-1               |   Currently in standby mode.
api-1               |   Number of jobs executed: 0
api-1               |   Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 1 threads.
api-1               |   Using job-store 'org.springframework.scheduling.quartz.LocalDataSourceJobStore' - which supports persistence. and is clustered.
api-1               | 
api-1               | 2024-09-03 14:00:42.711  INFO 1 --- [           main] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler 'reportportal' initialized from an externally provided properties instance.
api-1               | 2024-09-03 14:00:42.711  INFO 1 --- [           main] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler version: 2.3.2
api-1               | 2024-09-03 14:00:42.711  INFO 1 --- [           main] org.quartz.core.QuartzScheduler          : JobFactory set to: com.epam.ta.reportportal.core.configs.SchedulerConfiguration$2@381db99e
api-1               | 2024-09-03 14:00:43.177  WARN 1 --- [           main] o.s.s.o.p.t.s.JwtAccessTokenConverter    : Unable to create an RSA verifier from verifierKey (ignoreable if using MAC)
api-1               | 2024-09-03 14:00:43.590  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sauceLabsIntegrationService' defined in URL [jar:file:/usr/app/service-api-5.11.1-exec.jar!/BOOT-INF/classes!/com/epam/ta/reportportal/core/integration/util/SauceLabsIntegrationService.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'encryptConfiguration' defined in URL [jar:file:/usr/app/service-api-5.11.1-exec.jar!/BOOT-INF/lib/commons-dao-5.11.6.jar!/com/epam/ta/reportportal/config/EncryptConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Empty key
api-1               | 2024-09-03 14:00:43.594  INFO 1 --- [           main] c.e.t.r.c.c.SchedulerConfiguration$1     : Shutting down Quartz Scheduler
api-1               | 2024-09-03 14:00:43.594  INFO 1 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler reportportal_$_api:15a2fe1e67369e6ab796a84e9662bf3a shutting down.
api-1               | 2024-09-03 14:00:43.595  INFO 1 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler reportportal_$_api:15a2fe1e67369e6ab796a84e9662bf3a paused.
api-1               | 2024-09-03 14:00:43.686  INFO 1 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler reportportal_$_api:15a2fe1e67369e6ab796a84e9662bf3a shutdown complete.
api-1               | 2024-09-03 14:00:43.694  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
api-1               | 2024-09-03 14:00:43.720  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
api-1               | 2024-09-03 14:00:43.721  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
api-1               | 2024-09-03 14:00:43.764  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 
api-1               | 
api-1               | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
api-1               | 2024-09-03 14:00:43.843 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
api-1               | 
api-1               | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sauceLabsIntegrationService' defined in URL [jar:file:/usr/app/service-api-5.11.1-exec.jar!/BOOT-INF/classes!/com/epam/ta/reportportal/core/integration/util/SauceLabsIntegrationService.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'encryptConfiguration' defined in URL [jar:file:/usr/app/service-api-5.11.1-exec.jar!/BOOT-INF/lib/commons-dao-5.11.6.jar!/com/epam/ta/reportportal/config/EncryptConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Empty key
api-1               | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:801)
api-1               | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:224)
api-1               | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
api-1               | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
api-1               | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
api-1               | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
api-1               | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
api-1               | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
api-1               | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
api-1               | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
api-1               | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
api-1               | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)
api-1               | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
api-1               | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
api-1               | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:780)
api-1               | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:453)
api-1               | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:343)
api-1               | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1370)
api-1               | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1359)
api-1               | 	at com.epam.ta.reportportal.core.configs.ReportPortalApp.main(ReportPortalApp.java:38)
api-1               | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
api-1               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
api-1               | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
api-1               | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
api-1               | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
api-1               | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
api-1               | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'encryptConfiguration' defined in URL [jar:file:/usr/app/service-api-5.11.1-exec.jar!/BOOT-INF/lib/commons-dao-5.11.6.jar!/com/epam/ta/reportportal/config/EncryptConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Empty key
api-1               | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
api-1               | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
api-1               | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
api-1               | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
api-1               | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
api-1               | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
api-1               | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
api-1               | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:405)
api-1               | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
api-1               | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
api-1               | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
api-1               | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
api-1               | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
api-1               | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
api-1               | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
api-1               | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
api-1               | 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
api-1               | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
api-1               | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
api-1               | 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:911)
api-1               | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788)
api-1               | 	... 25 common frames omitted
api-1               | Caused by: java.lang.IllegalArgumentException: Empty key
api-1               | 	at java.base/javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:107)
api-1               | 	at org.jclouds.encryption.internal.JCECrypto.hmac(JCECrypto.java:73)
api-1               | 	at org.jclouds.encryption.internal.JCECrypto.hmacSHA1(JCECrypto.java:90)
api-1               | 	at org.jclouds.s3.filters.RequestAuthorizeSignatureV2.sign(RequestAuthorizeSignatureV2.java:181)
api-1               | 	at org.jclouds.s3.filters.RequestAuthorizeSignatureV2.calculateSignature(RequestAuthorizeSignatureV2.java:171)
api-1               | 	at org.jclouds.s3.filters.RequestAuthorizeSignatureV2.filter(RequestAuthorizeSignatureV2.java:125)
api-1               | 	at org.jclouds.http.internal.BaseHttpCommandExecutorService.invoke(BaseHttpCommandExecutorService.java:90)
api-1               | 	at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:91)
api-1               | 	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:74)
api-1               | 	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:45)
api-1               | 	at org.jclouds.rest.internal.DelegatesToInvocationFunction.handle(DelegatesToInvocationFunction.java:156)
api-1               | 	at org.jclouds.rest.internal.DelegatesToInvocationFunction.invoke(DelegatesToInvocationFunction.java:123)
api-1               | 	at jdk.proxy2/jdk.proxy2.$Proxy229.objectExists(Unknown Source)
api-1               | 	at org.jclouds.s3.blobstore.S3BlobStore.blobExists(S3BlobStore.java:208)
api-1               | 	at com.epam.ta.reportportal.filesystem.distributed.s3.S3DataStore.exists(S3DataStore.java:132)
api-1               | 	at com.epam.ta.reportportal.config.EncryptConfiguration.loadOrGenerateEncryptorPassword(EncryptConfiguration.java:127)
api-1               | 	at com.epam.ta.reportportal.config.EncryptConfiguration.afterPropertiesSet(EncryptConfiguration.java:110)
api-1               | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
api-1               | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
api-1               | 	... 45 common frames omitted
api-1               | 

```

On uat service, I have this error:

```
uat-1               |     ____                        __  ____             __        __
uat-1               |    / __ \___  ____  ____  _____/ /_/ __ \____  _____/ /_____ _/ /
uat-1               |   / /_/ / _ \/ __ \/ __ \/ ___/ __/ /_/ / __ \/ ___/ __/ __ `/ /
uat-1               |  / _, _/  __/ /_/ / /_/ / /  / /_/ ____/ /_/ / /  / /_/ /_/ / /
uat-1               | /_/ |_|\___/ .___/\____/_/   \__/_/    \____/_/   \__/\__,_/_/
uat-1               |           /_/
uat-1               |                 Authorization Service: 5.11.1
uat-1               |                 Built with ♡ by EPAM Systems
uat-1               |                 Spring Boot  (v2.5.14)
uat-1               | 
uat-1               | 2024-09-03 14:02:02.038  INFO 1 --- [           main] c.e.r.auth.AuthServerApplication         : Starting AuthServerApplication using Java 11.0.20.1 on 3fcb31f246a2 with PID 1 (/usr/app/service-authorization-5.11.1-exec.jar started by root in /usr/app)
uat-1               | 2024-09-03 14:02:02.042  INFO 1 --- [           main] c.e.r.auth.AuthServerApplication         : The following 1 profile is active: "default"
uat-1               | 2024-09-03 14:02:05.014  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
uat-1               | 2024-09-03 14:02:05.693  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 669 ms. Found 31 JPA repository interfaces.
uat-1               | 2024-09-03 14:02:09.190  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9999 (http)
uat-1               | 2024-09-03 14:02:09.205  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
uat-1               | 2024-09-03 14:02:09.206  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.86]
uat-1               | 2024-09-03 14:02:09.370  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
uat-1               | 2024-09-03 14:02:09.370  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 7190 ms
uat-1               | 2024-09-03 14:02:09.708  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
uat-1               | 2024-09-03 14:02:10.062  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
uat-1               | 2024-09-03 14:02:11.475  INFO 1 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
uat-1               | 2024-09-03 14:02:11.637  INFO 1 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.4.24.Final
uat-1               | 2024-09-03 14:02:12.108  INFO 1 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
uat-1               | 2024-09-03 14:02:13.270  INFO 1 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: com.epam.ta.reportportal.commons.JsonbAwarePostgresDialect
uat-1               | 2024-09-03 14:02:16.998  INFO 1 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
uat-1               | 2024-09-03 14:02:17.020  INFO 1 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
uat-1               | 2024-09-03 14:02:21.517  WARN 1 --- [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
uat-1               | 2024-09-03 14:02:22.903  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'encryptConfiguration' defined in URL [jar:file:/usr/app/service-authorization-5.11.1-exec.jar!/BOOT-INF/lib/commons-dao-5.11.6.jar!/com/epam/ta/reportportal/config/EncryptConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Empty key
uat-1               | 2024-09-03 14:02:22.919  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
uat-1               | 2024-09-03 14:02:22.958  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
uat-1               | 2024-09-03 14:02:22.960  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
uat-1               | 2024-09-03 14:02:23.002  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 
uat-1               | 
uat-1               | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
uat-1               | 2024-09-03 14:02:23.072 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
uat-1               | 
uat-1               | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'encryptConfiguration' defined in URL [jar:file:/usr/app/service-authorization-5.11.1-exec.jar!/BOOT-INF/lib/commons-dao-5.11.6.jar!/com/epam/ta/reportportal/config/EncryptConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Empty key
uat-1               | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.20.jar!/:5.3.20]
uat-1               | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.20.jar!/:5.3.20]
uat-1               | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.20.jar!/:5.3.20]
uat-1               | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.20.jar!/:5.3.20]
uat-1               | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.20.jar!/:5.3.20]
uat-1               | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.20.jar!/:5.3.20]
uat-1               | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.20.jar!/:5.3.20]
uat-1               | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.20.jar!/:5.3.20]
uat-1               | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.20.jar!/:5.3.20]
uat-1               | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.20.jar!/:5.3.20]
uat-1               | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.14.jar!/:2.5.14]
uat-1               | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:780) ~[spring-boot-2.5.14.jar!/:2.5.14]
uat-1               | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:453) ~[spring-boot-2.5.14.jar!/:2.5.14]
uat-1               | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:343) ~[spring-boot-2.5.14.jar!/:2.5.14]
uat-1               | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1370) ~[spring-boot-2.5.14.jar!/:2.5.14]
uat-1               | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1359) ~[spring-boot-2.5.14.jar!/:2.5.14]
uat-1               | 	at com.epam.reportportal.auth.AuthServerApplication.main(AuthServerApplication.java:40) ~[classes!/:na]
uat-1               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
uat-1               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
uat-1               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
uat-1               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
uat-1               | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[service-authorization-5.11.1-exec.jar:na]
uat-1               | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[service-authorization-5.11.1-exec.jar:na]
uat-1               | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[service-authorization-5.11.1-exec.jar:na]
uat-1               | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[service-authorization-5.11.1-exec.jar:na]
uat-1               | Caused by: java.lang.IllegalArgumentException: Empty key
uat-1               | 	at java.base/javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:95) ~[na:na]
uat-1               | 	at org.jclouds.encryption.internal.JCECrypto.hmac(JCECrypto.java:73) ~[jclouds-core-2.5.0.jar!/:2.5.0]
uat-1               | 	at org.jclouds.encryption.internal.JCECrypto.hmacSHA1(JCECrypto.java:90) ~[jclouds-core-2.5.0.jar!/:2.5.0]
uat-1               | 	at org.jclouds.s3.filters.RequestAuthorizeSignatureV2.sign(RequestAuthorizeSignatureV2.java:181) ~[s3-2.5.0.jar!/:2.5.0]
uat-1               | 	at org.jclouds.s3.filters.RequestAuthorizeSignatureV2.calculateSignature(RequestAuthorizeSignatureV2.java:171) ~[s3-2.5.0.jar!/:2.5.0]
uat-1               | 	at org.jclouds.s3.filters.RequestAuthorizeSignatureV2.filter(RequestAuthorizeSignatureV2.java:125) ~[s3-2.5.0.jar!/:2.5.0]
uat-1               | 	at org.jclouds.http.internal.BaseHttpCommandExecutorService.invoke(BaseHttpCommandExecutorService.java:90) ~[jclouds-core-2.5.0.jar!/:2.5.0]
uat-1               | 	at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:91) ~[jclouds-core-2.5.0.jar!/:2.5.0]
uat-1               | 	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:74) ~[jclouds-core-2.5.0.jar!/:2.5.0]
uat-1               | 	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:45) ~[jclouds-core-2.5.0.jar!/:2.5.0]
uat-1               | 	at org.jclouds.rest.internal.DelegatesToInvocationFunction.handle(DelegatesToInvocationFunction.java:156) ~[jclouds-core-2.5.0.jar!/:2.5.0]
uat-1               | 	at org.jclouds.rest.internal.DelegatesToInvocationFunction.invoke(DelegatesToInvocationFunction.java:123) ~[jclouds-core-2.5.0.jar!/:2.5.0]
uat-1               | 	at com.sun.proxy.$Proxy230.objectExists(Unknown Source) ~[na:na]
uat-1               | 	at org.jclouds.s3.blobstore.S3BlobStore.blobExists(S3BlobStore.java:208) ~[s3-2.5.0.jar!/:2.5.0]
uat-1               | 	at com.epam.ta.reportportal.filesystem.distributed.s3.S3DataStore.exists(S3DataStore.java:132) ~[commons-dao-5.11.6.jar!/:na]
uat-1               | 	at com.epam.ta.reportportal.config.EncryptConfiguration.loadOrGenerateEncryptorPassword(EncryptConfiguration.java:127) ~[commons-dao-5.11.6.jar!/:na]
uat-1               | 	at com.epam.ta.reportportal.config.EncryptConfiguration.afterPropertiesSet(EncryptConfiguration.java:110) ~[commons-dao-5.11.6.jar!/:na]
uat-1               | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.20.jar!/:5.3.20]
uat-1               | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.20.jar!/:5.3.20]
uat-1               | 	... 24 common frames omitted
uat-1               | 
```

**Versions:**
 - Linux 22.04

**Comment by Pink-Bumblebee** [comment]
Hello @ulrich-geraud , may I ask you: are you still observing your issue? Or maybe somehow you've resolved it?

**Comment by ulrich-geraud** [comment]
Hello @Pink-Bumblebee , yes I still have the same problem. Do you have any idea which can help me to solve it ?

**Comment by raikbitters** [comment]
Hello @ulrich-geraud, you must use the same bracket configuration for all services. "RP_BINARYSTORE_S3_BUCKETPREFIX" has different values.

**Comment by ravindrasajjan** [comment]
I am getting below error while trying to connect S3 bucket where reportportal is running in K8S.

_`_`Caused by: java.lang.IllegalArgumentException: requested location us-east-1, which is not in the configured locations: {us-standard=Suppliers.ofInstance(https://s3.amazonaws.com/) │`_`_

Below is the yaml configs for S3 storage
  storage:
    type: s3
    bucket:
      bucketDefaultName: <bucket_name>
      type: single
    region: <region>
    accesskey: <access_key>
    secretkey: <secret key>
    ssl: false
    
Did any one of you come across this issue? any insight on the fix?
