### ISSUE TITLE
Error: "PKIX path building failed" while enabling TLS (SSL) in Traefik v2.0.7

### ISSUE THREAD

**Issue by Priyanshu19992002** [reportportal/reportportal#2342]
## Description
We have enabled TLS (SSL) on ReportPortal by following this documentation https://reportportal.io/docs/installation-steps-advanced/SetupTSLSSLInTraefik2.0.x . 

We were able to successfully enable TLS (SSL) using this documentation and the test data was successfully getting ingested in ReportPortal but then there was a vulnerability reported by our team that TLSv1.0 and TLS v1.1 is being used by the application and that need to be removed and enable TLS v1.2 and above. So, after debugging we found there were two weak ciphers present in our connection **TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA** and **TLS_RSA_WITH_3DES_EDE_CBC_SHA** so in order to remove this we just updated the file **certs_traefik.yaml** mentioned in above RP TLS documentation with below content

```
tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
        - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
        - TLS_RSA_WITH_AES_128_GCM_SHA256
        - TLS_RSA_WITH_AES_256_GCM_SHA384
  certificates:
    - certFile: /etc/certs/examplecert.crt
      keyFile: /etc/certs/examplecert.key
```

After updating the **certs_traefik.yaml** file with above content our vulnerability got fixed but then ingestion into ReportPortal got broked with below error
```
ERROR com.epam.reportportal.service.Launch - [22] ReportPortal execution error
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security-provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
at sun.security.ssl.Alert.createSSLException (Alert.java:131)
at sun.security.ssl.TransportContext.fatal(TransportContext.java:355) at sun.security.ssl.TransportContext.fatal(TransportContext.java: 298) at sun.security.ssl.TransportContext.fatal(TransportContext.java:293)
at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java: 1357)
at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage-java: 1232)
at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume (CertificateMessage.java: 1175)
at sun.security.ssl.SSLHandshake.consumeSSLHandshake.java: 377)
at sun.security.ssl.HandshakeContext.dispatch (HandshakeContext.java:444) at sun.security.ssl.HandshakeContext.dispatch (HandshakeContext.java:422) at sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
at sun.security.ssl.SSLTransport.decode (SSLTransport.java: 156)
at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1427)
at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpljava:1333)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java: 444)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java: 415)
```

We are unable to understand what has exactly broked as we are able to access the RP HTTPS URL perfectly and also we can see the correct certificates in the URL. Can you please help us with the solution to setup SSL (TLS) in ReportPortal for Docker installation or if you could let us know how we can fix the above issue?

```
 - OS = RHEL 8
 - Version of RP = API Service: 5.10.1;Index Service: 5.10.0;Jobs Service: 5.10.0;Authorization Service: 5.10.0;Service UI: 5.10.0;
 - RP Agent = serenity-reportportal-integration (v1.5.7)
 ```

**Comment by Priyanshu19992002** [comment]
It is resolved. Certificates were missing from CI tool.
