### ISSUE TITLE
NPE during getting users list from the admin panel

### ISSUE THREAD

**Issue by Kanaduchi** [reportportal/reportportal#2343]
**Describe the bug**
I got an NPE during  getting the list of all users from the admin panel

GET: /api/users/all?page.page=1&page.size=50&page.sort=fullName%2CASC
ERROR:
```
Sep 17 09:46:46 ERROR 7b7331bd6c34 api 1 --- [o-8585-exec-307] .t.r.c.e.r.ReportPortalExceptionResolver : ReportPortalExceptionResolver > Cannot invoke "com.epam.ta.reportportal.entity.Metadata.getMetadata()" because the return value of "com.epam.ta.reportportal.entity.user.User.getMetadata()" is null
Sep 17 09:46:46 7b7331bd6c34 api java.lang.NullPointerException: Cannot invoke "com.epam.ta.reportportal.entity.Metadata.getMetadata()" because the return value of "com.epam.ta.reportportal.entity.user.User.getMetadata()" is null
Sep 17 09:46:46 7b7331bd6c34 api 	at com.epam.ta.reportportal.ws.converter.converters.UserConverter.lambda$static$3(UserConverter.java:54)
Sep 17 09:46:46 7b7331bd6c34 api 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
Sep 17 09:46:46 7b7331bd6c34 api 	at java.base/java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:1085)
Sep 17 09:46:46 7b7331bd6c34 api 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
Sep 17 09:46:46 7b7331bd6c34 api 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
Sep 17 09:46:46 7b7331bd6c34 api 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
Sep 17 09:46:46 7b7331bd6c34 api 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
Sep 17 09:46:46 7b7331bd6c34 api 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
Sep 17 09:46:46 7b7331bd6c34 api 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
Sep 17 09:46:46 7b7331bd6c34 api 	at org.springframework.data.domain.Chunk.getConvertedContent(Chunk.java:173)
Sep 17 09:46:46 7b7331bd6c34 api 	at org.springframework.data.domain.PageImpl.map(PageImpl.java:106)
```

**Expected behavior**
List of users should be loaded

**Versions:**
 Version of RP: 5.11.0

**Comment by Pink-Bumblebee** [comment]
@Kanaduchi , have you tried to check your command in API swagger at your reportportal instance? Do you have admin rights? Maybe you can add some screenshots of your admin panel?

**Comment by Kanaduchi** [comment]
@Pink-Bumblebee 
Yes, I am an admin of RP instance

Here is my request:
GET: https://myrpinstance/api/users/all?page.page=1&page.size=50
RESPONSE:
```{
    "errorCode": 5000,
    "message": "Unclassified error [Cannot invoke \"com.epam.ta.reportportal.entity.Metadata.getMetadata()\" because the return value of \"com.epam.ta.reportportal.entity.user.User.getMetadata()\" is null]"
}```

UI doesn't work:
![Screenshot 2024-09-17 at 11 26 17](https://github.com/user-attachments/assets/f9f7095a-9bca-430b-b0e6-510d83cd1c27)

I can go to DB, try to find an incorrect user, and fix it. 

But I guess such problems should be processed correctly on the API side and do not block UI admin panel

**Comment by Pink-Bumblebee** [comment]
@Kanaduchi 
There is weird situation. In DB you could try to use this command: `update public.users set "metadata" = '{}' where metadata is null;`

**Comment by Kanaduchi** [comment]
@Pink-Bumblebee Looks like api doesn't return metadata field for superadmin user:
```
        {
            "id": 121,
            "userId": "superadmin",
            "email": "super@reltio.com",
            "photoId": "dXNlcnMvc3VwZXJhZG1pbg",
            "fullName": "Super Admin",
            "accountType": "INTERNAL",
            "userRole": "ADMINISTRATOR",
            "photoLoaded": true,
            "assignedProjects": {
                "superadmin_personal": {
                    "projectRole": "PROJECT_MANAGER",
                    "entryType": "PERSONAL"
                }
            }
        },
```

but in the database I see it:
<img width="968" alt="image" src="https://github.com/user-attachments/assets/db97dcd4-d42d-4037-8853-bfc5b2bc3a61">

**Comment by Pink-Bumblebee** [comment]
@Kanaduchi , sorry, is it a problem?

**Comment by Kanaduchi** [comment]
@Pink-Bumblebee Yes, UI doesn't load list of users:
<img width="1201" alt="image" src="https://github.com/user-attachments/assets/0d6247cc-1315-495c-89ab-956ed72f82f9">

**Comment by Pink-Bumblebee** [comment]
@Kanaduchi , haven't you deleted and then restored 'superadmin' account?
Dev engineer said, that it should be like this : {"metadata": {"last_login": 1726489438347}} , not just {"last_login": XXXX...}

**Comment by Kanaduchi** [comment]
@Pink-Bumblebee Thank you for help! 
I've fixed the metadata field and now everything is working fine. 

Problem was that our security department removed this user by some script. Because RP cannot works without such user I recreated it manually.
