### ISSUE TITLE
Cannot construct instance of `com.epam.reportportal.log.LogMessage` 

### ISSUE THREAD

**Issue by zsbutosi** [reportportal/reportportal#2366]
**Describe the bug**
I was trying to update our report portal instance from v24.1 to v24.2.
We implemented it in kubernetes, with AWS Rabbit MQ version 3.13.3.
When I updated the service-job to version 5.12.0, and tests starting to send logs, I got the following exceptions:
```
WARN 1 --- [ntContainer#0-1] s.a.r.l.ConditionalRejectingErrorHandler : Execution of Rabbit message listener failed.
org.springframework.amqp.rabbit.support.ListenerExecutionFailedException: Failed to convert message
at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:157) ~[spring-rabbit-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1722) ~[spring-rabbit-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1641) ~[spring-rabbit-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1629) ~[spring-rabbit-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1620) ~[spring-rabbit-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1564) ~[spring-rabbit-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:994) ~[spring-rabbit-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:941) ~[spring-rabbit-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:86) ~[spring-rabbit-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1323) ~[spring-rabbit-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1225) ~[spring-rabbit-2.4.17.jar!/:2.4.17]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: org.springframework.amqp.support.converter.MessageConversionException: Failed to convert Message content
at org.springframework.amqp.support.converter.AbstractJackson2MessageConverter.doFromMessage(AbstractJackson2MessageConverter.java:367) ~[spring-amqp-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.support.converter.AbstractJackson2MessageConverter.fromMessage(AbstractJackson2MessageConverter.java:321) ~[spring-amqp-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.support.converter.AbstractJackson2MessageConverter.fromMessage(AbstractJackson2MessageConverter.java:304) ~[spring-amqp-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.rabbit.listener.adapter.AbstractAdaptableMessageListener.extractMessage(AbstractAdaptableMessageListener.java:343) ~[spring-rabbit-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter$MessagingMessageConverterAdapter.extractPayload(MessagingMessageListenerAdapter.java:367) ~[spring-rabbit-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.support.converter.MessagingMessageConverter.fromMessage(MessagingMessageConverter.java:132) ~[spring-amqp-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.toMessagingMessage(MessagingMessageListenerAdapter.java:244) ~[spring-rabbit-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:147) ~[spring-rabbit-2.4.17.jar!/:2.4.17]
... 11 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.epam.reportportal.log.LogMessage` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
at [Source: (String)"{"id":195252382,"logTime":"2024-10-03T09:26:18.693Z","logMessage":"c.e.r.u.SubscriptionUtils - [rp-io-100] - Start test item completed with error 
retrofit2.adapter.rxjava2.HttpException: HTTP 503 
  at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
  at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
  at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
  at io.reactivex"[truncated 874 chars]; line: 1, column: 2]
at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67) ~[jackson-databind-2.15.3.jar!/:2.15.3]
at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1915) ~[jackson-databind-2.15.3.jar!/:2.15.3]
at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:414) ~[jackson-databind-2.15.3.jar!/:2.15.3]
at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1360) ~[jackson-databind-2.15.3.jar!/:2.15.3]
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1424) ~[jackson-databind-2.15.3.jar!/:2.15.3]
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[jackson-databind-2.15.3.jar!/:2.15.3]
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.15.3.jar!/:2.15.3]
at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.15.3.jar!/:2.15.3]
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825) ~[jackson-databind-2.15.3.jar!/:2.15.3]
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772) ~[jackson-databind-2.15.3.jar!/:2.15.3]
at org.springframework.amqp.support.converter.AbstractJackson2MessageConverter.convertBytesToObject(AbstractJackson2MessageConverter.java:428) ~[spring-amqp-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.support.converter.AbstractJackson2MessageConverter.convertContent(AbstractJackson2MessageConverter.java:395) ~[spring-amqp-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.support.converter.AbstractJackson2MessageConverter.doFromMessage(AbstractJackson2MessageConverter.java:364) ~[spring-amqp-2.4.17.jar!/:2.4.17]
... 18 common frames omitted

WARN 1 --- [ntContainer#0-1] ingErrorHandler$DefaultExceptionStrategy : Fatal message conversion error; message rejected; it will be dropped or routed to a dead letter exchange, if so configured: (Body:'[B@6f1308c7(byte[188])' MessageProperties [headers={__TypeId__=com.epam.ta.reportportal.entity.log.LogMessage}, contentType=application/json, contentEncoding=UTF-8, contentLength=0, receivedDeliveryMode=PERSISTENT, priority=0, redelivered=false, receivedExchange=processing, receivedRoutingKey=log_message_saving, deliveryTag=94, consumerTag=amq.ctag-VgCHHm5y3Io10Z_SrwGT1Q, consumerQueue=log_message_saving])
ERROR 1 --- [ntContainer#0-1] o.s.a.r.l.SimpleMessageListenerContainer : Execution of Rabbit message listener failed, and the error handler threw an exception
org.springframework.amqp.AmqpRejectAndDontRequeueException: Error Handler converted exception to fatal
at org.springframework.amqp.rabbit.listener.ConditionalRejectingErrorHandler.handleError(ConditionalRejectingErrorHandler.java:147) ~[spring-rabbit-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeErrorHandler(AbstractMessageListenerContainer.java:1526) ~[spring-rabbit-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.handleListenerException(AbstractMessageListenerContainer.java:1810) ~[spring-rabbit-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1585) ~[spring-rabbit-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:994) ~[spring-rabbit-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:941) ~[spring-rabbit-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:86) ~[spring-rabbit-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1323) ~[spring-rabbit-2.4.17.jar!/:2.4.17]
at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1225) ~[spring-rabbit-2.4.17.jar!/:2.4.17]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
``` 

I got similar exceptions for every message from rabbit mq.

As I saw, in the service-jobs changes, a new configuration file was added: `JacksonConfiguration`. Do I need any more configuration to use the service properly with the updated version (beside what was in the migration document)?

**Expected behavior**
Not to have exceptions during processing the messages.

**Screenshots**
N/A

**Versions:**
 - Version of RP: [API Service: 5.12.0, Jobs Service: 5.12.0, Index Service:  5.12.0, Authorization Service:  5.12.0, Service UI:  5.12.0]
 - AWS Rabbit MQ, version 3.13.3, and based on [this](https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/rabbitmq-basic-elements-plugins.html), the following plugins are available: Shovel plugin, Federation plugin and Consistent Hash exchange plugin

**Comment by Pink-Bumblebee** [comment]
@zsbutosi , may I ask you : have you followed this guide https://github.com/reportportal/kubernetes/wiki/Migration-guide#migration-to-2420 ?

**Comment by zsbutosi** [comment]
@Pink-Bumblebee Yes, I did the update based on that guide.

**Comment by irynakozak2** [comment]
@zsbutosi Hi! Could you please connect to the RabbitMQ management and send to us the following details:
1) In "Exchanges" you should have the following:
- e.reporting
- e.reporting.retry
2) In "Queues and Streams" you should have the following:
- `q.parkingLot.reporting` (ex. dead letter in 24.1)
- `q.retry.reporting.ttl` (1 retry queue for all API replicas)
- `q.reporting.*.0-10` (new reporting queues itself, the default count per 1 API is 10).

All queues should have a running state and old reporting queues should not persist after the upgrade:
<img width="931" alt="image" src="https://github.com/user-attachments/assets/fc2796ab-3964-49f3-b9ac-8def2058d5f2">
If some messages are left in those queues, you may need to redeploy your RabbitMQ.

Example of the new async look:
<img width="572" alt="image" src="https://github.com/user-attachments/assets/663dad4c-ff91-4a92-b8f7-1686f941e9e8">
<img width="858" alt="image" src="https://github.com/user-attachments/assets/1fd54c03-b22e-43b7-b5e4-51a0155cd1ba">

**Comment by zsbutosi** [comment]
@irynakozak2 
Thank you for your reply.

I connected to the rabbitMq instance:
1. I have both e.reporting and e.reporting.retry 
<img width="751" alt="Screenshot 2024-10-04 at 10 48 23" src="https://github.com/user-attachments/assets/4e6b25a3-67af-40a0-88d3-bf3114d4fdda">

2. And as I see, only the `q.reporting...` queues are working. the simple `reporting....` queues are empty.
<img width="1622" alt="Screenshot 2024-10-04 at 10 53 00" src="https://github.com/user-attachments/assets/b85fe6fe-8b08-48ee-bc85-5fb94b85e43b">

Even after restarting the Rabbit MQ instance, I still got the exception when I try to use the service-jobs:5.12.0 version. 

Do I need to delete and create a new MQ instance?
I was using rabbit mq v3.13.3 version before the update too.
I didn't need to update that when I updated the services.

Thx

**Comment by irynakozak2** [comment]
@zsbutosi Everything looks nice in RabbitMQ, thank you for the quick response! Not sure already, that the RabbitMQ redeployment is needed, and we will double-check on our side and I will return to you shortly.

**Comment by hlebkanonik** [comment]
Hi @zsbutosi! Could you please confirm that you have removed double-entry values from the Helm chart?

<img width="1596" alt="image" src="https://github.com/user-attachments/assets/fae3cc1c-c72d-4882-8a73-28a1603a79c8">
<img width="1582" alt="image" src="https://github.com/user-attachments/assets/bee26e4d-bf70-4b68-807e-2a501dc37f70">
<img width="1616" alt="image" src="https://github.com/user-attachments/assets/9a7159be-d715-4075-b8f5-22e823411ff4">
https://github.com/reportportal/kubernetes/compare/reportportal-24.1.7...reportportal-24.2.0

**Comment by zsbutosi** [comment]
@hlebkanonik 
The double entry was still in the system. 
By removing the `RP_ELASTICSEARCH_HOST` references from bot api and jobs pods, resolved the issue. 
Its working without any issue with the latest versions for all services.

Thank you for all of your support! 
I appreciate it!

**Comment by irynakozak2** [comment]
We are glad to hear that everything is fine and thank you for the contribution!
