### ISSUE TITLE
service-api container keeps restarting.

### ISSUE THREAD

**Issue by akshayamaldhure** [reportportal/reportportal#2372]
**Describe the bug**
After restarting all the containers, we have suddenly started getting this error in the `service-api` container logs and it keeps restarting. We tried stopping all the containers and removing all the containers and images and do a `docker system prune`. We even tried downgrading to version 24.1, but that fails for a different reason. So essentially, nothing we tried so far is working and this is a SOS call for help as our ReportPortal instance is down for us.

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pluginStartUpService': Invocation of init method failed; nested exception is com.epam.reportportal.rules.exception.ReportPortalException: Error during plugin uploading: 'Plugin with ID = 'junit' of the same VERSION = '1.0.0' has already been uploaded.'
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:780)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:453)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1359)
	at com.epam.ta.reportportal.core.configs.ReportPortalApp.main(ReportPortalApp.java:38)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: com.epam.reportportal.rules.exception.ReportPortalException: Error during plugin uploading: 'Plugin with ID = 'junit' of the same VERSION = '1.0.0' has already been uploaded.'
	at com.epam.reportportal.rules.commons.validation.ErrorTypeBasedRuleValidator.verify(ErrorTypeBasedRuleValidator.java:31)
	at com.epam.ta.reportportal.core.integration.plugin.impl.PluginLoaderImpl.lambda$resolvePluginDetails$3(PluginLoaderImpl.java:103)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at com.epam.ta.reportportal.core.integration.plugin.impl.PluginLoaderImpl.resolvePluginDetails(PluginLoaderImpl.java:101)
	at com.epam.ta.reportportal.plugin.Pf4jPluginManager.uploadPlugin(Pf4jPluginManager.java:344)
	at com.epam.ta.reportportal.plugin.PluginStartUpService.loadLatestVersion(PluginStartUpService.java:64)
	at com.epam.ta.reportportal.plugin.PluginStartUpService.lambda$loadPlugins$0(PluginStartUpService.java:56)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at com.epam.ta.reportportal.plugin.PluginStartUpService.loadPlugins(PluginStartUpService.java:56)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
```

Attaching the complete container log (remove the .zip extension to view the txt file).
[service-api-container-log.txt.zip](https://github.com/user-attachments/files/17304147/service-api-container-log.txt.zip)

**Expected behavior**
service-api container should start up and run gracefully.

**Screenshots**
NA

**Versions:**
 - OS, Browser (macOS, Chrome 129.0.6668.60)
 - Version of RP [cannot obtain this as we are getting the Loading screen continuously, but we are using this version of docker-compose.yml file https://github.com/reportportal/reportportal/blob/v24.2/docker-compose.yml]

**Comment by akshayamaldhure** [comment]
We tried `delete from integration_type where name='junit'` in the Postgres and it made it work. Please let me know if this is the right thing to do.

**Comment by Pink-Bumblebee** [comment]
@akshayamaldhure Yes, it is working workaround.

**Comment by akshayamaldhure** [comment]
Thanks for the confirmation. Closing this here.

**Comment by diranged** [comment]
Can this be re-opened? We are using the latest release and we see this issue regularly.
