### ISSUE TITLE
A null value (null) was output during logging

### ISSUE THREAD

**Issue by GigiOrGugu** [reportportal/reportportal#2373]
This log appeared during testing :
> 18:50:49.206 [rp-io-11] DEBUG com.epam.reportportal.service.Launch - null
==============================================================
More logs below : 
2 Scenarios (2 passed)
7 Steps (7 passed)
1m22.986s

18:50:49.062 [rp-io-6] DEBUG com.epam.reportportal.utils.SubscriptionUtils - Logging context completed
18:50:49.072 [rp-io-8] DEBUG com.epam.reportportal.utils.SubscriptionUtils - Launch logging context completed
18:50:49.080 [rp-io-99] DEBUG com.epam.reportportal.service.Launch - TestItem with ID = '0d0f8ed6-9df8-4414-bd5a-80a82a755746' successfully finished.
18:50:49.080 [rp-io-99] DEBUG com.epam.reportportal.utils.SubscriptionUtils - Finish test item completed
18:50:49.106 [rp-io-9] DEBUG com.epam.reportportal.service.Launch - TestItem with ID = 'f1ec5c42-d912-4b7d-94e2-0ee8516d4a81' successfully finished.
18:50:49.106 [rp-io-9] DEBUG com.epam.reportportal.utils.SubscriptionUtils - Finish test item completed
18:50:49.143 [rp-io-10] DEBUG com.epam.reportportal.service.Launch - TestItem with ID = 'c029d90c-acb5-4ee3-841b-893c2b3f3ba8' successfully finished.
18:50:49.143 [rp-io-10] DEBUG com.epam.reportportal.utils.SubscriptionUtils - Finish test item completed
18:50:49.168 [rp-io-10] DEBUG com.epam.reportportal.service.Launch - TestItem with ID = '0e3a9160-c1ba-4da6-95d7-0204bdea2c05' successfully finished.
18:50:49.168 [rp-io-10] DEBUG com.epam.reportportal.utils.SubscriptionUtils - Finish test item completed
18:50:49.206 [rp-io-11] DEBUG com.epam.reportportal.service.Launch - null
18:50:49.701 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:50:50.801 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:50:51.900 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:50:52.998 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:50:54.100 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:50:55.201 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:50:56.300 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:50:57.400 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:50:58.500 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:50:59.600 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:00.700 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:01.801 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:02.900 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:04.001 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:05.100 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:06.200 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:07.297 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:08.396 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:09.498 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:10.599 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:11.697 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:12.798 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:13.900 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:15.000 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:16.097 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:17.201 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:18.301 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:19.401 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:20.498 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:21.600 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:22.701 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:23.798 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:24.897 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:26.001 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:27.099 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:28.197 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:29.299 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:30.401 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:31.498 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:32.601 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:33.701 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:34.797 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:35.901 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:37.001 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:38.101 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:39.201 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:40.301 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:41.400 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:42.497 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:43.600 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:44.701 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:45.801 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:46.901 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:47.997 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:49.102 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://127.0.0.1:4723 : 1
18:51:49.102 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Adding Candidate expired Channel [id: 0x4bcd16d9, L:/127.0.0.1:56451 - R:/127.0.0.1:4723] isIdleTimeoutExpired=true isRemotelyClosed=false isTtlExpired=false
18:51:49.103 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Closing Idle Channel [id: 0x4bcd16d9, L:/127.0.0.1:56451 - R:/127.0.0.1:4723]
18:51:49.108 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Closed 1 connections out of 1 in 6 ms
18:51:49.112 [AsyncHttpClient-1-2] DEBUG org.asynchttpclient.netty.handler.HttpHandler - Channel Closed: [id: 0x4bcd16d9, L:/127.0.0.1:56451 ! R:/127.0.0.1:4723] with attribute DISCARD
18:55:49.227 [main] WARN com.epam.reportportal.service.statistics.StatisticsService - Unable to complete execution of all dependencies
java.util.concurrent.TimeoutException: The source did not signal an event for 300 seconds and has been terminated.
at io.reactivex.internal.operators.completable.CompletableTimeout$DisposeTask.run(CompletableTimeout.java:109)
at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 384.1 s -- in TestRunner
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:26 min
[INFO] Finished at: 2024-08-29T18:55:49+08:00
[INFO] ------------------------------------------------------------------------

============================================
pom info:

<dependencies>
        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>1.2.5</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>1.2.5</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.github.mkolisnyk</groupId>
            <artifactId>cucumber-runner</artifactId>
            <version>1.3.5</version>
            <scope>test</scope>
        </dependency>

       <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-cucumber</artifactId>
            <version>5.1.0-RC-3</version>
        </dependency>

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-logback</artifactId>
            <version>5.1.0-RC-1</version>
        </dependency>

        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>5.4.0</version>
        </dependency>

        
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.17.0</version>
        </dependency>

        
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.17.0</version>
        </dependency>

        
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>8.5.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.seleniumhq.selenium</groupId>
                    <artifactId>selenium-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.seleniumhq.selenium</groupId>
                    <artifactId>selenium-remote-driver</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.seleniumhq.selenium</groupId>
                    <artifactId>selenium-support</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-api</artifactId>
            <version>4.12.0</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-remote-driver</artifactId>
            <version>4.12.0</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-support</artifactId>
            <version>4.12.0</version>
        </dependency>

        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>5.4.0</version>
        </dependency>

    </dependencies>

**Comment by AlexanderSQA** [comment]
I have a same issue. And I also have no idea how to avoid (or resolve) it. Because of this my test run takes a minute longer already on 4 pilot tests. Really need help with that.

**Comment by alena-babrova** [comment]
Hello @GigiOrGugu, @AlexanderSQA,

Could you please tell me if the issue is still relevant?

**Comment by alena-babrova** [comment]
Dear @GigiOrGugu, @AlexanderSQA 

As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to reopen the ticket with details.
