### ISSUE TITLE
Rerun creating a new launch

### ISSUE THREAD

**Issue by atulsharmacsk** [reportportal/reportportal#2375]
Hi All,

I am using cucumber with reportportal & not able to make a rerun of any launch, I have tried with rp.reurn=true & also tried with rp.rerun.of='$(luanch_id)'

This is the pom.xml setup- https://github.com/atulsharmacsk/CucumberReportPortal/blob/master/pom.xml
This is the jenkins file setup where before rerun i ma appending the reportportal.properties eith rerun information-https://github.com/atulsharmacsk/CucumberReportPortal/blob/master/JenkinsFile

I see there is one open issue-https://github.com/reportportal/reportportal/issues/1588 but in that it is mentioned as intermittent issue but for me its always happening & also the below error is not mentioned in that.

I can see one error in logs of reportportal-api, not sure if this could be the reason of rerun not working
2024-07-14 10:54:34 2024-07-14 05:24:34.108  INFO 1 --- [-listener-exec6] c.e.t.r.c.a.a.indexer.BatchLogIndexer    : Indexing of 1 logs is finished for 1 items.
2024-07-14 10:54:48 2024-07-14 05:24:48.402 ERROR 1 --- [a.Spring.bean-1] c.e.t.r.w.rabbit.AsyncReportingListener  : exception : java.lang.NullPointerException, message : null,  cause :
2024-07-14 10:54:48 2024-07-14 05:24:48.405  WARN 1 --- [a.Spring.bean-1] s.a.r.l.ConditionalRejectingErrorHandler : Execution of Rabbit message listener failed.
2024-07-14 10:54:48
2024-07-14 10:54:48 org.springframework.amqp.rabbit.support.ListenerExecutionFailedException: Listener threw exception
2024-07-14 10:54:48     at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.wrapToListenerExecutionFailedExceptionIfNeeded(AbstractMessageListenerContainer.java:1778)
2024-07-14 10:54:48     at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1724)
2024-07-14 10:54:48     at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1594)
2024-07-14 10:54:48     at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1571)
2024-07-14 10:54:48     at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1562)
2024-07-14 10:54:48     at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1506)
2024-07-14 10:54:48     at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:967)
2024-07-14 10:54:48     at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:914)
2024-07-14 10:54:48     at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:83)
2024-07-14 10:54:48     at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1291)
2024-07-14 10:54:48     at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1197)
2024-07-14 10:54:48     at java.base/java.lang.Thread.run(Thread.java:829)
2024-07-14 10:54:48 Caused by: org.springframework.amqp.AmqpRejectAndDontRequeueException: null
2024-07-14 10:54:48     at [com.epam.ta.reportportal.ws](http://com.epam.ta.reportportal.ws/).rabbit.AsyncReportingListener.onMessage(AsyncReportingListener.java:186)
2024-07-14 10:54:48     at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1720)
2024-07-14 10:54:48     ... 10 common frames omitted
2024-07-14 10:54:48 Caused by: java.lang.NullPointerException: null
2024-07-14 10:54:48     at [com.epam.ta.reportportal.ws](http://com.epam.ta.reportportal.ws/).rabbit.AsyncReportingListener.createItemLog(AsyncReportingListener.java:299)
2024-07-14 10:54:48     at [com.epam.ta.reportportal.ws](http://com.epam.ta.reportportal.ws/).rabbit.AsyncReportingListener.onLogCreate(AsyncReportingListener.java:231)
2024-07-14 10:54:48     at [com.epam.ta.reportportal.ws](http://com.epam.ta.reportportal.ws/).rabbit.AsyncReportingListener.onMessage(AsyncReportingListener.java:163)
2024-07-14 10:54:48     ... 11 common frames omitted
2024-07-14 10:54:48
2024-07-14 10:55:48 2024-07-14 05:25:48.437 ERROR 1 --- [a.Spring.bean-1] c.e.t.r.w.rabbit.AsyncReportingListener  : exception : java.lang.NullPointerException, message : null,  cause :
2024-07-14 10:55:48 2024-07-14 05:25:48.438  WARN 1 --- [a.Spring.bean-1] s.a.r.l.ConditionalRejectingErrorHandler : Execution of Rabbit message listener failed.
2024-07-14 10:55:48
2024-07-14 10:55:48 org.springframework.amqp.rabbit.support.ListenerExecutionFailedException: Listener threw exception
2024-07-14 10:55:48     at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.wrapToListenerExecutionFailedExceptionIfNeeded(AbstractMessageListenerContainer.java:1778)
2024-07-14 10:55:48     at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1724)
2024-07-14 10:55:48     at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1594)
2024-07-14 10:55:48     at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1571)
2024-07-14 10:55:48     at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1562)
2024-07-14 10:55:48     at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1506)
2024-07-14 10:55:48     at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:967)
2024-07-14 10:55:48     at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:914)
2024-07-14 10:55:48     at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:83)
2024-07-14 10:55:48     at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1291)
2024-07-14 10:55:48     at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1197)
2024-07-14 10:55:48     at java.base/java.lang.Thread.run(Thread.java:829)
2024-07-14 10:55:48 Caused by: org.springframework.amqp.AmqpRejectAndDontRequeueException: null
2024-07-14 10:55:48     at [com.epam.ta.reportportal.ws](http://com.epam.ta.reportportal.ws/).rabbit.AsyncReportingListener.onMessage(AsyncReportingListener.java:186)
2024-07-14 10:55:48     at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1720)
2024-07-14 10:55:48     ... 10 common frames omitted
2024-07-14 10:55:48 Caused by: java.lang.NullPointerException: null
2024-07-14 10:55:48     at [com.epam.ta.reportportal.ws](http://com.epam.ta.reportportal.ws/).rabbit.AsyncReportingListener.createItemLog(AsyncReportingListener.java:299)
2024-07-14 10:55:48     at [com.epam.ta.reportportal.ws](http://com.epam.ta.reportportal.ws/).rabbit.AsyncReportingListener.onLogCreate(AsyncReportingListener.java:231)
2024-07-14 10:55:48     at [com.epam.ta.reportportal.ws](http://com.epam.ta.reportportal.ws/).rabbit.AsyncReportingListener.onMessage(AsyncReportingListener.java:163)
2024-07-14 10:55:48     ... 11 common frames omitted
2024-07-14 10:55:48
2024-07-14 10:56:48 2024-07-14 05:26:48.562 ERROR 1 --- [a.Spring.bean-1] c.e.t.r.w.rabbit.AsyncReportingListener  : Dropping on maximum retry limit request of type = LOG, for target id = df0b8729-38f5-4870-810e-76083a496a8 (edited) 

[pom.xml](https://github.com/atulsharmacsk/CucumberReportPortal/blob/master/pom.xml)

**Comment by alena-babrova** [comment]
Hello @atulsharmacsk,

Could you please tell me if the issue is still relevant for you?

**Comment by alena-babrova** [comment]
Dear @atulsharmacsk,

As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please do not hesitate to reopen the ticket with details.
