### ISSUE TITLE
Deadlocks on the database cause hanging test execution on CI

### ISSUE THREAD

**Issue by 501NotImplemented** [reportportal/reportportal#2396]
**Describe the bug**
I am using a ReportPortal 5.12.0 with @reportportal/agent-js-playwright 5.11.11

The database and the app are deployed on Rocky Linux and two _**separate**_ VMs.

When running the regression test suite, from CI logs I observe that RP JS agent is throwing the 413 error response, while there is one underlying 500 error coming from the API itself.

When I look at the API container docker logs, there are logs indicating the SQL deadlock (please see the logs attached).

From the tests itself, it looks that the issue is occuring for the tests that have retries enabled. 
My Playwright config is set to capture the screenshots, trace files and video on the first retry, so they are sent as an attachments to the ReportPortal.

### CI log
`
[run-playwright-tests-feature-sharded] Error: Request failed with status code 413
[run-playwright-tests-feature-sharded] URL: https://reportportal.*****.******/api/v1/myProject/log
[run-playwright-tests-feature-sharded] method: POST
[run-playwright-tests-feature-sharded]     at /app/node_modules/.pnpm/@reportportal+client-javascript@5.3.0/node_modules/@reportportal/client-javascript/lib/rest.js:56:15
[run-playwright-tests-feature-sharded]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[run-playwright-tests-feature-sharded] Error: Request failed with status code 413
[run-playwright-tests-feature-sharded] URL: https://reportportal.*****.******/api/v1/myProject/log
[run-playwright-tests-feature-sharded] method: POST
[run-playwright-tests-feature-sharded]     at /app/node_modules/.pnpm/@reportportal+client-javascript@5.3.0/node_modules/@reportportal/client-javascript/lib/rest.js:56:15
[run-playwright-tests-feature-sharded]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[run-playwright-tests-feature-sharded] Error: Request failed with status code 413
[run-playwright-tests-feature-sharded] URL: https://reportportal.*****.******/api/v1/myProject/log
[run-playwright-tests-feature-sharded] method: POST
[run-playwright-tests-feature-sharded]     at /app/node_modules/.pnpm/@reportportal+client-javascript@5.3.0/node_modules/@reportportal/client-javascript/lib/rest.js:56:15
[run-playwright-tests-feature-sharded]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[run-playwright-tests-feature-sharded] Error: Request failed with status code 500: {"errorCode":5000,"message":"Unclassified error [could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.LockAcquisitionException: could not execute statement]"}
[run-playwright-tests-feature-sharded] URL: https://reportportal.*****.******/api/v1/myProject/item/faa75c1a-b491-4b4b-85e5-d9176657d073
[run-playwright-tests-feature-sharded] method: PUT
[run-playwright-tests-feature-sharded]     at /app/node_modules/.pnpm/@reportportal+client-javascript@5.3.0/node_modules/@reportportal/client-javascript/lib/rest.js:56:15
[run-playwright-tests-feature-sharded]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[run-playwright-tests-feature-sharded] Failed to finish test. Error: Request failed with status code 500: {"errorCode":5000,"message":"Unclassified error [could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.LockAcquisitionException: could not execute statement]"}
[run-playwright-tests-feature-sharded] URL: https://reportportal.*****.******/api/v1/myProject/item/faa75c1a-b491-4b4b-85e5-d9176657d073
[run-playwright-tests-feature-sharded] method: PUT
[run-playwright-tests-feature-sharded]     at /app/node_modules/.pnpm/@reportportal+client-javascript@5.3.0/node_modules/@reportportal/client-javascript/lib/rest.js:56:15
[run-playwright-tests-feature-sharded]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[run-playwright-tests-feature-sharded] Error: Request failed with status code 413
[run-playwright-tests-feature-sharded] URL: https://reportportal.*****.******/api/v1/myProject/log
[run-playwright-tests-feature-sharded] method: POST
[run-playwright-tests-feature-sharded]     at /app/node_modules/.pnpm/@reportportal+client-javascript@5.3.0/node_modules/@reportportal/client-javascript/lib/rest.js:56:15
[run-playwright-tests-feature-sharded]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[run-playwright-tests-feature-sharded] Error: Request failed with status code 413
[run-playwright-tests-feature-sharded] URL: https://reportportal.*****.******/api/v1/myProject/log
[run-playwright-tests-feature-sharded] method: POST
[run-playwright-tests-feature-sharded]     at /app/node_modules/.pnpm/@reportportal+client-javascript@5.3.0/node_modules/@reportportal/client-javascript/lib/rest.js:56:15
[run-playwright-tests-feature-sharded]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[run-playwright-tests-feature-sharded] Error: Request failed with status code 413
[run-playwright-tests-feature-sharded] URL: https://reportportal.*****.******/api/v1/myProject/log
[run-playwright-tests-feature-sharded] method: POST
[run-playwright-tests-feature-sharded]     at /app/node_modules/.pnpm/@reportportal+client-javascript@5.3.0/node_modules/@reportportal/client-javascript/lib/rest.js:56:15
[run-playwright-tests-feature-sharded]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[run-playwright-tests-feature-sharded] Error: Request failed with status code 413
[run-playwright-tests-feature-sharded] URL: https://reportportal.*****.******/api/v1/myProject/log
[run-playwright-tests-feature-sharded] method: POST
[run-playwright-tests-feature-sharded]     at /app/node_modules/.pnpm/@reportportal+client-javascript@5.3.0/node_modules/@reportportal/client-javascript/lib/rest.js:56:15
[run-playwright-tests-feature-sharded]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[run-playwright-tests-feature-sharded] Error: Request failed with status code 413
[run-playwright-tests-feature-sharded] URL: https://reportportal.*****.******/api/v1/myProject/log
[run-playwright-tests-feature-sharded] method: POST
[run-playwright-tests-feature-sharded]     at /app/node_modules/.pnpm/@reportportal+client-javascript@5.3.0/node_modules/@reportportal/client-javascript/lib/rest.js:56:15
[run-playwright-tests-feature-sharded]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[run-playwright-tests-feature-sharded] Error: Request failed with status code 413
[run-playwright-tests-feature-sharded] URL: https://reportportal.*****.******/api/v1/myProject/log
[run-playwright-tests-feature-sharded] method: POST
[run-playwright-tests-feature-sharded]     at /app/node_modules/.pnpm/@reportportal+client-javascript@5.3.0/node_modules/@reportportal/client-javascript/lib/rest.js:56:15
[run-playwright-tests-feature-sharded]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[run-playwright-tests-feature-sharded] Error: Request failed with status code 413
[run-playwright-tests-feature-sharded] URL: https://reportportal.*****.******/api/v1/myProject/log
[run-playwright-tests-feature-sharded] method: POST
[run-playwright-tests-feature-sharded]     at /app/node_modules/.pnpm/@reportportal+client-javascript@5.3.0/node_modules/@reportportal/client-javascript/lib/rest.js:56:15
[run-playwright-tests-feature-sharded]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[run-playwright-tests-feature-sharded] Error: Request failed with status code 413
[run-playwright-tests-feature-sharded] URL: https://reportportal.*****.******/api/v1/myProject/log
[run-playwright-tests-feature-sharded] method: POST
[run-playwright-tests-feature-sharded]     at /app/node_modules/.pnpm/@reportportal+client-javascript@5.3.0/node_modules/@reportportal/client-javascript/lib/rest.js:56:15
[run-playwright-tests-feature-sharded]     at processTicksAndRejections (node:internal/process/task_queues:95:5)`
...
[CI Log.txt](https://github.com/user-attachments/files/17600248/CI.Log.txt)

### API container log
`Caused by: org.hibernate.exception.LockAcquisitionException: could not extract ResultSet
        at org.hibernate.dialect.PostgreSQL81Dialect$4.convert(PostgreSQL81Dialect.java:500)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:67)
        at org.hibernate.loader.Loader.getResultSet(Loader.java:2322)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2075)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2037)
        at org.hibernate.loader.Loader.doQuery(Loader.java:956)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:357)
        at org.hibernate.loader.Loader.doList(Loader.java:2868)
        at org.hibernate.loader.Loader.doList(Loader.java:2850)
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2682)
        at org.hibernate.loader.Loader.list(Loader.java:2677)
        at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:338)
        at org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:2186)
        at org.hibernate.internal.AbstractSharedSessionContract.list(AbstractSharedSessionContract.java:1204)
        at org.hibernate.query.internal.NativeQueryImpl.doList(NativeQueryImpl.java:177)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1617)
        ... 147 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 2068497 waits for ExclusiveLock on tuple (22433,100) of relation 17592 of database 16384; blocked by process 2068030.
Process 2068030 waits for ShareLock on transaction 8397217; blocked by process 2068366.
Process 2068366 waits for ShareLock on transaction 8397229; blocked by process 2068497.
  Hint: See server log for query details.
  Where: SQL statement "UPDATE statistics
            SET s_counter = s_counter - cur_statistics_fields.s_counter
            WHERE statistics.statistics_field_id = cur_statistics_fields.statistics_field_id
              AND (launch_id = cur_launch_id OR (item_id = ANY(processed_test_item.arr_path) AND item_id != test_item_id))"
PL/pgSQL function delete_item_statistics(bigint) line 29 at SQL statement
SQL statement "SELECT delete_item_statistics(retry_id)"
PL/pgSQL function handle_retry(bigint,bigint) line 30 at PERFORM`

[API container log.txt](https://github.com/user-attachments/files/17600247/API.container.log.txt)

**Expected behavior**
Test results are successfully updated on the fly. The test execution continues.

**Screenshots**
If applicable

**Versions:**
 - Rocky Linux
 - Build: 5.12.0

**Comment by owens-ben** [comment]
Also having this issue when running Detox tests 

RP version 5.10 and @reportportal+agent-js-jest+5.0.6

```Error: Request failed with status code 500: {"errorCode":5000,"message":"Unclassified error [org.hibernate.exception.LockAcquisitionException: could not extract ResultSet]"}
URL: https://reportportal-api.mycompany.com/api/v1/MY_PROJECT/item/a71ed333-6272-4515-983d-a9b4aa7f06c5
method: POST
    at /bitrise/src/node_modules/@reportportal/client-javascript/lib/rest.js:56:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
19:23:58.728 detox[17834] i Error: Request failed with status code 500: {"errorCode":5000,"message":"Unclassified error [org.hibernate.exception.LockAcquisitionException: could not extract ResultSet]"}
URL: https://reportportal-api.mycompany.com/api/v1/MY_PROJECT/item/a71ed333-6272-4515-983d-a9b4aa7f06c5
method: POST
    at /bitrise/src/node_modules/@reportportal/client-javascript/lib/rest.js:56:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
19:23:58.728 detox[17834] i Error: Request failed with status code 500: {"errorCode":5000,"message":"Unclassified error [org.hibernate.exception.LockAcquisitionException: could not extract ResultSet]"}
URL: https://reportportal-api.mycompany.com/api/v1/MY_PROJECT/item/a71ed333-6272-4515-983d-a9b4aa7f06c5
method: POST
    at /bitrise/src/node_modules/@reportportal/client-javascript/lib/rest.js:56:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
19:23:58.729 detox[17834] i Error: Request failed with status code 500: {"errorCode":5000,"message":"Unclassified error [org.hibernate.exception.LockAcquisitionException: could not extract ResultSet]"}
URL: https://reportportal-api.mycompany.com/api/v1/MY_PROJECT/item/a71ed333-6272-4515-983d-a9b4aa7f06c5
method: POST
    at /bitrise/src/node_modules/@reportportal/client-javascript/lib/rest.js:56:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
19:23:58.779 detox[17822] E Command failed with exit code = 1:```
