### ISSUE TITLE
Tests not reported correctly - V24.2, .Net

### ISSUE THREAD

**Issue by heilwood** [reportportal/reportportal#2402]
When we starting tests execution they not imidiatly sent to reportportal, when all tests are finished we see that error below in API container. Maybe its because dotnet has 7 precision datetime, but we not sure.

**Expected:**
Test should be reported correctly

**Actual:**
` {"errorCode":40025,"message":"Start time of child ['2024-11-08T11:20:27.807125700Z'] item should be same or later than start time ['2024-11-08T11:20:27.807126Z'] of the parent item/launch '14074902'"}
   at ReportPortal.Client.Resources.ServiceBaseResource.CheckSuccessStatusCode(HttpResponseMessage response, Stream stream)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendHttpRequestAsync[TResponse](HttpMethod httpMethod, String uri, HttpContent httpContent, CancellationToken cancellationToken)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendAsJsonAsync[TResponse,TRequest](HttpMethod httpMethod, String uri, TRequest request, CancellationToken cancellationToken)
   at ReportPortal.Client.Resources.ServiceTestItemResource.StartAsync(String uuid, StartTestItemRequest request, CancellationToken cancellationToken)
   at ReportPortal.Shared.Internal.Delegating.BaseRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttemptCallback, IStatisticsCounter statisticsCounter, String logicalOperationName)
   at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt, IStatisticsCounter statisticsCounter, String logicalOperationName)
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass25_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass30_0.<<Finish>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass30_0.<<Finish>b__0>d.MoveNext()`

**Versions:**
 - C#, .Net, Nugets 3.9, VStest logger
 - V24.2 - Services 5.12

**Comment by nvborisenko** [comment]
Investigated: the .net client sends datetime as `2024-11-13T11:47:02.5923066Z` which is transformed to `2024-11-13T11:47:02.592307Z` on server side. I don't think it is good that API transforms user's data.

**Comment by ysparrow** [comment]
Hi, do we have any ETA when this will be fixed?

**Comment by DzmitryHumianiuk** [comment]
@nvborisenko, I assume this has been fixed (and released) on the backend side, and now it just requires updating the .NET agent?  
Is my understanding correct?

**Comment by nvborisenko** [comment]
No, this is another issue on server side. Our .net client sends very "detailed" microseconds, and server eats it to be "normally detailed", what causes issue.

**Comment by mat-scalepoint** [comment]
Any updates on the issue?

**Comment by DzmitryHumianiuk** [comment]
> Any updates on the issue?
under discussion. the plan to squeeze it into the nearest hot fix.

**Comment by DzmitryHumianiuk** [comment]
@mat-scalepoint it is also fixed now.
there is a final release image ready, but still undergo some release checks. will be available pretty soon

**Comment by heilwood** [comment]
thank you, looks like fixed
