### ISSUE TITLE
Request header is too large

### ISSUE THREAD

**Issue by aladdin-atypon** [reportportal/reportportal#2403]
**Describe the bug**
On reportportal-api all api calls fail with HTTP 400, in the logs of the api we can see :

java.lang.IllegalArgumentException: Request header is too large
	at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:770)
	at org.apache.coyote.http11.Http11InputBuffer.parseHeader(Http11InputBuffer.java:964)
	at org.apache.coyote.http11.Http11InputBuffer.parseHeaders(Http11InputBuffer.java:591)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:286)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:1583)  

**Expected behavior**
The calls should be running without any issue

**Screenshots**
If applicable

**Versions:**
 - deploying via helm into k8s
 - 5.11.0  
 
 
Full logs [rp.log](https://github.com/user-attachments/files/17722657/rp.log)

**Comment by Pink-Bumblebee** [comment]
@aladdin-atypon , please check this thread https://github.com/reportportal/reportportal/issues/2250, maybe information will be helpful.

**Comment by alena-babrova** [comment]
Hello @aladdin-atypon,

Could you please tell us if your issue is resolved? Did increasing of `SERVER_MAX-HTTP-REQUEST-HEADER-SIZE` help?

**Comment by aladdin-atypon** [comment]
@alena-babrova , it was a weird header injected by Dynatrace which is a monitoring tool.

I suggest to run NGINX in debug mode, probably the long header is something unintentional and should be identified and removed rather than keep increasing the max header size.
