### ISSUE TITLE
System.Text.Json.JsonException parsing startTime when getting a launch

### ISSUE THREAD

**Issue by dstewart-kb4** [reportportal/reportportal#2405]
Hello, I'm getting the following error when getting a launch. We just updated our ReportPortal.Shared nuget from 3.7.0 to 3.9.0 after upgrading ReportPortal from 23.1 to 24.2.

```
System.Text.Json.JsonException : The JSON value could not be converted to System.DateTime. Path: $.startTime | LineNumber: 0 | BytePositionInLine: 218.
  ----> System.FormatException : The JSON value is not in a supported DateTime format.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObjectAsync(Stream utf8Json, CancellationToken cancellationToken)
   at ReportPortal.Client.Converters.ModelSerializer.DeserializeAsync[T](Stream stream, CancellationToken cancellationToken)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendHttpRequestAsync[TResponse](HttpMethod httpMethod, String uri, HttpContent httpContent, CancellationToken cancellationToken)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendAsJsonAsync[TResponse,TRequest](HttpMethod httpMethod, String uri, TRequest request, CancellationToken cancellationToken)
   at ReportPortal.Client.Resources.ServiceLaunchResource.GetAsync(String uuid, CancellationToken cancellationToken)
```
The line where this occurs is
```
// Removed the actual values here
service = new Service(
                new Uri("rp endpoint"),
                "project",
                "token"));

var launchCreatedResponse = service.Launch.StartAsync(new StartLaunchRequest()
{
    Name = "TestItemControllerTests Integration Test",
    Description = "Dummy Description",
    StartTime = DateTime.UtcNow,
}).WaitForTaskSuccess();

var launchResponse = service.Launch.GetAsync(launchCreatedResponse.Uuid).GetAwaiter().GetResult();
```

**Comment by nvborisenko** [comment]
@Pink-Bumblebee what is correct datetime format?

**Comment by dstewart-kb4** [comment]
I just attempted the same on the demo reportportal and am getting `2024-11-13T13:22:01.407297+0000`

**Comment by nvborisenko** [comment]
![image](https://github.com/user-attachments/assets/ec8133f7-ab89-4253-a33e-989f43cc34d6)

**Comment by dstewart-kb4** [comment]
Could there be some kind of culture/locality issue? This is a screenshot of the devtools from demo reportportal
![image](https://github.com/user-attachments/assets/76b8eb61-3fee-44c2-97c9-25073dd8b871)

**Comment by nvborisenko** [comment]
Now it is:

![image](https://github.com/user-attachments/assets/deda23e5-3df3-406e-b791-3e16b6a72bd2)

**Comment by dstewart-kb4** [comment]
@nvborisenko Created this PR for fixing the DateTime deserialization https://github.com/reportportal/client-dotnet/pull/150

**Comment by nvborisenko** [comment]
Who knows what DateTime format is expected?! It is changed again.

**Comment by nvborisenko** [comment]
From swagger docs:
```json
"startTime": "2024-11-13T17:02:50.571Z",
"endTime": "2024-11-13T17:02:50.571Z",
"lastModified": "2024-11-13T17:02:50.571Z"
```

**Comment by dstewart-kb4** [comment]
By using .NET `DateTime.Parse` it allows for the parsing of multiple formats as specified here https://learn.microsoft.com/en-us/dotnet/api/system.datetime.parse?view=net-8.0#the-string-to-parse

This would allow it to handle both `2024-11-13T17:02:50.571Z` and `2024-11-13T13:22:01.407297+0000`

**Comment by nvborisenko** [comment]
I know how to fix it, I don't like that API has been breaking changed without any notifications. Or it is just a bug on server side.

**Comment by dstewart-kb4** [comment]
@nvborisenko @HardNorth To give some more information, we have noticed that agent-dotnet-reqnroll is also affected by this DateTime parsing issue, however, agent-python-behave is not affected by it. This leads me to believe that any .NET based project consuming a GET request that contains a DateTime will not work since they are all using the same parser from the ReportPortal.Shared nuget package.

**Comment by nvborisenko** [comment]
@DzmitryHumianiuk may be you know what is expected format for DateTime?

**Comment by DzmitryHumianiuk** [comment]
@pbortnik could you please share expected DateTime format?

**Comment by nvborisenko** [comment]
The issue here is very simple: the team decided to make a breaking change... and they even couldn't suppose it is a breaking change.

It was aligned "recently":

![image](https://github.com/user-attachments/assets/457d0fa4-2c0e-4470-a4b9-667bf2f2a4e8)

**Comment by DzmitryHumianiuk** [comment]
@nvborisenko the intent was indeed to support multiple formats, both in milliseconds and microseconds. 
Regardless of what format you send, the backend is designed to round everything to microseconds. 
For milliseconds, the system should simply multiply the value by 1000.

However, it seems something went off-track.

**Comment by nvborisenko** [comment]
> simply multiply the value by 1000

Now it is clear why it is happening: https://github.com/reportportal/reportportal/issues/2402

Please announce what is datetime format is expected and don't change  it pleasae.

**Comment by goblinmaks** [comment]
@DzmitryHumianiuk when we can expect issue will be fixed? 
Thanks a lot

**Comment by DzmitryHumianiuk** [comment]
@goblinmaks, the team is actively discussing this. Standardization will require a separate release, as it involves a breaking change.  
The next release, 24.2.2, is scheduled for early December.

**Comment by DirkStr** [comment]
Hi @DzmitryHumianiuk - thanks for evaluating a potential solution. Do you have already a rough estimation if and when an update could be available? Thanks a lot in advance!

**Comment by DzmitryHumianiuk** [comment]
@DirkStr already released as a part of 24.2.2.

https://github.com/reportportal/reportportal/releases/tag/v24.2.2

**Comment by heilwood** [comment]
> @DirkStr already released as a part of 24.2.2.
> 
> https://github.com/reportportal/reportportal/releases/tag/v24.2.2

This link is not working (returning 404) and i can't find v24.2.2 on release page, do we need to wait more?

**Comment by Pink-Bumblebee** [comment]
@heilwood , please wait for a couple days.

**Comment by heilwood** [comment]
**ReportPortal v24.2.2**

**service-api:5.13.1**

**Vstest Logger**

Latest nuget packages, still same issue:

```
2024-12-19 13:35:40.433 ERROR 1 --- [io-8585-exec-11] .r.r.c.e.r.ReportPortalExceptionResolver : ReportPortalExceptionResolver > Start time of child ['2024-12-19T13:35:26.187359900Z'] item should be same or later than start time ['2024-12-19T13:35:26.187360Z'] of the parent item/launch '14374380'

com.epam.reportportal.rules.exception.ReportPortalException: Start time of child ['2024-12-19T13:35:26.187359900Z'] item should be same or later than start time ['2024-12-19T13:35:26.187360Z'] of the parent item/launch '14374380'
        at com.epam.reportportal.rules.commons.validation.ErrorTypeBasedRuleValidator.verify(ErrorTypeBasedRuleValidator.java:31)
        at com.epam.ta.reportportal.core.item.validator.parent.StartTimeConditionValidator.validate(StartTimeConditionValidator.java:17)
        at com.epam.ta.reportportal.core.item.impl.StartTestItemHandlerImpl.lambda$startChildItem$4(StartTestItemHandlerImpl.java:160)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at com.epam.ta.reportportal.core.item.impl.StartTestItemHandlerImpl.startChildItem(StartTestItemHandlerImpl.java:160)
        at com.epam.ta.reportportal.core.item.impl.StartTestItemHandlerImpl$$FastClassBySpringCGLIB$$17d020e.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at com.epam.ta.reportportal.core.item.impl.StartTestItemHandlerImpl$$EnhancerBySpringCGLIB$$a69069b4.startChildItem(<generated>)
        at com.epam.ta.reportportal.ws.controller.TestItemController.startChildItem(TestItemController.java:146)
        at com.epam.ta.reportportal.ws.controller.TestItemController$$FastClassBySpringCGLIB$$b0260678.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:67)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at com.epam.ta.reportportal.ws.controller.TestItemController$$EnhancerBySpringCGLIB$$a1c4284b.startChildItem(<generated>)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:903)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:809)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.web.multipart.support.MultipartFilter.doFilterInternal(MultipartFilter.java:125)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:352)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:117)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:131)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:85)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)

**Comment by nvborisenko** [comment]
Related to https://github.com/reportportal/reportportal/issues/2402
