### ISSUE TITLE
RP24.2 api container shows prj-users not found error

### ISSUE THREAD

**Issue by meenakshimoody1** [reportportal/reportportal#2415]
We don't see any user or project related errors in UI but api container shows below error all the time-

`2024-11-07 02:17:10.792 ERROR 1 --- [-8585-exec-6713] c.e.r.r.c.e.rest.DefaultErrorResolver    : prj-users not found: container prj-users not in [prj-keystore, rp-bucket, prj-4]

org.jclouds.blobstore.ContainerNotFoundException: prj-users not found: container prj-users not in [prj-keystore, rp-bucket, prj-4]
        at org.jclouds.blobstore.config.LocalBlobStore.cnfe(LocalBlobStore.java:382)
        at org.jclouds.blobstore.config.LocalBlobStore.getBlob(LocalBlobStore.java:637)
        at org.jclouds.blobstore.config.LocalBlobStore.getBlob(LocalBlobStore.java:205)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
       ......................................................
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
        at java.base/java.lang.Thread.run(Thread.java:1583)

2024-11-07 02:17:10.792  WARN 1 --- [-8585-exec-6713] c.e.r.r.c.e.rest.RestExceptionHandler    : Resolved [org.jclouds.blobstore.ContainerNotFoundException: prj-users not found: container prj-users not in [prj-keystore, rp-bucket, prj-4]]`

Do we expect anything to be created under folder in ec2 at /home/ec2-user/data/opensearch ? Or this error can be ignored ? Or can the folders be created manually to stop these errors ?

We have below details for volumes created -
Local Volumes space usage:

`VOLUME NAME                                                        LINKS     SIZE
7a6b8d454ed3c0dc67c585f59415d1b7dddddddddd69c9111d826b2513f548fe   1         17.67MB
reportportal_storage                                               5                                                      38.25MB
reportportal_opensearch                                            1                                                   70.85MB
4193cea35f8594da59cb1565e6f5sssssssssssssss78b05e389a5d28252382b   1         32.77kB
151eb6738b10d1f2ede4184aaaaaaaa0d52a750e8968e56f41bf7dcddd04d1ca   1         32.77kB

I see data folders when I exec to opensearch container so does this look good?

sh-5.2$ cd data

sh-5.2$ ls -lrt
total 20
-rw-rw-r--. 1 opensearch opensearch  5 Oct 18 16:04 rca_enabled.conf
-rw-rw-r--. 1 opensearch opensearch  5 Oct 18 16:04 performance_analyzer_enabled.conf
-rw-rw-r--. 1 opensearch opensearch  5 Oct 18 16:04 thread_contention_monitoring_enabled.conf
-rw-rw-r--. 1 opensearch opensearch  5 Oct 18 16:04 logging_enabled.conf
-rw-rw-r--. 1 opensearch opensearch  5 Oct 18 16:04 batch_metrics_enabled.conf
drwxrwxr-x. 3 opensearch opensearch 15 Oct 18 16:04 nodes
sh-5.2$ cd nodes
sh-5.2$ ls
0
sh-5.2$ cd 0

sh-5.2$ ls -lrt
total 32
-rw-rw-r--.  1 opensearch opensearch     0 Oct 18 16:04 node.lock
drwxrwxr-x. 14 opensearch opensearch 16384 Nov 14 17:35 indices
drwxrwxr-x.  2 opensearch opensearch 16384 Nov 14 17:35 _state
sh-5.2$ cd indices
sh-5.2$ ls -lrt
total 0
drwxrwxr-x. 4 opensearch opensearch 29 Nov  3 00:35 Ucffff5jVBa1TzKJCdH4-WPr-g
drwxrwxr-x. 4 opensearch opensearch 29 Nov  4 22:21 xOQeGPonmF9zlQ8Q
drwxrwxr-x. 4 opensearch opensearch 29 Nov  5 04:37 MNzTQqNPFVVnDVuXQ
drwxrwxr-x. 4 opensearch opensearch 29 Nov 14 17:35 mC4TTmGo0cYh4paZA`

**Comment by meenakshimoody1** [comment]
@APiankouski can you suggest on this issue?

**Comment by meenakshimoody1** [comment]
@DzmitryHumianiuk Can you get some help on this to resolve the issue as we just started using the new version so want to fix all errors before we go too far.

**Comment by meenakshimoody1** [comment]
@DzmitryHumianiuk can you please assign someone to help on this whenever possible?

**Comment by DzmitryHumianiuk** [comment]
@meenakshimoody1 seem like resolved here
https://reportportal.slack.com/archives/C2GTZU8N5/p1730341924193099

**Comment by meenakshimoody1** [comment]
@DzmitryHumianiuk As per this slack thread I confirmed that required volumes are created and size is increasing for them.
But not sure of the root cause of the error itself.
