### ISSUE TITLE
[Feature Request] Add “Minimum should match percentage” to Unique Errors analysis

### ISSUE THREAD

**Issue by DS9475** [reportportal/reportportal#2422]
**Describe the solution you'd like**

As in title, I'd like to have a setting for Minimum should match percentage for a Unique Errors analysis so small differences in stacktrace would still be combined into one entry in Unique Errors table.

**Is your feature request related to a problem? Please describe.**
My example of 2 nearly identical logs that were not combined into one unique error:

Log1:
`org.openqa.selenium.NotFoundException: Didn't find any okButton nor button-ok locators
Build info: version: '4.26.0', revision: '8ccf0219d7'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-113-generic', java.version: '11.0.24'
Driver info: driver.version: unknown
	at my.package.test.pages.BasePage.getOKButtonLocator(BasePage.java:134)
	at my.package.test.pages.clientorders.NewClientOrderPage.submitClientOrder(NewClientOrderPage.java:341)
	at my.package.automatedtests.AddClientOrderTest.clientOrderTemplateCreatedFromScratch(AddClientOrderTest.java:452)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at eu.etransit.automatedtests.base.TestInterceptor.interceptTestMethod(TestInterceptor.java:198)`
	
Log2:
`org.openqa.selenium.NotFoundException: Didn't find any okButton nor button-ok locators
Build info: version: '4.26.0', revision: '8ccf0219d7'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-113-generic', java.version: '11.0.24'
Driver info: driver.version: unknown
	at my.package.test.pages.BasePage.getOKButtonLocator(BasePage.java:134)
	at my.package.test.pages.clientorders.NewClientOrderPage.submitClientOrder(NewClientOrderPage.java:341)
	at my.package.automatedtests.AddClientOrderTest.clientOrderTemplateSavedFromCopiedLoad(AddClientOrderTest.java:361)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at eu.etransit.automatedtests.base.TestInterceptor.interceptTestMethod(TestInterceptor.java:198)`
	

You can paste those 2 logs into any online text compare tools to see that only in one line, a few characters differ
	
	
![image](https://github.com/user-attachments/assets/1bcc46e8-d5b6-4260-bca0-c91e26ed6d80)

**Comment by Kozovskaya** [comment]
Hello @DS9475 
Thanks for your request. I've created ticket in our Backlog, we will discuss and prioritize it within the team.
