### ISSUE TITLE
[rp-io-93] ERROR com.epam.reportportal.service.Launch - [127] ReportPortal execution error retrofit2.adapter.rxjava2.HttpException: HTTP 429 

### ISSUE THREAD

**Issue by shashankshampi** [reportportal/reportportal#2433]
**Describe the bug**
When execution of Test suite I starts getting retrofit2.adapter.rxjava2.HttpException: HTTP 429 and my launch never get closed and test count also never get updated in the launch resulting in missing of test in launch and logs get flooded with same error each time. Thoese test got errored out never get added in total test.

`2024-12-04T11:04:06.8039494Z [rp-io-43] ERROR com.epam.reportportal.utils.SubscriptionUtils - Start test item completed with error 
2024-12-04T11:04:06.8040906Z 2024-12-04 11:04:06,803 | INFO | [ io.nethermind.app.FrameworkListener ] -> After Class: online.voyager.message.sanity.InternalMessagesSanityTest
2024-12-04T11:04:06.8042190Z retrofit2.adapter.rxjava2.HttpException: HTTP 429 
2024-12-04T11:04:06.8043042Z 	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
2024-12-04T11:04:06.8044105Z 	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
2024-12-04T11:04:06.8045295Z 	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
2024-12-04T11:04:06.8046457Z 	at io.reactivex.Observable.subscribe(Observable.java:12267)
2024-12-04T11:04:06.8047499Z 	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
2024-12-04T11:04:06.8048384Z 	at io.reactivex.Observable.subscribe(Observable.java:12267)
2024-12-04T11:04:06.8049488Z 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
2024-12-04T11:04:06.8050861Z 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
2024-12-04T11:04:06.8052011Z 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
2024-12-04T11:04:06.8053021Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-12-04T11:04:06.8054261Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-12-04T11:04:06.8055434Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-12-04T11:04:06.8056317Z 	at java.base/java.lang.Thread.run(Thread.java:833)`

In log attached you can find the Test status:
Tests run: 76, Failures: 1, Errors: 0, Skipped: 5

Compare it with total test in report portal is 30 and those test with 429 error are not added in report portal.

**Screenshots**
<img width="1412" alt="Screenshot 2024-12-04 at 4 57 26 PM" src="https://github.com/user-attachments/assets/934ccaf4-e263-4ebf-8325-f4e0d09bda9f">

**Versions:**
 - using in maven Java project
 - Running via Github action with ubuntu latest runner
<img width="424" alt="image" src="https://github.com/user-attachments/assets/c0f37b5d-d328-4d9a-9858-a618bb3a7c9c">

Log:
[9_Run Tests.txt](https://github.com/user-attachments/files/18007343/9_Run.Tests.txt)

**Comment by Pink-Bumblebee** [comment]
In your file there are a lot of 
`2024-12-04T11:04:04.3086820Z 2024-12-04 11:04:04,303 | ERROR| [ io.nethermind.common.reporter.ExtentReportUtil ] -> Error while Logging Extent report with error: java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because "io.nethermind.common.reporter.ExtentReportUtil.test" is null` 
before 
`2024-12-04T11:04:04.3124689Z [rp-io-46] ERROR com.epam.reportportal.utils.SubscriptionUtils - Start test item completed with error ` 
followed by `2024-12-04T11:04:04.3125739Z retrofit2.adapter.rxjava2.HttpException: HTTP 429 `.

Error 429 - https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429. 
Please check your reporting sequence.

**Comment by HardNorth** [comment]
@shashankshampi Which ReportPortal instance do you use?

**Comment by HardNorth** [comment]
@shashankshampi Which kind of load balancer?
