### ISSUE TITLE
Error opening an attachment

### ISSUE THREAD

**Issue by arunapadhu85** [reportportal/reportportal#2443]
**Describe the bug**
When we try to open an attachment from UI (by clicking on "Open in new tab" or on attachment), the UI is unresponsive and show the following error in the console,
261.app.3cade61c.js:1 TypeError: Cannot set properties of null (setting 'onbeforeunload')
    at 261.app.3cade61c.js:1:403105
    at f (124.app.a6badd2f.js:1:3515055)
    at Generator.<anonymous> (124.app.a6badd2f.js:1:3516392)
    at Generator.next (124.app.a6badd2f.js:1:3515418)
    at j (124.app.a6badd2f.js:1:2734830)
    at l (124.app.a6badd2f.js:1:2735667)

**Expected behavior**
Expect to open the attachment

**Screenshots**
If applicable
![Uploading Screenshot 2024-12-16 at 5.15.22 AM.png…]()

**Versions:**
 - OS, Browser
 - Build: 5.11.0

**Comment by Pink-Bumblebee** [comment]
@arunapadhu85 , sorry, but your screenshot is not opening. Also please check do you have enough disk space at reportportal storage.

**Comment by arunapadhu85** [comment]
![Uploading Screenshot 2024-12-16 at 5.15.22 AM.png…]()

**Comment by alena-babrova** [comment]
Hello @arunapadhu85,

Is the issue still relevant for you? 
If yes, please provide more details, like attachment example, browser console log (what error occurs and what request is attempted to be executed if such), etc.

**Comment by alena-babrova** [comment]
Dear @arunapadhu85,

As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.
