### ISSUE TITLE
Service auto analyzer is not running

### ISSUE THREAD

**Issue by mnanse** [reportportal/reportportal#2445]
Hello,

Our QA team wants to enable auto analysis on several projects. Problem is the checkbox is grayed out but the service is running. So the question is, why is this service considered not to be running when it is?

![image](https://github.com/user-attachments/assets/009c3bc0-246b-4120-aa0d-4ceb68ceb151)

![image](https://github.com/user-attachments/assets/ef78144b-1714-41cf-8c00-95bd8fc67959)

I can see sometimes these errors in the logs:

- API Service

```
c.e.t.r.dao.custom.ElasticSearchClient   : Search error logs-reportportal-49 Terms: 
{
    "id": [
        251181,
        251182
    ]
}
 Message: Text '2024-12-04T11:09:26.760615855' could not be parsed, unparsed text found at index 26
```

- Analyzer service

```
2024-12-16 10:42:19,091 - ERROR - analyzerApp.suggestService - InvalidXMLError: message: Invalid XML provided for "ListObjectResult" - erroring tag <IsTruncated>. Message: 'NoneType' object has no attribute 'text'
--
Traceback (most recent call last):
File "/venv/lib/python3.10/site-packages/minio/parsers.py", line 101, in get_child_text
return self.element.find('s3:{}'.format(name), _XML_NS).text
AttributeError: 'NoneType' object has no attribute 'text'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/backend/./app/service/suggest_service.py", line 360, in suggest_items
_suggest_decision_maker_to_use = self.model_chooser.choose_model(
File "/backend/./app/commons/model_chooser.py", line 57, in choose_model
folders = self.object_saver.get_folder_objects(project_id, model_name_folder)
File "/backend/./app/commons/object_saving/object_saver.py", line 63, in get_folder_objects
return self.saving_strategy[self.binarystore_type]().get_folder_objects(
File "/backend/./app/commons/object_saving/minio_client.py", line 110, in get_folder_objects
for obj in self.minioClient.list_objects(project_id, prefix=folder):
File "/venv/lib/python3.10/site-packages/minio/api.py", line 2301, in _list_objects
objects, is_truncated, start_after = parse_list_objects(
File "/venv/lib/python3.10/site-packages/minio/parsers.py", line 273, in parse_list_objects
is_truncated = root.get_child_text('IsTruncated').lower() == 'true'
File "/venv/lib/python3.10/site-packages/minio/parsers.py", line 103, in get_child_text
raise InvalidXMLError(
minio.error.InvalidXMLError: InvalidXMLError: message: Invalid XML provided for "ListObjectResult" - erroring tag <IsTruncated>. Message: 'NoneType' object has no attribute 'text'
```

But I don't really understand them.

We are running ReportPortal 5.11.0 on AWS ECS. I tried to update to 5.12.0 as suggested in another issue (https://github.com/reportportal/reportportal/issues/2097) but it doesn't help.

I deployed another stack and I get the same issue so maybe it is related to our setup on AWS. If so, Can I know how the service status is checked ?

Thanks !

**Comment by HardNorth** [comment]
@mnanse Please try using version `5.13.0` which contains newer library versions.

**Comment by mnanse** [comment]
I'm trying to update to 5.13.0 but I keep getting errors for several services.

- Api service :
`
ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'unbindQueuesOnShutdown' defined in URL [jar:file:/usr/app/service-api-5.13.0-exec.jar!/BOOT-INF/classes!/com/epam/ta/reportportal/reporting/async/UnbindQueuesOnShutdown.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'reportingBindings' defined in class path resource [com/epam/ta/reportportal/reporting/async/config/ReportingTopologyConfiguration.class]: Unsatisfied dependency expressed through method 'reportingBindings' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'reportingQueues' defined in class path resource [com/epam/ta/reportportal/reporting/async/config/ReportingTopologyConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.util.List]: Factory method 'reportingQueues' threw exception; nested exception is org.springframework.amqp.AmqpIOException: java.io.IOException
`

- Analyzer service :

```
The analyzer has failed
invalid Amazon AWS host *********.s3.amazonaws.com

Traceback (most recent call last):
--
File "app/main.py", line 446, in <module>
threads = init_amqp(amqp_client)
^^^^^^^^^^^^^^^^^^^^^^
File "app/main.py", line 164, in init_amqp
_model_chooser = model_chooser.ModelChooser(APP_CONFIG, SEARCH_CONFIG)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/backend/app/commons/model_chooser.py", line 51, in __init__
self.object_saver = object_saving.create(self.app_config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/backend/app/commons/object_saving/__init__.py", line 22, in create
return ObjectSaver(app_config=app_config, project_id=project_id, path=path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/backend/app/commons/object_saving/object_saver.py", line 51, in __init__
self.storage = STORAGE_FACTORIES[app_config.binaryStoreType](app_config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/backend/app/commons/object_saving/object_saver.py", line 28, in create_minio_client
return MinioClient(app_config)
^^^^^^^^^^^^^^^^^^^^^^^
File "/backend/app/commons/object_saving/minio_client.py", line 40, in __init__
self.minio_client = Minio(
^^^^^^
File "/venv/lib64/python3.11/site-packages/minio/api.py", line 153, in __init__
self._base_url = BaseURL(
^^^^^^^^
File "/venv/lib64/python3.11/site-packages/minio/helpers.py", line 557, in __init__
self._aws_info, region_in_host = _get_aws_info(
^^^^^^^^^^^^^^
File "/venv/lib64/python3.11/site-packages/minio/helpers.py", line 460, in _get_aws_info
raise ValueError(f"invalid Amazon AWS host {host}")
ValueError: invalid Amazon AWS host *********.s3.amazonaws.com
```

I even got this exception for the Job service :
`
2024-12-17T10:46:04.622Z  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'indexerServiceClientImpl' defined in URL [jar:nested:/usr/app/service-jobs-5.13.0-exec.jar/!BOOT-INF/classes/!/com/epam/reportportal/analyzer/index/IndexerServiceClientImpl.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'managementTemplate' defined in class path resource [com/epam/reportportal/config/rabbit/AnalyzerRabbitMqConfiguration.class]: Failed to instantiate [com.epam.reportportal.analyzer.RabbitMqManagementClient]: Factory method 'managementTemplate' threw exception with message: java.net.ProtocolException: Invalid status line: "     "
`

To solve this, I had to put back old environment variables like `RP_AMQP_API_ADDRESS`

**Comment by HardNorth** [comment]
@mnanse Analyzer's error says it fails due to invalid AWS host name, I don't see what exactly wrong since you removed significant part, but it fails on these lines:
```python
    if not _AWS_S3_ENDPOINT_REGEX.match(host):
        raise ValueError(f"invalid Amazon AWS host {host}")
```
So your URL does not match this regex pattern:
`^(((bucket\.|accesspoint\.)vpce(-(?!_)[a-z_\d]+(?<!-)(?<!_))+\.s3\.)|((?!s3)(?!-)(?!_)[a-z_\d-]{1,63}(?<!-)(?<!_)\.)s3-control(-(?!_)[a-z_\d]+(?<!-)(?<!_))*\.|(s3(-(?!_)[a-z_\d]+(?<!-)(?<!_))*\.))((?!s3)(?!-)(?!_)[a-z_\d-]{1,63}(?<!-)(?<!_)\.)*amazonaws\.com(|\.cn)$`

Because of that I would recommend you double-check that you specified correct S3 parameters and copy-pasted whole S3 URL Amazon gave you.

**Comment by mnanse** [comment]
Hello,

I managed to solve most of the errors I encountered. But the `invalid Amazon AWS host` one is still blocking me. 

Before 5.13.0, I used to configure `MINIO_SHORT_HOST` environment variable with the value `reportportal.s3.eu-central-1.amazonaws.com`.

Since I updated to 5.13.0, when I configure the same value for the  `MINIO_SHORT_HOST` environment variable I get this error. The URL doesn't match the regex pattern, but why ? This is just the bucket regional domain name. I tried without the regional part and the result is the same.

Now, as I read the documentation of the analyzer repo https://github.com/reportportal/service-auto-analyzer, I found this variable :
```
ANALYZER_BINSTORE_BUCKETPREFIX

The prefix for buckets which will be transformed to project folder by appending Project ID, E.G. prj-2. 
It can contain root path, like: my-bucket/reportportal/prj-, then the service will operate in single bucket mode and will put everything to my-bucket bucket, under reportportal/prj-2 (for default project of default user) path.
```
So I tried the following configuration :

- MINIO_SHORT_HOST = s3.eu-central-1.amazonaws.com
- ANALYZER_BINSTORE_BUCKETPREFIX = reportportal/project-data/

I got the following error : `ValueError: invalid bucket name mybucket/project-data`
I tried with the example above (`my-bucket/reportportal/prj-`) but I got the same error.

If I just configure the name of my bucket in `ANALYZER_BINSTORE_BUCKETPREFIX`, report portal tries to create one bucket per project, which is not what I want (this is the multibucket architecture right ?).

So the question is, how am I supposed to configure the bucket ?

Here is the actual config :
```
{
  name  = "LOGGING_LEVEL"
  value = "debug"
},
{
  name  = "AMQP_EXCHANGE_NAME"
  value = "analyzer_default"
},
{
  name  = "AMQP_VIRTUAL_HOST"
  value = "analyzer"
},
{
  name  = "ES_PROJECT_INDEX_PREFIX"
  value = "rp_"
},
{
  name  = "MINIO_SHORT_HOST"
  value = "reportportal.s3.eu-central-1.amazonaws.com"
},
{
  name  = "ANALYZER_BINARYSTORE_MINIO_REGION"
  value = "eu-central-1"
},
{
  name  = "ANALYZER_BINARYSTORE_TYPE"
  value = "minio"
}
```

I aslo have `MINIO_ACCESS_KEY` and `MINIO_SECRET_KEY` configured as secrets.

**Comment by HardNorth** [comment]
@mnanse Yes, looks like there is a bug, if you specify bucket prefix longer than 2 parts it picks path as bucket name, that's definitely incorrect. Just specify "my-bucket/reportportal-" and this will work.
