### ISSUE TITLE
Migration Process Fails to Update the DB

### ISSUE THREAD

**Issue by EdennBar** [reportportal/reportportal#2449]
reportportal-analyzer-0                              0/1     Init:0/1           0                 4m3s
reportportal-analyzer-train-0                        0/1     PodInitializing    0                 4m1s
reportportal-api-5cff9466d-4h29p                     0/1     Running            1 (26s ago)       65s
reportportal-api-f7c67949b-sb4k6                     0/1     Running            2 (26s ago)       101s
reportportal-index-c8bbb668b-6vrst                   1/1     Running            0                 4m34s
reportportal-jobs-6778b9f6c8-6wfgs                   0/1     Running            2 (71s ago)       4m34s
reportportal-jobs-764cdb4db7-qtszd                   0/1     Error              1 (69s ago)       2m14s
reportportal-metrics-gatherer-649b658d78-46tkm       1/1     Running            0                 2d10h
reportportal-metrics-gatherer-796fcbddc5-88bcw       0/1     Init:0/1           0                 4m34s
reportportal-migrations-flqfd                        0/1     Completed          0                 4m33s
reportportal-minio-7d664c44b6-nm45w                  1/1     Running            0                 4m34s
reportportal-postgresql-0                            1/1     Running            0                 4m1s
reportportal-rabbitmq-0                              0/1     Running            0                 4m21s
reportportal-uat-64ccbf5b5c-gbcr7                    0/1     Error              1 (99s ago)       4m34s
reportportal-uat-6c6c96dfdd-72wdl                    0/1     Running            43 (74s ago)      2d10h
reportportal-ui-84855c9779-8kbqf                     1/1     Running            0                 4m34s

 .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::               (v2.7.18)

2024-12-19 08:14:38.191  INFO 1 --- [           main] c.e.reportportal.ServiceJobApplication   : Starting ServiceJobApplication using Java 21.0.4 on reportportal-jobs-764cdb4db7-qtszd with PID 1 (/usr/app/service-jobs-5.12.0-exec.jar started by root in /usr/app)
2024-12-19 08:14:38.199  INFO 1 --- [           main] c.e.reportportal.ServiceJobApplication   : No active profile set, falling back to 1 default profile: "default"
2024-12-19 08:15:01.586  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8686 (http)
2024-12-19 08:15:01.683  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-12-19 08:15:01.684  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.86]
2024-12-19 08:15:02.680  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/jobs]   : Initializing Spring embedded WebApplicationContext
2024-12-19 08:15:02.681  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 23877 ms
2024-12-19 08:15:04.489  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2024-12-19 08:15:06.978  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2024-12-19 08:15:17.481  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'indexerServiceClientImpl' defined in URL [jar:file:/usr/app/service-jobs-5.12.0-exec.jar!/BOOT-INF/classes!/com/epam/reportportal/analyzer/index/IndexerServiceClientImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'managementTemplate' defined in class path resource [com/epam/reportportal/config/rabbit/AnalyzerRabbitMqConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.epam.reportportal.analyzer.RabbitMqManagementClient]: Factory method 'managementTemplate' threw exception; nested exception is com.rabbitmq.http.client.HttpException: java.net.ConnectException
2024-12-19 08:15:17.484  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2024-12-19 08:15:17.489  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2024-12-19 08:15:17.580  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2024-12-19 08:15:17.782  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-12-19 08:15:18.079 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'indexerServiceClientImpl' defined in URL [jar:file:/usr/app/service-jobs-5.12.0-exec.jar!/BOOT-INF/classes!/com/epam/reportportal/analyzer/index/IndexerServiceClientImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'managementTemplate' defined in class path resource [com/epam/reportportal/config/rabbit/AnalyzerRabbitMqConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.epam.reportportal.analyzer.RabbitMqManagementClient]: Factory method 'managementTemplate' threw exception; nested exception is com.rabbitmq.http.client.HttpException: java.net.ConnectException
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:801) ~[spring-beans-5.3.31.jar!/:5.3.31]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:224) ~[spring-beans-5.3.31.jar!/:5.3.31]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.31.jar!/:5.3.31]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222) ~[spring-beans-5.3.31.jar!/:5.3.31]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.31.jar!/:5.3.31]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.31.jar!/:5.3.31]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.31.jar!/:5.3.31]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.31.jar!/:5.3.31]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.31.jar!/:5.3.31]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.31.jar!/:5.3.31]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.31.jar!/:5.3.31]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:929) ~[spring-context-5.3.31.jar!/:5.3.31]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:591) ~[spring-context-5.3.31.jar!/:5.3.31]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.18.jar!/:2.7.18]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[spring-boot-2.7.18.jar!/:2.7.18]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409) ~[spring-boot-2.7.18.jar!/:2.7.18]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.18.jar!/:2.7.18]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) ~[spring-boot-2.7.18.jar!/:2.7.18]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289) ~[spring-boot-2.7.18.jar!/:2.7.18]
	at com.epam.reportportal.ServiceJobApplication.main(ServiceJobApplication.java:28) ~[classes!/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[service-jobs-5.12.0-exec.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[service-jobs-5.12.0-exec.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[service-jobs-5.12.0-exec.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[service-jobs-5.12.0-exec.jar:na]
	
	
2024-12-19 08:11:10.624 GMT [84715] STATEMENT:  select user0_.id as id1_23_, user0_.active as active2_23_, user0_.attachment as attachme3_23_, user0_.attachment_thumbnail as attachme4_23_, user0_.email as email5_23_, user0_.external_id as external6_23_, user0_.full_name as full_nam7_23_, user0_.expired as expired8_23_, user0_.login as login9_23_, user0_.metadata as metadat10_23_, user0_.password as passwor11_23_, user0_.role as role12_23_, user0_.type as type13_23_, user0_.uuid as uuid14_23_ from public.users user0_ where user0_.login=$1
2024-12-19 08:17:54.812 GMT [85397] ERROR:  column user0_.active does not exist at character 30

$ k get sts
NAME                          READY   AGE
opensearch-cluster-master     1/1     3d
reportportal-analyzer         1/1     3d
reportportal-analyzer-train   1/1     3d
reportportal-postgresql       1/1     3d
reportportal-rabbitmq         0/1     3d
	

Everything works fine locally on the Docker Desktop cluster with Ingress enabled. 
However, when deploying to the AWS cluster, I encountered errors. The only change I made for AWS was setting ingress.enabled to false, as I have done in previous deployments (before the new release).

Thank you for your help. I look forward to your response! :)

**Comment by APiankouski** [comment]
Hello @EdennBar, can you run migration service 5.13.0
Required script to fix issue https://github.com/reportportal/migrations/blob/develop/migrations/90_add_user_fields.up.sql
It's strange that this column was added in 5.13.0 version, but I see that you have service 5.12.0

**Comment by EdennBar** [comment]
> Hello @EdennBar, can you run migration service 5.13.0 Required script to fix issue https://github.com/reportportal/migrations/blob/develop/migrations/90_add_user_fields.up.sql It's strange that this column was added in 5.13.0 version, but I see that you have service 5.12.0

It works, thanks for the quick response!
