### ISSUE TITLE
RP RC4 constantly crash during run automation test on certain test

### ISSUE THREAD

**Issue by KursLabIgor** [reportportal/reportportal#313]
ReportPortal exception was thrown.
11:28:18 System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
11:28:18    at ReportPortal.Shared.LaunchReporter.<>c.<Finish>b__6_1(TestReporter tn)
11:28:18    at System.Collections.Generic.List`1.ForEach(Action`1 action)
11:28:18    at ReportPortal.Shared.LaunchReporter.<>c__DisplayClass6_0.<<Finish>b__0>d.MoveNext()
11:28:18    --- End of inner exception stack trace ---
11:28:18    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
11:28:18    at System.Threading.Tasks.Task.Wait()
11:28:18    at ReportPortal.NUnitExtension.ReportPortalListener.FinishRun(XmlDocument xmlDoc)
11:28:18 ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
11:28:18    at ReportPortal.Shared.LaunchReporter.<>c.<Finish>b__6_1(TestReporter tn)
11:28:18    at System.Collections.Generic.List`1.ForEach(Action`1 action)
11:28:18    at ReportPortal.Shared.LaunchReporter.<>c__DisplayClass6_0.<<Finish>b__0>d.MoveNext()<---

**Comment by KursLabIgor** [comment]
Problem that after 5 retry of test RP crash with error above. We have nunit3 framework with custom retry mechanism. Seems like it is regression from RP 3.

**Comment by KursLabIgor** [comment]
Problem was in internal app which cause crash nunit as result RP also
