### ISSUE TITLE
Unexpected logouts sometime occurs

### ISSUE THREAD

**Issue by iKozzz** [reportportal/reportportal#34]
https://your.site.com/api/v1/mg2/launch?page.page=1&page.size=50&page.sort=start_time%2CDESC&tab.id=allCases
Status code 401

{error: "invalid_token", error_description: "1f7w7ldc-9cc1-49aa-8557-asdd1h9ac24f"}

Please leave a comment and clarify what exact logs should i attach in case you need them.

Another unexpected logout:
`scripts.d34776b3.js:1 Uncaught TypeError: Cannot read property 'clear' of null
    at i.setupRequestParamsForLevel (https://your.conpany.com/ui/compiled/js/scripts.d34776b3.js:1:2067429)
    at i.updateNavigationState (https://your.conpany.com/ui/compiled/js/scripts.d34776b3.js:1:2066846)
    at i.update (https://your.conpany.com/ui/compiled/js/scripts.d34776b3.js:1:2041047)
    at u (https://your.conpany.com/ui/compiled/js/scripts.d34776b3.js:1:2139663)
    at Object.openRouted (https://your.conpany.com/ui/compiled/js/scripts.d34776b3.js:1:2140049)
    at i.<anonymous> (https://your.conpany.com/ui/compiled/js/scripts.d34776b3.js:1:2251137)
    at Object.<anonymous> (https://your.conpany.com/ui/compiled/js/scripts.d34776b3.js:1:2248286)
    at l (https://your.conpany.com/ui/compiled/js/scripts.d34776b3.js:1:33984)
    at Object.add [as done] (https://your.conpany.com/ui/compiled/js/scripts.d34776b3.js:1:34298)
    at i.openLaunches (https://your.conpany.com/ui/compiled/js/scripts.d34776b3.js:1:2248268)`

**Comment by avarabyeu** [comment]
This is expected behavior. Tokens for UI represent user session which expires after some time. You can increase session live time by setting:

> - rp.session.live=1800 #in seconds

For the UAT service
