### ISSUE TITLE
Unable to connect ldap 4.0

### ISSUE THREAD

**Issue by tareqalayan** [reportportal/reportportal#371]
Hi guys, 

I am trying to connect my ldap to the reportportal. 
In the UI i don't see any error message or successful message (i think you should add more freindly messages beside the fast blue line on top )

when i try to connet i get a credential error. 
and when i look on logs i see 2018-03-19 11:55:53.477 ERROR 1 --- [nio-8080-exec-1] c.e.t.r.c.e.rest.RestExceptionHandler    : Handled error:
com.epam.ta.reportportal.exception.ReportPortalException: OAuth integration 'ldap' not found. Did you use correct name?
        at com.epam.reportportal.auth.endpoint.AuthConfigurationEndpoint.lambda$getSettings$0(AuthConfigurationEndpoint.java:104) ~[app.jar:4.0.0]
        at java.util.Optional.orElseThrow(Optional.java:290) ~[na:1.8.0_151]
        at com.epam.reportportal.auth.endpoint.AuthConfigurationEndpoint.getSettings(AuthConfigurationEndpoint.java:104) ~[app.jar:4.0.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
        at org.springframe

can you please advice?

**Comment by avarabyeu** [comment]
@tareqalayan could you please provide us with some screenshot of your auth configuration page?

**Comment by tareqalayan** [comment]
https://up1-vrutkovs.int.open.paas.redhat.com/#s_b6CuBDRQZdk2h7HjWvbA

@avarabyeu  thanks

**Comment by evjlobanova** [comment]
@tamasmartin could you please check your link?

**Comment by avarabyeu** [comment]
@tareqalayan unfortunately, this resource is blocked in our corporate network. I'll have a look later today from home

**Comment by tareqalayan** [comment]
@avarabyeu it will be also blocked from your home :) 

can you point me on what to test ?

**Comment by tareqalayan** [comment]
https://paste.fedoraproject.org/paste/MaKgDaB2nB7O1GRgaYLLqg @avarabyeu

**Comment by avarabyeu** [comment]
@evjlobanova plz add to 4.2 milestone

**Comment by grafuls** [comment]
Same here. I can see the logs from the AUT container being clogged with this exceptions every time I navigate to the authorization configuration page.
I can't see any logs on the API container when hitting submit neither.

**Comment by avarabyeu** [comment]
Fixing error message for now. Connection check on submit LDAP settings will be implemented as part of 5 release.
