### ISSUE TITLE
Error when throwing SkipException from BeforeClass method when using agent-java-testng

### ISSUE THREAD

**Issue by talgreen1** [reportportal/reportportal#393]
Hi,

When trying to throw skip exception from a BeforeClass method, there is an error in the Report Portal (See below).

We are using the Following:
TestNG Version: 6.11 (Happens also with 6.14.2)
Report Portal Version: 4.0.0
agent-java-testng version: 4.0.0

I’m attaching an example project - [skip.zip](https://github.com/reportportal/reportportal/files/1912408/skip.zip)

The stack trace is: 
`io.reactivex.exceptions.OnErrorNotImplementedException: Report Portal returned error
Status code: 406
Status message: Not Acceptable
Error Message: Finish test item is not allowed. Test item '5ad343722ab79c0001eb1646' has descendants with 'IN_PROGRESS' status. All descendants '[TestItemid='5ad343722ab79c0001eb1647', name='resetBrowser', type=BEFORE_METHOD, startTime=Sun Apr 15 12:20:02 UTC 2018, endTime=Sun Apr 15 12:20:02 UTC 2018, status=SKIPPED, tags=null, statistics=TestItemStatistics [executionCounter=TestItemExecutionCounter [total=0, passed=0, failed=0, skipped=0], issueCounter=IssueCounter [productBug=total=0, PB001=0, automationBug=AB001=0, total=0, systemIssue=total=0, SI001=0, toInvestigate=total=1, TI001=1, noDefect=ND001=0, total=0]], issue=TestItemIssueissueType='TI001', issueDescription='null', externalSystemIssues=null, autoAnalyzed=false, ignoreAnalyzer=false, path=[5ad343722ab79c0001eb1644, 5ad343722ab79c0001eb1646], parent='5ad343722ab79c0001eb1646', launchRef='5ad343722ab79c0001eb1643', hasChilds=false, itemDescription='', parameters=null, lastModified=Sun Apr 15 12:20:02 UTC 2018, uniqueId='auto:131b91f75aeb066f4ce664d4e7fa74f8', retries=null, TestItemid='5ad343722ab79c0001eb1648', name='beforeClass', type=BEFORE_CLASS, startTime=Sun Apr 15 12:20:02 UTC 2018, endTime=null, status=IN_PROGRESS, tags=null, statistics=TestItemStatistics [executionCounter=TestItemExecutionCounter [total=0, passed=0, failed=0, skipped=0], issueCounter=IssueCounter [productBug=total=0, PB001=0, automationBug=AB001=0, total=0, systemIssue=total=0, SI001=0, toInvestigate=total=0, TI001=0, noDefect=ND001=0, total=0]], issue=null, path=[5ad343722ab79c0001eb1644, 5ad343722ab79c0001eb1646], parent='5ad343722ab79c0001eb1646', launchRef='5ad343722ab79c0001eb1643', hasChilds=false, itemDescription='', parameters=null, lastModified=Sun Apr 15 12:20:02 UTC 2018, uniqueId='auto:d0c46eb09f5a59ef34fd29075ce317d5', retries=null, TestItemid='5ad343722ab79c0001eb1649', name='beforeClass', type=BEFORE_CLASS, startTime=Sun Apr 15 12:20:02 UTC 2018, endTime=Sun Apr 15 12:20:02 UTC 2018, status=SKIPPED, tags=null, statistics=TestItemStatistics [executionCounter=TestItemExecutionCounter [total=0, passed=0, failed=0, skipped=0], issueCounter=IssueCounter [productBug=total=0, PB001=0, automationBug=AB001=0, total=0, systemIssue=total=0, SI001=0, toInvestigate=total=1, TI001=1, noDefect=ND001=0, total=0]], issue=TestItemIssueissueType='TI001', issueDescription='null', externalSystemIssues=null, autoAnalyzed=false, ignoreAnalyzer=false, path=[5ad343722ab79c0001eb1644, 5ad343722ab79c0001eb1646], parent='5ad343722ab79c0001eb1646', launchRef='5ad343722ab79c0001eb1643', hasChilds=false, itemDescription='', parameters=null, lastModified=Sun Apr 15 12:20:02 UTC 2018, uniqueId='auto:d0c46eb09f5a59ef34fd29075ce317d5', retries=null, TestItemid='5ad343722ab79c0001eb164a', name='resetBrowser', type=BEFORE_METHOD, startTime=Sun Apr 15 12:20:02 UTC 2018, endTime=Sun Apr 15 12:20:02 UTC 2018, status=SKIPPED, tags=null, statistics=TestItemStatistics [executionCounter=TestItemExecutionCounter [total=0, passed=0, failed=0, skipped=0], issueCounter=IssueCounter [productBug=total=0, PB001=0, automationBug=AB001=0, total=0, systemIssue=total=0, SI001=0, toInvestigate=total=1, TI001=1, noDefect=ND001=0, total=0]], issue=TestItemIssueissueType='TI001', issueDescription='null', externalSystemIssues=null, autoAnalyzed=false, ignoreAnalyzer=false, path=[5ad343722ab79c0001eb1644, 5ad343722ab79c0001eb1646], parent='5ad343722ab79c0001eb1646', launchRef='5ad343722ab79c0001eb1643', hasChilds=false, itemDescription='', parameters=null, lastModified=Sun Apr 15 12:20:02 UTC 2018, uniqueId='auto:131b91f75aeb066f4ce664d4e7fa74f8', retries=null, TestItemid='5ad343722ab79c0001eb164b', name='test1', type=STEP, startTime=Sun Apr 15 12:20:02 UTC 2018, endTime=Sun Apr 15 12:20:02 UTC 2018, status=SKIPPED, tags=null, statistics=TestItemStatistics [executionCounter=TestItemExecutionCounter [total=1, passed=0, failed=0, skipped=1], issueCounter=IssueCounter [productBug=total=0, PB001=0, automationBug=AB001=0, total=0, systemIssue=total=0, SI001=0, toInvestigate=total=1, TI001=1, noDefect=ND001=0, total=0]], issue=TestItemIssueissueType='TI001', issueDescription='null', externalSystemIssues=null, autoAnalyzed=false, ignoreAnalyzer=false, path=[5ad343722ab79c0001eb1644, 5ad343722ab79c0001eb1646], parent='5ad343722ab79c0001eb1646', launchRef='5ad343722ab79c0001eb1643', hasChilds=false, itemDescription='', parameters=null, lastModified=Sun Apr 15 12:20:02 UTC 2018, uniqueId='auto:f9ab0e74ecbe3bd6d2d47ff161a3453d', retries=null, TestItemid='5ad343722ab79c0001eb164c', name='test2', type=STEP, startTime=Sun Apr 15 12:20:02 UTC 2018, endTime=Sun Apr 15 12:20:02 UTC 2018, status=SKIPPED, tags=null, statistics=TestItemStatistics [executionCounter=TestItemExecutionCounter [total=1, passed=0, failed=0, skipped=1], issueCounter=IssueCounter [productBug=total=0, PB001=0, automationBug=AB001=0, total=0, systemIssue=total=0, SI001=0, toInvestigate=total=1, TI001=1, noDefect=ND001=0, total=0]], issue=TestItemIssueissueType='TI001', issueDescription='null', externalSystemIssues=null, autoAnalyzed=false, ignoreAnalyzer=false, path=[5ad343722ab79c0001eb1644, 5ad343722ab79c0001eb1646], parent='5ad343722ab79c0001eb1646', launchRef='5ad343722ab79c0001eb1643', hasChilds=false, itemDescription='', parameters=null, lastModified=Sun Apr 15 12:20:02 UTC 2018, uniqueId='auto:2524f5a606b202af41bd3cbf01230560', retries=null]'
Error Type: FINISH_ITEM_NOT_ALLOWED

	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.operators.maybe.MaybeCallbackObserver.onError(MaybeCallbackObserver.java:83)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeOnMaybeObserver.onError(MaybeSubscribeOn.java:96)
	at io.reactivex.internal.operators.maybe.MaybeCache.onError(MaybeCache.java:103)
	at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:50)
	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77)
	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 406
Status message: Not Acceptable
Error Message: Finish test item is not allowed. Test item '5ad343722ab79c0001eb1646' has descendants with 'IN_PROGRESS' status. All descendants '[TestItemid='5ad343722ab79c0001eb1647', name='resetBrowser', type=BEFORE_METHOD, startTime=Sun Apr 15 12:20:02 UTC 2018, endTime=Sun Apr 15 12:20:02 UTC 2018, status=SKIPPED, tags=null, statistics=TestItemStatistics [executionCounter=TestItemExecutionCounter [total=0, passed=0, failed=0, skipped=0], issueCounter=IssueCounter [productBug=total=0, PB001=0, automationBug=AB001=0, total=0, systemIssue=total=0, SI001=0, toInvestigate=total=1, TI001=1, noDefect=ND001=0, total=0]], issue=TestItemIssueissueType='TI001', issueDescription='null', externalSystemIssues=null, autoAnalyzed=false, ignoreAnalyzer=false, path=[5ad343722ab79c0001eb1644, 5ad343722ab79c0001eb1646], parent='5ad343722ab79c0001eb1646', launchRef='5ad343722ab79c0001eb1643', hasChilds=false, itemDescription='', parameters=null, lastModified=Sun Apr 15 12:20:02 UTC 2018, uniqueId='auto:131b91f75aeb066f4ce664d4e7fa74f8', retries=null, TestItemid='5ad343722ab79c0001eb1648', name='beforeClass', type=BEFORE_CLASS, startTime=Sun Apr 15 12:20:02 UTC 2018, endTime=null, status=IN_PROGRESS, tags=null, statistics=TestItemStatistics [executionCounter=TestItemExecutionCounter [total=0, passed=0, failed=0, skipped=0], issueCounter=IssueCounter [productBug=total=0, PB001=0, automationBug=AB001=0, total=0, systemIssue=total=0, SI001=0, toInvestigate=total=0, TI001=0, noDefect=ND001=0, total=0]], issue=null, path=[5ad343722ab79c0001eb1644, 5ad343722ab79c0001eb1646], parent='5ad343722ab79c0001eb1646', launchRef='5ad343722ab79c0001eb1643', hasChilds=false, itemDescription='', parameters=null, lastModified=Sun Apr 15 12:20:02 UTC 2018, uniqueId='auto:d0c46eb09f5a59ef34fd29075ce317d5', retries=null, TestItemid='5ad343722ab79c0001eb1649', name='beforeClass', type=BEFORE_CLASS, startTime=Sun Apr 15 12:20:02 UTC 2018, endTime=Sun Apr 15 12:20:02 UTC 2018, status=SKIPPED, tags=null, statistics=TestItemStatistics [executionCounter=TestItemExecutionCounter [total=0, passed=0, failed=0, skipped=0], issueCounter=IssueCounter [productBug=total=0, PB001=0, automationBug=AB001=0, total=0, systemIssue=total=0, SI001=0, toInvestigate=total=1, TI001=1, noDefect=ND001=0, total=0]], issue=TestItemIssueissueType='TI001', issueDescription='null', externalSystemIssues=null, autoAnalyzed=false, ignoreAnalyzer=false, path=[5ad343722ab79c0001eb1644, 5ad343722ab79c0001eb1646], parent='5ad343722ab79c0001eb1646', launchRef='5ad343722ab79c0001eb1643', hasChilds=false, itemDescription='', parameters=null, lastModified=Sun Apr 15 12:20:02 UTC 2018, uniqueId='auto:d0c46eb09f5a59ef34fd29075ce317d5', retries=null, TestItemid='5ad343722ab79c0001eb164a', name='resetBrowser', type=BEFORE_METHOD, startTime=Sun Apr 15 12:20:02 UTC 2018, endTime=Sun Apr 15 12:20:02 UTC 2018, status=SKIPPED, tags=null, statistics=TestItemStatistics [executionCounter=TestItemExecutionCounter [total=0, passed=0, failed=0, skipped=0], issueCounter=IssueCounter [productBug=total=0, PB001=0, automationBug=AB001=0, total=0, systemIssue=total=0, SI001=0, toInvestigate=total=1, TI001=1, noDefect=ND001=0, total=0]], issue=TestItemIssueissueType='TI001', issueDescription='null', externalSystemIssues=null, autoAnalyzed=false, ignoreAnalyzer=false, path=[5ad343722ab79c0001eb1644, 5ad343722ab79c0001eb1646], parent='5ad343722ab79c0001eb1646', launchRef='5ad343722ab79c0001eb1643', hasChilds=false, itemDescription='', parameters=null, lastModified=Sun Apr 15 12:20:02 UTC 2018, uniqueId='auto:131b91f75aeb066f4ce664d4e7fa74f8', retries=null, TestItemid='5ad343722ab79c0001eb164b', name='test1', type=STEP, startTime=Sun Apr 15 12:20:02 UTC 2018, endTime=Sun Apr 15 12:20:02 UTC 2018, status=SKIPPED, tags=null, statistics=TestItemStatistics [executionCounter=TestItemExecutionCounter [total=1, passed=0, failed=0, skipped=1], issueCounter=IssueCounter [productBug=total=0, PB001=0, automationBug=AB001=0, total=0, systemIssue=total=0, SI001=0, toInvestigate=total=1, TI001=1, noDefect=ND001=0, total=0]], issue=TestItemIssueissueType='TI001', issueDescription='null', externalSystemIssues=null, autoAnalyzed=false, ignoreAnalyzer=false, path=[5ad343722ab79c0001eb1644, 5ad343722ab79c0001eb1646], parent='5ad343722ab79c0001eb1646', launchRef='5ad343722ab79c0001eb1643', hasChilds=false, itemDescription='', parameters=null, lastModified=Sun Apr 15 12:20:02 UTC 2018, uniqueId='auto:f9ab0e74ecbe3bd6d2d47ff161a3453d', retries=null, TestItemid='5ad343722ab79c0001eb164c', name='test2', type=STEP, startTime=Sun Apr 15 12:20:02 UTC 2018, endTime=Sun Apr 15 12:20:02 UTC 2018, status=SKIPPED, tags=null, statistics=TestItemStatistics [executionCounter=TestItemExecutionCounter [total=1, passed=0, failed=0, skipped=1], issueCounter=IssueCounter [productBug=total=0, PB001=0, automationBug=AB001=0, total=0, systemIssue=total=0, SI001=0, toInvestigate=total=1, TI001=1, noDefect=ND001=0, total=0]], issue=TestItemIssueissueType='TI001', issueDescription='null', externalSystemIssues=null, autoAnalyzed=false, ignoreAnalyzer=false, path=[5ad343722ab79c0001eb1644, 5ad343722ab79c0001eb1646], parent='5ad343722ab79c0001eb1646', launchRef='5ad343722ab79c0001eb1643', hasChilds=false, itemDescription='', parameters=null, lastModified=Sun Apr 15 12:20:02 UTC 2018, uniqueId='auto:2524f5a606b202af41bd3cbf01230560', retries=null]'
Error Type: FINISH_ITEM_NOT_ALLOWED

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:62)
	at com.epam.reportportal.restendpoint.http.DefaultErrorHandler.handle(DefaultErrorHandler.java:56)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.call(HttpClientRestEndpoint.java:486)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.call(HttpClientRestEndpoint.java:455)
	at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:46)
	... 13 more
Exception in thread "RxCachedThreadScheduler-9" io.reactivex.exceptions.OnErrorNotImplementedException: Report Portal returned error
Status code: 406
Status message: Not Acceptable
Error Message: Finish test item is not allowed. Test item '5ad343722ab79c0001eb1646' has descendants with 'IN_PROGRESS' status. All descendants '[TestItemid='5ad343722ab79c0001eb1647', name='resetBrowser', type=BEFORE_METHOD, startTime=Sun Apr 15 12:20:02 UTC 2018, endTime=Sun Apr 15 12:20:02 UTC 2018, status=SKIPPED, tags=null, statistics=TestItemStatistics [executionCounter=TestItemExecutionCounter [total=0, passed=0, failed=0, skipped=0], issueCounter=IssueCounter [productBug=total=0, PB001=0, automationBug=AB001=0, total=0, systemIssue=total=0, SI001=0, toInvestigate=total=1, TI001=1, noDefect=ND001=0, total=0]], issue=TestItemIssueissueType='TI001', issueDescription='null', externalSystemIssues=null, autoAnalyzed=false, ignoreAnalyzer=false, path=[5ad343722ab79c0001eb1644, 5ad343722ab79c0001eb1646], parent='5ad343722ab79c0001eb1646', launchRef='5ad343722ab79c0001eb1643', hasChilds=false, itemDescription='', parameters=null, lastModified=Sun Apr 15 12:20:02 UTC 2018, uniqueId='auto:131b91f75aeb066f4ce664d4e7fa74f8', retries=null, TestItemid='5ad343722ab79c0001eb1648', name='beforeClass', type=BEFORE_CLASS, startTime=Sun Apr 15 12:20:02 UTC 2018, endTime=null, status=IN_PROGRESS, tags=null, statistics=TestItemStatistics [executionCounter=TestItemExecutionCounter [total=0, passed=0, failed=0, skipped=0], issueCounter=IssueCounter [productBug=total=0, PB001=0, automationBug=AB001=0, total=0, systemIssue=total=0, SI001=0, toInvestigate=total=0, TI001=0, noDefect=ND001=0, total=0]], issue=null, path=[5ad343722ab79c0001eb1644, 5ad343722ab79c0001eb1646], parent='5ad343722ab79c0001eb1646', launchRef='5ad343722ab79c0001eb1643', hasChilds=false, itemDescription='', parameters=null, lastModified=Sun Apr 15 12:20:02 UTC 2018, uniqueId='auto:d0c46eb09f5a59ef34fd29075ce317d5', retries=null, TestItemid='5ad343722ab79c0001eb1649', name='beforeClass', type=BEFORE_CLASS, startTime=Sun Apr 15 12:20:02 UTC 2018, endTime=Sun Apr 15 12:20:02 UTC 2018, status=SKIPPED, tags=null, statistics=TestItemStatistics [executionCounter=TestItemExecutionCounter [total=0, passed=0, failed=0, skipped=0], issueCounter=IssueCounter [productBug=total=0, PB001=0, automationBug=AB001=0, total=0, systemIssue=total=0, SI001=0, toInvestigate=total=1, TI001=1, noDefect=ND001=0, total=0]], issue=TestItemIssueissueType='TI001', issueDescription='null', externalSystemIssues=null, autoAnalyzed=false, ignoreAnalyzer=false, path=[5ad343722ab79c0001eb1644, 5ad343722ab79c0001eb1646], parent='5ad343722ab79c0001eb1646', launchRef='5ad343722ab79c0001eb1643', hasChilds=false, itemDescription='', parameters=null, lastModified=Sun Apr 15 12:20:02 UTC 2018, uniqueId='auto:d0c46eb09f5a59ef34fd29075ce317d5', retries=null, TestItemid='5ad343722ab79c0001eb164a', name='resetBrowser', type=BEFORE_METHOD, startTime=Sun Apr 15 12:20:02 UTC 2018, endTime=Sun Apr 15 12:20:02 UTC 2018, status=SKIPPED, tags=null, statistics=TestItemStatistics [executionCounter=TestItemExecutionCounter [total=0, passed=0, failed=0, skipped=0], issueCounter=IssueCounter [productBug=total=0, PB001=0, automationBug=AB001=0, total=0, systemIssue=total=0, SI001=0, toInvestigate=total=1, TI001=1, noDefect=ND001=0, total=0]], issue=TestItemIssueissueType='TI001', issueDescription='null', externalSystemIssues=null, autoAnalyzed=false, ignoreAnalyzer=false, path=[5ad343722ab79c0001eb1644, 5ad343722ab79c0001eb1646], parent='5ad343722ab79c0001eb1646', launchRef='5ad343722ab79c0001eb1643', hasChilds=false, itemDescription='', parameters=null, lastModified=Sun Apr 15 12:20:02 UTC 2018, uniqueId='auto:131b91f75aeb066f4ce664d4e7fa74f8', retries=null, TestItemid='5ad343722ab79c0001eb164b', name='test1', type=STEP, startTime=Sun Apr 15 12:20:02 UTC 2018, endTime=Sun Apr 15 12:20:02 UTC 2018, status=SKIPPED, tags=null, statistics=TestItemStatistics [executionCounter=TestItemExecutionCounter [total=1, passed=0, failed=0, skipped=1], issueCounter=IssueCounter [productBug=total=0, PB001=0, automationBug=AB001=0, total=0, systemIssue=total=0, SI001=0, toInvestigate=total=1, TI001=1, noDefect=ND001=0, total=0]], issue=TestItemIssueissueType='TI001', issueDescription='null', externalSystemIssues=null, autoAnalyzed=false, ignoreAnalyzer=false, path=[5ad343722ab79c0001eb1644, 5ad343722ab79c0001eb1646], parent='5ad343722ab79c0001eb1646', launchRef='5ad343722ab79c0001eb1643', hasChilds=false, itemDescription='', parameters=null, lastModified=Sun Apr 15 12:20:02 UTC 2018, uniqueId='auto:f9ab0e74ecbe3bd6d2d47ff161a3453d', retries=null, TestItemid='5ad343722ab79c0001eb164c', name='test2', type=STEP, startTime=Sun Apr 15 12:20:02 UTC 2018, endTime=Sun Apr 15 12:20:02 UTC 2018, status=SKIPPED, tags=null, statistics=TestItemStatistics [executionCounter=TestItemExecutionCounter [total=1, passed=0, failed=0, skipped=1], issueCounter=IssueCounter [productBug=total=0, PB001=0, automationBug=AB001=0, total=0, systemIssue=total=0, SI001=0, toInvestigate=total=1, TI001=1, noDefect=ND001=0, total=0]], issue=TestItemIssueissueType='TI001', issueDescription='null', externalSystemIssues=null, autoAnalyzed=false, ignoreAnalyzer=false, path=[5ad343722ab79c0001eb1644, 5ad343722ab79c0001eb1646], parent='5ad343722ab79c0001eb1646', launchRef='5ad343722ab79c0001eb1643', hasChilds=false, itemDescription='', parameters=null, lastModified=Sun Apr 15 12:20:02 UTC 2018, uniqueId='auto:2524f5a606b202af41bd3cbf01230560', retries=null]'
Error Type: FINISH_ITEM_NOT_ALLOWED

	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.operators.maybe.MaybeCallbackObserver.onError(MaybeCallbackObserver.java:83)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeOnMaybeObserver.onError(MaybeSubscribeOn.java:96)
	at io.reactivex.internal.operators.maybe.MaybeCache.onError(MaybeCache.java:103)
	at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:50)
	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77)
	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 406
Status message: Not Acceptable
Error Message: Finish test item is not allowed. Test item '5ad343722ab79c0001eb1646' has descendants with 'IN_PROGRESS' status. All descendants '[TestItemid='5ad343722ab79c0001eb1647', name='resetBrowser', type=BEFORE_METHOD, startTime=Sun Apr 15 12:20:02 UTC 2018, endTime=Sun Apr 15 12:20:02 UTC 2018, status=SKIPPED, tags=null, statistics=TestItemStatistics [executionCounter=TestItemExecutionCounter [total=0, passed=0, failed=0, skipped=0], issueCounter=IssueCounter [productBug=total=0, PB001=0, automationBug=AB001=0, total=0, systemIssue=total=0, SI001=0, toInvestigate=total=1, TI001=1, noDefect=ND001=0, total=0]], issue=TestItemIssueissueType='TI001', issueDescription='null', externalSystemIssues=null, autoAnalyzed=false, ignoreAnalyzer=false, path=[5ad343722ab79c0001eb1644, 5ad343722ab79c0001eb1646], parent='5ad343722ab79c0001eb1646', launchRef='5ad343722ab79c0001eb1643', hasChilds=false, itemDescription='', parameters=null, lastModified=Sun Apr 15 12:20:02 UTC 2018, uniqueId='auto:131b91f75aeb066f4ce664d4e7fa74f8', retries=null, TestItemid='5ad343722ab79c0001eb1648', name='beforeClass', type=BEFORE_CLASS, startTime=Sun Apr 15 12:20:02 UTC 2018, endTime=null, status=IN_PROGRESS, tags=null, statistics=TestItemStatistics [executionCounter=TestItemExecutionCounter [total=0, passed=0, failed=0, skipped=0], issueCounter=IssueCounter [productBug=total=0, PB001=0, automationBug=AB001=0, total=0, systemIssue=total=0, SI001=0, toInvestigate=total=0, TI001=0, noDefect=ND001=0, total=0]], issue=null, path=[5ad343722ab79c0001eb1644, 5ad343722ab79c0001eb1646], parent='5ad343722ab79c0001eb1646', launchRef='5ad343722ab79c0001eb1643', hasChilds=false, itemDescription='', parameters=null, lastModified=Sun Apr 15 12:20:02 UTC 2018, uniqueId='auto:d0c46eb09f5a59ef34fd29075ce317d5', retries=null, TestItemid='5ad343722ab79c0001eb1649', name='beforeClass', type=BEFORE_CLASS, startTime=Sun Apr 15 12:20:02 UTC 2018, endTime=Sun Apr 15 12:20:02 UTC 2018, status=SKIPPED, tags=null, statistics=TestItemStatistics [executionCounter=TestItemExecutionCounter [total=0, passed=0, failed=0, skipped=0], issueCounter=IssueCounter [productBug=total=0, PB001=0, automationBug=AB001=0, total=0, systemIssue=total=0, SI001=0, toInvestigate=total=1, TI001=1, noDefect=ND001=0, total=0]], issue=TestItemIssueissueType='TI001', issueDescription='null', externalSystemIssues=null, autoAnalyzed=false, ignoreAnalyzer=false, path=[5ad343722ab79c0001eb1644, 5ad343722ab79c0001eb1646], parent='5ad343722ab79c0001eb1646', launchRef='5ad343722ab79c0001eb1643', hasChilds=false, itemDescription='', parameters=null, lastModified=Sun Apr 15 12:20:02 UTC 2018, uniqueId='auto:d0c46eb09f5a59ef34fd29075ce317d5', retries=null, TestItemid='5ad343722ab79c0001eb164a', name='resetBrowser', type=BEFORE_METHOD, startTime=Sun Apr 15 12:20:02 UTC 2018, endTime=Sun Apr 15 12:20:02 UTC 2018, status=SKIPPED, tags=null, statistics=TestItemStatistics [executionCounter=TestItemExecutionCounter [total=0, passed=0, failed=0, skipped=0], issueCounter=IssueCounter [productBug=total=0, PB001=0, automationBug=AB001=0, total=0, systemIssue=total=0, SI001=0, toInvestigate=total=1, TI001=1, noDefect=ND001=0, total=0]], issue=TestItemIssueissueType='TI001', issueDescription='null', externalSystemIssues=null, autoAnalyzed=false, ignoreAnalyzer=false, path=[5ad343722ab79c0001eb1644, 5ad343722ab79c0001eb1646], parent='5ad343722ab79c0001eb1646', launchRef='5ad343722ab79c0001eb1643', hasChilds=false, itemDescription='', parameters=null, lastModified=Sun Apr 15 12:20:02 UTC 2018, uniqueId='auto:131b91f75aeb066f4ce664d4e7fa74f8', retries=null, TestItemid='5ad343722ab79c0001eb164b', name='test1', type=STEP, startTime=Sun Apr 15 12:20:02 UTC 2018, endTime=Sun Apr 15 12:20:02 UTC 2018, status=SKIPPED, tags=null, statistics=TestItemStatistics [executionCounter=TestItemExecutionCounter [total=1, passed=0, failed=0, skipped=1], issueCounter=IssueCounter [productBug=total=0, PB001=0, automationBug=AB001=0, total=0, systemIssue=total=0, SI001=0, toInvestigate=total=1, TI001=1, noDefect=ND001=0, total=0]], issue=TestItemIssueissueType='TI001', issueDescription='null', externalSystemIssues=null, autoAnalyzed=false, ignoreAnalyzer=false, path=[5ad343722ab79c0001eb1644, 5ad343722ab79c0001eb1646], parent='5ad343722ab79c0001eb1646', launchRef='5ad343722ab79c0001eb1643', hasChilds=false, itemDescription='', parameters=null, lastModified=Sun Apr 15 12:20:02 UTC 2018, uniqueId='auto:f9ab0e74ecbe3bd6d2d47ff161a3453d', retries=null, TestItemid='5ad343722ab79c0001eb164c', name='test2', type=STEP, startTime=Sun Apr 15 12:20:02 UTC 2018, endTime=Sun Apr 15 12:20:02 UTC 2018, status=SKIPPED, tags=null, statistics=TestItemStatistics [executionCounter=TestItemExecutionCounter [total=1, passed=0, failed=0, skipped=1], issueCounter=IssueCounter [productBug=total=0, PB001=0, automationBug=AB001=0, total=0, systemIssue=total=0, SI001=0, toInvestigate=total=1, TI001=1, noDefect=ND001=0, total=0]], issue=TestItemIssueissueType='TI001', issueDescription='null', externalSystemIssues=null, autoAnalyzed=false, ignoreAnalyzer=false, path=[5ad343722ab79c0001eb1644, 5ad343722ab79c0001eb1646], parent='5ad343722ab79c0001eb1646', launchRef='5ad343722ab79c0001eb1643', hasChilds=false, itemDescription='', parameters=null, lastModified=Sun Apr 15 12:20:02 UTC 2018, uniqueId='auto:2524f5a606b202af41bd3cbf01230560', retries=null]'
Error Type: FINISH_ITEM_NOT_ALLOWED

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:62)
	at com.epam.reportportal.restendpoint.http.DefaultErrorHandler.handle(DefaultErrorHandler.java:56)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.call(HttpClientRestEndpoint.java:486)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.call(HttpClientRestEndpoint.java:455)
	at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:46)
	... 13 more 

`

**Comment by pbortnik** [comment]
@talgreen1 try to use the latest 4.0.2 version of testng agent

**Comment by talgreen1** [comment]
@pbortnik , @evjlobanova Hi - any update on this one?

**Comment by rajkumar-cp** [comment]
+1 We were also facing the same type of issue.

pom Libraray:-
			<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>client-java</artifactId>
			<version>4.0.8</version>
		</dependency>
	   <dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>agent-java-testng</artifactId>
			<version>4.2.0</version>
		</dependency>
			<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>logger-java-log4j</artifactId>
			<version>4.0.1</version>
		</dependency>
Error Message:-
Oct 04, 2019 12:51:58 PM com.epam.reportportal.service.LoggingCallback$2 accept
SEVERE: [48] ReportPortal execution error
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 406
Status message: Not Acceptable
Error Message: Finish test item is not allowed. Test item '5d95d893b9d82100017e70cd' has descendants with 'IN_PROGRESS' status. All descendants abc
Error Type: FINISH_ITEM_NOT_ALLOWED

Please let us know if there are any updates on this issue.
