### ISSUE TITLE
Cannot send file to ReportPortal

### ISSUE THREAD

**Issue by ampc** [reportportal/reportportal#493]
**Describe the bug**
Every test returns the following error:

```java
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - GET /session/083f8bcb-99a9-4238-8ef2-20dc896e105e/log/types did not match a known command
[main] ERROR com.epam.reportportal.service.ReportPortal - Cannot send file to ReportPortal
java.lang.NullPointerException
        at com.epam.reportportal.service.ReportPortal$3.apply(ReportPortal.java:211)
        at com.epam.reportportal.service.ReportPortal$3.apply(ReportPortal.java:200)
        at com.epam.reportportal.service.LoggingContext$4.apply(LoggingContext.java:163)
        at com.epam.reportportal.service.LoggingContext$4.apply(LoggingContext.java:160)
        at io.reactivex.internal.operators.maybe.MaybeMap$MapMaybeObserver.onSuccess(MaybeMap.java:82)
        at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:66)
        at io.reactivex.Maybe.subscribe(Maybe.java:3727)
        at io.reactivex.internal.operators.maybe.MaybeMap.subscribeActual(MaybeMap.java:40)
        at io.reactivex.Maybe.subscribe(Maybe.java:3727)
        at io.reactivex.internal.operators.maybe.MaybeToFlowable.subscribeActual(MaybeToFlowable.java:45)
        at io.reactivex.Flowable.subscribe(Flowable.java:13041)
        at io.reactivex.Flowable.subscribe(Flowable.java:12987)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.drain(FlowableOnBackpressureBuffer.java:187)
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.onNext(FlowableOnBackpressureBuffer.java:112)
        at io.reactivex.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.onNext(FlowableFromObservable.java:52)
        at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:264)
        at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:183)
        at com.epam.reportportal.service.LoggingContext.emit(LoggingContext.java:160)
        at com.epam.reportportal.service.ReportPortal.emitLog(ReportPortal.java:148)
        at com.epam.reportportal.service.ReportPortal.emitLog(ReportPortal.java:200)
        at com.github.invictum.reportportal.StepDataExtractorsHolder.lambda$null$0(StepDataExtractorsHolder.java:27)
        at java.util.Collections$SingletonSet.forEach(Collections.java:4767)
        at com.github.invictum.reportportal.StepDataExtractorsHolder.lambda$proceed$1(StepDataExtractorsHolder.java:27)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at com.github.invictum.reportportal.StepDataExtractorsHolder.proceed(StepDataExtractorsHolder.java:25)
        at com.github.invictum.reportportal.handler.FlatHandler.lambda$finishTest$1(FlatHandler.java:92)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.github.invictum.reportportal.handler.FlatHandler.finishTest(FlatHandler.java:92)
        at com.github.invictum.reportportal.ReportPortalListener.testFinished(ReportPortalListener.java:51)
        at net.thucydides.core.steps.StepEventBus.testFinished(StepEventBus.java:297)
        at net.thucydides.junit.listeners.JUnitStepListener.testFinished(JUnitStepListener.java:98)
        at org.junit.runner.notification.SynchronizedRunListener.testFinished(SynchronizedRunListener.java:56)
        at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:190)
        at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
        at org.junit.runner.notification.RunNotifier.fireTestFinished(RunNotifier.java:187)
        at org.junit.internal.runners.model.EachTestNotifier.fireTestFinished(EachTestNotifier.java:38)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:331)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:460)
        at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:435)
        at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:42)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:239)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - 
```
**reportportal.properties**
```
rp.endpoint = http://localhost:8080
rp.uuid = 5853034d-62f9-4de6-926a-a0918ee612a2
rp.launch = Create_Users
rp.project = Create_Users
```

pom.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>qa.tests.createusers</groupId>
    <artifactId>qa.tests.createusers</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <serenity.version>1.9.28</serenity.version>
        <serenity.maven.version>1.9.28</serenity.maven.version>
        <junit.version>4.12</junit.version>
        <slf4j.version>1.7.25</slf4j.version>
        <maven.failsafe.plugin.version>2.18</maven.failsafe.plugin.version>
        <maven.compiler.plugin.version>3.2</maven.compiler.plugin.version>
        <java.version>1.8</java.version>
        <aspectj.version>1.9.0</aspectj.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <repositories>
        <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>bintray-epam-reportportal</id>
            <name>bintray</name>
            <url>http://dl.bintray.com/epam/reportportal</url>
        </repository>
    </repositories>
    <dependencies>
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-junit4</artifactId>
            <version>2.6.0</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-rest-assured</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.javafaker</groupId>
            <artifactId>javafaker</artifactId>
            <version>0.14</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-jdbc</artifactId>
            <version>5.0.4.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.oracle</groupId>
            <artifactId>ojdbc8</artifactId>
            <version>12.2.0.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-configuration2</artifactId>
            <version>2.3</version>
        </dependency>
        <dependency>
            <groupId>com.github.invictum</groupId>
            <artifactId>serenity-reportportal-integration</artifactId>
            <version>1.2.0</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>${maven.failsafe.plugin.version}</version>
                <configuration>
                    <includes>
                        <include>**/*.java</include>
                    </includes>
                    <argLine>
                        -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                    </argLine>
                    <properties>
                        <property>
                            <name>listener</name>
                            <value>io.qameta.allure.junit4.AllureJunit4</value>
                        </property>
                    </properties>
                    <systemProperties>
                        <property>
                            <name>allure.results.directory</name>
                            <value>${project.build.directory}/allure-results</value>
                        </property>
                    </systemProperties>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjweaver</artifactId>
                        <version>${aspectj.version}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>io.qameta.allure</groupId>
                <artifactId>allure-maven</artifactId>
                <version>2.9</version>
                <executions>
                    <execution>
                        <id>allure-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.7.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.maven.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-core</artifactId>
                        <version>${serenity.version}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

**Expected behavior**
Run test without errors

**Versions:**
 - OS, Browser
 - Version of RP [
Current version: `API Service: 4.2.1; Index Service: 4.2.0; Jira Service: 4.2.0; Authorization Service: 4.2.0; Service UI: 4.2.2;`

**Comment by DzmitryHumianiuk** [comment]
@revaultch could you plz take a look

**Comment by avarabyeu** [comment]
remove allure from classpath :)

**Comment by DzmitryHumianiuk** [comment]
@ampc still actual?
