### ISSUE TITLE
email notification

### ISSUE THREAD

**Issue by Moshik177** [reportportal/reportportal#525]
Hi , 

i try to get notification mail after running build from the Jenkins , i configure the server details and the notification on project , but nothing is happening , i am running the test from the Jenkins and i am seeing the report on the website but no notification was sent from report portal , thanks!

**Comment by DzmitryHumianiuk** [comment]
@Moshik177 

**1st.** check if email server configured in administration panel. http://reportportal.io/docs/Configuration-of-Report%3Eemail-server-configuration

**2nd.** RP will not send email, if launch not finished. And you see it on UI with running dots.
That means that your execution was not finalized by your process. Due to fail, or due to un-finished test cases in run.

**Comment by Moshik177** [comment]
all the launches were finished without the dots.. and i am configure the smtp server and i checked from the report portal address that i am getting to the smtp on the relevant port

**Comment by DzmitryHumianiuk** [comment]
@Moshik177 dot's means that launches are still **in progress**.
You should find in logs message from report portal, similar to this:

`
{
   "error_code":40023, 
   "message":"Finish launch is not allowed. Launch '5bcf54392ab79c00010b71fb' has items '[5bcf54d52ab79c00010b7305,5bcf54d62ab79c00010b7306]' with 'IN_PROGRESS' status"
}
`

that means that you test cases are still running. at the moment, when executor try to finish execution.
take a look into those test case, find the reason why it not finalized on time.

btw, which framework/runner you use for you test cases?

**Comment by Moshik177** [comment]
i see the debug rp logs 
for example.. 18:25:57.879 DEBUG c.e.r.s.Launch - rp-io-6 - TestItem with ID = '5be1c0663cdea20001cdfe53' successfully finished. 
i am using testNG framework

**Comment by DzmitryHumianiuk** [comment]
@Moshik177 
find the same like { "error_code":40023, in logs
find which items it returns,
find log for those items

**Comment by Moshik177** [comment]
i can see this errors(below), after adding the debug rp logs at the beginning of the test, i will try to fix them , but i didn't see any "error_code":40023


18:25:00,018 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
18:25:00,018 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
18:25:00,018 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/C:/Users/moshik.kalash/moshiksRepo/ezbob-automation-infra/ezbob-automation-infrastructure/target/classes/logback.xml]
18:25:00,139 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
18:25:00,149 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
18:25:00,169 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
18:25:00,179 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
18:25:00,280 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [com.epam.reportportal.logback.appender.ReportPortalAppender]
18:25:00,280 |-ERROR in ch.qos.logback.core.joran.action.AppenderAction - Could not create an Appender of type [com.epam.reportportal.logback.appender.ReportPortalAppender]. ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type com.epam.reportportal.logback.appender.ReportPortalAppender
	at ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type com.epam.reportportal.logback.appender.ReportPortalAppender
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:69)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:45)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:34)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:52)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:269)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:145)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:128)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at 	at com.epam.reportportal.testng.BaseTestNGListener.<clinit>(BaseTestNGListener.java:38)
	at 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at 	at java.lang.Class.newInstance(Class.java:442)
	at 	at org.testng.internal.ClassHelper.newInstance(ClassHelper.java:69)
	at 	at org.testng.internal.DefaultListenerFactory.createListener(DefaultListenerFactory.java:13)
	at 	at org.testng.TestRunner.initListeners(TestRunner.java:315)
	at 	at org.testng.TestRunner.init(TestRunner.java:274)
	at 	at org.testng.TestRunner.init(TestRunner.java:241)
	at 	at org.testng.TestRunner.<init>(TestRunner.java:167)
	at 	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:663)
	at 	at org.testng.SuiteRunner.init(SuiteRunner.java:260)
	at 	at org.testng.SuiteRunner.<init>(SuiteRunner.java:198)
	at 	at org.testng.TestNG.createSuiteRunner(TestNG.java:1271)
	at 	at org.testng.TestNG.createSuiteRunners(TestNG.java:1249)
	at 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1107)
	at 	at org.testng.TestNG.runSuites(TestNG.java:1028)
	at 	at org.testng.TestNG.run(TestNG.java:996)
	at 	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at 	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.lang.ClassNotFoundException: com.epam.reportportal.logback.appender.ReportPortalAppender
	at 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:56)
	at 	... 42 common frames omitted
18:25:00,280 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@12:91 - ActionException in Action for tag [appender] ch.qos.logback.core.joran.spi.ActionException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type com.epam.reportportal.logback.appender.ReportPortalAppender
	at ch.qos.logback.core.joran.spi.ActionException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type com.epam.reportportal.logback.appender.ReportPortalAppender
	at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:76)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:269)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:145)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:128)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at 	at com.epam.reportportal.testng.BaseTestNGListener.<clinit>(BaseTestNGListener.java:38)
	at 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at 	at java.lang.Class.newInstance(Class.java:442)
	at 	at org.testng.internal.ClassHelper.newInstance(ClassHelper.java:69)
	at 	at org.testng.internal.DefaultListenerFactory.createListener(DefaultListenerFactory.java:13)
	at 	at org.testng.TestRunner.initListeners(TestRunner.java:315)
	at 	at org.testng.TestRunner.init(TestRunner.java:274)
	at 	at org.testng.TestRunner.init(TestRunner.java:241)
	at 	at org.testng.TestRunner.<init>(TestRunner.java:167)
	at 	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:663)
	at 	at org.testng.SuiteRunner.init(SuiteRunner.java:260)
	at 	at org.testng.SuiteRunner.<init>(SuiteRunner.java:198)
	at 	at org.testng.TestNG.createSuiteRunner(TestNG.java:1271)
	at 	at org.testng.TestNG.createSuiteRunners(TestNG.java:1249)
	at 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1107)
	at 	at org.testng.TestNG.runSuites(TestNG.java:1028)
	at 	at org.testng.TestNG.run(TestNG.java:996)
	at 	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at 	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type com.epam.reportportal.logback.appender.ReportPortalAppender
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:69)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:45)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:34)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:52)
	at 	... 39 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.epam.reportportal.logback.appender.ReportPortalAppender
	at 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:56)
	at 	... 42 common frames omitted
18:25:00,280 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [binary_data_logger] to TRACE
18:25:00,280 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [binary_data_logger] to false
18:25:00,280 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - Could not find an appender named [RP]. Did you define it below instead of above in the configuration file?
18:25:00,280 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - See http://logback.qos.ch/codes.html#appender_order for more details.
18:25:00,280 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
18:25:00,280 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - Could not find an appender named [RP]. Did you define it below instead of above in the configuration file?
18:25:00,280 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - See http://logback.qos.ch/codes.html#appender_order for more details.
18:25:00,280 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
18:25:00,280 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
18:25:00,280 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@4b53f538 - Registering current configuration as safe fallback point

18:25:02.376 INFO  c.e.r.s.Launch - main - Not rerun!

**Comment by Moshik177** [comment]
i add the logger-java-logback dependency and the errors gone , but i still don't get the mail , can you advise?

**Comment by DzmitryHumianiuk** [comment]
@Moshik177 stack trace above is all about missing logback libs.

try to find in logs:
`Finish launch is not allowed. Launch `
`Finish test item is not allowed. Test item`

**Comment by Moshik177** [comment]
i dont have finish launch.. 
at the end of the run i get

13:59:38.671 [main] INFO  TestRunner:60  - --------------------------------------------------Test: wizardSanityTest finished successfully.--------------------------------------------------
13:59:38.687 DEBUG c.e.r.s.Launch - rp-io-38 - TestItem with ID = '5be425083cdea20001ce3582' successfully finished.
13:59:38.687 DEBUG c.e.r.u.SubscriptionUtils - rp-io-38 - Finish test item completed
13:59:38.748 [main] INFO  TestRunnerUI:64  - ======================================TestRunnerUI is stopping.======================================
13:59:38.748 [main] INFO  TestRunnerUI:66  - Quitting browser.
13:59:38.750 DEBUG c.e.r.s.Launch - rp-io-23 - TestItem with ID = '5be424b13cdea20001ce2cde' successfully finished.
13:59:38.750 DEBUG c.e.r.u.SubscriptionUtils - rp-io-23 - Finish test item completed
13:59:38.758 DEBUG c.e.r.s.Launch - rp-io-19 - TestItem with ID = '5be424ad3cdea20001ce2cdd' successfully finished.
13:59:38.758 DEBUG c.e.r.u.SubscriptionUtils - rp-io-19 - Finish test item completed
13:59:39.345 [main] INFO  WebDriverKiller:46  - -----------------------------------Killing all running webdriver processes-----------------------------------
13:59:39.345 [main] INFO  WebDriverKiller:49  - **** WEBDRIVER PROCESS KILLER ****
13:59:39.514 [main] INFO  WebDriverKiller:59  - chromedriver.exe is NOT running.
13:59:39.674 [main] INFO  WebDriverKiller:59  - geckodriver.exe is NOT running.
13:59:39.840 [main] INFO  WebDriverKiller:59  - MicrosoftWebDriver.exe is NOT running.
13:59:40.006 [main] INFO  WebDriverKiller:59  - IEDriverServer.exe is NOT running.
13:59:40.177 [main] INFO  WebDriverKiller:59  - phantomjs.exe is NOT running.
13:59:40.177 [main] INFO  WebDriverKiller:65  - -------------------------------------------------------------------------------------------------------------
13:59:40.177 [main] INFO  TestRunnerUI:73  - =====================================================================================================
13:59:40.250 DEBUG c.e.r.s.Launch - rp-io-46 - Launch with ID = '5be424ad3cdea20001ce2cdb' successfully

**Comment by Moshik177** [comment]
i am also send test mail with my smtp server from the reportportal server (like the reportportal need to do just without the data) and it went well so it something on the configuration on the reportportal or on my project , what i must have to send a mail ... tell me

**Comment by DzmitryHumianiuk** [comment]
RP send mail notification only for launches which finished correctly.

If you launches stays with running dots on UI, then these launches are not finished.
you have to find why your launch are not finalized properly.

try to drill down via launch structure, and find which suite is still running. which class and which test is still IN_PROGRESS state.
review the logs of it.

**Comment by Moshik177** [comment]
![image](https://user-images.githubusercontent.com/11841608/48209577-33d85480-e37e-11e8-920a-3f02eda34381.png)

there is not launch that are not finish , it's something else

**Comment by DzmitryHumianiuk** [comment]
@Moshik177 ok. looks like you launches completed correctly.

Just to double check. 
You have correct configuration at `Administrate`->`server settings`->`E-mail server`?

**Comment by Moshik177** [comment]
yes,  i config the smtp mail server of the organization , (i am getting mails from the Jenkins with this smtp mail so it's not the issue) and i also send echo mail test from the report portal server through smtp mail , maybe i need to configure something else i don't know  (beside the mail server and the notification) , maybe you can clarify

**Comment by DzmitryHumianiuk** [comment]
@Moshik177 let's see what we have in response from server.

Open **server config page**
![image](https://user-images.githubusercontent.com/11332788/48625159-7540b380-e9bf-11e8-9f84-480b91535def.png)

Open browser console. Open Network tab
![image](https://user-images.githubusercontent.com/11332788/48625189-97d2cc80-e9bf-11e8-9179-928bebb65568.png)

Add config and click **Submit**
see what is in `email` reply 
![image](https://user-images.githubusercontent.com/11332788/48625221-aae59c80-e9bf-11e8-994b-666c416a29ac.png)


**also try to 'play' with TLS/SSL** (on/off)

![image](https://user-images.githubusercontent.com/11332788/48625367-0d3e9d00-e9c0-11e8-85ef-434579111429.png)
