### ISSUE TITLE
ReportPortalExсeption status: 406 Error Type: FINISH_TIME_EARLIER_THAN_START_TIME

### ISSUE THREAD

**Issue by Zakaryan92** [reportportal/reportportal#544]
Error Message: Finish time 'Thu Jan 01 00:00:00 UTC 1970' is earlier than start time 'Tue Dec 25 12:36:55 UTC 2018' for resource with ID '5c2225bfbfe5230001e4a049'
Error Type: FINISH_TIME_EARLIER_THAN_START_TIME

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:83)
	at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:59)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:517)
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
	at io.reactivex.Maybe.subscribe(Maybe.java:4096)
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77)
	at io.reactivex.Maybe.subscribe(Maybe.java:4096)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Zakaryan92** [comment]
<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>agent-java-testng</artifactId>
			<version>4.2.1-BETA</version>			
		</dependency>
		<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>logger-java-logback</artifactId>
			<version>4.0.0</version>
		</dependency>
		<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>logger-java-log4j</artifactId>
			<version>4.0.1</version>
		</dependency>

**Comment by Zakaryan92** [comment]
>  <dependency>
	<groupId>com.epam.reportportal</groupId>
	<artifactId>agent-java-testng</artifactId>
	<version>4.2.1-BETA</version>

**Comment by Zakaryan92** [comment]
@nvborisenko can you view this?

**Comment by nvborisenko** [comment]
I am from .net world. @Zakaryan92 I suggest to provide more details like:
how you execute tests
is this issue reproducible always
try to prepare small test project to reproduce the issue

**Comment by Zakaryan92** [comment]
Thanks for responding, it was a our project issue. @nvborisenko

**Comment by Rea2** [comment]
Hi. I faced the similar problem

**Comment by Rea2** [comment]
Hi. I faced a similar error.   In my case, it looks like report portal doesn't allow to have previous_step finsih_time = current_step start_time. Is it bag of feature?
