### ISSUE TITLE
Connection Refused error

### ISSUE THREAD

**Issue by bawarim** [reportportal/reportportal#546]
Hi,

I have integrated my cucumber test framework with report portal. But I am getting below error when running my cucumber feature file with report portal. 

```
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at rp.org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:171)
	... 5 more
Exception in thread "pool-2-thread-1" io.reactivex.exceptions.OnErrorNotImplementedException: Unable to execute request
	at io.reactivex.internal.functions.Functions$14.accept(Functions.java:229)
	at io.reactivex.internal.functions.Functions$14.accept(Functions.java:226)
	at io.reactivex.internal.operators.maybe.MaybeCallbackObserver.onError(MaybeCallbackObserver.java:81)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeOnMaybeObserver.onError(MaybeSubscribeOn.java:96)
	at io.reactivex.internal.operators.maybe.MaybeCache.onError(MaybeCache.java:103)
	at io.reactivex.internal.operators.maybe.MaybeMap$MapMaybeObserver.onError(MaybeMap.java:94)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onErrorInner(MaybePeek.java:147)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onError(MaybePeek.java:134)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onErrorInner(MaybePeek.java:147)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onError(MaybePeek.java:134)
	at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver.onError(MaybeFlatten.java:103)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeOnMaybeObserver.onError(MaybeSubscribeOn.java:96)
	at io.reactivex.internal.operators.maybe.MaybeCache.onError(MaybeCache.java:103)
	at io.reactivex.internal.operators.maybe.MaybeCreate$Emitter.onError(MaybeCreate.java:94)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.failed(HttpClientRestEndpoint.java:582)
	at rp.org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
	at rp.org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:419)
	at rp.org.apache.http.impl.nio.client.AbstractClientExchangeHandler.connectionRequestFailed(AbstractClientExchangeHandler.java:335)
	at rp.org.apache.http.impl.nio.client.AbstractClientExchangeHandler.access$100(AbstractClientExchangeHandler.java:62)
	at rp.org.apache.http.impl.nio.client.AbstractClientExchangeHandler$1.failed(AbstractClientExchangeHandler.java:378)
	at rp.org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
	at rp.org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalPoolEntryCallback.failed(PoolingNHttpClientConnectionManager.java:504)
	at rp.org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
	at rp.org.apache.http.nio.pool.RouteSpecificPool.failed(RouteSpecificPool.java:163)
	at rp.org.apache.http.nio.pool.AbstractNIOConnPool.requestFailed(AbstractNIOConnPool.java:542)
	at rp.org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.failed(AbstractNIOConnPool.java:817)
	at rp.org.apache.http.impl.nio.reactor.SessionRequestImpl.failed(SessionRequestImpl.java:160)
	at rp.org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:173)
	at rp.org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:145)
	at rp.org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
	at rp.org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192)
	at rp.org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.epam.restendpoint.http.exception.RestEndpointIOException: Unable to execute request
	... 19 more
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at rp.org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:171)
	... 5 more
```

**Comment by DzmitryHumianiuk** [comment]
@bawarim connection to server was closed.
check if it's reachable from testing environment.

**Comment by bawarim** [comment]
Yes, report portal server is reachable from the execution machine. My report portal is installed on linux machine and I am executing my script on windows VM.

**Comment by akoltochihin** [comment]
Try to use
`rp.endpoint=http://172.26.52.103:8080`
in `reportportal.properties`, probably it will help

**Comment by bawarim** [comment]
@akoltochihin  That worked. Thank you 👍

**Comment by DzmitryHumianiuk** [comment]
### **Resolution:**
copy correct configuration from Profile page of you instance.

**Comment by SawanRawath** [comment]
> Try to use
> `rp.endpoint=http://172.26.52.103:8080`
> in `reportportal.properties`, probably it will help

Hi where I can find reportportal.properties
