### ISSUE TITLE
Error: Cannot build ReportPortal client when doing parallel execution 

### ISSUE THREAD

**Issue by bawarim** [reportportal/reportportal#579]
Hi,
I am getting below error when trying to run multiple feature files parallel. 
```
**[ERROR] Cannot build ReportPortal client
java.net.MalformedURLException: null
	at java.net.URL.<init>(Unknown Source) ~[na:1.8.0_201]
	at java.net.URL.<init>(Unknown Source) ~[na:1.8.0_201]
	at java.net.URL.<init>(Unknown Source) ~[na:1.8.0_201]
	at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:301) [client-java-4.0.8.jar:na]
	at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:263) [client-java-4.0.8.jar:na]
	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:251) [client-java-4.0.8.jar:na]
	at com.epam.reportportal.cucumber.AbstractReporter.buildReportPortal(AbstractReporter.java:105) [agent-java-cucumber-4.0.2.jar:na]
	at com.epam.reportportal.cucumber.AbstractReporter$1.get(AbstractReporter.java:75) [agent-java-cucumber-4.0.2.jar:na]
	at com.epam.reportportal.cucumber.AbstractReporter$1.get(AbstractReporter.java:68) [agent-java-cucumber-4.0.2.jar:na]
	at rp.com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:120) [client-java-4.0.8.jar:na]
	at com.epam.reportportal.cucumber.ScenarioReporter$1.get(ScenarioReporter.java:62) [agent-java-cucumber-4.0.2.jar:na]
	at com.epam.reportportal.cucumber.ScenarioReporter$1.get(ScenarioReporter.java:55) [agent-java-cucumber-4.0.2.jar:na]
	at rp.com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:120) [client-java-4.0.8.jar:na]
	at com.epam.reportportal.cucumber.ScenarioReporter.getRootItemId(ScenarioReporter.java:106) [agent-java-cucumber-4.0.2.jar:na]
	at com.epam.reportportal.cucumber.AbstractReporter.beforeFeature(AbstractReporter.java:125) [agent-java-cucumber-4.0.2.jar:na]
	at com.epam.reportportal.cucumber.AbstractReporter.feature(AbstractReporter.java:299) [agent-java-cucumber-4.0.2.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_201]
	at cucumber.runtime.Utils$1.call(Utils.java:40) [cucumber-core-1.2.5.jar:na]
	at cucumber.runtime.Timeout.timeout(Timeout.java:16) [cucumber-core-1.2.5.jar:na]
	at cucumber.runtime.Utils.invoke(Utils.java:34) [cucumber-core-1.2.5.jar:na]
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:294) [cucumber-core-1.2.5.jar:na]
	at com.sun.proxy.$Proxy23.feature(Unknown Source) [na:na]
	at cucumber.runtime.junit.JUnitReporter.feature(JUnitReporter.java:184) [cucumber-junit-1.2.5.jar:na]
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:69) [cucumber-junit-1.2.5.jar:na]
	at com.github.mkolisnyk.cucumber.runner.ExtendedCucumber.runChild(ExtendedCucumber.java:108) [cucumber-runner-1.3.1.jar:1.3.1]
	at com.github.mkolisnyk.cucumber.runner.ExtendedCucumber.runChild(ExtendedCucumber.java:32) [cucumber-runner-1.3.1.jar:1.3.1]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at com.github.mkolisnyk.cucumber.runner.ExtendedCucumber.run(ExtendedCucumber.java:148) [cucumber-runner-1.3.1.jar:1.3.1]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206) [.cp/:na]
Caused by: java.lang.NullPointerException: null
	... 44 common frames omitted**
```

**Comment by DzmitryHumianiuk** [comment]
@bawarim how it was resolved for you?

explanation can help other users.

**Comment by bawarim** [comment]
Sorry my bad. It was get closed accidentally.

**Comment by DzmitryHumianiuk** [comment]
@bawarim any other details?

client version?
agent version?

how you configure execution?

**Comment by bawarim** [comment]
I got the issue. 

Report portal properties file was not coming under complied classes target folder, So it was giving error 'Cannot build ReportPortal client'.
Then i copied the below resource in pom.xml and it worked. Now properties file is also coming into the target folder after compilation. 
<resource>
            <directory>Source Code</directory>
            <includes>                      
                <include>*.xml</include>
                <include>*.properties</include>
            </includes>
        </resource>

**Comment by DzmitryHumianiuk** [comment]
@bawarim can be closed?
