### ISSUE TITLE
Exception while reporting specflow scenario in report portal 

### ISSUE THREAD

**Issue by bawarim** [reportportal/reportportal#608]
I am using below Json file for my SpecFlow scenarios.

{
    "$schema": "https://raw.githubusercontent.com/reportportal/agent-net-specflow/master/ReportPortal.SpecFlowPlugin/ReportPortal.config.schema",
    "enabled": true,
    "server": {
        "url": "http://xxx.xx.xx.xx:8080",
        "project": "AUTOMATION_PERSONAL",
        "authentication": {
            "uuid": "rt56uuuu-3435-4db7-8876-3214560be13"
        }
    },
    "launch": {
        "name": "SpecFlow Demo Launch",
        "description": "this is description",
        "debugMode": true,
        "tags": [ "t1", "t2" ]
    }
}

Getting below exception in ReportPortal logs 

Finishing to send results to ReportPortal...
System.AggregateException: One or more errors occurred. (Cannot finish launch due inner items failed to finish.) ---> System.Exception: Cannot finish launch due inner items failed to finish. ---> System.AggregateException: One or more errors occurred. (Cannot finish test item due starting item failed.) (Cannot finish test item due starting item failed.) ---> System.Exception: Cannot finish test item due starting item failed. ---> System.AggregateException: One or more errors occurred. (Cannot start a test item due parent failed to start.) (Cannot start a test item due parent failed to start.) ---> System.Exception: Cannot start a test item due parent failed to start. ---> System.AggregateException: One or more errors occurred. (There was an error deserializing the object of type ReportPortal.Client.Models.Launch. Encountered unexpected character '<'.) (There was an error deserializing the object of type ReportPortal.Client.Models.Launch. Encountered unexpected character '<'.) ---> System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type ReportPortal.Client.Models.Launch. Encountered unexpected character '<'. ---> System.Xml.XmlException: Encountered unexpected character '<'.
   at System.Xml.XmlExceptionHelper.ThrowXmlException(XmlDictionaryReader reader, XmlException exception)
   at System.Runtime.Serialization.Json.XmlJsonReader.ReadAttributes()
   at System.Runtime.Serialization.Json.XmlJsonReader.ReadNonExistentElementName(StringHandleConstStringType elementName)
   at System.Runtime.Serialization.Json.XmlJsonReader.Read()
   at System.Xml.XmlBaseReader.IsStartElement()
   at System.Xml.XmlBaseReader.IsStartElement(XmlDictionaryString localName, XmlDictionaryString namespaceUri)
   at System.Runtime.Serialization.XmlReaderDelegator.IsStartElement(XmlDictionaryString localname, XmlDictionaryString ns)
   at System.Runtime.Serialization.XmlObjectSerializer.IsRootElement(XmlReaderDelegator reader, DataContract contract, XmlDictionaryString name, XmlDictionaryString ns)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.InternalIsStartObject(XmlReaderDelegator reader)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.InternalReadObject(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   --- End of inner exception stack trace ---
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.ReadObject(XmlDictionaryReader reader)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.ReadObject(Stream stream)
   at ReportPortal.Client.Converters.ModelSerializer.Deserialize[T](String json)
   at ReportPortal.Client.Service.StartLaunchAsync(StartLaunchRequest model)
   at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass11_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass15_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass20_0.<<Finish>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass16_0.<<Finish>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at ReportPortal.SpecFlowPlugin.ReportPortalHooks.AfterTestRun()

**Comment by nvborisenko** [comment]
Try to add `/api/v1` to `url` property in config.
Or project name is case sensitive, not sure.

Or upgrade nuget packages if there are available.

**Comment by bawarim** [comment]
@nvborisenko Tried adding api/vi and case sensitive project name but still getting the same error. 
nuget packages are updated.

**Comment by bawarim** [comment]
@nvborisenko Thank you :)
Adding /api/v1 in json file worked. The problem is that it was not updating the json file in output folder even i have marked Copy to output directory -> copy if newer. 
I have deleted the file from output folder. And then it worked.
