### ISSUE TITLE
'ReportPortal.NUnitExtension.ReportPortalListener' threw an exception

### ISSUE THREAD

**Issue by RonZAllstar** [reportportal/reportportal#623]
Hi guys,

I keep getting this error when running our test.
I've created the Addins file and I'm running report portal on docker (Windows 10) - all containers are up.
We have a .Net application.

Folder Structure:
C:
|- NUnitRunner
  |- nunit.console.exe
  |- ReportPortal.addins
|- YourProject
  |- bin
    |- Debug
      |- YourProject.Tests.dll
      |- ReportPortal.NUnitExtension.dll

ReportPortal.addins (example):
-../YourProject/bin/Debug/ReportPortal.NUnitExtension.dll

ReportPortal.config (example):
`{
  "$schema": "https://raw.githubusercontent.com/reportportal/agent-net-nunit/master/ReportPortal.NUnitExtension/ReportPortal.config.schema",
  "enabled": true,
  "server": {
    "url": "http://localhost:8080/api/v1",
    "project": "SUPERADMIN_PERSONAL",
    "authentication": {
      "uuid": "[i get this from RP Profile]"
    }
  },
  "launch": {
    "name": "VS Test Demo Launch",
    "description": "this is description",
    "debugMode": true,
    "tags": [ "t1", "t2" ]
  }
}`

**Steps**:
1. I check all containers are up
2. I check that I can log into ReportPortal on my localhost
3. run the following command to execute test:
`C:\YourProject\bin\Debug>nunit3-console TemplateGame.dll --where "class=~Test"`
4. Exception is throw

Error Message:
`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'ReportPortal.NUnitExtension.ReportPortalListener' threw an exception. ---> System.Collections.Generic.KeyNotFoundException: Property 'Server:Url' not found in the configuration.
   at ReportPortal.Shared.Configuration.Configuration.GetValue[T](String property)
   at ReportPortal.NUnitExtension.ReportPortalListener..cctor()
   --- End of inner exception stack trace ---
   at ReportPortal.NUnitExtension.ReportPortalListener..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at NUnit.Engine.Extensibility.ExtensionNode.CreateExtensionObject(Object[] args)
   at NUnit.Engine.Extensibility.ExtensionNode.get_ExtensionObject()
   at NUnit.Engine.Services.ExtensionService.<GetExtensions>d__19`1.MoveNext()
   at NUnit.Engine.Runners.MasterTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
   at NUnit.ConsoleRunner.Program.Main(String[] args)`

**Comment by nvborisenko** [comment]
Agent cannot find  configuration file. `ReportPortal.config.json` file should be located in the same folder where `ReportPortal.NUnitExtension.dll` is. Make sure you copy this file to output.
