### ISSUE TITLE
v5 reportportal "Authorization successful" yet "bad credential"

### ISSUE THREAD

**Issue by alnhk** [reportportal/reportportal#664]
After we deployed reportportal (branch = v5_services) to k8s , we are not able to login to UI using username =superadmin and password=erebus, below is the exception stack captured as per uat, is there anything to correct? we prepared first time using v5_service, and yes, we are only using rabbitmq, postgres, reportportal (analyzer, index, ui, authorization,api,migration)

We could see that log of k8s pod for "migration" is marked as "COMPLETED" and "NO CHANGE". 

```2019-07-18 18:07:18.243 DEBUG 1 --- [nio-9999-exec-5] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/sso/oauth/token'; against '/sso/oauth/token'
2019-07-18 18:07:18.243 DEBUG 1 --- [nio-9999-exec-5] o.s.s.w.a.i.FilterSecurityInterceptor    : Secure object: FilterInvocation: URL: /sso/oauth/token; Attributes: [fullyAuthenticated]
2019-07-18 18:07:18.243 DEBUG 1 --- [nio-9999-exec-5] o.s.s.w.a.i.FilterSecurityInterceptor    : Previously Authenticated: org.springframework.security.authentication.UsernamePasswordAuthenticationToken@9bd2: Principal: org.springframework.security.core.userdetails.User@e94: Username: ui; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Not granted any authorities; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@ffff6a82: RemoteIpAddress: 10.233.103.0; SessionId: null; Not granted any authorities
2019-07-18 18:07:18.243 DEBUG 1 --- [nio-9999-exec-5] o.s.s.access.vote.AffirmativeBased       : Voter: org.springframework.security.web.access.expression.WebExpressionVoter@79ec5cbd, returned: 1
2019-07-18 18:07:18.243 DEBUG 1 --- [nio-9999-exec-5] o.s.s.w.a.i.FilterSecurityInterceptor    : Authorization successful
2019-07-18 18:07:18.243 DEBUG 1 --- [nio-9999-exec-5] o.s.s.w.a.i.FilterSecurityInterceptor    : RunAsManager did not change Authentication object
2019-07-18 18:07:18.243 DEBUG 1 --- [nio-9999-exec-5] o.s.security.web.FilterChainProxy        : /sso/oauth/token reached end of additional filter chain; proceeding with original chain
2019-07-18 18:07:18.246 DEBUG 1 --- [nio-9999-exec-5] .s.o.p.e.FrameworkEndpointHandlerMapping : Mapped to public org.springframework.http.ResponseEntity<org.springframework.security.oauth2.common.OAuth2AccessToken> org.springframework.security.oauth2.provider.endpoint.TokenEndpoint.postAccessToken(java.security.Principal,java.util.Map<java.lang.String, java.lang.String>) throws org.springframework.web.HttpRequestMethodNotSupportedException
2019-07-18 18:07:18.247 DEBUG 1 --- [nio-9999-exec-5] .o.p.p.ResourceOwnerPasswordTokenGranter : Getting access token for: ui
2019-07-18 18:07:18.247 DEBUG 1 --- [nio-9999-exec-5] o.s.s.authentication.ProviderManager     : Authentication attempt using com.epam.reportportal.auth.basic.BasicPasswordAuthenticationProvider
2019-07-18 18:07:18.261 ERROR 1 --- [nio-9999-exec-5] c.e.t.r.c.e.rest.RestExceptionHandler    : Handled error: 

org.springframework.security.oauth2.common.exceptions.InvalidGrantException: Bad credentials
    at org.springframework.security.oauth2.provider.password.ResourceOwnerPasswordTokenGranter.getOAuth2Authentication(ResourceOwnerPasswordTokenGranter.java:79) ~[spring-security-oauth2-2.2.1.RELEASE.jar:na]
    at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.getAccessToken(AbstractTokenGranter.java:70) ~[spring-security-oauth2-2.2.1.RELEASE.jar:na]
    at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.grant(AbstractTokenGranter.java:65) ~[spring-security-oauth2-2.2.1.RELEASE.jar:na]
    at org.springframework.security.oauth2.provider.CompositeTokenGranter.grant(CompositeTokenGranter.java:38) ~[spring-security-oauth2-2.2.1.RELEASE.jar:na]
    at org.springframework.security.oauth2.config.annotation.web.configurers.AuthorizationServerEndpointsConfigurer$4.grant(AuthorizationServerEndpointsConfigurer.java:561) ~[spring-security-oauth2-2.2.1.RELEASE.jar:na]```

**Comment by alnhk** [comment]
@DzmitryHumianiuk : Please advise ^^^

**Comment by DzmitryHumianiuk** [comment]
We need help of Aleh Belausau here

**Comment by rajanvyas** [comment]
Hi, we are also getting the same issue, while deploying it to k8s, migration is marked as "COMPLETED" and "NO CHANGE".

Any solution or pointers suggested?

**Comment by DzmitryHumianiuk** [comment]
@AlehB  @avarabyeu

**Comment by AlehB** [comment]
Dear @alnhk ,

**Comment by AlehB** [comment]
Hi @alnhk @rajanvyas,
Please use https://github.com/reportportal/kubernetes/tree/master/reportportal/v5/v5 instead of v5_services if you are not going to use AWS RDS and AWS ES
You need to check all K8s services logs to see if there any issues. It hard to guess what exactly may be a cause.
@rajanvyas , could you please try to login in Chrom with Google Chrome developer console open on Network tab, and let me know if there any suspicious?
