### ISSUE TITLE
Error occurs when we execute scripts from DEV server

### ISSUE THREAD

**Issue by farhaanfsk** [reportportal/reportportal#679]
**Describe the bug**
 [15] ReportPortal execution error
```
rp.org.apache.http.conn.HttpHostConnectException: Connect to rp.epam.com:443 [rp.epam.com/3.121.137.210] failed: Connection timed out: connect
	at rp.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at rp.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
	at rp.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at rp.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at rp.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at rp.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:493)
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
	at io.reactivex.Maybe.subscribe(Maybe.java:4096)
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77)
	at io.reactivex.Maybe.subscribe(Maybe.java:4096)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at rp.org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:339)
	at rp.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 21 common frames omitted
2019-08-02 06:18:47,648 - [DEBUG] - [com.epam.reportportal.utils.SubscriptionUtils$1] - Launch file create successfully completed
2019-08-02 06:18:47,648 - [ERROR] - [com.epam.reportportal.service.LoggingCallback$2] - [15] ReportPortal execution error
rp.org.apache.http.conn.HttpHostConnectException: Connect to rp.epam.com:443 [rp.epam.com/3.121.137.210] failed: Connection timed out: connect
	at rp.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at rp.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
	at rp.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at rp.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at rp.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at rp.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:493)
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
	at io.reactivex.Maybe.subscribe(Maybe.java:4096)
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77)
	at io.reactivex.Maybe.subscribe(Maybe.java:4096)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at rp.org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:339)
	at rp.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 21 common frames omitted
```
**Expected behavior**
should display the launch in report portal

**Screenshots**
If applicable

**Versions:**
 - OS, Browser, windows 8
 - Version of RP
Current version: Analysis Service: 4.3.0; API Service: 4.3.11; Index Service: 4.2.0; Jira Service: 4.3.0; Rally Service: 4.3.0; EPAM Authorization Service: 4.2.1; Service UI: 4.3.7;

**Comment by DzmitryHumianiuk** [comment]
@farhaanfsk can you ping rp instance from your Dev server?
looks like it's just unreachable from particular env.

**Comment by DzmitryHumianiuk** [comment]
@farhaanfsk up

**Comment by SrikanthSunder** [comment]
@farhaanfsk, just my thought, are you able to access Report Portal UI from that particular Server? Also, once you kick the script, try visualizing the behavior in the Report Portal UI, seems like the launch file is getting affected in the middle of script run.

**Comment by farhaanfsk** [comment]
Hi @DzmitryHumianiuk, Sorry for late reply
I got Request Timeout from DEV Server
from local I got a response though

**Comment by DzmitryHumianiuk** [comment]
@farhaanfsk ask you network engineers.
Your instance of RP should be accessible from dev envy as well

**Comment by evjlobanova** [comment]
We close this issue.
@farhaanfsk feel free to reopen it, in case it is still the problem
