### ISSUE TITLE
how to configure report portal to display JBehave BDD scenarios count instead of steps count

### ISSUE THREAD

**Issue by udaygadamsetty** [reportportal/reportportal#708]
I tried all the internet but couldn't find a way to display statistics on the reportportal based on jbehave bdd scenarios instead of steps.  I am using report portal jbehave plugin [agent-java-jbehave] v4.2.0. Using ReportPortalViewGenerator from my jbehave runner.
Any help on configuring jbehave or report portal would be highly appreciated.
Thanks in advance.

**Comment by DzmitryHumianiuk** [comment]
@udaygadamsetty try Story reporter
https://github.com/reportportal/agent-java-jbehave/blob/master/src/main/java/com/epam/reportportal/jbehave/ReportPortalStoryReporter.java

it misses documentation,
but we plan to focus on all java integrations next months.

**Comment by udaygadamsetty** [comment]
getting error while using that file 
Failed to run story features/TestFeature.feature
org.jbehave.core.model.ExamplesTable$RowNotFound: 1
	at org.jbehave.core.model.ExamplesTable.getRow(ExamplesTable.java:310)
	at com.epam.reportportal.jbehave.JBehaveContext$Examples.getCurrentExampleParams(JBehaveContext.java:187)
	at com.epam.reportportal.jbehave.JBehaveUtils.startStep(JBehaveUtils.java:193)
	at com.epam.reportportal.jbehave.ReportPortalStoryReporter.beforeStep(ReportPortalStoryReporter.java:68)
	at org.jbehave.core.reporters.DelegatingStoryReporter.beforeStep(DelegatingStoryReporter.java:127)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.beforeStep(ConcurrentStoryReporter.java:230)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.describeTo(StepCreator.java:590)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:338)
	at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1072)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:938)
	at org.jbehave.core.embedder.PerformableTree$ExamplePerformableScenario.perform(PerformableTree.java:1011)
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:883)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:811)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:784)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:416)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:387)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:291)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:265)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

the scenario format I am using is 
Scenario: US276175-02 The system shall persist multiple copies of the same A01 messages with a unique reference ID to blob with no MAJOR errors
Given Source system is <emrName>
And At facility <facilityName>
And Bob Smith is processed with message reference <refValue1> via A01
When Chuck observes the A01 message to be persisted to blob for Bob Smith
And Chuck observes the A01 messages processing to generate <errorCode1> error in the exception log
And Bob Smith is processed with message reference <refValue2> via A01
Then Chuck expects the A01 message with <attribute> of <refValue2> to be persisted to blob
And Chuck expects the A01 messages processing to generate <errorCode2> error in the exception log
Examples:
| emrName | facilityName | attribute    | refValue1 | refValue2 | errorCode1 | errorCode2 |
| EPIC          | TJH               | messageId | 876543    | 637372    | no               | no               |

**Comment by udaygadamsetty** [comment]
@DzmitryHumianiuk
Other issue I am seeing while using that ReportPortalStoryReporter is that the steps are getting duplicated.
![image](https://user-images.githubusercontent.com/52989311/64718878-ab8a7a80-d48c-11e9-9a50-17b10931d9af.png)

**Comment by DzmitryHumianiuk** [comment]
@udaygadamsetty that means that you have listener connected 2 times
