### ISSUE TITLE
Sometimes launches doesn`t finish

### ISSUE THREAD

**Issue by Vonaburt** [reportportal/reportportal#717]
**Describe the bug**
Some launches look like it doesn`t finish although launches finish in fact. 
I tried to find any error in docker API container logs, but find only this:

`Exception in thread "pool-3-thread-1" com.epam.ta.reportportal.exception.ReportPortalException: Impossible interact with external system. There are no analyzer's clients.
        at com.epam.ta.reportportal.commons.validation.ErrorTypeBasedRuleValidator.verify(ErrorTypeBasedRuleValidator.java:37)
        at com.epam.ta.reportportal.core.analyzer.impl.LogIndexerService.lambda$indexAllLogs$3(LogIndexerService.java:211)
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:164)
        at com.epam.ta.reportportal.core.analyzer.impl.LogIndexerService.indexAllLogs(LogIndexerService.java:207)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`

**Expected behavior**
Then the launch finished, ReportPortal should show on the web-form that launch finish.

**Screenshots**
In the next screenshot, you can see that a launch is "in progress", but in fact, it`s already done.

![image](https://user-images.githubusercontent.com/2561647/65522572-a2b99000-def3-11e9-9cee-5ffd5e24f29a.png)

And about 1 day later launch fails with an "interrupt" result.

![image](https://user-images.githubusercontent.com/2561647/65522623-b6fd8d00-def3-11e9-831d-93f889c5d131.png)

![image](https://user-images.githubusercontent.com/2561647/65522749-e3190e00-def3-11e9-8268-331f1a7c09ba.png)

**Versions:**
 - Windows 10, Chrome 76.0.3809.132 
 - Version of RP: API Service: 4.3.0; Index Service: 4.2.0; Jira Service: 4.3.0; Authorization Service: 4.2.0; Service UI: 4.3.0;

**Comment by evjlobanova** [comment]
PLease check version 5.0, verify after release.
