### ISSUE TITLE
[v5bug] TestNG | Retry Analyser brings inconsistency on the terminating launches on RP 

### ISSUE THREAD

**Issue by jonacarvalheiro** [reportportal/reportportal#719]
**Describe the bug**
If I had a retry analyser to an AnnotationTransformer, the launches start to be inconsistent regarding the terminating launch.  
I use v4 in k8  and works perfectly

**To Reproduce**
Retry.class
` @Override
    public boolean retry(ITestResult iTestResult) {
        if (iTestResult.getStatus() == ITestResult.FAILURE) {                      //Check if test not succeed
           if (count < maxTry) {                            //Check if maxtry count is reached
                count++;                                     //Increase the maxTry count by 1
                //Mark test as failed

                return true;                                 //Tells TestNG to re-run the test
            }

        }
        return false;
    }`

AnnotationTransformer.class

`    @Override
    public void transform(ITestAnnotation annotation, Class testClass, Constructor testConstructor, Method testMethod) {
        annotation.setRetryAnalyzer(Retry.class);

    }`

values.yaml

`serviceindex:
  name: Index Service
  repository: reportportal/service-index
  tag: 5.0.3
  pullPolicy: Always
  resources:
    requests:
      cpu: 150m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  service:
    type: ClusterIP
    port: 8080
    aanotations: {}

uat:
  repository: reportportal/service-authorization
  name: Authorization Service
  tag: 5.0.0-BETA-12
  pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 2048Mi
  sessionLiveTime: 86400
  service:
    type: ClusterIP
    port: 9999
    aanotations: {}

serviceui:
  repository: reportportal/service-ui
  tag: 5.0.0-BETA-12
  name: UI Service
  pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  service:
    type: ClusterIP
    port: 8080
    aanotations: {}

serviceapi:
  repository: reportportal/service-api
  tag: 5.0.0-BETA-12
  name: API Service
  pullPolicy: Always
  resources:
    requests:
      cpu: 500m
      memory: 1024Mi
    limits:
      cpu: 1000m
      memory: 2048Mi
  service:
    type: ClusterIP
    port: 8585
    aanotations: {}

migrations:
  repository: reportportal/migrations
  tag: 5.0.0-BETA-8
  pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

serviceanalyzer:
  repository: reportportal/service-analyzer
  tag: 5.0.0-BETA-4
  name: Analyzer Service
  pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  service:
    type: ClusterIP
    port: 8080
    aanotations: {}

rabbitmq:
  SecretName: ""
  installdep:
    enable: false
  endpoint:
    external: true
    address: <rabbitmq_chart_name>-rabbitmq-ha.default.svc.cluster.local
    port: 5672
    user: rabbitmq
    apiport: 15672
    apiuser: rabbitmq

postgresql:
  SecretName: ""
  installdep:
    enable: false
  endpoint:
    external: true
    cloudservice: false
    address: <postgresql_chart_name>-postgresql.default.svc.cluster.local
    port: 5432
    user: rpuser
    dbName: reportportal
    password:

elasticsearch:
  installdep:
    enable: false
  endpoint:
    external: true
    cloudservice: false
    address: <es_chart_name>-elasticsearch-coordinating-only.default.svc.cluster.local
    port: 9200

# Ingress configuration for the ui
# If you have installed ingress controller and want to expose application - set INGRESS.ENABLE to true.
# If you have some domain name set INGRESS.USEDOMAINNAME variable to true and set this fqdn to INGRESS.HOSTS
# If you don't have any domain names - set INGRESS.USEDOMAINNAME to false
ingress:
  enable: true
  # IF YOU HAVE SOME DOMAIN NAME SET INGRESS.USEDOMAINNAME to true
  usedomainname: false
  hosts:
    - reportportal.k8.com
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/x-forwarded-prefix: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: 128m

# node selector for all components, if any
nodeSelector:
  enabled: false
  selector:
    reportportal: true

# RBAC is required for service-index in order to collect status/info over all services
rbac:
  create: true
  serviceAccount:
      create: true
      name: reportportal

rp:
  infoEndpoint: "/info"
  healthEndpoint: "/health"

`

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]
 - Version [77.0.3865.90]

**Comment by HardNorth** [comment]
Well I was able to reproduce the case by setting `<suite name="Retry launch crush test" parallel="true" thread-count="5">` or `<suite name="API QA Test Suite" verbose="1" parallel="tests" thread-count="1" configfailurepolicy="continue" >`. The essential thing here is running multi-thread execution using **sync (v1)** API.
Then we can get such a nasty error:
```
18:47:21.237 ERROR c.e.r.u.SubscriptionUtils - rp-io-26 - [55] ReportPortal Finish test item execution error
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 500
Status message: 
Error Message: Unclassified error [could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.LockAcquisitionException: could not execute statement]
Error Type: UNCLASSIFIED_ERROR

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:83)
	at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:59)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:517)
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Well, since v1 endpoint is not designed for parallel execution I think the real issue here is a lack of validation.
So @Yumfriez, I suppose that's your case.

**Comment by HardNorth** [comment]
@jonacarvalheiro this bug should be addressed in the next Beta release.
