### ISSUE TITLE
v5: Cucumber+Java+TestNG+Logback Nested Steps Not working

### ISSUE THREAD

**Issue by arunkumar-muthusamy** [reportportal/reportportal#762]
Hi @evjlobanova,

Based on [/reportportal/issues/275](https://github.com/reportportal/reportportal/issues/275), I tried to integrate Cucumber BDD tests (implemented with Java), Run with TestNG, logged using Logback... But, the steps are getting displayed in flat structure.. please find below the details,

ReportPortal Version:
```
API Service: 5.0.0-RC-1
Index Service: 5.0.4
Authorization Service: 5.0
Service UI: 5.0.0-RC-1
```
Dependency in `pom.xml`
```xml
....
		<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>agent-java-testng</artifactId>
			<version>5.0.0-BETA-6</version>
		</dependency>
		<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>logger-java-logback</artifactId>
			<version>5.0.0-BETA-4</version>
		</dependency>
		<dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-cucumber4</artifactId>
            <version>5.0.0-BETA-1</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>4.2.6</version>
        </dependency>
		<dependency>
		    <groupId>io.cucumber</groupId>
		    <artifactId>cucumber-testng</artifactId>
		    <version>4.2.6</version>
		</dependency>
.....
```

CucumberRunner

```java
@CucumberOptions(plugin = { "pretty",
		"com.epam.reportportal.cucumber.ScenarioReporter" }, features = "src/main/java/com/saucedemo/cucumber/features", glue = "com.saucedemo.cucumber.steps", tags = {
				"@Regression,@TestngScenario" })

public class CucumberRunner extends AbstractTestNGCucumberTests {

}
```

StepDefinition

```java
public class Login extends CucumberRunner {
        Logger ReportPortalLogger = LoggerFactory.getLogger("report_portal_logger");
// Appender named "report_portal_logger" is defined in logback.xml
	LoginPage sauceDemo = new LoginPage();

	@Given("^I am on SauceDemo login page$")
	public void verify_if_im_on_login_page() throws Throwable {
		ReportPortalLogger.info ("Open Browser and navigate to login page");
		sauceDemo.startBrowser();
		ReportPortalLogger.info  ("Verify if i'm on Sauce Demo Login Page");
		sauceDemo.shouldBeOnLoginScreen();
	}
	
	@When ("^I login with \"(.*?)\", \"(.*?)\"$")
	public void login_to_sauce_demo(String userName, String password) throws Throwable {
		ReportPortalLogger.info (String.format("Login to saucedemo with credentials ${1}, ${2}", userName, password));
		sauceDemo.loginWith(userName, password);
	}
	
	@Then ("I should be logged in successfully")
	public void verifyLogin() throws Throwable {
		ReportPortalLogger.info ( String.format("Verify if user logged in successfully"));
		sauceDemo.shouldLoginSuccessfully();
	}
	
	@Then ("I logout of application")
	public void logout() throws Throwable {
		ReportPortalLogger.info ( String.format("Logout of saucedemo application"));
		sauceDemo.logout();
	}
	
	@Then ("I should be logout successfully")
	public void verifyLogout() throws Throwable {
		ReportPortalLogger.info ( String.format("Verify if the user logout successfully"));
		sauceDemo.shouldBeOnLoginScreen();
	}
}
```
LoginPage

```java
public class LoginPage extends BasePage {
	private TextBox txtBoxUserName = new TextBox("id=user-name","User Name TextBox");
	private TextBox txtBoxPassword = new TextBox("xpath=//input[@placeholder='Password']","Password TextBox");
	
	private Button btnLogin = new Button("xpath=//input[@type='submit']","Login Button");
	private Button btnOpenMenu = new Button("xpath=//button[text()= 'Open Menu']", "Open Menu on left top corner");
	
	private Link linkLogout = new Link ("id=logout_sidebar_link", "Logout link on sildebar");
	
	private Label lblProducts = new Label ("xpath=//div[@class='product_label' and text() = 'Products' ]", "Products Label/Header");
	
	public LoginPage shouldBeOnLoginScreen() {
		txtBoxUserName.verifyElementPresent();
		txtBoxPassword.verifyElementPresent();
		btnLogin.verifyElementPresent();
		return new LoginPage();
		
	}
	public LoginPage loginWith(String userName, String password) {
		txtBoxUserName.input(userName);
		txtBoxPassword.input(password, true);
		btnLogin.click();
		return new LoginPage();
		
	}
	
	public LoginPage shouldLoginSuccessfully() {
		lblProducts.verifyElementPresent();
		return new LoginPage();
	}
	
	public LoginPage logout() {
		btnOpenMenu.click();
		linkLogout.click();
		return new LoginPage();
	}
}
```
Note: BasePage has all our Framework/Functional libs

`login.feature`

```properties
Feature: Login to SauceDemo
  
@TestngScenario
  Scenario: Login With Valid Credentials
    Given I am on SauceDemo login page
    When I login with "valid.userName", "valid.password"
    Then I should be logged in successfully
    When I logout of application
    Then I should be logout successfully
```

Here is how results are showing up in ReportPortal.

![image](https://user-images.githubusercontent.com/47788194/70000473-177afd00-1529-11ea-917e-5ae15f46d1ed.png)

![image](https://user-images.githubusercontent.com/47788194/70000520-2eb9ea80-1529-11ea-9591-814ac0564bed.png)

I'm expecting the Nested Steps to work as below,
```properties
--- Given I am on SauceDemo login page
        <nested steps>
         Navigating to testURL >>  https://www.saucedemo.com
         Page source of testURL >>  https://www.saucedemo.com
         Verify if i'm on Sauce Demo Login Page
--- When I login with "valid.userName", "valid.password"
       <nested steps>
--- Then I should be logged in successfully
       <nested steps>
```

Please help me understand, what I'm missing to make the Nested Steps work.

**Comment by arunkumar-muthusamy** [comment]
Hi @DzmitryHumianiuk / @evjlobanova , Can you pls help me with this issue?

**Comment by evjlobanova** [comment]
@arunkumar-muthusamy Hello! Which versions of agent do you use?
@Yumfriez could you please look and help?

**Comment by evjlobanova** [comment]
@Yumfriez could you please send a dev quide for nested steps?

**Comment by Yumfriez** [comment]
@arunkumar-muthusamy To enable 'nested steps' you should specify 'javaagent with aspectj weaver dependency' in your `pom build config` and add `aop-ajc.xml` file to the `META-INF folder inside resources dir`. Then you should mark required methods with '@Step' annotation
Here is a link for nested steps guide: https://github.com/reportportal/client-java/wiki/Nested-steps
This is a fully configured nested steps example: https://github.com/reportportal/examples-java/pull/7/files

**Comment by DzmitryHumianiuk** [comment]
@arunkumar-muthusamy let us know the results.
we have it in focus for now

**Comment by arunkumar-muthusamy** [comment]
@DzmitryHumianiuk @Yumfriez @evjlobanova , Thank you so much for helping out!!

It worked like a charm for regular `Java+TestNG+Logback` test. But not for the Cucumber BDD. In @Yumfriez document references, it never talked about Cucumber support. SO I assume, my original question is still open. 

Please find below the details. 

Regular test `Java+TestNG+Logback`:

```
public class AUTO123457_SauceDemo_Login_With_Valid_User_Step_Reporting extends BaseTest {
	LoginPage sauceDemo = new LoginPage();
	@Test
	public void verifyIconOnSkuDetailPage() {
		
		step0 ();
		step1 ();
		step2 ();
		step3 ();
		
	}
	
	@Step ("Step 0: Start Browser")
	private void step0 () {
		lib.startBrowser();
	}
	
	
	@Step ("Step 1: Login to saucedemo application")
	private void step1 () {
		sauceDemo.shouldBeOnLoginScreen().loginWith("valid.userName", "valid.password");

	}
	
	@Step ("Step 2: Login should be successful")
	private void step2 () {
		sauceDemo.shouldLoginSuccessfully();
	}
	
	@Step ("Step 3:  Logout of saucedemo application")
	private void step3 () {
		sauceDemo.logout().shouldBeOnLoginScreen();
	}
}
``` 
ReportPortal Logs came out as expected:
![image](https://user-images.githubusercontent.com/47788194/70644031-2a1fc100-1c10-11ea-9441-135f3eba3159.png)

![image](https://user-images.githubusercontent.com/47788194/70644053-3ad03700-1c10-11ea-9790-ebab677ae361.png)

----------------------------------------------------------------------------------------------
For Cucumber BDD, I added `@Step` annotation to my Step definition
```
public class LoginSteps extends CucumberRunner {

	LoginPage sauceDemo = new LoginPage();
	
	@Step ("Login to app")
	@Given("^I am on SauceDemo login page$")
	public void verify_if_im_on_login_page() throws Throwable {
		sauceDemo.logger.logTestMessage(TestMessageType.TESTSTEP, "Open Browser and navigte to login page");
		sauceDemo.startBrowser();
		sauceDemo.logger.logTestMessage(TestMessageType.TESTSTEP, "Verify if i'm on Sauce Dmeo Login Page");
		sauceDemo.shouldBeOnLoginScreen();
	}
...
...
...

}
```
CucumberRunner
```
@CucumberOptions(plugin = { "pretty", "com.epam.reportportal.cucumber.ScenarioReporter" }, features = "src/main/java/com/saucedemo/cucumber/features", glue = "com.saucedemo.cucumber.steps", tags = {"@Positive,@Negative" })
public class CucumberRunner extends AbstractTestNGCucumberTests {}
```

Here is the console output for Cucumber BDD Tests with `@Step` annotation,
```
Feature: Login to SauceDemo
	Verify the login for SauceDemo

  @Positive @Smoke
  Scenario: Login With Valid Credentials                 # src/main/java/com/saucedemo/cucumber/features/login.feature:5
    Given I am on SauceDemo login page                   # LoginSteps.verify_if_im_on_login_page()
      java.lang.NullPointerException
	at com.epam.reportportal.aspect.StepAspect.startNestedStep(StepAspect.java:87)
	at com.saucedemo.cucumber.steps.LoginSteps.verify_if_im_on_login_page(LoginSteps.java:19)
	at ✽.I am on SauceDemo login page(file:src/main/java/com/saucedemo/cucumber/features/login.feature:6)

    When I login with "valid.userName", "valid.password" # LoginSteps.login_to_sauce_demo(String,String)
    Then I should be logged in successfully              # LoginSteps.verifyLogin()
    When I logout of application                         # LoginSteps.logout()
    Then I should be logout successfully                 # LoginSteps.verifyLogout()

  @Negative
  Scenario: Login With locked out Credentials                                # src/main/java/com/saucedemo/cucumber/features/login.feature:13
    Given I am on SauceDemo login page                                       # LoginSteps.verify_if_im_on_login_page()
      java.lang.NullPointerException
	at com.epam.reportportal.aspect.StepAspect.startNestedStep(StepAspect.java:87)
	at com.saucedemo.cucumber.steps.LoginSteps.verify_if_im_on_login_page(LoginSteps.java:19)
	at ✽.I am on SauceDemo login page(file:src/main/java/com/saucedemo/cucumber/features/login.feature:14)

    When I login with "locked_out_user.userName", "locked_out_user.password" # LoginSteps.login_to_sauce_demo(String,String)
    Then I should not be logged in successfully                              # LoginSteps.verifyNotLogin()

Failed scenarios:
src/main/java/com/saucedemo/cucumber/features/login.feature:5 # Login With Valid Credentials
src/main/java/com/saucedemo/cucumber/features/login.feature:13 # Login With locked out Credentials

2 Scenarios (2 failed)
8 Steps (2 failed, 6 skipped)
0m2.319s

java.lang.NullPointerException
	at com.epam.reportportal.aspect.StepAspect.startNestedStep(StepAspect.java:87)
	at com.saucedemo.cucumber.steps.LoginSteps.verify_if_im_on_login_page(LoginSteps.java:19)
	at ✽.I am on SauceDemo login page(file:src/main/java/com/saucedemo/cucumber/features/login.feature:6)

java.lang.NullPointerException
	at com.epam.reportportal.aspect.StepAspect.startNestedStep(StepAspect.java:87)
	at com.saucedemo.cucumber.steps.LoginSteps.verify_if_im_on_login_page(LoginSteps.java:19)
	at ✽.I am on SauceDemo login page(file:src/main/java/com/saucedemo/cucumber/features/login.feature:14)

FAILED: runScenario("Login With locked out Credentials", "Login to SauceDemo")
        Runs Cucumber Scenarios
java.lang.NullPointerException
	at com.epam.reportportal.aspect.StepAspect.startNestedStep(StepAspect.java:87)
	at com.saucedemo.cucumber.steps.LoginSteps.verify_if_im_on_login_page(LoginSteps.java:19)
	at ✽.I am on SauceDemo login page(file:src/main/java/com/saucedemo/cucumber/features/login.feature:14)

FAILED: runScenario("Login With Valid Credentials", "Login to SauceDemo")
        Runs Cucumber Scenarios
java.lang.NullPointerException
	at com.epam.reportportal.aspect.StepAspect.startNestedStep(StepAspect.java:87)
	at com.saucedemo.cucumber.steps.LoginSteps.verify_if_im_on_login_page(LoginSteps.java:19)
	at ✽.I am on SauceDemo login page(file:src/main/java/com/saucedemo/cucumber/features/login.feature:6)


===============================================
    Default test
    Tests run: 2, Failures: 2, Skips: 0
===============================================
```

**Comment by DzmitryHumianiuk** [comment]
Team started progress on this.

**Comment by mariabeqa** [comment]
Hi @Yumfriez 
Any updates on this one? I'm facing the same issue

**Comment by KacperWieczorek** [comment]
> @arunkumar-muthusamy To enable `nested steps` you should specify `javaagent with aspectj weaver dependency` in your `pom build config` and add `aop-ajc.xml` file to the `META-INF folder inside resources dir`. Then you should mark required methods with '@step' annotation Here is a link for nested steps guide: https://github.com/reportportal/client-java/wiki/Nested-steps This is a fully configured nested steps example: https://github.com/reportportal/examples-java/pull/7/files

This would be nice to have in Nested Step Wiki page.

**Comment by DzmitryHumianiuk** [comment]
@KacperWieczorek agree

**Comment by Onish1204** [comment]
With Cucumber+TestNG, it shows a dummy scenario runScenario (io.cucumber.testng.AbstractTestNGCucumberTests.runScenario) as Scenario for every actual scenario. I don't want to get it visible on report portal along with actual scenario. 
![image](https://user-images.githubusercontent.com/29482178/156370298-d7f159b2-b69a-4fee-a910-71ff2407e403.png)

Test Runner code:
<img width="439" alt="TestRunner" src="https://user-images.githubusercontent.com/29482178/156370504-ed718bd6-5ca0-4b7d-91b5-402fd29c01fe.PNG">

Pls suggest....

**Comment by DzmitryHumianiuk** [comment]
@HardNorth could you please take a look here?

**Comment by HardNorth** [comment]
@Onish1204 @DzmitryHumianiuk I created an example specially for the case of Cucumber + TestNG:  https://github.com/reportportal/examples-java/tree/master/example-cucumber6-testng

And no. I don't see any issues. No additional/missed steps, problems, etc.

I believe this is another case where people are trying to integrate different frameworks with the same runner in one module. E.G. TestNG tests with Cucumber tests over TestNG runner.

I should make it clear: we have TestNG and Cucumber agents separately by the reason that the structure of reporting of these frameworks is different. And there is no way to determine from the agent whether someone run pure TestNG test or Cucumber + TestNG test. So such cases when you have TestNG + Cucumber over TestNG tests in one module won't be supported.
