### ISSUE TITLE
[v5bug]: 5.0.0-RC5: POST api/v1/cloud/launch returns 500. SimpleGrantedAuthority exception

### ISSUE THREAD

**Issue by OstapJ** [reportportal/reportportal#790]
**Describe the bug**
InternalReportPortalClientException: Report portal is not functioning correctly. Response is not json is thrown when we try to create a Launch (POST “https://reportportal.dev.ring.net/api/v1/cloud/launch")

**To Reproduce**
1. Execute the test

**Expected behavior**
The launch is created, there is no exception

**Screenshots**

**Server**
Analysis Service: 5.0.0-RC-5;API Service: 5.0.0-SNAPSHOT;Index Service: 5.0.5;Authorization Service: 5.0.0-RC-5;Service UI: 5.0.0-RC-5;

**Client**
'agent-java-testng:4.2.3-BETA'
'org.testng:testng:6.14.3'

**Additional context**
The response body from the server is below:
`<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1></body></html>`

The server log is below:
`2019-12-27 15:16:39.193 ERROR 1 --- [io-8585-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
java.lang.IllegalArgumentException: java.io.InvalidClassException: org.springframework.security.core.authority.SimpleGrantedAuthority; local class incompatible: stream classdesc serialVersionUID = 510, local class serialVersionUID = 520
	at org.springframework.security.oauth2.common.util.DefaultSerializationStrategy.deserialize(DefaultSerializationStrategy.java:67)
	at org.springframework.security.oauth2.common.util.SerializationUtils.deserialize(SerializationUtils.java:77)
	at com.epam.ta.reportportal.auth.CombinedTokenStore.readAuthentication(CombinedTokenStore.java:67)
	at org.springframework.security.oauth2.provider.token.store.JwtTokenStore.readAuthentication(JwtTokenStore.java:70)
	at com.epam.ta.reportportal.auth.CombinedTokenStore.readAuthentication(CombinedTokenStore.java:54)
	at com.epam.ta.reportportal.auth.CombinedTokenStore$$FastClassBySpringCGLIB$$753697c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:353)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.epam.ta.reportportal.auth.CombinedTokenStore$$EnhancerBySpringCGLIB$$92ba702.readAuthentication(<generated>)
	at org.springframework.security.oauth2.provider.token.DefaultTokenServices.loadAuthentication(DefaultTokenServices.java:242)
	at org.springframework.security.oauth2.provider.token.DefaultTokenServices$$FastClassBySpringCGLIB$$5a1f25c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)`

**Comment by ihar-kahadouski** [comment]
@OstapJ please regenerate API token and try to report launch again using the new one

**Comment by OstapJ** [comment]
@ihar-kahadouski thanks, indeed the token regeneration helped to resolve the issue.
