### ISSUE TITLE
java.lang.NoClassDefFoundError: rp/com/google/common/base/Supplier

### ISSUE THREAD

**Issue by ShashiSasuke02** [reportportal/reportportal#819]
**Not able to run the test displaying below error.**
ava.lang.NoClassDefFoundError: rp/com/google/common/base/Supplier
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at org.testng.internal.ClassHelper.newInstance(ClassHelper.java:65)
	at org.testng.TestNG.addListeners(TestNG.java:1012)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:976)
	at org.testng.TestNG.run(TestNG.java:1102)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ClassNotFoundException: rp.com.google.common.base.Supplier
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 11 more

**Comment by HardNorth** [comment]
@ShashiSasuke02 Looks like you have issues with your dependencies. They do not contain Google Guava: https://search.maven.org/artifact/com.google.guava/guava

Well, actually not a RP issue.
