### ISSUE TITLE
[v5]sql error

### ISSUE THREAD

**Issue by kareka** [reportportal/reportportal#822]
**Describe the bug**

Have done installation using shell script on lentos
getting sql error while trying to generate demo data or going on launches

Caused by: org.postgresql.util.PSQLException: ERROR: relation "public.item_attribute" does not exist
  Position: 1141
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:138)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3928)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:294)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:368)
	... 141 common frames omitted

2020-02-17 16:13:34.181  WARN 22812 --- [nio-8585-exec-7] c.e.t.r.c.e.rest.RestExceptionHandler    : Resolved [org.jooq.exception.DataAccessException: SQL [with "filtered" as (select "public"."launch"."id" as "id", "launch"."start_time" as "startTime", "launch"."number" as "number" from "public"."launch" where ("launch"."mode" = ?::"public"."launch_mode_enum" and "launch"."project_id" = ?) group by "public"."launch"."id" order by "launch"."start_time" desc, "launch"."number" desc, "launch"."id" asc limit ?) select "public"."launch"."id", "public"."launch"."uuid", "public"."launch"."name", "public"."launch"."description", "public"."launch"."start_time", "public"."launch"."end_time", "public"."launch"."project_id", "public"."launch"."user_id", "public"."launch"."number", "public"."launch"."last_modified", "public"."launch"."mode", "public"."launch"."status", "public"."launch"."has_retries", "public"."launch"."rerun", "public"."launch"."approximate_duration", "public"."item_attribute"."key", "public"."item_attribute"."value", "public"."item_attribute"."system", "public"."statistics"."s_counter", "public"."statistics_field"."name", "public"."users"."id", "public"."users"."login" from "public"."launch" join "filtered" on "public"."launch"."id" = "filtered"."id" left outer join "public"."item_attribute" on "public"."launch"."id" = "public"."item_attribute"."launch_id" left outer join "public"."users" on "public"."launch"."user_id" = "public"."users"."id" left outer join "public"."statistics" on "public"."launch"."id" = "public"."statistics"."launch_id" left outer join "public"."statistics_field" on "public"."statistics"."statistics_field_id" = "public"."statistics_field"."sf_id" order by "launch"."start_time" desc, "launch"."number" desc, "launch"."id" asc]; ERROR: relation "public.item_attribute" does not exist
  Position: 1141]

**To Reproduce**
click to generate demo data
**Expected behavior**
demo data should be generate
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khatray** [comment]
Please close this as this issue is fixed
