### ISSUE TITLE
java.lang.NoClassDefFound  Error: rp/com/google/common/base/Supplier[v5]

### ISSUE THREAD

**Issue by ShashiSasuke02** [reportportal/reportportal#842]
**java.lang.NoClassDefFound**
Caused by: java.lang.ClassNotFoundException: rp.com.google.common.base.Supplier
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 1 more

**Using TestNG runner and listeners**
ReportPortalTestNGListener listener = new ReportPortalTestNGListener();
        TestNG testNg = new TestNG();
        List<String> lSuites = new ArrayList<String>();
        Collections.addAll(lSuites, "path.xml");
        testNg.setTestSuites(lSuites);
        testNg.addListener(listener);
        testNg.run();

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser Firefox

**Project Spec**
 - Gradle
 - Java
Can any one help me to resolve this issue.

Thanks

**Comment by HardNorth** [comment]
I need to know your dependencies versions to help. Currently it's looking like you have 5th client and 4th agent.
