### ISSUE TITLE
[v5] DataException when data provider object is too long

### ISSUE THREAD

**Issue by olexandr-mosin** [reportportal/reportportal#849]
**Describe the bug**
PRv5 does not show some tests results and can't finish a run even when build was done.
![Screenshot 2020-03-05 at 11 38 05](https://user-images.githubusercontent.com/53187889/75968428-051cb080-5ed6-11ea-9b75-cc350089de85.png)

**To Reproduce**
1. implement simple test with data provider (separate class)
2. add several strings in this provider
-"7777777777777777777777777777779vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiZGVmYXVsdC1xYSIsInR5cCI6IkpXVCJ9.eyJhcHBfaWQiOiJyaW5nX27777777777777777777777777777777777777777777777777777wiZXhwIjoxNTgzMzk3MDMxLCJoYXJkd2FyZV9pZCI6IkhBUkRXQVJFLVRFU1QiLCJpYXQiOjE1ODMzOTYxMzEsInJuZCI6IlhNQm02bFdQbEdDbUF3Iiwic2NvcGVzIjpbImNsaWVudCJdLCJ1c2VyX2lkIjo4NDUxfQ.WambcfB3TWa1Y41SgBe-DtG0qpfjh7kMy3C8Q85n3k-IyawAPb000000000000000000000vcFeA2tP_k9a-gQ"

 -"test"
 3. run test under RPv5

**Expected behavior**
- Report is created in the RP
- Run is done. I can see a duration and finish time
- All test cases included in report
- No errors from PR in a log

**Actual behavior**
- Report is created
- Run is not done after the build is over
- Only second case ("test") is in the report
- error in the build log 

**Error log**
` Mar-05 09:30:38.037 [rp-io-30] ERROR SubscriptionUtils:96 - [108] ReportPortal Finish test item execution error
    com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
    Status code: 500
    Status message: 
    Error Message: Unclassified error [org.hibernate.exception.DataException: could not execute statement]
    Error Type: UNCLASSIFIED_ERROR

    	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:83)
    	at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:59)
    	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:526)
    	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
    	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
    	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
    	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
    	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:748)`

**Additional context**
- looks like it fails when logger get too long string (we use gson.toString and tokens in data provider, so objects could has over 700 characters )
- when I change data to shorter one - RP works fine
- this issue does not reproduce on RPv4

Current version:
Analysis Service: 5.0.0;
API Service: 5.0.0;
Index Service: 5.0.5;
Authorization Service: 5.0.0;
Service UI: 5.0.0;
testng:7.1.1'
client-java:5.0.0-BETA-9'
agent-java-testng:5.0.0-BETA-9')

**Comment by pbortnik** [comment]
@HardNorth Seems that issue somewhere in backend side. Should be investigated. 
@evjlobanova Create a technical task.

**Comment by DzmitryHumianiuk** [comment]
1. Change limit from 512 to 1024
2. If length more than 1024 then: take hash of param, can len of hash from param. append value hash to it
3. Change the way to store TicketID as: if no explicit declaration then post `codeReference(Hash of params)`


@olexandr-mosin please use explicit `TestCaseID` declaration to avoid this until fixed.
https://github.com/reportportal/client-java/wiki/Test-case-ID
