### ISSUE TITLE
[FR] Google SSO and SAML auth

### ISSUE THREAD

**Issue by amalsgit** [reportportal/reportportal#877]

**Comment by evjlobanova** [comment]
Feature SAML auth will be available in version 5.3

**Comment by sapna-dentsu** [comment]
The SAML is there but is there any documentation?

**Comment by evjlobanova** [comment]
@sapna-dentsu Documentation is here @sapna-dentsu Documentation is here https://reportportal.io/docs/SAML-integration
We will update it today with explanation video

**Comment by malmor** [comment]
Could you provide some additional documentation about which endpoints reportportal expects the SAML provider to send the responses to?

In the video (https://youtu.be/ljXvCVWG4mQ) one can see the settings in okta and I think the destination url was something similar to "https://HOST/uat/saml/sp/SSO/alias/report-portal-sp" (this part maybe needs a bit of documentation 😉)

We really want to get this great feature up and running 😃 👍

**Comment by sapna-dentsu** [comment]
Thanks @evjlobanova for the documentation. 
I'm getting 403 error with the URL. I'm assigned to Okta app, but still getting 403

**Comment by winstondz** [comment]
I am new to okta too and wanted to understand more about the process we need to do inside okta for RP integration. Could you point me to the relevant page. I went through the video, but it starts off by directly going into applications and selecting rp-okta inside okta. Do I need to create a new app inside okta?

**Comment by malmor** [comment]
Any updates on this?

**Comment by isaac88** [comment]
Hello @evjlobanova 
I've updated my Report Portal Helm Chart to the latest version 5.2.3
and I don't see the SAML plugin and in the [docs](https://reportportal.io/docs/Plugins%3Eupload-plugin) said that we don't need to install it.

How I can install it ?

**Comment by Kanaduchi** [comment]
@evjlobanova  Any updates on this? Is there any documentation for Single Sign On url (e.g. uat/saml/sp/SSO/alias/report-portal-sp)? Without such url it is impossible to configure SAML

**Comment by evjlobanova** [comment]
This url should look like this:

https://<your domain adress>/uat/saml/sp/SSO/alias/report-portal-sp

Could you please specify which kind of documentation you need for this url? 
We will check and update if need

**Comment by Kanaduchi** [comment]
Thank you!
I think it should mentioned in https://reportportal.io/docs/SAML-integration
With screenshot for Okta
<img width="753" alt="Screen Shot 2020-09-28 at 1 21 53 PM" src="https://user-images.githubusercontent.com/7042994/94521132-f701f900-0246-11eb-87de-2b12b335ffe6.png">

**Comment by evjlobanova** [comment]
It is shown on the video in documentation
thank you for feedback, I will update docs

**Comment by Kanaduchi** [comment]
@evjlobanova I'm trying to set this integration but get 403 error, when okta redirects back to reportportal

Request URL: https://url/uat/saml/sp/SSO/alias/report-portal-sp
Request Method: POST
Status Code: 403 Forbidden
Form Data:
```
<?xml version="1.0" encoding="UTF-8"?><saml2p:Response Destination="https://url/uat/saml/sp/SSO/alias/report-portal-sp" ID="id6855360991033344473426481" InResponseTo="ARQ4c6e98b-e8e5-423f-91d5-8ee9c41235db" IssueInstant="2020-10-01T02:32:31.080Z" Version="2.0" xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol">
<saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">http://www.okta.com/somecode</saml2:Issuer><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/><ds:Reference URI="#id6855360991033344473426481"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><ds:DigestValue>signature=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>value==</ds:X509Certificate></ds:X509Data></ds:KeyInfo></ds:Signature><saml2p:Status xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol"><saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/></saml2p:Status><saml2:Assertion ID="id68553609911016631496413587" IssueInstant="2020-10-01T02:32:31.080Z" Version="2.0" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"><saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">http://www.okta.com/somecode</saml2:Issuer><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/><ds:Reference URI="#id68553609911016631496413587"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><ds:DigestValue>signature=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>value==</ds:X509Certificate></ds:X509Data></ds:KeyInfo></ds:Signature><saml2:Subject xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"><saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">andrey.topchiy@url.com</saml2:NameID><saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"><saml2:SubjectConfirmationData InResponseTo="ARQ4c6e98b-e8e5-423f-91d5-8ee9c41235db" NotOnOrAfter="2020-10-01T02:37:31.080Z" Recipient="https://url/uat/saml/sp/SSO/alias/report-portal-sp"/></saml2:SubjectConfirmation></saml2:Subject><saml2:Conditions NotBefore="2020-10-01T02:27:31.080Z" NotOnOrAfter="2020-10-01T02:37:31.080Z" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"><saml2:AudienceRestriction><saml2:Audience>report.portal.sp.id</saml2:Audience></saml2:AudienceRestriction></saml2:Conditions><saml2:AuthnStatement AuthnInstant="2020-10-01T02:32:30.461Z" SessionIndex="ARQ4c6e98b-e8e5-423f-91d5-8ee9c41235db" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"><saml2:AuthnContext><saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml2:AuthnContextClassRef></saml2:AuthnContext></saml2:AuthnStatement></saml2:Assertion></saml2p:Response>
```

**Comment by Kanaduchi** [comment]
In the log I see a lot of errors:
`2020-10-01 14:27:17.070 ERROR 6 --- [-8585-exec-1625] .t.r.c.e.r.ReportPortalExceptionResolver : ReportPortalExceptionResolver > You do not have enough permissions.
api_1            |
api_1            | com.epam.ta.reportportal.exception.ReportPortalException: You do not have enough permissions.
api_1            |      at com.epam.ta.reportportal.commons.validation.ErrorTypeBasedRuleValidator.verify(ErrorTypeBasedRuleValidator.java:32)
api_1            |      at com.epam.ta.reportportal.auth.permissions.BaseProjectPermission.isAllowed(BaseProjectPermission.java:55)
api_1            |      at com.epam.ta.reportportal.auth.permissions.ReporterPermission.isAllowed(ReporterPermission.java:28)
api_1            |      at com.epam.ta.reportportal.auth.permissions.ReportPortalPermissionEvaluator.checkPermission(ReportPortalPermissionEvaluator.java:76)
api_1            |      at com.epam.ta.reportportal.auth.permissions.ReportPortalPermissionEvaluator.hasPermission(ReportPortalPermissionEvaluator.java:61)
api_1            |      at org.springframework.security.access.expression.SecurityExpressionRoot.hasPermission(SecurityExpressionRoot.java:175)
api_1            |      at jdk.internal.reflect.GeneratedMethodAccessor249.invoke(Unknown Source)
api_1            |      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
api_1            |      at java.base/java.lang.reflect.Method.invoke(Unknown Source)
api_1            |      at org.springframework.expression.spel.support.ReflectiveMethodExecutor.execute(ReflectiveMethodExecutor.java:129)
api_1            |      at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:112)
api_1            |      at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:95)
api_1            |      at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:117)
api_1            |      at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:308)
api_1            |      at org.springframework.security.access.expression.ExpressionUtils.evaluateAsBoolean(ExpressionUtils.java:26)
api_1            |      at org.springframework.security.access.expression.method.ExpressionBasedPreInvocationAdvice.before(ExpressionBasedPreInvocationAdvice.java:59)
api_1            |      at org.springframework.security.access.prepost.PreInvocationAuthorizationAdviceVoter.vote(PreInvocationAuthorizationAdviceVoter.java:72)
api_1            |      at org.springframework.security.access.prepost.PreInvocationAuthorizationAdviceVoter.vote(PreInvocationAuthorizationAdviceVoter.java:40)
api_1            |      at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:63)
api_1            |      at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:233)
api_1            |      at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:65)
api_1            |      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
api_1            |      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
api_1            |      at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
api_1            |      at com.epam.ta.reportportal.ws.controller.LaunchController$$EnhancerBySpringCGLIB$$f9e6f09.startLaunch(<generated>)
api_1            |      at jdk.internal.reflect.GeneratedMethodAccessor628.invoke(Unknown Source)
api_1            |      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
api_1            |      at java.base/java.lang.reflect.Method.invoke(Unknown Source)
api_1            |      at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
api_1            |      at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
api_1            |      at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
api_1            |      at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
api_1            |      at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
api_1            |      at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
api_1            |      at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
api_1            |      at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
api_1            |      at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
api_1            |      at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
api_1            |      at javax.servlet.http.HttpServlet.service(HttpServlet.java:665)
api_1            |      at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
api_1            |      at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
api_1            |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
api_1            |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api_1            |      at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
api_1            |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api_1            |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api_1            |      at org.springframework.web.multipart.support.MultipartFilter.doFilterInternal(MultipartFilter.java:125)
api_1            |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
api_1            |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api_1            |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api_1            |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
api_1            |      at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
api_1            |      at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
api_1            |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api_1            |      at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
api_1            |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api_1            |      at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
api_1            |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api_1            |      at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
api_1            |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api_1            |      at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
api_1            |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api_1            |      at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
api_1            |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api_1            |      at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:180)
api_1            |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api_1            |      at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
api_1            |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api_1            |      at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
api_1            |      at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
api_1            |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
api_1            |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api_1            |      at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
api_1            |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api_1            |      at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
api_1            |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
api_1            |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api_1            |      at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
api_1            |      at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
api_1            |      at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
api_1            |      at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
api_1            |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api_1            |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api_1            |      at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
api_1            |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
api_1            |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api_1            |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api_1            |      at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
api_1            |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
api_1            |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api_1            |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api_1            |      at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)
api_1            |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
api_1            |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api_1            |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api_1            |      at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
api_1            |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
api_1            |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api_1            |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api_1            |      at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
api_1            |      at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
api_1            |      at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
api_1            |      at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
api_1            |      at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
api_1            |      at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
api_1            |      at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
api_1            |      at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
api_1            |      at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
api_1            |      at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
api_1            |      at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
api_1            |      at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
api_1            |      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
api_1            |      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
api_1            |      at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
api_1            |      at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by jseriff** [comment]
We are also running into this issue.  It seems that Okta sends the Destination attribute, which ReportPortal attempts to validate.  ReportPortal seems to set the base-url for validation to /uat only, which is not a valid value to set in Okta.  This does not appear to be configurable in ReportPortal. 

I'm not sure there is a way around this currently, until ReportPortal is either modified to not validate the Destination attribute, or the validation uses the fully qualified URL for the service.

**Comment by michaelpecan** [comment]
@evjlobanova  do you have a future release version for google sso?

**Comment by qxd1617** [comment]
Hi, is the OKTA issue regarding /uat still unresolved? Any progress update for it?

**Comment by VolhaKarenko** [comment]
Hi @qxd1617, the issue is resolved in version 5.6. A new field "RP callback URL" was added to OKTA configuration, please find more info here: https://reportportal.io/docs/SAML-integration

**Comment by Miriambnzdn** [comment]
Any update about google sso ?

**Comment by komalmusai** [comment]
Is there any documentation on getting ReportPoral.io SAML setup via OneLogin?

**Comment by raikbitters** [comment]
@komalmusai hi. As I see, for SSO with OneLogin by SAML, you need to use a SAML 2.0 Endpoint (HTTP) and an X.509 Certificate. ReportPortal SAML doesn't support uploading the X.509 .pem file.

If you know how to use App Federation Metadata URL, try this documentation: https://reportportal.io/docs/Azure-SAML-integration.
