### ISSUE TITLE
[v5] - IncompatibleClassChangeError error in the logs and UI at random time

### ISSUE THREAD

**Issue by willyhalim** [reportportal/reportportal#998]
Had this issue when using report portal V5 daily ( at random time ) . **After restart it looks fine.**

Was wondering what could be causing this issue ? Could it some jobs run at ReportPortal at specifc time that could cause this issue ?

We are using JDK 1.8 to run service-api and service-uat.

```
[2020-06-04 14:56:14,074] [reportportal_Worker-1] INFO com.epam.ta.reportportal.job.CleanLogsJob - Cleaning outdated logs has been started
[2020-06-04 14:57:17,324] [QuartzScheduler_reportportal-api:b58e7f179ac99cbaafd2d43e2392f4ca_MisfireHandler] INFO org.springframework.scheduling.quartz.LocalDataSourceJobStore - Handling 4 trigger(s) that missed their scheduled fire-time.
[2020-06-04 15:56:14,076] [reportportal_Worker-1] INFO com.epam.ta.reportportal.job.CleanLogsJob - Cleaning outdated logs has been started
[2020-06-04 15:57:17,347] [QuartzScheduler_reportportal-api:b58e7f179ac99cbaafd2d43e2392f4ca_MisfireHandler] INFO org.springframework.scheduling.quartz.LocalDataSourceJobStore - Handling 4 trigger(s) that missed their scheduled fire-time.
[2020-06-04 16:21:46,657] [http-nio-8585-exec-133] ERROR com.epam.ta.reportportal.commons.exception.rest.RestExceptionHandler - Handled error:
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.IncompatibleClassChangeError
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1055)
```

```

Caused by: java.lang.IncompatibleClassChangeError: null
        at org.hibernate.query.criteria.internal.path.AbstractPathImpl.get(AbstractPathImpl.java:127)
        at org.springframework.data.jpa.repository.support.SimpleJpaRepository$ByIdsSpecification.toPredicate(SimpleJpaRepository.java:844)
        at org.springframework.data.jpa.repository.support.SimpleJpaRepository.applySpecificationToCriteria(SimpleJpaRepository.java:762)
        at org.springframework.data.jpa.repository.support.SimpleJpaRepository.getQuery(SimpleJpaRepository.java:693)
        at org.springframework.data.jpa.repository.support.SimpleJpaRepository.getQuery(SimpleJpaRepository.java:677)
        at org.springframework.data.jpa.repository.support.SimpleJpaRepository.findAllById(SimpleJpaRepository.java:385)
        at sun.reflect.GeneratedMethodAccessor522.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:371)
        at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:204)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:657)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:621)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:605)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.transaction.interceptor.TransactionInterceptor$$Lambda$866/974805190.proceedWithInvocation(Unknown Source)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:353)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:178)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy247.findAllById(Unknown Source)
        at com.epam.ta.reportportal.core.log.impl.GetLogHandlerImpl.lambda$getNestedItems$2(GetLogHandlerImpl.java:134)
        at com.epam.ta.reportportal.core.log.impl.GetLogHandlerImpl$$Lambda$1796/604234112.apply(Unknown Source)
        at java.util.Optional.map(Optional.java:215)
```

**Comment by evjlobanova** [comment]
@pbortnik @Yumfriez Could you please take a look on this issue?

**Comment by DzmitryHumianiuk** [comment]
Probably fixed overtime.
please update to the latest version.
